Dokit: StatusService::ServiceUuids Struct Reference
StatusService::ServiceUuids Struct Reference
UUIDs of the Pokit Status service.
#include <statusservice.h>
Static Public Attributes
static const QBluetoothUuid pokitMeter { QStringLiteral("57d3a771-267c-4394-8872-78223e92aec4") }
UUID of the Pokit Meter's Pokit Status service.
static const QBluetoothUuid pokitPro { QStringLiteral("57d3a771-267c-4394-8872-78223e92aec5") }
UUID of the Pokit Pro's Pokit Status service.
Detailed Description
UUIDs of the Pokit Status service.
Pokit Bluetooth API errata
Pokit API 1.00 (and 0.02) states the Status Service UUID as 57d3a771-267c-4394-8872-78223e92aec4 which is correct for the Pokit Meter, but Pokit Pro uses 57d3a771-267c-4394-8872-78223e92aec5 instead, that is the last digit is a 5 not 4.
Definition at line 30 of file statusservice.h.
Member Data Documentation
pokitMeter
const QBluetoothUuid StatusService::ServiceUuids::pokitMeter { QStringLiteral("57d3a771-267c-4394-8872-78223e92aec4") } inline static
UUID of the Pokit Meter's Pokit Status service.
Definition at line 32 of file statusservice.h.
{ QStringLiteral("57d3a771-267c-4394-8872-78223e92aec4") };
Referenced by isPokitProduct(), pokitProduct(), StatusServicePrivate::serviceDiscovered(), and PokitDevice::serviceToString().
pokitPro
const QBluetoothUuid StatusService::ServiceUuids::pokitPro { QStringLiteral("57d3a771-267c-4394-8872-78223e92aec5") } inline static
UUID of the Pokit Pro's Pokit Status service.
Definition at line 35 of file statusservice.h.
{ QStringLiteral("57d3a771-267c-4394-8872-78223e92aec5") };
Referenced by isPokitProduct(), pokitProduct(), StatusServicePrivate::serviceDiscovered(), and PokitDevice::serviceToString().
The documentation for this struct was generated from the following file:
statusservice.h