    <select id="version">
     <option value="main">dev</option>
     <option value="0.5.2">v0.5.2</option>
     <option value="0.5.1">v0.5.1</option>
     <option value="0.5.0">v0.5.0</option>
     <option value="0.4.0">v0.4.0</option>
     <option value="0.3.0">v0.3.0</option>
     <option value="0.2.0">v0.2.0</option>
     <option value="0.1.2">v0.1.2</option>
     <option value="0.1.1">v0.1.1</option>
     <option value="0.1.0">v0.1.0</option>
    </select>
    <select id="visibility">
     <option value="doc">User docs</option>
     <option value="int">Internal</option>
     <option value="cov">Coverage</option>
    </select>
