Dokit: StatusService Class Reference
StatusService Class Reference
The StatusService class accesses the Pokit Status service of Pokit devices.
Classes
struct CharacteristicUuids
Characteristics available via the Pokit Status service.
struct DeviceCharacteristics
Attributes included in the Device Characteristics characterstic.
struct ServiceUuids
UUIDs of the Pokit Status service.
struct Status
Attributes included in the Status characterstic.
Public Types
enum class DeviceStatus : quint8 {
Idle = 0 , MultimeterDcVoltage = 1 , MultimeterAcVoltage = 2 , MultimeterDcCurrent = 3 ,
MultimeterAcCurrent = 4 , MultimeterResistance = 5 , MultimeterDiode = 6 , MultimeterContinuity = 7 ,
MultimeterTemperature = 8 , DsoModeSampling = 9 , LoggerModeSampling = 10
}
Values supported by the Status attribute of the Status characteristic.
enum class BatteryStatus : quint8 { Low = 0 , Good = 1 }
Values supported by the Battery Status attribute of the Status characteristic.
enum class SwitchPosition : quint8 { Voltage = 0 , MultiMode = 1 , HighCurrent = 2 }
Values supported by the (undocumented) Switch Position attribute of the Status characteristic.
enum class ChargingStatus : quint8 { Discharging = 0 , Charging = 1 , Charged = 2 }
Values supported by the (undocumented) Charging Statue attribute of the Status characteristic.
enum class TorchStatus : quint8 { Off = 0 , On = 1 }
Values supported by the single byte of the attribute of the (undocumented) Torch characteristic.
enum class ButtonStatus : quint8 { Released = 0 , Pressed = 1 , Held = 2 }
Values supported by the second byte of the attribute of the (undocumented) Button Press characteristic.
Signals
void deviceCharacteristicsRead (const StatusService::DeviceCharacteristics &characteristics)
This signal is emitted when the Device Characteristics characteristic has been read successfully.
void deviceNameRead (const QString &deviceName)
This signal is emitted when the Device Name characteristic has been read successfully.
void deviceNameWritten ()
This signal is emitted when the Device Name characteristic has been written successfully.
void deviceStatusRead (const StatusService::Status &status)
This signal is emitted when the Status characteristic has been read successfully.
void deviceLedFlashed ()
This signal is emitted when device's LED has flashed in response to a write of the Flash LED characteristic.
void torchStatusRead (const TorchStatus &status)
This signal is emitted when the Torch characteristic has been read successfully.
void torchStatusWritten ()
This signal is emitted when the Torch characteristic has been written successfully.
void buttonPressRead (const quint8 &unknown, const ButtonStatus status)
This signal is emitted when the Button Press characteristic has been read successfully.
Signals inherited from AbstractPokitService
void serviceDetailsDiscovered ()
This signal is emitted when the Pokit service details have been discovered.
void serviceErrorOccurred (QLowEnergyService::ServiceError newError)
This signal is emitted whenever an error occurs on the underlying QLowEnergyService.
Public Member Functions
StatusService (QLowEnergyController *const pokitDevice, QObject *parent=nullptr)
Constructs a new Pokit service with parent.
~StatusService () override
Destroys this StatusService object.
bool readCharacteristics () override
Read all characteristics.
bool readDeviceCharacteristics ()
Read the Status service's Device Characteristics characteristic.
bool readStatusCharacteristic ()
Read the Status service's Status characteristic.
bool readNameCharacteristic ()
Read the Status service's Name characteristic.
bool readTorchCharacteristic ()
Read the Status service's (undocumented) Torch characteristic.
bool readButtonPressCharacteristic ()
Read the Status service's (undocumented) Button Press characteristic.
DeviceCharacteristics deviceCharacteristics () const
Returns the most recent value of the Status service's Device Characteristics characteristic.
Status status () const
Returns the most recent value of the Status service's Status characteristic.
bool enableStatusNotifications ()
Enables client-side notifications of device status changes.
bool disableStatusNotifications ()
Disables client-side notifications of device status changes.
QString deviceName () const
Returns the most recent value of the Status services's Device Name characteristic.
bool setDeviceName (const QString &name)
Set's the Pokit device's name to name.
bool flashLed ()
Flash the Pokit device's LED.
std::optional< TorchStatus > torchStatus () const
Returns the most recent value of the Status services's Torch characteristic.
bool setTorchStatus (const TorchStatus status)
Set the Pokit device's torch to status.
bool enableTorchStatusNotifications ()
Enables client-side notifications of torch status changes.
bool disableTorchStatusNotifications ()
Disables client-side notifications of torch status changes.
std::optional< ButtonStatus > buttonPress () const
Returns the most recent value of the Status services's Button Press characteristic.
bool enableButtonPressedNotifications ()
Enables client-side notifications of button presses.
bool disableButtonPressedNotifications ()
Disables client-side notifications of button presses.
Public Member Functions inherited from AbstractPokitService
virtual ~AbstractPokitService ()
Destroys this AbstractPokitService object.
bool autoDiscover () const
Returns true if autodiscovery of services and service details is enabled, false otherwise.
void setAutoDiscover (const bool discover=true)
If discover is true, autodiscovery will be attempted.
std::optional< PokitProduct > pokitProduct () const
Returns the Pokit product this service is attached to.
void setPokitProduct (const PokitProduct product)
Sets the current Pokit product.
QLowEnergyService * service ()
Returns a non-const pointer to the internal service object, if any.
const QLowEnergyService * service () const
Returns a const pointer to the internal service object, if any.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Member Functions
static QString toString (const StatusService::DeviceStatus &status)
Returns a string version of the status enum label.
static QString toString (const StatusService::BatteryStatus &status)
Returns a string version of the status enum label.
static QString toString (const StatusService::SwitchPosition &position)
Returns a string version of the position enum label.
static QString toString (const StatusService::ChargingStatus &status)
Returns a string version of the status enum label.
static QString toString (const StatusService::TorchStatus &status)
Returns a string version of the status enum label.
static QString toString (const StatusService::ButtonStatus &status)
Returns a string version of the status enum label.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Protected Member Functions
StatusService (StatusServicePrivate *const d, QObject *const parent)
Constructs a new Pokit service with parent, and private implementation d.
Protected Member Functions inherited from AbstractPokitService
AbstractPokitService (AbstractPokitServicePrivate *const d, QObject *const parent)
Constructs a new Pokit service with parent, and private implementation d.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Friends
class TestStatusService
Additional Inherited Members
Public Attributes inherited from QObject
typedef QObjectList
Protected Attributes inherited from AbstractPokitService
AbstractPokitServicePrivate * d_ptr
Internal d-pointer.
Properties inherited from QObject
objectName
Detailed Description
The StatusService class accesses the Pokit Status service of Pokit devices.
Definition at line 24 of file statusservice.h.
Member Enumeration Documentation
BatteryStatus
enum class StatusService::BatteryStatus : quint8 strong
Values supported by the Battery Status attribute of the Status characteristic.
Enumerator
Low
Low (replace battery).
Good
Good.
Definition at line 90 of file statusservice.h.
                             : quint8 {
        Low = 0,  ///< Low (replace battery).
        Good = 1, ///< Good.
    };
ButtonStatus
enum class StatusService::ButtonStatus : quint8 strong
Values supported by the second byte of the attribute of the (undocumented) Button Press characteristic.
Enumerator
Released
Button was released.
Pressed
Button was pressed.
Held
Button was held down (for typically 1,500ms).
Definition at line 129 of file statusservice.h.
                            : quint8 {
        Released = 0, ///< Button was released.
        Pressed  = 1, ///< Button was pressed.
        Held     = 2, ///< Button was held down (for typically 1,500ms).
    };
ChargingStatus
enum class StatusService::ChargingStatus : quint8 strong
Values supported by the (undocumented) Charging Statue attribute of the Status characteristic.
Enumerator
Discharging
Battery is dischargin.
Charging
Battery is being charged.
Charged
Battery is fully charged.
Definition at line 105 of file statusservice.h.
                              : quint8 {
        Discharging = 0, ///< Battery is dischargin.
        Charging    = 1, ///< Battery is being charged.
        Charged     = 2, ///< Battery is fully charged.
    };
DeviceStatus
enum class StatusService::DeviceStatus : quint8 strong
Values supported by the Status attribute of the Status characteristic.
Enumerator
Idle
Device is idle.
MultimeterDcVoltage
Multimeter is measuring DC voltage.
MultimeterAcVoltage
Multimeter is measuring AC voltage.
MultimeterDcCurrent
Multimeter is measuring DC current.
MultimeterAcCurrent
Multimeter is measuring AC current.
MultimeterResistance
Multimeter is measuring resistance.
MultimeterDiode
Multimeter is measuring diode.
MultimeterContinuity
Multimeter is measuring continuity.
MultimeterTemperature
Multimeter is measuring temperature.
DsoModeSampling
DSO is sampling.
LoggerModeSampling
Data Logger is sampling.
Definition at line 74 of file statusservice.h.
                            : quint8 {
        Idle = 0,                 ///< Device is idle.
        MultimeterDcVoltage = 1,  ///< Multimeter is measuring DC voltage.
        MultimeterAcVoltage = 2,  ///< Multimeter is measuring AC voltage.
        MultimeterDcCurrent = 3,  ///< Multimeter is measuring DC current.
        MultimeterAcCurrent = 4,  ///< Multimeter is measuring AC current.
        MultimeterResistance = 5, ///< Multimeter is measuring resistance.
        MultimeterDiode = 6,      ///< Multimeter is measuring diode.
        MultimeterContinuity = 7, ///< Multimeter is measuring continuity.
        MultimeterTemperature = 8,///< Multimeter is measuring temperature.
        DsoModeSampling = 9,      ///< DSO is sampling.
        LoggerModeSampling = 10,  ///< Data Logger is sampling.
    };
SwitchPosition
enum class StatusService::SwitchPosition : quint8 strong
Values supported by the (undocumented) Switch Position attribute of the Status characteristic.
Pokit Bluetooth API errata
These enum values are undocumented, but easily testable with a physical Pokit Pro device. Internally, Pokit's Android app calls these: SWITCH_MODE_VOLTAGE, SWITCH_MODE_ALL and SWITCH_MODE_CURRENT.
Enumerator
Voltage
Device is switched to Voltage position.
MultiMode
Device is switched to Resistance / Low Current / Capacitance / Diode position.
HighCurrent
Device is switched to High Current position.
Definition at line 97 of file statusservice.h.
                              : quint8 {
        Voltage     = 0, ///< Device is switched to Voltage position.
        MultiMode   = 1, ///< Device is switched to Resistance / Low Current / Capacitance / Diode position.
        HighCurrent = 2, ///< Device is switched to High Current position.
    };
TorchStatus
enum class StatusService::TorchStatus : quint8 strong
Values supported by the single byte of the attribute of the (undocumented) Torch characteristic.
Enumerator
Off
Torch is off.
On
Torch is on.
Definition at line 122 of file statusservice.h.
                           : quint8 {
        Off = 0, ///< Torch is off.
        On  = 1, ///< Torch is on.
    };
Constructor & Destructor Documentation
StatusService() [1/2]
StatusService::StatusService (QLowEnergyController *const pokitDevice, QObject * parent = nullptr)
Constructs a new Pokit service with parent.
Definition at line 124 of file statusservice.cpp.
    : AbstractPokitService(new StatusServicePrivate(controller, this), parent)
{
}
~StatusService()
StatusService::~StatusService () override
Destroys this StatusService object.
Definition at line 145 of file statusservice.cpp.
{
}
StatusService() [2/2]
StatusService::StatusService (StatusServicePrivate *const d, QObject *const parent) protected
Constructs a new Pokit service with parent, and private implementation d.
Definition at line 134 of file statusservice.cpp.
    : AbstractPokitService(d, parent)
{
}
Member Function Documentation
buttonPress()
std::optional< StatusService::ButtonStatus > StatusService::buttonPress () const
Returns the most recent value of the Status services's Button Press characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (eg if the device does not support the Torch characteristic), then nullopt is returned.
Definition at line 492 of file statusservice.cpp.
{
    Q_D(const StatusService);
    const QLowEnergyCharacteristic characteristic = d->getCharacteristic(CharacteristicUuids::buttonPress);
    return (characteristic.isValid()) ? StatusServicePrivate::parseButtonPress(characteristic.value()) : std::nullopt;
}
References StatusService::CharacteristicUuids::buttonPress, QLowEnergyCharacteristic::isValid(), StatusServicePrivate::parseButtonPress(), and QLowEnergyCharacteristic::value().
Referenced by StatusCommand::outputDeviceStatus().
buttonPressRead
StatusService::buttonPressRead (const quint8 & unknown, const ButtonStatus status) signal
This signal is emitted when the Button Press characteristic has been read successfully.
See also
readButtonPressCharacteristic
deviceCharacteristics()
StatusService::DeviceCharacteristics StatusService::deviceCharacteristics () const
Returns the most recent value of the Status service's Device Characteristics characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then a null result is returned, which can be checked via the returned DeviceCharacteristics::firmwareVersion, like:
const DeviceCharacteristics characteristics = service->deviceCharacteristics();
if (!characteristics.firmwareVersion.isNull()) {
    ...
}
Definition at line 252 of file statusservice.cpp.
{
    Q_D(const StatusService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::deviceCharacteristics);
    return (characteristic.isValid())
        ? StatusServicePrivate::parseDeviceCharacteristics(characteristic.value())
        : StatusService::DeviceCharacteristics();
}
References StatusService::CharacteristicUuids::deviceCharacteristics, QLowEnergyCharacteristic::isValid(), StatusServicePrivate::parseDeviceCharacteristics(), and QLowEnergyCharacteristic::value().
Referenced by StatusCommand::serviceDetailsDiscovered().
deviceCharacteristicsRead
StatusService::deviceCharacteristicsRead (const StatusService::DeviceCharacteristics & characteristics) signal
This signal is emitted when the Device Characteristics characteristic has been read successfully.
See also
readDeviceCharacteristics
deviceName()
QString StatusService::deviceName () const
Returns the most recent value of the Status services's Device Name characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then a null QString is returned.
Definition at line 325 of file statusservice.cpp.
{
    Q_D(const StatusService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::name);
    return (characteristic.isValid()) ? QString::fromUtf8(characteristic.value()) : QString();
}
References QString::fromUtf8(), QLowEnergyCharacteristic::isValid(), StatusService::CharacteristicUuids::name, and QLowEnergyCharacteristic::value().
Referenced by StatusCommand::outputDeviceStatus().
deviceNameRead
StatusService::deviceNameRead (const QString & deviceName) signal
This signal is emitted when the Device Name characteristic has been read successfully.
See also
readDeviceName
deviceNameWritten
StatusService::deviceNameWritten () signal
This signal is emitted when the Device Name characteristic has been written successfully.
See also
setDeviceName
Referenced by SetNameCommand::getService().
deviceStatusRead
StatusService::deviceStatusRead (const StatusService::Status & status) signal
This signal is emitted when the Status characteristic has been read successfully.
See also
readDeviceStatus
disableButtonPressedNotifications()
bool StatusService::disableButtonPressedNotifications ()
Disables client-side notifications of button presses.
Instantaneous button press statussed can still be fetched by readButtonPressCharacteristic().
Returns true is the request was successfully submited to the device queue, false otherwise.
Definition at line 479 of file statusservice.cpp.
{
    Q_D(StatusService);
    return d->disableCharacteristicNotificatons(CharacteristicUuids::buttonPress);
}
References StatusService::CharacteristicUuids::buttonPress.
disableStatusNotifications()
bool StatusService::disableStatusNotifications ()
Disables client-side notifications of device status changes.
Instantaneous status can still be fetched by readStatusCharacteristic().
Returns true is the request was successfully submited to the device queue, false otherwise.
Definition at line 312 of file statusservice.cpp.
{
    Q_D(StatusService);
    return d->disableCharacteristicNotificatons(CharacteristicUuids::status);
}
References StatusService::CharacteristicUuids::status.
disableTorchStatusNotifications()
bool StatusService::disableTorchStatusNotifications ()
Disables client-side notifications of torch status changes.
Instantaneous torch status can still be fetched by readTorchCharacteristic().
Returns true is the request was successfully submited to the device queue, false otherwise.
Definition at line 451 of file statusservice.cpp.
{
    Q_D(StatusService);
    return d->disableCharacteristicNotificatons(CharacteristicUuids::torch);
}
References StatusService::CharacteristicUuids::torch.
enableButtonPressedNotifications()
bool StatusService::enableButtonPressedNotifications ()
Enables client-side notifications of button presses.
This is an alternative to manually requesting individual reads via readButtonPressCharacteristic().
Returns true is the request was successfully submited to the device queue, false otherwise.
Successfully read values (if any) will be emitted via the torchStatusRead() signal.
Definition at line 466 of file statusservice.cpp.
{
    Q_D(StatusService);
    return d->enableCharacteristicNotificatons(CharacteristicUuids::buttonPress);
}
References StatusService::CharacteristicUuids::buttonPress.
enableStatusNotifications()
bool StatusService::enableStatusNotifications ()
Enables client-side notifications of device status changes.
This is an alternative to manually requesting individual reads via readStatusCharacteristic().
Returns true is the request was successfully submited to the device queue, false otherwise.
Successfully read values (if any) will be emitted via the deviceStatusRead() signal.
Definition at line 299 of file statusservice.cpp.
{
    Q_D(StatusService);
    return d->enableCharacteristicNotificatons(CharacteristicUuids::status);
}
References StatusService::CharacteristicUuids::status.
enableTorchStatusNotifications()
bool StatusService::enableTorchStatusNotifications ()
Enables client-side notifications of torch status changes.
This is an alternative to manually requesting individual reads via readTorchCharacteristic().
Returns true is the request was successfully submited to the device queue, false otherwise.
Successfully read values (if any) will be emitted via the torchStatusRead() signal.
Definition at line 438 of file statusservice.cpp.
{
    Q_D(StatusService);
    return d->enableCharacteristicNotificatons(CharacteristicUuids::torch);
}
References StatusService::CharacteristicUuids::torch.
flashLed()
bool StatusService::flashLed ()
Flash the Pokit device's LED.
Returns true if the flash request was successfully queued, false otherwise.
Emits deviceLedFlashed() if/when the LED has flashed successfully.
Note
This operation is only supported by Pokit Meter devices. Pokit Pro devices will report an Bluetooth ATT error 0x80.
Pokit Bluetooth API errata
The Android app can turn Pokit Pro LEDs on/off. Perhaps that is handled by an undocumented use of this characteristic. Or perhaps its via some other service.
Definition at line 375 of file statusservice.cpp.
{
    Q_D(const StatusService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::flashLed);
    if (!characteristic.isValid()) {
        return false;
    }
    // The Flash LED characeristic is write-only, and takes a single uint8 "LED" parameter, which
    // must always be 1. Presumably this is an index for which LED to flash, but the Pokit API docs
    // say that "any value other than 1 will be ignored", which makes sense given that all current
    // Pokit devices have only one LED.
    const QByteArray value(1, '\x01');
    d->service->writeCharacteristic(characteristic, value);
    return (d->service->error() != QLowEnergyService::ServiceError::CharacteristicWriteError);
}
References StatusService::CharacteristicUuids::flashLed, and QLowEnergyCharacteristic::isValid().
Referenced by FlashLedCommand::serviceDetailsDiscovered().
readButtonPressCharacteristic()
bool StatusService::readButtonPressCharacteristic ()
Read the Status service's (undocumented) Button Press characteristic.
Returns true is the read request is succesfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits buttonPressRead() if/when the characteristic has been read successfully.
Definition at line 231 of file statusservice.cpp.
{
    Q_D(StatusService);
    return d->readCharacteristic(CharacteristicUuids::buttonPress);
}
References StatusService::CharacteristicUuids::buttonPress.
Referenced by readCharacteristics().
readCharacteristics()
bool StatusService::readCharacteristics () override virtual
Read all characteristics.
This convenience function will queue refresh requests of all characteristics supported by this service.
Relevant *Service::*Read signals will be emitted by derived class objects as each characteristic is successfully read.
Implements AbstractPokitService.
Definition at line 150 of file statusservice.cpp.
{
    const bool r1 = readDeviceCharacteristics();
    const bool r2 = readStatusCharacteristic();
    const bool r3 = readNameCharacteristic();
    const bool r4 = ((service() != nullptr) && (service()->characteristic(CharacteristicUuids::torch).isValid()))
        ? readTorchCharacteristic() : true;
    const bool r5 = ((service() != nullptr) && (service()->characteristic(CharacteristicUuids::buttonPress).isValid()))
        ? readButtonPressCharacteristic() : true;
    return (r1 && r2 && r3 && r4 && r5);
}
References StatusService::CharacteristicUuids::buttonPress, QLowEnergyService::characteristic(), QLowEnergyCharacteristic::isValid(), readButtonPressCharacteristic(), readDeviceCharacteristics(), readNameCharacteristic(), readStatusCharacteristic(), readTorchCharacteristic(), AbstractPokitService::service(), and StatusService::CharacteristicUuids::torch.
readDeviceCharacteristics()
bool StatusService::readDeviceCharacteristics ()
Read the Status service's Device Characteristics characteristic.
Returns true is the read request is succesfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits deviceCharacteristicsRead() if/when the characteristic has been read successfully.
Definition at line 171 of file statusservice.cpp.
{
    Q_D(StatusService);
    return d->readCharacteristic(CharacteristicUuids::deviceCharacteristics);
}
References StatusService::CharacteristicUuids::deviceCharacteristics.
Referenced by readCharacteristics().
readNameCharacteristic()
bool StatusService::readNameCharacteristic ()
Read the Status service's Name characteristic.
Returns true is the read request is succesfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits deviceNameRead() if/when the characteristic has been read successfully.
Definition at line 201 of file statusservice.cpp.
{
    Q_D(StatusService);
    return d->readCharacteristic(CharacteristicUuids::name);
}
References StatusService::CharacteristicUuids::name.
Referenced by readCharacteristics().
readStatusCharacteristic()
bool StatusService::readStatusCharacteristic ()
Read the Status service's Status characteristic.
Returns true is the read request is succesfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits deviceStatusRead() if/when the characteristic has been read successfully.
Definition at line 186 of file statusservice.cpp.
{
    Q_D(StatusService);
    return d->readCharacteristic(CharacteristicUuids::status);
}
References StatusService::CharacteristicUuids::status.
Referenced by readCharacteristics().
readTorchCharacteristic()
bool StatusService::readTorchCharacteristic ()
Read the Status service's (undocumented) Torch characteristic.
Returns true is the read request is succesfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits torchStatusRead() if/when the characteristic has been read successfully.
Definition at line 216 of file statusservice.cpp.
{
    Q_D(StatusService);
    return d->readCharacteristic(CharacteristicUuids::torch);
}
References StatusService::CharacteristicUuids::torch.
Referenced by readCharacteristics().
setDeviceName()
bool StatusService::setDeviceName (const QString & name)
Set's the Pokit device's name to name.
Returns true if the write request was successfully queued, false otherwise.
Emits deviceNameWritten() if/when the name has been set.
Definition at line 340 of file statusservice.cpp.
{
    Q_D(const StatusService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::name);
    if (!characteristic.isValid()) {
        return false;
    }
    const QByteArray value = name.toUtf8();
    if (value.length() > 11) {
        qCWarning(d->lc).noquote() << tr(R"(Device name "%1" is too long (%2 > 11 bytes): 0x3)")
            .arg(name).arg(value.length()).arg(QLatin1String(value.toHex()));
        return false;
    }
    d->service->writeCharacteristic(characteristic, value);
    return (d->service->error() != QLowEnergyService::ServiceError::CharacteristicWriteError);
}
References QString::arg(), QLowEnergyCharacteristic::isValid(), QByteArray::length(), StatusService::CharacteristicUuids::name, QByteArray::toHex(), QString::toUtf8(), and QObject::tr().
Referenced by SetNameCommand::serviceDetailsDiscovered().
setTorchStatus()
bool StatusService::setTorchStatus (const TorchStatus status)
Set the Pokit device's torch to status.
Returns true if the request was successfully queued, false otherwise.
Emits torchStatusWritten() if/when the LED has flashed successfully.
Note
This operation is only supported by Pokit Pro devices, and not Pokit Meter devices.
Definition at line 416 of file statusservice.cpp.
{
    Q_D(const StatusService);
    const QLowEnergyCharacteristic characteristic = d->getCharacteristic(CharacteristicUuids::torch);
    if (!characteristic.isValid()) {
        return false;
    }
    const QByteArray value(1, static_cast<char>(status));
    d->service->writeCharacteristic(characteristic, value);
    return (d->service->error() != QLowEnergyService::ServiceError::CharacteristicWriteError);
}
References QLowEnergyCharacteristic::isValid(), status(), and StatusService::CharacteristicUuids::torch.
Referenced by SetTorchCommand::serviceDetailsDiscovered().
status()
StatusService::Status StatusService::status () const
Returns the most recent value of the Status service's Status characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then the returned StatusService::Status::batteryLevel member will be a quiet NaN, which can be checked like:
const StatusService::Status status = statusService->status();
if (qIsNaN(status.batteryVoltage)) {
    // Handle failure.
}
Not all Pokit devices support the Status::batteryStatus member, in which case the member will be initilialised to the maximum value supported by the underlying type (ie 255) to indicate "not set"
Definition at line 280 of file statusservice.cpp.
{
    Q_D(const StatusService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::status);
    return (characteristic.isValid()) ? StatusServicePrivate::parseStatus(characteristic.value())
        : StatusService::Status{ DeviceStatus::Idle, std::numeric_limits<float>::quiet_NaN(),
                                 BatteryStatus::Low, std::nullopt, std::nullopt };
}
References Idle, QLowEnergyCharacteristic::isValid(), Low, StatusServicePrivate::parseStatus(), StatusService::CharacteristicUuids::status, and QLowEnergyCharacteristic::value().
Referenced by StatusCommand::outputDeviceStatus(), setTorchStatus(), toString(), toString(), toString(), toString(), and toString().
torchStatus()
std::optional< StatusService::TorchStatus > StatusService::torchStatus () const
Returns the most recent value of the Status services's Torch characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (eg if the device does not support the Torch characteristic), then nullopt is returned.
Definition at line 400 of file statusservice.cpp.
{
    Q_D(const StatusService);
    const QLowEnergyCharacteristic characteristic = d->getCharacteristic(CharacteristicUuids::torch);
    return (characteristic.isValid()) ? StatusServicePrivate::parseTorchStatus(characteristic.value()) : std::nullopt;
}
References QLowEnergyCharacteristic::isValid(), StatusServicePrivate::parseTorchStatus(), StatusService::CharacteristicUuids::torch, and QLowEnergyCharacteristic::value().
Referenced by StatusCommand::outputDeviceStatus().
torchStatusRead
StatusService::torchStatusRead (const TorchStatus & status) signal
This signal is emitted when the Torch characteristic has been read successfully.
See also
setTorchStatus
torchStatusWritten
StatusService::torchStatusWritten () signal
This signal is emitted when the Torch characteristic has been written successfully.
See also
readTorchCharacteristic
Referenced by SetTorchCommand::getService().
toString() [1/6]
QString StatusService::toString (const StatusService::BatteryStatus & status) static
Returns a string version of the status enum label.
Definition at line 53 of file statusservice.cpp.
{
    switch (status) {
    case BatteryStatus::Low:  return QLatin1String("Low");
    case BatteryStatus::Good: return QLatin1String("Good");
    }
    return QString();
}
References Good, Low, and status().
toString() [2/6]
QString StatusService::toString (const StatusService::ButtonStatus & status) static
Returns a string version of the status enum label.
Definition at line 111 of file statusservice.cpp.
{
    switch (status) {
    case ButtonStatus::Released: return QLatin1String("Released");
    case ButtonStatus::Pressed:  return QLatin1String("Pressed");
    case ButtonStatus::Held:     return QLatin1String("Held");
    }
    return QString();
}
References Held, Pressed, Released, and status().
toString() [3/6]
QString StatusService::toString (const StatusService::ChargingStatus & status) static
Returns a string version of the status enum label.
Definition at line 86 of file statusservice.cpp.
{
    switch (status) {
    case ChargingStatus::Discharging: return QLatin1String("Discharging");
    case ChargingStatus::Charging:    return QLatin1String("Charging");
    case ChargingStatus::Charged:     return QLatin1String("Charged");
    }
    return QString();
}
References Charged, Charging, Discharging, and status().
toString() [4/6]
QString StatusService::toString (const StatusService::DeviceStatus & status) static
Returns a string version of the status enum label.
Definition at line 32 of file statusservice.cpp.
{
    switch (status) {
    case DeviceStatus::Idle:                 return  QLatin1String("Idle");
    case DeviceStatus::MultimeterDcVoltage:  return  QLatin1String("MultimeterDcVoltage");
    case DeviceStatus::MultimeterAcVoltage:  return  QLatin1String("MultimeterAcVoltage");
    case DeviceStatus::MultimeterDcCurrent:  return  QLatin1String("MultimeterDcCurrent");
    case DeviceStatus::MultimeterAcCurrent:  return  QLatin1String("MultimeterAcCurrent");
    case DeviceStatus::MultimeterResistance: return  QLatin1String("MultimeterResistance");
    case DeviceStatus::MultimeterDiode:      return  QLatin1String("MultimeterDiode");
    case DeviceStatus::MultimeterContinuity: return  QLatin1String("MultimeterContinuity");
    case DeviceStatus::MultimeterTemperature:return  QLatin1String("MultimeterTemperature");
    case DeviceStatus::DsoModeSampling:      return  QLatin1String("DsoModeSampling");
    case DeviceStatus::LoggerModeSampling:   return  QLatin1String("LoggerModeSampling");
    }
    return QString();
}
References DsoModeSampling, Idle, LoggerModeSampling, MultimeterAcCurrent, MultimeterAcVoltage, MultimeterContinuity, MultimeterDcCurrent, MultimeterDcVoltage, MultimeterDiode, MultimeterResistance, MultimeterTemperature, and status().
Referenced by StatusServicePrivate::characteristicRead(), StatusCommand::outputDeviceStatus(), StatusServicePrivate::parseButtonPress(), StatusServicePrivate::parseStatus(), StatusServicePrivate::parseTorchStatus(), and SetTorchCommand::serviceDetailsDiscovered().
toString() [5/6]
QString StatusService::toString (const StatusService::SwitchPosition & position) static
Returns a string version of the position enum label.
Definition at line 73 of file statusservice.cpp.
{
    switch (position) {
    case SwitchPosition::Voltage:     return QLatin1String("Voltage");
    case SwitchPosition::MultiMode:   return QLatin1String("MultiMode");
    case SwitchPosition::HighCurrent: return QLatin1String("HighCurrent");
    }
    return QString();
}
References HighCurrent, MultiMode, and Voltage.
toString() [6/6]
QString StatusService::toString (const StatusService::TorchStatus & status) static
Returns a string version of the status enum label.
Definition at line 99 of file statusservice.cpp.
{
    switch (status) {
    case TorchStatus::Off: return QLatin1String("Off");
    case TorchStatus::On:  return QLatin1String("On");
    }
    return QString();
}
References Off, On, and status().
Friends And Related Symbol Documentation
TestStatusService
friend class TestStatusService friend
Definition at line 190 of file statusservice.h.
The documentation for this class was generated from the following files:
statusservice.h
statusservice.cpp