Dokit: DataLoggerService::CharacteristicUuids Struct Reference
DataLoggerService::CharacteristicUuids Struct Reference
Characteristics available via the DataLogger service.
#include <dataloggerservice.h>
Static Public Attributes
static const QBluetoothUuid settings { QStringLiteral("5f97c62b-a83b-46c6-b9cd-cac59e130a78") }
UUID of the DataLogger service's Settings characterstic.
static const QBluetoothUuid metadata { QStringLiteral("9acada2e-3936-430b-a8f7-da407d97ca6e") }
UUID of the DataLogger service's Metadata characterstic.
static const QBluetoothUuid reading { QStringLiteral("3c669dab-fc86-411c-9498-4f9415049cc0") }
UUID of the DataLogger service's Reading characterstic.
Detailed Description
Characteristics available via the DataLogger service.
Definition at line 31 of file dataloggerservice.h.
Member Data Documentation
metadata
const QBluetoothUuid DataLoggerService::CharacteristicUuids::metadata { QStringLiteral("9acada2e-3936-430b-a8f7-da407d97ca6e") } inline static
UUID of the DataLogger service's Metadata characterstic.
Definition at line 36 of file dataloggerservice.h.
{ QStringLiteral("9acada2e-3936-430b-a8f7-da407d97ca6e") };
Referenced by DataLoggerServicePrivate::characteristicChanged(), DataLoggerServicePrivate::characteristicRead(), DataLoggerServicePrivate::characteristicWritten(), PokitDevice::charcteristicToString(), DataLoggerService::disableMetadataNotifications(), DataLoggerService::enableMetadataNotifications(), DataLoggerService::metadata(), DataLoggerService::readMetadataCharacteristic(), and DataLoggerService::setSettings().
reading
const QBluetoothUuid DataLoggerService::CharacteristicUuids::reading { QStringLiteral("3c669dab-fc86-411c-9498-4f9415049cc0") } inline static
UUID of the DataLogger service's Reading characterstic.
Definition at line 39 of file dataloggerservice.h.
{ QStringLiteral("3c669dab-fc86-411c-9498-4f9415049cc0") };
Referenced by DataLoggerServicePrivate::characteristicChanged(), DataLoggerServicePrivate::characteristicRead(), DataLoggerServicePrivate::characteristicWritten(), PokitDevice::charcteristicToString(), DataLoggerService::disableReadingNotifications(), and DataLoggerService::enableReadingNotifications().
settings
const QBluetoothUuid DataLoggerService::CharacteristicUuids::settings { QStringLiteral("5f97c62b-a83b-46c6-b9cd-cac59e130a78") } inline static
UUID of the DataLogger service's Settings characterstic.
Definition at line 33 of file dataloggerservice.h.
{ QStringLiteral("5f97c62b-a83b-46c6-b9cd-cac59e130a78") };
Referenced by DataLoggerServicePrivate::characteristicChanged(), DataLoggerServicePrivate::characteristicRead(), DataLoggerServicePrivate::characteristicWritten(), PokitDevice::charcteristicToString(), and DataLoggerService::setSettings().
The documentation for this struct was generated from the following file:
dataloggerservice.h