Dokit: CalibrationService Class Reference
CalibrationService Class Reference
The CalibrationService class accesses the Calibrartion service of Pokit devices.
Classes
struct CharacteristicUuids
Characteristics available via the Calibration service.
Signals
void temperatureCalibrated ()
This signal is emitted when the Temperature characteristic has been written succesfully.
Signals inherited from AbstractPokitService
void serviceDetailsDiscovered ()
This signal is emitted when the Pokit service details have been discovered.
void serviceErrorOccurred (QLowEnergyService::ServiceError newError)
This signal is emitted whenever an error occurs on the underlying QLowEnergyService.
Public Member Functions
CalibrationService (QLowEnergyController *const pokitDevice, QObject *parent=nullptr)
Constructs a new Pokit service with parent.
~CalibrationService () override
Destroys this CalibrationService object.
bool readCharacteristics () override
Read all characteristics.
bool calibrateTemperature (const float ambientTemperature)
Calibrates the Pokit device's temperature to ambientTemperature.
Public Member Functions inherited from AbstractPokitService
virtual ~AbstractPokitService ()
Destroys this AbstractPokitService object.
bool autoDiscover () const
Returns true if autodiscovery of services and service details is enabled, false otherwise.
void setAutoDiscover (const bool discover=true)
If discover is true, autodiscovery will be attempted.
std::optional< PokitProduct > pokitProduct () const
Returns the Pokit product this service is attached to.
void setPokitProduct (const PokitProduct product)
Sets the current Pokit product.
QLowEnergyService * service ()
Returns a non-const pointer to the internal service object, if any.
const QLowEnergyService * service () const
Returns a const pointer to the internal service object, if any.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Attributes
static const QBluetoothUuid serviceUuid { QStringLiteral("6f53be2f-780b-49b8-a7c3-e8a052b3ae2c") }
UUID of the Calibration service.
Protected Member Functions
CalibrationService (CalibrationServicePrivate *const d, QObject *const parent)
Constructs a new Pokit service with parent, and private implementation d.
Protected Member Functions inherited from AbstractPokitService
AbstractPokitService (AbstractPokitServicePrivate *const d, QObject *const parent)
Constructs a new Pokit service with parent, and private implementation d.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Friends
class TestCalibrationService
Additional Inherited Members
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Protected Attributes inherited from AbstractPokitService
AbstractPokitServicePrivate * d_ptr
Internal d-pointer.
Properties inherited from QObject
objectName
Detailed Description
The CalibrationService class accesses the Calibrartion service of Pokit devices.
Definition at line 22 of file calibrationservice.h.
Constructor & Destructor Documentation
CalibrationService() [1/2]
CalibrationService::CalibrationService (QLowEnergyController *const pokitDevice, QObject * parent = nullptr)
Constructs a new Pokit service with parent.
Definition at line 24 of file calibrationservice.cpp.
    : AbstractPokitService(new CalibrationServicePrivate(controller, this), parent)
{
}
~CalibrationService()
CalibrationService::~CalibrationService () override
Destroys this CalibrationService object.
Definition at line 45 of file calibrationservice.cpp.
{
}
CalibrationService() [2/2]
CalibrationService::CalibrationService (CalibrationServicePrivate *const d, QObject *const parent) protected
Constructs a new Pokit service with parent, and private implementation d.
Definition at line 34 of file calibrationservice.cpp.
    : AbstractPokitService(d, parent)
{
}
Member Function Documentation
calibrateTemperature()
bool CalibrationService::calibrateTemperature (const float ambientTemperature)
Calibrates the Pokit device's temperature to ambientTemperature.
Returns true if the write request was successfully queued, false otherwise.
Emits temperatureCalibrated() if/when the name has been set.
Definition at line 70 of file calibrationservice.cpp.
{
    static_assert(sizeof(float) == 4, "Pokit devices expect 32-bit floats");
    Q_D(const CalibrationService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::temperature);
    if (!characteristic.isValid()) {
        return false;
    }
    const QByteArray newValue = CalibrationServicePrivate::encodeTemperature(ambientTemperature);
    qCDebug(d->lc).noquote() << tr("Writing new temperature %1 (0x%2).")
        .arg(ambientTemperature).arg(QLatin1String(newValue.toHex()));
    d->service->writeCharacteristic(characteristic, newValue);
    return (d->service->error() != QLowEnergyService::ServiceError::CharacteristicWriteError);
}
References QString::arg(), CalibrationServicePrivate::encodeTemperature(), QLowEnergyCharacteristic::isValid(), CalibrationService::CharacteristicUuids::temperature, QByteArray::toHex(), and QObject::tr().
Referenced by CalibrateCommand::serviceDetailsDiscovered().
readCharacteristics()
bool CalibrationService::readCharacteristics () override virtual
Read all characteristics.
This implementation always returns true, since the Calibration service provides no readable characteristics (they're all write-only).
Implements AbstractPokitService.
Definition at line 56 of file calibrationservice.cpp.
{
    Q_D(CalibrationService);
    qCDebug(d->lc).noquote() << tr("Ignoring read request; the Calibration service is write-only.");
    return true;
}
References QObject::tr().
temperatureCalibrated
CalibrationService::temperatureCalibrated () signal
This signal is emitted when the Temperature characteristic has been written succesfully.
See also
calibrateTemperature
Referenced by CalibrateCommand::getService().
Friends And Related Symbol Documentation
TestCalibrationService
friend class TestCalibrationService friend
Definition at line 61 of file calibrationservice.h.
Member Data Documentation
serviceUuid
const QBluetoothUuid CalibrationService::serviceUuid { QStringLiteral("6f53be2f-780b-49b8-a7c3-e8a052b3ae2c") } inline static
UUID of the Calibration service.
Definition at line 28 of file calibrationservice.h.
{ QStringLiteral("6f53be2f-780b-49b8-a7c3-e8a052b3ae2c") };
Referenced by PokitDevice::serviceToString().
The documentation for this class was generated from the following files:
calibrationservice.h
calibrationservice.cpp