Dokit: PokitMeter Namespace Reference
PokitMeter Namespace Reference
Encapsulates details specific to Pokit Meter devices.
Enumerations
enum class CurrentRange : quint8 {
_10mA = 0 , _30mA = 1 , _150mA = 2 , _300mA = 3 ,
_2A = 4 , AutoRange = 255
}
Values supported by the Pokit Meter's Range attributes in *Current modes.
enum class ResistanceRange : quint8 {
_160 = 0 , _330 = 1 , _890 = 2 , _1K5 = 3 ,
_10K = 4 , _100K = 5 , _470K = 6 , _1M = 7 ,
AutoRange = 255
}
Values supported by the Pokit Meter's Range attributes in Resistance mode.
enum class VoltageRange : quint8 {
_300mV = 0 , _2V = 1 , _6V = 2 , _12V = 3 ,
_30V = 4 , _60V = 5 , AutoRange = 255
}
Values supported by the Pokit Meter's Range attributes in *Voltage modes.
Functions
QTPOKIT_EXPORT QString toString (const CurrentRange &range)
Returns range as a user-friendly string.
QTPOKIT_EXPORT QVariant maxValue (const CurrentRange &range)
Returns the maximum value for range in (integer) microamps, or the string "Auto".
QTPOKIT_EXPORT QString toString (const ResistanceRange &range)
Returns range as a user-friendly string.
QTPOKIT_EXPORT QVariant maxValue (const ResistanceRange &range)
Returns the maximum value for range in (integer) ohms, or the string "Auto".
QTPOKIT_EXPORT QString toString (const VoltageRange &range)
Returns range as a user-friendly string.
QTPOKIT_EXPORT QVariant maxValue (const VoltageRange &range)
Returns the maximum value for range in (integer) millivolts, or the string "Auto".
Detailed Description
Encapsulates details specific to Pokit Meter devices.
Enumeration Type Documentation
CurrentRange
enum class PokitMeter::CurrentRange : quint8 strong
Values supported by the Pokit Meter's Range attributes in *Current modes.
Enumerator
_10mA
Up to 10mA.
_30mA
Up to 30mA.
_150mA
Up to 150mA.
_300mA
Up to 300mA.
_2A
Up to 2A.
AutoRange
Auto-range.
Definition at line 22 of file pokitmeter.h.
                            : quint8 {
        _10mA     = 0,  ///< Up to 10mA.
        _30mA     = 1,  ///< Up to 30mA.
        _150mA    = 2,  ///< Up to 150mA.
        _300mA    = 3,  ///< Up to 300mA.
        _2A       = 4,  ///< Up to 2A.
        AutoRange = 255 ///< Auto-range.
    };
ResistanceRange
enum class PokitMeter::ResistanceRange : quint8 strong
Values supported by the Pokit Meter's Range attributes in Resistance mode.
Enumerator
_160
Up to 160Ω.
_330
Up to 330Ω.
_890
Up to 890Ω.
_1K5
Up to 1.5KΩ.
_10K
Up to 10KΩ.
_100K
Up to 100KΩ.
_470K
Up to 470KΩ.
_1M
Up to 1MΩ.
AutoRange
Auto-range.
Definition at line 34 of file pokitmeter.h.
                               : quint8 {
        _160      = 0,  ///< Up to 160Ω.
        _330      = 1,  ///< Up to 330Ω.
        _890      = 2,  ///< Up to 890Ω.
        _1K5      = 3,  ///< Up to 1.5KΩ.
        _10K      = 4,  ///< Up to 10KΩ.
        _100K     = 5,  ///< Up to 100KΩ.
        _470K     = 6,  ///< Up to 470KΩ.
        _1M       = 7,  ///< Up to 1MΩ.
        AutoRange = 255 ///< Auto-range.
    };
VoltageRange
enum class PokitMeter::VoltageRange : quint8 strong
Values supported by the Pokit Meter's Range attributes in *Voltage modes.
Enumerator
_300mV
Up to 300mV.
_2V
Up to 2V.
_6V
Up to 6V.
_12V
Up to 12V.
_30V
Up to 30V.
_60V
Up to 60V DC (42V AC).
AutoRange
Auto-range.
Definition at line 49 of file pokitmeter.h.
                            : quint8 {
        _300mV    = 0,  ///< Up to 300mV.
        _2V       = 1,  ///< Up to 2V.
        _6V       = 2,  ///< Up to 6V.
        _12V      = 3,  ///< Up to 12V.
        _30V      = 4,  ///< Up to 30V.
        _60V      = 5,  ///< Up to 60V DC (42V AC).
        AutoRange = 255 ///< Auto-range.
    };
Function Documentation
maxValue() [1/3]
QVariant PokitMeter::maxValue (const CurrentRange & range)
Returns the maximum value for range in (integer) microamps, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned.
Definition at line 33 of file pokitmeter.cpp.
{
    switch (range) {
    case CurrentRange::_10mA:     return    10'000;
    case CurrentRange::_30mA:     return    30'000;
    case CurrentRange::_150mA:    return   150'000;
    case CurrentRange::_300mA:    return   300'000;
    case CurrentRange::_2A:       return 2'000'000;
    case CurrentRange::AutoRange: return QCoreApplication::translate("PokitMeter", "Auto", "CurrentRange");
    default:                      return QVariant();
    }
}
References _10mA, _150mA, _2A, _300mA, _30mA, AutoRange, and QCoreApplication::translate().
Referenced by CurrentRange::maxValue(), ResistanceRange::maxValue(), and VoltageRange::maxValue().
maxValue() [2/3]
QVariant PokitMeter::maxValue (const ResistanceRange & range)
Returns the maximum value for range in (integer) ohms, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned.
Definition at line 67 of file pokitmeter.cpp.
{
    switch (range) {
    case ResistanceRange::_160:      return       160;
    case ResistanceRange::_330:      return       330;
    case ResistanceRange::_890:      return       890;
    case ResistanceRange::_1K5:      return     1'500;
    case ResistanceRange::_10K:      return    10'000;
    case ResistanceRange::_100K:     return   100'000;
    case ResistanceRange::_470K:     return   470'000;
    case ResistanceRange::_1M:       return 1'000'000;
    case ResistanceRange::AutoRange: return QCoreApplication::translate("PokitMeter", "Auto", "ResistanceRange");
    default:                         return QVariant();
    }
}
References _100K, _10K, _160, _1K5, _1M, _330, _470K, _890, AutoRange, and QCoreApplication::translate().
maxValue() [3/3]
QVariant PokitMeter::maxValue (const VoltageRange & range)
Returns the maximum value for range in (integer) millivolts, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned.
Definition at line 102 of file pokitmeter.cpp.
{
    switch (range) {
    case VoltageRange::_300mV:    return    300;
    case VoltageRange::_2V:       return  2'000;
    case VoltageRange::_6V:       return  6'000;
    case VoltageRange::_12V:      return 12'000;
    case VoltageRange::_30V:      return 30'000;
    case VoltageRange::_60V:      return 60'000;
    case VoltageRange::AutoRange: return QCoreApplication::translate("PokitMeter", "Auto", "VoltageRange");
    default:                      return QVariant();
    }
}
References _12V, _2V, _300mV, _30V, _60V, _6V, AutoRange, and QCoreApplication::translate().
toString() [1/3]
QString PokitMeter::toString (const CurrentRange & range)
Returns range as a user-friendly string.
Definition at line 16 of file pokitmeter.cpp.
{
    switch (range) {
    case CurrentRange::_10mA:     return QCoreApplication::translate("PokitMeter", "Up to 10mA",  "CurrentRange");
    case CurrentRange::_30mA:     return QCoreApplication::translate("PokitMeter", "Up to 30mA",  "CurrentRange");
    case CurrentRange::_150mA:    return QCoreApplication::translate("PokitMeter", "Up to 150mA", "CurrentRange");
    case CurrentRange::_300mA:    return QCoreApplication::translate("PokitMeter", "Up to 300mA", "CurrentRange");
    case CurrentRange::_2A:       return QCoreApplication::translate("PokitMeter", "Up to 2A",    "CurrentRange");
    case CurrentRange::AutoRange: return QCoreApplication::translate("PokitMeter", "Auto-range",  "CurrentRange");
    default:                      return QString();
    }
}
References _10mA, _150mA, _2A, _300mA, _30mA, AutoRange, and QCoreApplication::translate().
Referenced by CurrentRange::toString(), ResistanceRange::toString(), and VoltageRange::toString().
toString() [2/3]
QString PokitMeter::toString (const ResistanceRange & range)
Returns range as a user-friendly string.
Definition at line 47 of file pokitmeter.cpp.
{
    switch (range) {
    case ResistanceRange::_160:      return QCoreApplication::translate("PokitMeter", "Up to 160Ω",  "ResistanceRange");
    case ResistanceRange::_330:      return QCoreApplication::translate("PokitMeter", "Up to 330Ω",  "ResistanceRange");
    case ResistanceRange::_890:      return QCoreApplication::translate("PokitMeter", "Up to 890Ω",  "ResistanceRange");
    case ResistanceRange::_1K5:      return QCoreApplication::translate("PokitMeter", "Up to 1.5KΩ", "ResistanceRange");
    case ResistanceRange::_10K:      return QCoreApplication::translate("PokitMeter", "Up to 10KΩ",  "ResistanceRange");
    case ResistanceRange::_100K:     return QCoreApplication::translate("PokitMeter", "Up to 100KΩ", "ResistanceRange");
    case ResistanceRange::_470K:     return QCoreApplication::translate("PokitMeter", "Up to 470KΩ", "ResistanceRange");
    case ResistanceRange::_1M:       return QCoreApplication::translate("PokitMeter", "Up to 1MΩ",   "ResistanceRange");
    case ResistanceRange::AutoRange: return QCoreApplication::translate("PokitMeter", "Auto-range",  "ResistanceRange");
    default:                         return QString();
    }
}
References _100K, _10K, _160, _1K5, _1M, _330, _470K, _890, AutoRange, and QCoreApplication::translate().
toString() [3/3]
QString PokitMeter::toString (const VoltageRange & range)
Returns range as a user-friendly string.
Definition at line 84 of file pokitmeter.cpp.
{
    switch (range) {
    case VoltageRange::_300mV:    return QCoreApplication::translate("PokitMeter", "Up to 300mV", "VoltageRange");
    case VoltageRange::_2V:       return QCoreApplication::translate("PokitMeter", "Up to 2V",    "VoltageRange");
    case VoltageRange::_6V:       return QCoreApplication::translate("PokitMeter", "Up to 6V",    "VoltageRange");
    case VoltageRange::_12V:      return QCoreApplication::translate("PokitMeter", "Up to 12V",   "VoltageRange");
    case VoltageRange::_30V:      return QCoreApplication::translate("PokitMeter", "Up to 30V",   "VoltageRange");
    case VoltageRange::_60V:      return QCoreApplication::translate("PokitMeter", "Up to 60V",   "VoltageRange");
    case VoltageRange::AutoRange: return QCoreApplication::translate("PokitMeter", "Auto-range",  "VoltageRange");
    default:                      return QString();
    }
}
References _12V, _2V, _300mV, _30V, _60V, _6V, AutoRange, and QCoreApplication::translate().