Dokit: pokitproducts.h File Reference
pokitproducts.h File Reference
Declares the PokitProduct enumeration, and related helper functions.
#include "qtpokit_global.h"
#include <QBluetoothDeviceInfo>
#include <QFlags>
#include <QString>
Enumerations
enum class PokitProduct : quint8 { PokitMeter = 0 , PokitPro = 1 }
Pokit products known to, and supported by, the QtPokit library.
Functions
QTPOKIT_EXPORT QString toString (const PokitProduct product)
Returns product as user-friendly string.
QTPOKIT_EXPORT bool isPokitProduct (const QBluetoothDeviceInfo &info)
Returns true if info describes a Pokit device.
QTPOKIT_EXPORT PokitProduct pokitProduct (const QBluetoothDeviceInfo &info)
Returns the PokitProduct corresponding the Bluetotoh device info.
Detailed Description
Declares the PokitProduct enumeration, and related helper functions.
Definition in file pokitproducts.h.
Enumeration Type Documentation
PokitProduct
enum class PokitProduct : quint8 strong
Pokit products known to, and supported by, the QtPokit library.
Enumerator
PokitMeter
Pokit Meter.
PokitPro
Pokit Pro.
Definition at line 21 of file pokitproducts.h.
                        : quint8 {
  //PokitClamp = 3, ///< \todo Pokit Clamp
    PokitMeter = 0, ///< Pokit Meter
    PokitPro   = 1, ///< Pokit Pro
};
Function Documentation
isPokitProduct()
QTPOKIT_EXPORT bool isPokitProduct (const QBluetoothDeviceInfo & info)
Returns true if info describes a Pokit device.
Currently, this is based on whether or not info's service UUIDs includes a known Pokit Status service, but this test criteria might be swapped for something else sometime.
Definition at line 43 of file pokitproducts.cpp.
{
    return isPokitProduct(info.serviceUuids());
}
References isPokitProduct(), and QBluetoothDeviceInfo::serviceUuids().
Referenced by PokitDiscoveryAgentPrivate::deviceDiscovered(), DeviceCommand::deviceDiscovered(), PokitDiscoveryAgentPrivate::deviceUpdated(), isPokitProduct(), and isPokitProduct().
pokitProduct()
QTPOKIT_EXPORT PokitProduct pokitProduct (const QBluetoothDeviceInfo & info)
Returns the PokitProduct corresponding the Bluetotoh device info.
If info is not a Pokit device, then result is undefined.
See also
isPokitProduct
Definition at line 55 of file pokitproducts.cpp.
{
    return pokitProduct(info.serviceUuids());
}
References pokitProduct(), and QBluetoothDeviceInfo::serviceUuids().
Referenced by DeviceCommand::deviceDiscovered(), pokitProduct(), and pokitProduct().
toString()
QTPOKIT_EXPORT QString toString (const PokitProduct product)
Returns product as user-friendly string.
Definition at line 26 of file pokitproducts.cpp.
{
    switch (product) {
    case PokitProduct::PokitMeter: return QStringLiteral("Pokit Meter");
    case PokitProduct::PokitPro:   return QStringLiteral("Pokit Pro");
    }
    qCWarning(lc).noquote() << QCoreApplication::translate("PokitProducts",
        "Unknown PokitProduct value: %1", "toString").arg((int)product);
    return QString();
}
References QString::arg(), PokitMeter, PokitPro, and QCoreApplication::translate().
Referenced by AbstractPokitServicePrivate::createServiceObject(), and DeviceCommand::deviceDiscovered().