var searchData=
[
  ['generate_0',['generate',['https://doc.qt.io/qt-5/qrandomgenerator.html#generate',1,'QRandomGenerator::generate()'],['https://doc.qt.io/qt-5/qrandomgenerator.html#generate-1',1,'QRandomGenerator::generate(ForwardIterator begin, ForwardIterator end)'],['https://doc.qt.io/qt-5/qrandomgenerator64.html#generate',1,'QRandomGenerator64::generate()']]],
  ['generate64_1',['generate64',['https://doc.qt.io/qt-5/qrandomgenerator.html#generate64',1,'QRandomGenerator']]],
  ['generatebyteordermark_2',['generateByteOrderMark',['https://doc.qt.io/qt-5/qtextstream.html#generateByteOrderMark',1,'QTextStream']]],
  ['generatedouble_3',['generateDouble',['https://doc.qt.io/qt-5/qrandomgenerator.html#generateDouble',1,'QRandomGenerator']]],
  ['genericaccess_4',['genericAccess',['../classPokitDevice.html#a226ebf9d65326afc3b2b8413c48412df',1,'PokitDevice::genericAccess()'],['../classPokitDevicePrivate.html#a9ee2bfe1547ebd2ab6b5929fed66e2e8',1,'PokitDevicePrivate::genericAccess()']]],
  ['genericaccessmutex_5',['genericAccessMutex',['../classPokitDevicePrivate.html#abc74b961e879309c59bc715e4dde7b75',1,'PokitDevicePrivate']]],
  ['genericaccessservice_6',['GenericAccessService',['../classGenericAccessService.html',1,'GenericAccessService'],['../classGenericAccessService.html#a983e2e33cdad3fcc8358f7e2f23cf1eb',1,'GenericAccessService::GenericAccessService(GenericAccessServicePrivate *const d, QObject *const parent)'],['../classGenericAccessService.html#a999e940bd5a049f384308a542dfe58c7',1,'GenericAccessService::GenericAccessService(QLowEnergyController *const pokitDevice, QObject *parent=nullptr)']]],
  ['genericaccessservice_2ecpp_7',['genericaccessservice.cpp',['../genericaccessservice_8cpp.html',1,'']]],
  ['genericaccessservice_2eh_8',['genericaccessservice.h',['../genericaccessservice_8h.html',1,'']]],
  ['genericaccessservice_5fp_2eh_9',['genericaccessservice_p.h',['../genericaccessservice__p_8h.html',1,'']]],
  ['genericaccessserviceprivate_10',['GenericAccessServicePrivate',['../classGenericAccessServicePrivate.html',1,'GenericAccessServicePrivate'],['../classGenericAccessServicePrivate.html#a654cf6dc58a82b2fa75cf735b2310181',1,'GenericAccessServicePrivate::GenericAccessServicePrivate()']]],
  ['genericiconname_11',['genericIconName',['https://doc.qt.io/qt-5/qmimetype.html#genericIconName-prop',1,'QMimeType::genericIconName()'],['https://doc.qt.io/qt-5/qmimetype.html#genericIconName-prop',1,'QMimeType::genericIconName() const const']]],
  ['gestureflags_12',['GestureFlags',['https://doc.qt.io/qt-5/qt.html#GestureFlag-enum',1,'Qt']]],
  ['get_13',['get',['https://doc.qt.io/qt-5/qsharedpointer.html#get',1,'QSharedPointer::get()'],['https://doc.qt.io/qt-5/qscopedpointer.html#get',1,'QScopedPointer::get()']]],
  ['getchar_14',['getChar',['https://doc.qt.io/qt-5/qiodevice.html#getChar',1,'QIODevice']]],
  ['getcharacteristic_15',['getCharacteristic',['../classAbstractPokitServicePrivate.html#aaac3ef8e3590334acdddb2b029865eb0',1,'AbstractPokitServicePrivate']]],
  ['getcoords_16',['getCoords',['https://doc.qt.io/qt-5/qrectf.html#getCoords',1,'QRectF::getCoords()'],['https://doc.qt.io/qt-5/qrect.html#getCoords',1,'QRect::getCoords()']]],
  ['getdate_17',['getDate',['https://doc.qt.io/qt-5/qdate.html#getDate',1,'QDate']]],
  ['getlockinfo_18',['getLockInfo',['https://doc.qt.io/qt-5/qlockfile.html#getLockInfo',1,'QLockFile']]],
  ['getrect_19',['getRect',['https://doc.qt.io/qt-5/qrectf.html#getRect',1,'QRectF::getRect()'],['https://doc.qt.io/qt-5/qrect.html#getRect',1,'QRect::getRect()']]],
  ['getservice_20',['getService',['../classCalibrationCommand.html#a71393e39586f7b84d196880dbc3c8c59',1,'CalibrationCommand::getService()'],['../classStatusCommand.html#abeff2e017b4c34cfab1c55addc776a09',1,'StatusCommand::getService()'],['../classSetNameCommand.html#ac57aeeca51642c3ba79e6c6578677210',1,'SetNameCommand::getService()'],['../classInfoCommand.html#a5a6f572882374077b39769b794fe7449',1,'InfoCommand::getService()'],['../classDeviceCommand.html#a8f890b3a7389d158ad8fd06aa54035b3',1,'DeviceCommand::getService()'],['../classFlashLedCommand.html#ae36389ece2050dd8546c5b379df942a9',1,'FlashLedCommand::getService()'],['../classMultimeterCommand.html#a8f76fdaec093abb2aae454bc7e5a8993',1,'MultimeterCommand::getService()']]],
  ['global_21',['global',['https://doc.qt.io/qt-5/qrandomgenerator.html#global',1,'QRandomGenerator']]],
  ['globalinstance_22',['globalInstance',['https://doc.qt.io/qt-5/qthreadpool.html#globalInstance',1,'QThreadPool']]],
  ['globalmatch_23',['globalMatch',['https://doc.qt.io/qt-5/qregularexpression.html#globalMatch',1,'QRegularExpression::globalMatch(const QString &amp;subject, int offset, QRegularExpression::MatchType matchType, QRegularExpression::MatchOptions matchOptions) const const'],['https://doc.qt.io/qt-5/qregularexpression.html#globalMatch-1',1,'QRegularExpression::globalMatch(const QStringRef &amp;subjectRef, int offset, QRegularExpression::MatchType matchType, QRegularExpression::MatchOptions matchOptions) const const']]],
  ['globalrestorepolicy_24',['globalRestorePolicy',['https://doc.qt.io/qt-5/qstatemachine.html#globalRestorePolicy-prop',1,'QStateMachine::globalRestorePolicy()'],['https://doc.qt.io/qt-5/qstatemachine.html#globalRestorePolicy',1,'QStateMachine::globalRestorePolicy() const const']]],
  ['globpatterns_25',['globPatterns',['https://doc.qt.io/qt-5/qmimetype.html#globPatterns-prop',1,'QMimeType::globPatterns()'],['https://doc.qt.io/qt-5/qmimetype.html#globPatterns-prop',1,'QMimeType::globPatterns() const const']]],
  ['good_26',['Good',['../classStatusService.html#a26ca2c6e0c1127261cc28a778512bf68a0c6ad70beb3a7e76c3fc7adab7c46acc',1,'StatusService']]],
  ['group_27',['group',['https://doc.qt.io/qt-5/qabstractanimation.html#group',1,'QAbstractAnimation::group()'],['https://doc.qt.io/qt-5/qfileinfo.html#group',1,'QFileInfo::group()'],['https://doc.qt.io/qt-5/qsettings.html#group',1,'QSettings::group()']]],
  ['groupid_28',['groupId',['https://doc.qt.io/qt-5/qfileinfo.html#groupId',1,'QFileInfo']]],
  ['groupseparator_29',['groupSeparator',['https://doc.qt.io/qt-5/qlocale.html#groupSeparator',1,'QLocale']]]
];
