QtPokit: DsoCommand Class Reference
DsoCommand Class Reference
The DsoCommand class implements the dso CLI command.
Public Slots
QStringList processOptions (const QCommandLineParser &parser) override
Processes the relevant options from the command line parser.
Public Slots inherited from DeviceCommand
bool start () override
Begins scanning for the Pokit device.
Public Slots inherited from AbstractCommand
virtual QStringList processOptions (const QCommandLineParser &parser)
Processes the relevant options from the command line parser.
virtual bool start ()=0
Begins the functionality of this command, and returns true if begun successfully, false otherwise.
Public Member Functions
DsoCommand (QObject *const parent)
Construct a new DsoCommand object with parent.
QStringList requiredOptions (const QCommandLineParser &parser) const override
Returns a list of CLI option names required by this command.
QStringList supportedOptions (const QCommandLineParser &parser) const override
Returns a list of CLI option names supported by this command.
Public Member Functions inherited from DeviceCommand
DeviceCommand (QObject *const parent)
Construct a new DeviceCommand object with parent.
Public Member Functions inherited from AbstractCommand
AbstractCommand (QObject *const parent)
Constructs a new command with parent.
virtual QStringList requiredOptions (const QCommandLineParser &parser) const
Returns a list of CLI option names required by this command.
virtual QStringList supportedOptions (const QCommandLineParser &parser) const
Returns a list of CLI option names supported by this command.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
virtual void * qt_metacast (const char *)
virtual int qt_metacall (QMetaObject::Call, int, void **)
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Protected Slots
void serviceDetailsDiscovered () override
Handles service detail discovery events.
Protected Slots inherited from DeviceCommand
virtual void controllerError (const QLowEnergyController::Error error)
Handles controller error events.
virtual void deviceDisconnected ()
Handles devics disconnection events.
virtual void serviceError (const QLowEnergyService::ServiceError error)
Handles service error events.
virtual void serviceDetailsDiscovered ()
Handles service detail discovery events.
Protected Slots inherited from AbstractCommand
virtual void deviceDiscovered (const QBluetoothDeviceInfo &info)=0
Handles PokitDiscoveryAgent::pokitDeviceDiscovered signal.
virtual void deviceDiscoveryFinished ()=0
Handles PokitDiscoveryAgent::deviceDiscoveryFinished signal.
Protected Member Functions
AbstractPokitService * getService () override
Returns a Pokit service object for the derived command class.
Protected Member Functions inherited from DeviceCommand
void disconnect (int exitCode=EXIT_SUCCESS)
Disconnects the underlying Pokit device, and sets exitCode to be return to the OS once the disconnection has taken place.
virtual AbstractPokitService * getService ()=0
Returns a Pokit service object for the derived command class.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Private Slots
void settingsWritten ()
Invoked when the DSO settings have been written.
void metadataRead (const DsoService::Metadata &metadata)
Invoked when metadata has been received from the DSO.
void outputSamples (const DsoService::Samples &samples)
Outputs DSO samples in the selected ouput format.
Static Private Member Functions
static DsoService::Range lowestRange (const DsoService::Mode mode, const quint32 desiredMax)
Returns the lowest mode range that can measure at least up to desired max, or AutoRange if no such range is available.
static DsoService::CurrentRange lowestCurrentRange (const quint32 desiredMax)
Returns the lowest current range that can measure at least up to desired max, or AutoRange if no such range is available.
static DsoService::VoltageRange lowestVoltageRange (const quint32 desiredMax)
Returns the lowest voltage range that can measure at least up to desired max, or AutoRange if no such range is available.
Private Attributes
DsoService * service
Bluetooth service this command interracts with.
DsoService::Settings settings
Settings for the Pokit device's DSO mode.
DsoService::Metadata metadata
Most recent DSO metadata.
qint32 samplesToGo
Number of samples we're expecting in the current window.
bool showCsvHeader
Whether or not to show a header as the first line of CSV output.
Friends
class TestDsoCommand
Additional Inherited Members
Public Types inherited from AbstractCommand
enum class OutputFormat { Csv , Json , Text }
Supported output formats.
Static Public Member Functions inherited from AbstractCommand
static QString escapeCsvField (const QString &field)
Returns an RFC 4180 compliant version of field.
static quint32 parseMicroValue (const QString &value, const QString &unit, const quint32 sensibleMinimum=0)
Returns value as a number of micros, such as microseconds, or microvolts.
static quint32 parseMilliValue (const QString &value, const QString &unit, const quint32 sensibleMinimum=0)
Returns value as a number of millis, such as milliseconds, or millivolts.
static quint32 parseWholeValue (const QString &value, const QString &unit)
Returns value as a number, with optional SI unit prefix, and optional unit suffix.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Static Protected Member Functions inherited from AbstractCommand
static Q_LOGGING_CATEGORY (lc, "pokit.ui.command", QtInfoMsg)
Logging category for UI commands.
Protected Attributes inherited from DeviceCommand
PokitDevice * device
Pokit Bluetooth device (if any) this command inerracts with.
int exitCodeOnDisconnect
Exit code to return on device disconnection.
Protected Attributes inherited from AbstractCommand
QString deviceToScanFor
Device (if any) that were passed to processOptions().
PokitDiscoveryAgent * discoveryAgent
Agent for Pokit device descovery.
OutputFormat format
Selected output format.
Properties inherited from QObject
objectName
Detailed Description
The DsoCommand class implements the dso CLI command.
Definition at line 8 of file dsocommand.h.
Constructor & Destructor Documentation
DsoCommand()
DsoCommand::DsoCommand (QObject *const parent) explicit
Construct a new DsoCommand object with parent.
Definition at line 22 of file dsocommand.cpp.
                                             : DeviceCommand(parent),
    service(nullptr), settings{
        DsoService::Command::FreeRunning, 0.0f, DsoService::Mode::DcVoltage,
        DsoService::VoltageRange::_30V_to_60V, 1000*1000, 1000}, showCsvHeader(true)
{
}
Member Function Documentation
getService()
AbstractPokitService * DsoCommand::getService () override protected virtual
Returns a Pokit service object for the derived command class.
This override returns a pointer to a DsoService object.
Implements DeviceCommand.
Definition at line 166 of file dsocommand.cpp.
{
    Q_ASSERT(device);
    if (!service) {
        service = device->dso();
        Q_ASSERT(service);
        connect(service, &DsoService::settingsWritten,
                this, &DsoCommand::settingsWritten);
    }
    return service;
}
References QObject::connect(), DeviceCommand::device, PokitDevice::dso(), service, DsoService::settingsWritten(), and settingsWritten().
lowestCurrentRange()
DsoService::CurrentRange DsoCommand::lowestCurrentRange (const quint32 desiredMax) static private
Returns the lowest current range that can measure at least up to desired max, or AutoRange if no such range is available.
Definition at line 227 of file dsocommand.cpp.
{
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, CurrentRange::_0_to_10mA)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, CurrentRange::_10mA_to_30mA)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, CurrentRange::_30mA_to_150mA)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, CurrentRange::_150mA_to_300mA)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, CurrentRange::_300mA_to_3A)
    return DsoService::CurrentRange::_300mA_to_3A; // Out of range, so go with the biggest.
}
References DsoService::_300mA_to_3A.
Referenced by lowestRange().
lowestRange()
DsoService::Range DsoCommand::lowestRange (const DsoService::Mode mode, const quint32 desiredMax) static private
Returns the lowest mode range that can measure at least up to desired max, or AutoRange if no such range is available.
Definition at line 197 of file dsocommand.cpp.
{
    switch (mode) {
    case DsoService::Mode::Idle:
        qCWarning(lc).noquote() << tr("Idle has no defined ranges.");
        Q_ASSERT(false); // Should never have been called with this Idle mode.
        break;
    case DsoService::Mode::DcVoltage:
    case DsoService::Mode::AcVoltage:
        return lowestVoltageRange(desiredMax);
    case DsoService::Mode::DcCurrent:
    case DsoService::Mode::AcCurrent:
        return lowestCurrentRange(desiredMax);
    default:
        qCWarning(lc).noquote() << tr("No defined ranges for mode %1.").arg((quint8)mode);
        Q_ASSERT(false); // Should never have been called with this invalid mode.
    }
    return DsoService::Range();
}
References DsoService::AcCurrent, DsoService::AcVoltage, QString::arg(), DsoService::DcCurrent, DsoService::DcVoltage, DsoService::Idle, lowestCurrentRange(), lowestVoltageRange(), and QObject::tr().
Referenced by processOptions().
lowestVoltageRange()
DsoService::VoltageRange DsoCommand::lowestVoltageRange (const quint32 desiredMax) static private
Returns the lowest voltage range that can measure at least up to desired max, or AutoRange if no such range is available.
Definition at line 241 of file dsocommand.cpp.
{
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_0_to_300mV)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_300mV_to_2V)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_2V_to_6V)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_6V_to_12V)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_12V_to_30V)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_30V_to_60V)
    return DsoService::VoltageRange::_30V_to_60V; // Out of range, so go with the biggest.
}
References DsoService::_30V_to_60V.
Referenced by lowestRange().
metadataRead
void DsoCommand::metadataRead (const DsoService::Metadata & metadata) private slot
Invoked when metadata has been received from the DSO.
Definition at line 270 of file dsocommand.cpp.
{
    qCDebug(lc) << "status:" << (int)(metadata.status);
    qCDebug(lc) << "scale:" << metadata.scale;
    qCDebug(lc) << "mode:" << DsoService::toString(metadata.mode);
    qCDebug(lc) << "range:" << DsoService::toString(metadata.range.voltageRange);
    qCDebug(lc) << "samplingWindow:" << (int)metadata.samplingWindow;
    qCDebug(lc) << "numberOfSamples:" << metadata.numberOfSamples;
    qCDebug(lc) << "samplingRate:" << metadata.samplingRate << "Hz";
    this->metadata = metadata;
    this->samplesToGo = metadata.numberOfSamples;
}
References metadata, DsoService::Metadata::mode, DsoService::Metadata::numberOfSamples, DsoService::Metadata::range, samplesToGo, DsoService::Metadata::samplingRate, DsoService::Metadata::samplingWindow, DsoService::Metadata::scale, DsoService::Metadata::status, DsoService::toString(), and DsoService::Range::voltageRange.
Referenced by settingsWritten().
outputSamples
void DsoCommand::outputSamples (const DsoService::Samples & samples) private slot
Outputs DSO samples in the selected ouput format.
Definition at line 286 of file dsocommand.cpp.
{
    QString unit;
    switch (metadata.mode) {
    case DsoService::Mode::DcVoltage: unit = QLatin1String("Vdc"); break;
    case DsoService::Mode::AcVoltage: unit = QLatin1String("Vac"); break;
    case DsoService::Mode::DcCurrent: unit = QLatin1String("Adc"); break;
    case DsoService::Mode::AcCurrent: unit = QLatin1String("Aac"); break;
    default:
        qCDebug(lc).noquote() << tr("No known unit for mode %1 \"%2\".").arg((int)metadata.mode)
            .arg(DsoService::toString(metadata.mode));
    }
    const QString range = DsoService::toString(metadata.range, metadata.mode);
    for (const qint16 &sample: samples) {
        static int sampleNumber = 0; ++sampleNumber;
        const float value = sample * metadata.scale;
        switch (format) {
        case OutputFormat::Csv:
            for (; showCsvHeader; showCsvHeader = false) {
                std::cout << qUtf8Printable(tr("sample_number,value,unit,range\n"));
            }
            std::cout << qUtf8Printable(QString::fromLatin1("%1,%2,%3,%4\n")
                .arg(sampleNumber).arg(value).arg(unit, range));
            break;
        case OutputFormat::Json:
            std::cout << QJsonDocument(QJsonObject{
                    { QLatin1String("value"),  value },
                    { QLatin1String("unit"),   unit },
                    { QLatin1String("range"),  range },
                    { QLatin1String("mode"),   DsoService::toString(metadata.mode) },
                }).toJson().toStdString();
            break;
        case OutputFormat::Text:
            std::cout << qUtf8Printable(tr("%1 %2 %3\n").arg(sampleNumber).arg(value).arg(unit));
            break;
        }
        --samplesToGo;
    }
    if (samplesToGo <= 0) {
        qCInfo(lc).noquote() << tr("Finished fetching %L1 samples (with %L3 to remaining).")
            .arg(metadata.numberOfSamples).arg(samplesToGo);
        if (device) disconnect(); // Will exit the application once disconnected.
    }
}
References DsoService::AcCurrent, DsoService::AcVoltage, QString::arg(), AbstractCommand::Csv, DsoService::DcCurrent, DsoService::DcVoltage, DeviceCommand::device, DeviceCommand::disconnect(), AbstractCommand::format, QString::fromLatin1(), AbstractCommand::Json, metadata, DsoService::Metadata::mode, DsoService::Metadata::numberOfSamples, DsoService::Metadata::range, samplesToGo, DsoService::Metadata::scale, showCsvHeader, AbstractCommand::Text, DsoService::toString(), and QObject::tr().
Referenced by settingsWritten().
processOptions
QStringList DsoCommand::processOptions (const QCommandLineParser & parser) override slot
Processes the relevant options from the command line parser.
This implementation extends DeviceCommand::processOptions to process additional CLI options supported (or required) by this command.
Definition at line 54 of file dsocommand.cpp.
{
    QStringList errors = DeviceCommand::processOptions(parser);
    if (!errors.isEmpty()) {
        return errors;
    }
    // Parse the (required) mode option.
    const QString mode = parser.value(QLatin1String("mode")).trimmed().toLower();
    if (mode.startsWith(QLatin1String("ac v")) || mode.startsWith(QLatin1String("vac"))) {
        settings.mode = DsoService::Mode::AcVoltage;
    } else if (mode.startsWith(QLatin1String("dc v")) || mode.startsWith(QLatin1String("vdc"))) {
        settings.mode = DsoService::Mode::DcVoltage;
    } else if (mode.startsWith(QLatin1String("ac c")) || mode.startsWith(QLatin1String("aac"))) {
        settings.mode = DsoService::Mode::AcCurrent;
    } else if (mode.startsWith(QLatin1String("dc c")) || mode.startsWith(QLatin1String("adc"))) {
        settings.mode = DsoService::Mode::DcCurrent;
    } else {
        errors.append(tr("Unknown DSO mode: %1").arg(parser.value(QLatin1String("mode"))));
        return errors;
    }
    // Parse the (required) range option.
    QString unit;
    {
        const QString value = parser.value(QLatin1String("range"));
        quint32 sensibleMinimum = 0;
        switch (settings.mode) {
        case DsoService::Mode::Idle:
            Q_ASSERT(false); // Not possible, since the mode parsing above never allows Idle.
            break;
        case DsoService::Mode::DcVoltage:
        case DsoService::Mode::AcVoltage:
            unit = QLatin1String("V");
            sensibleMinimum = 50; // mV.
            break;
        case DsoService::Mode::DcCurrent:
        case DsoService::Mode::AcCurrent:
            unit = QLatin1String("A");
            sensibleMinimum = 5; // mA.
            break;
        }
        Q_ASSERT(!unit.isEmpty());
        const quint32 rangeMax = parseMilliValue(value, unit, sensibleMinimum);
        if (rangeMax == 0) {
            errors.append(tr("Invalid range value: %1").arg(value));
        } else {
            settings.range = lowestRange(settings.mode, rangeMax);
        }
    }
    // Parse the trigger-level option.
    if (parser.isSet(QLatin1String("trigger-level"))) {
        const QString value = parser.value(QLatin1String("trigger-level"));
        const quint32 level = parseMicroValue(value, unit);
        if (level == 0) {
            errors.append(tr("Invalid trigger-level value: %1").arg(value));
        } else {
            settings.triggerLevel = level/1000.0/1000.0;
        }
    }
    // Parse the trigger-mode option.
    if (parser.isSet(QLatin1String("trigger-mode"))) {
        const QString triggerMode = parser.value(QLatin1String("trigger-mode")).trimmed().toLower();
        if (triggerMode.startsWith(QLatin1String("free"))) {
            settings.command = DsoService::Command::FreeRunning;
        } else if (triggerMode.startsWith(QLatin1String("ris"))) {
           settings.command = DsoService::Command::RisingEdgeTrigger;
        } else if (triggerMode.startsWith(QLatin1String("fall"))) {
            settings.command = DsoService::Command::FallingEdgeTrigger;
        } else {
            errors.append(tr("Unknown trigger mode: %1").arg(
                parser.value(QLatin1String("trigger-mode"))));
        }
    }
    // Ensure that if either trigger option is present, then both are.
    if (parser.isSet(QLatin1String("trigger-level")) !=
        parser.isSet(QLatin1String("trigger-mode"))) {
        errors.append(tr("If either option is provided, then both must be: trigger-level, trigger-mode"));
    }
    // Parse the interval option.
    if (parser.isSet(QLatin1String("interval"))) {
        const QString value = parser.value(QLatin1String("interval"));
        const quint32 interval = parseMicroValue(value, QLatin1String("s"), 500*1000);
        if (interval == 0) {
            errors.append(tr("Invalid interval value: %1").arg(value));
        } else {
            settings.samplingWindow = interval;
        }
    }
    // Parse the samples option.
    if (parser.isSet(QLatin1String("samples"))) {
        const QString value = parser.value(QLatin1String("samples"));
        const quint32 samples = parseWholeValue(value, QLatin1String("S"));
        if (samples == 0) {
            errors.append(tr("Invalid samples value: %1").arg(value));
        } else {
            settings.numberOfSamples = samples;
        }
    }
    return errors;
}
References DsoService::AcCurrent, DsoService::AcVoltage, QList::append(), DsoService::Settings::command, DsoService::DcCurrent, DsoService::DcVoltage, DsoService::Idle, QString::isEmpty(), QList::isEmpty(), QCommandLineParser::isSet(), lowestRange(), DsoService::Settings::mode, DsoService::Settings::numberOfSamples, AbstractCommand::parseMicroValue(), AbstractCommand::parseMilliValue(), AbstractCommand::parseWholeValue(), AbstractCommand::processOptions(), DsoService::Settings::range, DsoService::Settings::samplingWindow, settings, QString::startsWith(), QString::toLower(), QObject::tr(), DsoService::Settings::triggerLevel, QString::trimmed(), and QCommandLineParser::value().
requiredOptions()
QStringList DsoCommand::requiredOptions (const QCommandLineParser & parser) const override virtual
Returns a list of CLI option names required by this command.
The main console appication may use this list to output an eror (and exit) if any of the returned names are not found in the parsed CLI options.
The (already parsed) parser may be used adjust the returned required options depending on the value of other options. For example, the logger command only requires the --mode option if the --command option is start.
This base implementation simply returns an empty list. Derived classes should override this function to include any required options.
Reimplemented from AbstractCommand.
Definition at line 30 of file dsocommand.cpp.
{
    return DeviceCommand::requiredOptions(parser) + QStringList{
        QLatin1String("mode"),
        QLatin1String("range"),
    };
}
References AbstractCommand::requiredOptions().
serviceDetailsDiscovered
void DsoCommand::serviceDetailsDiscovered () override protected slot
Handles service detail discovery events.
This override fetches the current device's status, and outputs it in the selected format.
Definition at line 183 of file dsocommand.cpp.
{
    DeviceCommand::serviceDetailsDiscovered(); // Just logs consistently.
    const QString range = DsoService::toString(settings.range, settings.mode);
    qCInfo(lc).noquote() << tr("Sampling %1, with range %2, %L3 samples over %L4us").arg(
        DsoService::toString(settings.mode), (range.isNull()) ? QString::fromLatin1("N/A") : range)
        .arg(settings.numberOfSamples).arg(settings.samplingWindow);
    service->setSettings(settings);
}
References QString::arg(), QString::fromLatin1(), QString::isNull(), DsoService::Settings::mode, DsoService::Settings::numberOfSamples, DsoService::Settings::range, DsoService::Settings::samplingWindow, service, DeviceCommand::serviceDetailsDiscovered(), DsoService::setSettings(), settings, DsoService::toString(), and QObject::tr().
settingsWritten
void DsoCommand::settingsWritten () private slot
Invoked when the DSO settings have been written.
Definition at line 257 of file dsocommand.cpp.
{
    Q_ASSERT(service);
    qCDebug(lc).noquote() << tr("Settings written; DSO has started.");
    connect(service, &DsoService::metadataRead, this, &DsoCommand::metadataRead);
    connect(service, &DsoService::samplesRead, this, &DsoCommand::outputSamples);
    service->enableMetadataNotifications();
    service->enableReadingNotifications();
}
References QObject::connect(), DsoService::enableMetadataNotifications(), DsoService::enableReadingNotifications(), DsoService::metadataRead(), metadataRead(), outputSamples(), DsoService::samplesRead(), service, and QObject::tr().
Referenced by getService().
supportedOptions()
QStringList DsoCommand::supportedOptions (const QCommandLineParser & parser) const override virtual
Returns a list of CLI option names supported by this command.
The main console appication may use this list to output a warning for any parsed CLI options not included in the returned list.
The (already parsed) parser may be used adjust the returned supported options depending on the value of other options. For example, the logger command only supported the --timestamp option if the --command option is start.
This base implementation simply returns requiredOptions(). Derived classes should override this function to include optional options, such as:
QStringList Derived::supportedOptions(const QCommandLineParser &parser) const
{
    const QStringList list = AbstractCommand::supportedOptions(parser) + QStringList{ ... };
    list.sort();
    list.removeDuplicates(); // Optional, recommended.
    return list;
}
Reimplemented from AbstractCommand.
Definition at line 38 of file dsocommand.cpp.
{
    return DeviceCommand::supportedOptions(parser) + QStringList{
        QLatin1String("interval"),
        QLatin1String("samples"),
        QLatin1String("trigger-level"),
        QLatin1String("trigger-mode"),
    };
}
References AbstractCommand::supportedOptions().
Friends And Related Function Documentation
TestDsoCommand
friend class TestDsoCommand friend
Definition at line 42 of file dsocommand.h.
Member Data Documentation
metadata
DsoService::Metadata DsoCommand::metadata private
Most recent DSO metadata.
Definition at line 28 of file dsocommand.h.
Referenced by metadataRead(), and outputSamples().
samplesToGo
qint32 DsoCommand::samplesToGo private
Number of samples we're expecting in the current window.
Definition at line 29 of file dsocommand.h.
Referenced by metadataRead(), and outputSamples().
service
DsoService* DsoCommand::service private
Bluetooth service this command interracts with.
Definition at line 26 of file dsocommand.h.
Referenced by getService(), serviceDetailsDiscovered(), and settingsWritten().
settings
DsoService::Settings DsoCommand::settings private
Settings for the Pokit device's DSO mode.
Definition at line 27 of file dsocommand.h.
Referenced by processOptions(), and serviceDetailsDiscovered().
showCsvHeader
bool DsoCommand::showCsvHeader private
Whether or not to show a header as the first line of CSV output.
Definition at line 30 of file dsocommand.h.
Referenced by outputSamples().
The documentation for this class was generated from the following files:
dsocommand.h
dsocommand.cpp