Dokit: LoggerFetchCommand Class Reference
LoggerFetchCommand Class Reference
The LoggerFetchCommand class implements the logger CLI command.
Public Member Functions
LoggerFetchCommand (QObject *const parent=nullptr)
Construct a new LoggerFetchCommand object with parent.
Public Member Functions inherited from DeviceCommand
DeviceCommand (QObject *const parent=nullptr)
Construct a new DeviceCommand object with parent.
Public Member Functions inherited from AbstractCommand
AbstractCommand (QObject *const parent=nullptr)
Constructs a new command with parent.
virtual QStringList requiredOptions (const QCommandLineParser &parser) const
Returns a list of CLI option names required by this command.
virtual QStringList supportedOptions (const QCommandLineParser &parser) const
Returns a list of CLI option names supported by this command.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Protected Slots
void serviceDetailsDiscovered () override
Handles service detail discovery events.
Protected Slots inherited from DeviceCommand
virtual void controllerError (const QLowEnergyController::Error error)
Handles controller error events.
virtual void deviceDisconnected ()
Handles devics disconnection events.
virtual void serviceError (const QLowEnergyService::ServiceError error)
Handles service error events.
virtual void serviceDetailsDiscovered ()
Handles service detail discovery events.
Protected Slots inherited from AbstractCommand
virtual void deviceDiscovered (const QBluetoothDeviceInfo &info)=0
Handles PokitDiscoveryAgent::pokitDeviceDiscovered signal.
virtual void deviceDiscoveryFinished ()=0
Handles PokitDiscoveryAgent::deviceDiscoveryFinished signal.
Protected Member Functions
AbstractPokitService * getService () override
Returns a Pokit service object for the derived command class.
Protected Member Functions inherited from DeviceCommand
void disconnect (int exitCode=EXIT_SUCCESS)
Disconnects the underlying Pokit device, and sets exitCode to be return to the OS once the disconnection has taken place.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Private Slots
void metadataRead (const DataLoggerService::Metadata &data)
Invoked when metadata has been received from the data logger.
void outputSamples (const DataLoggerService::Samples &samples)
Outputs logger samples in the selected ouput format.
Private Attributes
DataLoggerService * service { nullptr }
Bluetooth service this command interracts with.
DataLoggerService::Metadata metadata
Most recent data logging metadata.
qint32 samplesToGo { 0 }
Number of samples we're still expecting to receive.
quint64 timestamp { 0 }
Current sample's epoch milliseconds timestamp.
bool showCsvHeader { true }
Whether or not to show a header as the first line of CSV output.
Friends
class TestLoggerFetchCommand
Additional Inherited Members
Public Types inherited from AbstractCommand
enum class OutputFormat { Csv , Json , Text }
Supported output formats.
Public Slots inherited from DeviceCommand
bool start () override
Begins scanning for the Pokit device.
Public Slots inherited from AbstractCommand
virtual QStringList processOptions (const QCommandLineParser &parser)
Processes the relevant options from the command line parser.
virtual bool start ()=0
Begins the functionality of this command, and returns true if begun successfully, false otherwise.
Static Public Member Functions inherited from AbstractCommand
static QString escapeCsvField (const QString &field)
Returns an RFC 4180 compliant version of field.
template<typename R >
static quint32 parseNumber (const QString &value, const QString &unit, const quint32 sensibleMinimum=0)
Returns value as an integer multiple of the ratio R.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Static Protected Member Functions inherited from DeviceCommand
template<typename T >
static T minRange (const quint32 maxValue)
static quint8 minCapacitanceRange (const PokitProduct product, const quint32 maxValue)
Returns the product's lowest capacitance range that can measure at least up to maxValue (nF), or AutoRange if no such range is available.
static quint8 minCurrentRange (const PokitProduct product, const quint32 maxValue)
Returns the product's lowest current range that can measure at least up to maxValue (A), or AutoRange if no such range is available.
static quint8 minResistanceRange (const PokitProduct product, const quint32 maxValue)
Returns the product's lowest resistance range that can measure at least up to maxValue (), or AutoRange if no such range is available.
static quint8 minVoltageRange (const PokitProduct product, const quint32 maxValue)
t Returns the product's lowest voltage range that can measure at least up to maxValue (mV), or AutoRange if no such range is available.
Static Protected Member Functions inherited from AbstractCommand
static Q_LOGGING_CATEGORY (lc, "dokit.cli.command", QtInfoMsg)
Logging category for UI commands.
Protected Attributes inherited from DeviceCommand
PokitDevice * device { nullptr }
Pokit Bluetooth device (if any) this command inerracts with.
int exitCodeOnDisconnect { EXIT_FAILURE }
Exit code to return on device disconnection.
Protected Attributes inherited from AbstractCommand
QString deviceToScanFor
Device (if any) that were passed to processOptions().
PokitDiscoveryAgent * discoveryAgent
Agent for Pokit device descovery.
OutputFormat format { OutputFormat::Text }
Selected output format.
Properties inherited from QObject
objectName
Detailed Description
The LoggerFetchCommand class implements the logger CLI command.
Definition at line 8 of file loggerfetchcommand.h.
Constructor & Destructor Documentation
LoggerFetchCommand()
LoggerFetchCommand::LoggerFetchCommand (QObject *const parent = nullptr) explicit
Construct a new LoggerFetchCommand object with parent.
Definition at line 32 of file loggerfetchcommand.cpp.
                                                             : DeviceCommand(parent)
{
}
Member Function Documentation
getService()
AbstractPokitService * LoggerFetchCommand::getService () override protected virtual
Returns a Pokit service object for the derived command class.
This override returns a pointer to a DataLoggerService object.
Implements DeviceCommand.
Definition at line 42 of file loggerfetchcommand.cpp.
{
    Q_ASSERT(device);
    if (!service) {
        service = device->dataLogger();
        Q_ASSERT(service);
        connect(service, &DataLoggerService::metadataRead, this, &LoggerFetchCommand::metadataRead);
        connect(service, &DataLoggerService::samplesRead, this, &LoggerFetchCommand::outputSamples);
    }
    return service;
}
References QObject::connect(), PokitDevice::dataLogger(), DeviceCommand::device, metadataRead(), DataLoggerService::metadataRead(), outputSamples(), DataLoggerService::samplesRead(), and service.
metadataRead
void LoggerFetchCommand::metadataRead (const DataLoggerService::Metadata & data) private slot
Invoked when metadata has been received from the data logger.
Definition at line 71 of file loggerfetchcommand.cpp.
{
    qCDebug(lc) << "status:"          << (int)(data.status);
    qCDebug(lc) << "scale:"           << data.scale;
    qCDebug(lc) << "mode:"            << DataLoggerService::toString(data.mode) << (quint8)data.mode;
    qCDebug(lc) << "range:"           << service->toString(data.range, data.mode) << data.range;
    qCDebug(lc) << "updateInterval:"  << (int)data.updateInterval;
    qCDebug(lc) << "numberOfSamples:" << data.numberOfSamples;
    qCDebug(lc) << "timestamp:"       << data.timestamp << QDateTime::fromSecsSinceEpoch(data.timestamp, DOKIT_QT_UTC);
    this->metadata = data;
    this->samplesToGo = data.numberOfSamples;
    this->timestamp = (quint64)data.timestamp * (quint64)1000;
    qCInfo(lc).noquote() << tr("Fetching %Ln logger sample/s...", nullptr, data.numberOfSamples);
}
References QDateTime::fromSecsSinceEpoch(), metadata, DataLoggerService::Metadata::mode, DataLoggerService::Metadata::numberOfSamples, DataLoggerService::Metadata::range, samplesToGo, DataLoggerService::Metadata::scale, service, DataLoggerService::Metadata::status, DataLoggerService::Metadata::timestamp, timestamp, DataLoggerService::toString(), QObject::tr(), and DataLoggerService::Metadata::updateInterval.
Referenced by getService().
outputSamples
void LoggerFetchCommand::outputSamples (const DataLoggerService::Samples & samples) private slot
Outputs logger samples in the selected ouput format.
Definition at line 89 of file loggerfetchcommand.cpp.
{
    QString unit;
    switch (metadata.mode) {
    case DataLoggerService::Mode::DcVoltage: unit = QLatin1String("Vdc"); break;
    case DataLoggerService::Mode::AcVoltage: unit = QLatin1String("Vac"); break;
    case DataLoggerService::Mode::DcCurrent: unit = QLatin1String("Adc"); break;
    case DataLoggerService::Mode::AcCurrent: unit = QLatin1String("Aac"); break;
    case DataLoggerService::Mode::Temperature: unit = QString::fromUtf8("C"); break;
    default:
        qCDebug(lc).noquote() << tr(R"(No known unit for mode %1 "%2".)").arg((int)metadata.mode)
            .arg(DataLoggerService::toString(metadata.mode));
    }
    const QString range = service->toString(metadata.range, metadata.mode);
    for (const qint16 &sample: samples) {
        const QString timeString = (metadata.timestamp == 0) ? QString::number(timestamp)
            : QDateTime::fromMSecsSinceEpoch(timestamp, DOKIT_QT_UTC).toString(Qt::ISODateWithMs);
        const float value = sample * metadata.scale;
        switch (format) {
        case OutputFormat::Csv:
            for (; showCsvHeader; showCsvHeader = false) {
                std::cout << qUtf8Printable(tr("timestamp,value,unit,range\n"));
            }
            std::cout << qUtf8Printable(QString::fromLatin1("%1,%2,%3,%4\n")
                .arg(timeString).arg(value).arg(unit, range));
            break;
        case OutputFormat::Json: {
            QJsonObject object{
                { QLatin1String("timestamp"), timeString },
                { QLatin1String("value"),     value },
                { QLatin1String("unit"),      unit },
                { QLatin1String("mode"),      DataLoggerService::toString(metadata.mode) },
            };
            if (!range.isEmpty()) {
                object.insert(QLatin1String("range"), range);
            }
            std::cout << QJsonDocument(object).toJson().toStdString();
        }   break;
        case OutputFormat::Text:
            std::cout << qUtf8Printable(tr("%1 %2 %3\n").arg(timeString).arg(value).arg(unit));
            break;
        }
        timestamp += metadata.updateInterval;
        --samplesToGo;
    }
    if (samplesToGo <= 0) {
        qCInfo(lc).noquote() << tr("Finished fetching %Ln sample/s (with %L1 remaining).",
            nullptr, metadata.numberOfSamples).arg(samplesToGo);
        if (device) disconnect(); // Will exit the application once disconnected.
    }
}
References DataLoggerService::AcCurrent, DataLoggerService::AcVoltage, QString::arg(), AbstractCommand::Csv, DataLoggerService::DcCurrent, DataLoggerService::DcVoltage, DeviceCommand::device, DeviceCommand::disconnect(), AbstractCommand::format, QString::fromLatin1(), QDateTime::fromMSecsSinceEpoch(), QString::fromUtf8(), QString::insert(), QString::isEmpty(), Qt::ISODateWithMs, AbstractCommand::Json, metadata, DataLoggerService::Metadata::mode, QString::number(), DataLoggerService::Metadata::numberOfSamples, DataLoggerService::Metadata::range, samplesToGo, DataLoggerService::Metadata::scale, service, showCsvHeader, DataLoggerService::Temperature, AbstractCommand::Text, DataLoggerService::Metadata::timestamp, timestamp, QJsonDocument::toJson(), QByteArray::toStdString(), DataLoggerService::toString(), QDateTime::toString(), QObject::tr(), and DataLoggerService::Metadata::updateInterval.
Referenced by getService().
serviceDetailsDiscovered
void LoggerFetchCommand::serviceDetailsDiscovered () override protected slot
Handles service detail discovery events.
This override fetches the current device's status, and outputs it in the selected format.
Definition at line 59 of file loggerfetchcommand.cpp.
{
    DeviceCommand::serviceDetailsDiscovered(); // Just logs consistently.
    qCInfo(lc).noquote() << tr("Fetching logger samples...");
    service->enableMetadataNotifications();
    service->enableReadingNotifications();
    service->fetchSamples();
}
References DataLoggerService::enableMetadataNotifications(), DataLoggerService::enableReadingNotifications(), DataLoggerService::fetchSamples(), service, DeviceCommand::serviceDetailsDiscovered(), and QObject::tr().
Friends And Related Symbol Documentation
TestLoggerFetchCommand
friend class TestLoggerFetchCommand friend
Definition at line 32 of file loggerfetchcommand.h.
Member Data Documentation
metadata
DataLoggerService::Metadata LoggerFetchCommand::metadata private
Most recent data logging metadata.
Definition at line 23 of file loggerfetchcommand.h.
Referenced by metadataRead(), and outputSamples().
samplesToGo
qint32 LoggerFetchCommand::samplesToGo { 0 } private
Number of samples we're still expecting to receive.
Definition at line 24 of file loggerfetchcommand.h.
{ 0 };    ///< Number of samples we're still expecting to receive.
Referenced by metadataRead(), and outputSamples().
service
DataLoggerService* LoggerFetchCommand::service { nullptr } private
Bluetooth service this command interracts with.
Definition at line 22 of file loggerfetchcommand.h.
{ nullptr }; ///< Bluetooth service this command interracts with.
Referenced by getService(), metadataRead(), outputSamples(), and serviceDetailsDiscovered().
showCsvHeader
bool LoggerFetchCommand::showCsvHeader { true } private
Whether or not to show a header as the first line of CSV output.
Definition at line 26 of file loggerfetchcommand.h.
{ true }; ///< Whether or not to show a header as the first line of CSV output.
Referenced by outputSamples().
timestamp
quint64 LoggerFetchCommand::timestamp { 0 } private
Current sample's epoch milliseconds timestamp.
Definition at line 25 of file loggerfetchcommand.h.
{ 0 };     ///< Current sample's epoch milliseconds timestamp.
Referenced by metadataRead(), and outputSamples().
The documentation for this class was generated from the following files:
loggerfetchcommand.h
loggerfetchcommand.cpp