Dokit: AbstractPokitService Class Reference
AbstractPokitService Class Reference abstract
The AbstractPokitService class provides a common base for Pokit services classes.
Signals
void serviceDetailsDiscovered ()
This signal is emitted when the Pokit service details have been discovered.
void serviceErrorOccurred (QLowEnergyService::ServiceError newError)
This signal is emitted whenever an error occurs on the underlying QLowEnergyService.
Public Member Functions
virtual ~AbstractPokitService ()
Destroys this AbstractPokitService object.
virtual bool readCharacteristics ()=0
Read all characteristics.
bool autoDiscover () const
Returns true if autodiscovery of services and service details is enabled, false otherwise.
void setAutoDiscover (const bool discover=true)
If discover is true, autodiscovery will be attempted.
std::optional< PokitProduct > pokitProduct () const
Returns the Pokit product this service is attached to.
void setPokitProduct (const PokitProduct product)
Sets the current Pokit product.
QLowEnergyService * service ()
Returns a non-const pointer to the internal service object, if any.
const QLowEnergyService * service () const
Returns a const pointer to the internal service object, if any.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Protected Member Functions
AbstractPokitService (AbstractPokitServicePrivate *const d, QObject *const parent)
Constructs a new Pokit service with parent, and private implementation d.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Attributes
AbstractPokitServicePrivate * d_ptr
Internal d-pointer.
Friends
class TestAbstractPokitService
Additional Inherited Members
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Properties inherited from QObject
objectName
Detailed Description
The AbstractPokitService class provides a common base for Pokit services classes.
Definition at line 26 of file abstractpokitservice.h.
Constructor & Destructor Documentation
~AbstractPokitService()
AbstractPokitService::~AbstractPokitService () virtual
Destroys this AbstractPokitService object.
Definition at line 38 of file abstractpokitservice.cpp.
{
    delete d_ptr;
}
References d_ptr.
AbstractPokitService()
AbstractPokitService::AbstractPokitService (AbstractPokitServicePrivate *const d, QObject *const parent) protected
Constructs a new Pokit service with parent, and private implementation d.
Definition at line 27 of file abstractpokitservice.cpp.
    : QObject(parent), d_ptr(d)
{
}
Member Function Documentation
autoDiscover()
bool AbstractPokitService::autoDiscover () const
Returns true if autodiscovery of services and service details is enabled, false otherwise.
See also
setAutoDiscover for more information on what autodiscovery provides.
Definition at line 60 of file abstractpokitservice.cpp.
{
    Q_D(const AbstractPokitService);
    return d->autoDiscover;
}
pokitProduct()
std::optional< PokitProduct > AbstractPokitService::pokitProduct () const
Returns the Pokit product this service is attached to.
See also
setPokitProduct
Definition at line 86 of file abstractpokitservice.cpp.
{
    Q_D(const AbstractPokitService);
    return d->pokitProduct;
}
Referenced by DeviceCommand::deviceDiscovered(), DataLoggerService::maxValue(), DsoService::maxValue(), MultimeterService::maxValue(), DsoCommand::serviceDetailsDiscovered(), LoggerStartCommand::serviceDetailsDiscovered(), MeterCommand::serviceDetailsDiscovered(), DataLoggerService::toString(), DsoService::toString(), and MultimeterService::toString().
readCharacteristics()
bool AbstractPokitService::readCharacteristics () pure virtual
Read all characteristics.
This convenience function will queue refresh requests of all characteristics supported by this service.
Relevant *Service::*Read signals will be emitted by derived class objects as each characteristic is successfully read.
Implemented in CalibrationService, DataLoggerService, DeviceInfoService, DsoService, GenericAccessService, MultimeterService, and StatusService.
service() [1/2]
QLowEnergyService * AbstractPokitService::service ()
Returns a non-const pointer to the internal service object, if any.
Definition at line 119 of file abstractpokitservice.cpp.
{
    Q_D(AbstractPokitService);
    return d->service;
}
Referenced by DeviceInfoService::readCharacteristics(), and StatusService::readCharacteristics().
service() [2/2]
const QLowEnergyService * AbstractPokitService::service () const
Returns a const pointer to the internal service object, if any.
Definition at line 128 of file abstractpokitservice.cpp.
{
    Q_D(const AbstractPokitService);
    return d->service;
}
serviceDetailsDiscovered
void AbstractPokitService::serviceDetailsDiscovered () signal
This signal is emitted when the Pokit service details have been discovered.
Once this signal has been emitted, cached characteristics values should be immediately available via derived classes' accessor functions, and refreshes can be queued via readCharacteristics() and any related read functions provided by derived classes.
Referenced by DeviceCommand::deviceDiscovered().
setAutoDiscover()
void AbstractPokitService::setAutoDiscover (const bool discover = true)
If discover is true, autodiscovery will be attempted.
Specifically, this may resulting in automatic invocation of:
QLowEnergyController::discoverServices if/when the internal controller is connected; and
QLowEnergyService::discoverDetails if/when an internal service object is created.
See also
autoDiscover
Definition at line 75 of file abstractpokitservice.cpp.
{
    Q_D(AbstractPokitService);
    d->autoDiscover = discover;
}
setPokitProduct()
void AbstractPokitService::setPokitProduct (const PokitProduct product)
Sets the current Pokit product.
This must be called to set the product before this object's BLE controller's services are discovered. If autoDiscover() is enabled, then this should be done before the controller's connectToDevice() is called.
For example:
Q_ASSERT(isPokitProduct(deviceInfo));
auto controller = QLowEnergyController::createCentral(deviceInfo);
auto service = new DsoService(controller);
service->setPokitProduct(pokitProduct(deviceInfo));
controller->connectToDevice();
See also
autoDiscover
pokitProduct
Definition at line 110 of file abstractpokitservice.cpp.
{
    Q_D(AbstractPokitService);
    d->pokitProduct = product;
}
Referenced by DeviceCommand::deviceDiscovered().
Friends And Related Symbol Documentation
TestAbstractPokitService
friend class TestAbstractPokitService friend
Definition at line 58 of file abstractpokitservice.h.
Member Data Documentation
d_ptr
AbstractPokitServicePrivate* AbstractPokitService::d_ptr protected
Internal d-pointer.
Definition at line 51 of file abstractpokitservice.h.
Referenced by ~AbstractPokitService().
The documentation for this class was generated from the following files:
abstractpokitservice.h
abstractpokitservice.cpp