var annotated_dup =
[
    [ "AbstractCommand", "classAbstractCommand.html", "classAbstractCommand" ],
    [ "AbstractPokitService", "classAbstractPokitService.html", "classAbstractPokitService" ],
    [ "AbstractPokitServicePrivate", "classAbstractPokitServicePrivate.html", "classAbstractPokitServicePrivate" ],
    [ "CalibrationCommand", "classCalibrationCommand.html", "classCalibrationCommand" ],
    [ "CalibrationService", "classCalibrationService.html", "classCalibrationService" ],
    [ "CalibrationServicePrivate", "classCalibrationServicePrivate.html", "classCalibrationServicePrivate" ],
    [ "DeviceCharacteristics", "structMultimeterService_1_1DeviceCharacteristics.html", null ],
    [ "DeviceCommand", "classDeviceCommand.html", "classDeviceCommand" ],
    [ "DeviceInfoService", "classDeviceInfoService.html", "classDeviceInfoService" ],
    [ "DeviceInfoServicePrivate", "classDeviceInfoServicePrivate.html", "classDeviceInfoServicePrivate" ],
    [ "FlashLedCommand", "classFlashLedCommand.html", "classFlashLedCommand" ],
    [ "GenericAccessService", "classGenericAccessService.html", "classGenericAccessService" ],
    [ "GenericAccessServicePrivate", "classGenericAccessServicePrivate.html", "classGenericAccessServicePrivate" ],
    [ "InfoCommand", "classInfoCommand.html", "classInfoCommand" ],
    [ "MultimeterCommand", "classMultimeterCommand.html", "classMultimeterCommand" ],
    [ "MultimeterService", "classMultimeterService.html", "classMultimeterService" ],
    [ "MultimeterServicePrivate", "classMultimeterServicePrivate.html", "classMultimeterServicePrivate" ],
    [ "PokitDevice", "classPokitDevice.html", "classPokitDevice" ],
    [ "PokitDevicePrivate", "classPokitDevicePrivate.html", "classPokitDevicePrivate" ],
    [ "PokitDiscoveryAgent", "classPokitDiscoveryAgent.html", "classPokitDiscoveryAgent" ],
    [ "PokitDiscoveryAgentPrivate", "classPokitDiscoveryAgentPrivate.html", "classPokitDiscoveryAgentPrivate" ],
    [ "ScanCommand", "classScanCommand.html", "classScanCommand" ],
    [ "SetNameCommand", "classSetNameCommand.html", "classSetNameCommand" ],
    [ "StatusCommand", "classStatusCommand.html", "classStatusCommand" ],
    [ "StatusService", "classStatusService.html", "classStatusService" ],
    [ "StatusServicePrivate", "classStatusServicePrivate.html", "classStatusServicePrivate" ]
];