var annotated_dup =
[
    [ "AbstractCommand", "classAbstractCommand.html", "classAbstractCommand" ],
    [ "AbstractPokitService", "classAbstractPokitService.html", "classAbstractPokitService" ],
    [ "AbstractPokitServicePrivate", "classAbstractPokitServicePrivate.html", "classAbstractPokitServicePrivate" ],
    [ "CalibrationCommand", "classCalibrationCommand.html", "classCalibrationCommand" ],
    [ "CalibrationService", "classCalibrationService.html", "classCalibrationService" ],
    [ "CalibrationServicePrivate", "classCalibrationServicePrivate.html", "classCalibrationServicePrivate" ],
    [ "DeviceCommand", "classDeviceCommand.html", "classDeviceCommand" ],
    [ "DeviceInfoService", "classDeviceInfoService.html", "classDeviceInfoService" ],
    [ "DeviceInfoServicePrivate", "classDeviceInfoServicePrivate.html", "classDeviceInfoServicePrivate" ],
    [ "FlashLedCommand", "classFlashLedCommand.html", "classFlashLedCommand" ],
    [ "GenericAccessService", "classGenericAccessService.html", "classGenericAccessService" ],
    [ "GenericAccessServicePrivate", "classGenericAccessServicePrivate.html", "classGenericAccessServicePrivate" ],
    [ "InfoCommand", "classInfoCommand.html", "classInfoCommand" ],
    [ "PokitDevice", "classPokitDevice.html", "classPokitDevice" ],
    [ "PokitDeviceDiscoveryAgent", "classPokitDeviceDiscoveryAgent.html", "classPokitDeviceDiscoveryAgent" ],
    [ "PokitDeviceDiscoveryAgentPrivate", "classPokitDeviceDiscoveryAgentPrivate.html", "classPokitDeviceDiscoveryAgentPrivate" ],
    [ "PokitDevicePrivate", "classPokitDevicePrivate.html", "classPokitDevicePrivate" ],
    [ "ScanCommand", "classScanCommand.html", "classScanCommand" ],
    [ "SetNameCommand", "classSetNameCommand.html", "classSetNameCommand" ],
    [ "StatusCommand", "classStatusCommand.html", "classStatusCommand" ],
    [ "StatusService", "classStatusService.html", "classStatusService" ],
    [ "StatusServicePrivate", "classStatusServicePrivate.html", "classStatusServicePrivate" ]
];