QtPokit: MultimeterCommand Class Reference
MultimeterCommand Class Reference
The MultimeterCommand class implements the meter CLI command.
Public Slots
QStringList processOptions (const QCommandLineParser &parser) override
Processes the relevant options from the command line parser.
Public Slots inherited from DeviceCommand
bool start () override
Begins scanning for the Pokit device.
Public Slots inherited from AbstractCommand
virtual QStringList processOptions (const QCommandLineParser &parser)
Processes the relevant options from the command line parser.
virtual bool start ()=0
Begins the functionality of this command, and returns true if begun successfully, false otherwise.
Public Member Functions
MultimeterCommand (QObject *const parent)
Construct a new MultimeterCommand object with parent.
QStringList requiredOptions () const override
Returns a list of CLI option names required by this command.
QStringList supportedOptions () const override
Returns a list of CLI option names supported by this command.
Public Member Functions inherited from DeviceCommand
DeviceCommand (QObject *const parent)
Construct a new DeviceCommand object with parent.
Public Member Functions inherited from AbstractCommand
AbstractCommand (QObject *const parent)
Constructs a new command with parent.
virtual QStringList requiredOptions () const
Returns a list of CLI option names required by this command.
virtual QStringList supportedOptions () const
Returns a list of CLI option names supported by this command.
Protected Slots
void serviceDetailsDiscovered () override
Handles service detail discovery events.
Protected Slots inherited from DeviceCommand
virtual void controllerError (const QLowEnergyController::Error error)
Handles controller error events.
virtual void serviceError (const QLowEnergyService::ServiceError error)
Handles service error events.
virtual void serviceDetailsDiscovered ()
Handles service detail discovery events.
Protected Member Functions
AbstractPokitService * getService () override
Returns a Pokit service object for the derived command class.
virtual AbstractPokitService * getService ()=0
Returns a Pokit service object for the derived command class.
Protected Member Functions inherited from AbstractCommand
virtual void deviceDiscovered (const QBluetoothDeviceInfo &info)=0
Handles PokitDiscoveryAgent::pokitDeviceDiscovered signal.
virtual void deviceDiscoveryFinished ()=0
Handles PokitDiscoveryAgent::deviceDiscoveryFinished signal.
Private Slots
void settingsWritten ()
Invoked when the multimeter settings have been written, to begin reading the meter values.
void outputReading (const MultimeterService::Reading &reading)
Outputs meter reading in the selected ouput format.
Private Attributes
MultimeterService * service
Bluetooth service this command interracts with.
MultimeterService::Settings settings
Setting for the Pokit device's multimeter mode.
int numberOfSamplesToRead
Number of samples to read, if specified on the CLI.
Friends
class TestMultimeterCommand
Additional Inherited Members
Public Types inherited from AbstractCommand
enum class OutputFormat { Csv , Json , Text }
Supported output formats.
Static Public Member Functions inherited from AbstractCommand
static QString escapeCsvField (const QString &field)
Returns an RFC 4180 compliant version of field.
static quint32 parseMilliseconds (const QString &value, const quint32 sensibleMiniumum=0)
Returns value as a number of milliseonds.
Static Protected Member Functions inherited from AbstractCommand
static Q_LOGGING_CATEGORY (lc, "pokit.ui.command", QtInfoMsg)
Logging category for UI commands.
Protected Attributes inherited from DeviceCommand
PokitDevice * device
Pokit Bluetooth device (if any) this command inerracts with.
Protected Attributes inherited from AbstractCommand
PokitDiscoveryAgent * discoveryAgent
Agent for Pokit device descovery.
OutputFormat format
Selected output format.
QString deviceToScanFor
Device (if any) that were passed to processOptions().
Detailed Description
The MultimeterCommand class implements the meter CLI command.
Definition at line 24 of file multimetercommand.h.
Constructor & Destructor Documentation
MultimeterCommand()
MultimeterCommand::MultimeterCommand (QObject *const parent) explicit
Construct a new MultimeterCommand object with parent.
Definition at line 36 of file multimetercommand.cpp.
                                                           : DeviceCommand(parent),
    service(nullptr), settings{
        MultimeterService::MultimeterMode::DcVoltage,
        { MultimeterService::VoltageRange::AutoRange },
        1000
    }, numberOfSamplesToRead(-1)
{
}
References MultimeterService::AutoRange.
Member Function Documentation
getService()
AbstractPokitService * MultimeterCommand::getService () override protected virtual
Returns a Pokit service object for the derived command class.
This override returns a pointer to a MultimeterService object.
Implements DeviceCommand.
Definition at line 131 of file multimetercommand.cpp.
{
    Q_ASSERT(device);
    if (!service) {
        service = device->multimeter();
        Q_ASSERT(service);
        connect(service, &MultimeterService::settingsWritten,
                this, &MultimeterCommand::settingsWritten);
    }
    return service;
}
References DeviceCommand::device, PokitDevice::multimeter(), service, MultimeterService::settingsWritten(), and settingsWritten().
outputReading
void MultimeterCommand::outputReading (const MultimeterService::Reading & reading) private slot
Outputs meter reading in the selected ouput format.
Definition at line 189 of file multimetercommand.cpp.
{
    QString status;
    if (reading.status.testFlag(MultimeterService::ReadingStatusFlag::Error)) {
        status = QLatin1String("Error");
    } else switch (reading.mode) {
    case MultimeterService::MultimeterMode::Idle:
        break;
    case MultimeterService::MultimeterMode::DcVoltage:
    case MultimeterService::MultimeterMode::AcVoltage:
    case MultimeterService::MultimeterMode::DcCurrent:
    case MultimeterService::MultimeterMode::AcCurrent:
    case MultimeterService::MultimeterMode::Resistance:
        status = (reading.status.testFlag(MultimeterService::ReadingStatusFlag::AutoRange)
            ? tr("Auto Range On") : tr("Auto Range Off"));
        break;
    case MultimeterService::MultimeterMode::Continuity:
        status = (reading.status.testFlag(MultimeterService::ReadingStatusFlag::AutoRange)
            ? tr("Continuity") : tr("No continuity"));
        break;
    case MultimeterService::MultimeterMode::Temperature:
    case MultimeterService::MultimeterMode::Diode:
        status = tr("Ok");
        break;
    }
    QString units;
    switch (reading.mode) {
    case MultimeterService::MultimeterMode::Idle:        break;
    case MultimeterService::MultimeterMode::DcVoltage:   units = QLatin1String("Vdc"); break;
    case MultimeterService::MultimeterMode::AcVoltage:   units = QLatin1String("Vac"); break;
    case MultimeterService::MultimeterMode::DcCurrent:   units = QLatin1String("Adc"); break;
    case MultimeterService::MultimeterMode::AcCurrent:   units = QLatin1String("Aac"); break;
    case MultimeterService::MultimeterMode::Resistance:  units = QString::fromUtf8(""); break;
    case MultimeterService::MultimeterMode::Diode:       break;
    case MultimeterService::MultimeterMode::Continuity:  break;
    case MultimeterService::MultimeterMode::Temperature: units = QString::fromUtf8("C"); break;
    }
    QString range;
    QVariant rangeMin, rangeMax;
    switch (reading.mode) {
    case MultimeterService::MultimeterMode::Idle:        break;
    case MultimeterService::MultimeterMode::DcVoltage:
    case MultimeterService::MultimeterMode::AcVoltage:
        range = MultimeterService::toString(reading.range.voltageRange);
        rangeMin = MultimeterService::minValue(reading.range.voltageRange);
        rangeMax = MultimeterService::maxValue(reading.range.voltageRange);
        break;
    case MultimeterService::MultimeterMode::DcCurrent:
    case MultimeterService::MultimeterMode::AcCurrent:
        range = MultimeterService::toString(reading.range.currentRange);
        rangeMin = MultimeterService::minValue(reading.range.currentRange);
        rangeMax = MultimeterService::maxValue(reading.range.currentRange);
        break;
    case MultimeterService::MultimeterMode::Resistance:
        range = MultimeterService::toString(reading.range.resitanceRange);
        rangeMin = MultimeterService::minValue(reading.range.resitanceRange);
        rangeMax = MultimeterService::maxValue(reading.range.resitanceRange);
        break;
    case MultimeterService::MultimeterMode::Diode:       break;
    case MultimeterService::MultimeterMode::Continuity:  break;
    case MultimeterService::MultimeterMode::Temperature: break;
    }
    switch (format) {
    case OutputFormat::Csv:
        for (static bool firstTime = true; firstTime; firstTime = false) {
            fputs(qPrintable(tr("mode,value,units,status,range_min_milli,range_max_milli\n")), stdout);
        }
        fputs(qPrintable(QString::fromLatin1("%1,%2,%3,%4,%5,%6\n")
            .arg(escapeCsvField(MultimeterService::toString(reading.mode)))
            .arg(reading.value, 0, 'f').arg(units, status, rangeMin.toString(), rangeMax.toString())
            ), stdout);
        break;
    case OutputFormat::Json: {
        QJsonObject jsonObject{
            { QLatin1String("status"), status },
            { QLatin1String("value"), qIsInf(reading.value) ?
                QJsonValue(tr("Infinity")) : QJsonValue(reading.value) },
            { QLatin1String("mode"),   MultimeterService::toString(reading.mode) },
        };
        if ((!rangeMin.isNull()) || (!rangeMax.isNull())) {
            jsonObject.insert(QLatin1String("range"), QJsonObject{
                { QLatin1String("min"),
                    #if (QT_VERSION >= QT_VERSION_CHECK(6, 0, 0))
                    (rangeMin.typeId() == QMetaType::Int)
                    #else
                    (rangeMin.type() == QVariant::Int)
                    #endif
                    ? QJsonValue(rangeMin.toInt()/1000.0) : rangeMin.toJsonValue() },
                { QLatin1String("max"),
                    #if (QT_VERSION >= QT_VERSION_CHECK(6, 0, 0))
                    (rangeMax.typeId() == QMetaType::Int) ?
                    #else
                    (rangeMax.type() == QVariant::Int) ?
                    #endif
                    QJsonValue(rangeMax.toInt()/1000.0) : rangeMax.toJsonValue() },
            });
        }
        fputs(QJsonDocument(jsonObject).toJson(), stdout);
    }   break;
    case OutputFormat::Text:
        fputs(qPrintable(tr("Mode:   %1 (0x%2)\n").arg(MultimeterService::toString(reading.mode))
            .arg((quint8)reading.mode,2,16,QLatin1Char('0'))), stdout);
        fputs(qPrintable(tr("Value:  %1 %2\n").arg(reading.value,0,'f').arg(units)), stdout);
        fputs(qPrintable(tr("Status: %1 (0x%2)\n").arg(status)
            .arg(reading.status,2,16,QLatin1Char('0'))), stdout);
        fputs(qPrintable(tr("Range:  %1 (0x%2)\n").arg(range)
            .arg((quint8)reading.range.voltageRange,2,16,QLatin1Char('0'))), stdout);
        break;
    }
    if (numberOfSamplesToRead > 0) {
        if (--numberOfSamplesToRead == 0) {
            service->stopClientReadings();
            QCoreApplication::exit(EXIT_SUCCESS);
        }
    }
}
References MultimeterService::AcCurrent, MultimeterService::AcVoltage, MultimeterService::AutoRange, MultimeterService::Continuity, AbstractCommand::Csv, MultimeterService::MultimeterRange::currentRange, MultimeterService::DcCurrent, MultimeterService::DcVoltage, MultimeterService::Diode, MultimeterService::Error, AbstractCommand::escapeCsvField(), AbstractCommand::format, MultimeterService::Idle, AbstractCommand::Json, MultimeterService::maxValue(), MultimeterService::minValue(), MultimeterService::Reading::mode, numberOfSamplesToRead, MultimeterService::Reading::range, MultimeterService::Resistance, MultimeterService::MultimeterRange::resitanceRange, service, MultimeterService::Reading::status, MultimeterService::stopClientReadings(), MultimeterService::Temperature, AbstractCommand::Text, MultimeterService::toString(), MultimeterService::Reading::value, and MultimeterService::MultimeterRange::voltageRange.
Referenced by settingsWritten().
processOptions
QStringList MultimeterCommand::processOptions (const QCommandLineParser & parser) override slot
Processes the relevant options from the command line parser.
This implementation extends DeviceCommand::processOptions to process additional CLI options supported (or required) by this command.
Todo:
Parse the range.
Definition at line 68 of file multimetercommand.cpp.
{
    QStringList errors = DeviceCommand::processOptions(parser);
    if (!errors.isEmpty()) {
        return errors;
    }
    // Parse the (required) mode option.
    const QString mode = parser.value(QLatin1String("mode")).trimmed().toLower();
    if (mode.startsWith(QLatin1String("ac v")) || mode.startsWith(QLatin1String("vac"))) {
        settings.mode = MultimeterService::MultimeterMode::AcVoltage;
    } else if (mode.startsWith(QLatin1String("dc v")) || mode.startsWith(QLatin1String("vdc"))) {
        settings.mode = MultimeterService::MultimeterMode::DcVoltage;
    } else if (mode.startsWith(QLatin1String("ac c")) || mode.startsWith(QLatin1String("aac"))) {
        settings.mode = MultimeterService::MultimeterMode::AcCurrent;
    } else if (mode.startsWith(QLatin1String("dc c")) || mode.startsWith(QLatin1String("aac"))) {
        settings.mode = MultimeterService::MultimeterMode::DcCurrent;
    } else if (mode.startsWith(QLatin1String("res"))) {
        settings.mode = MultimeterService::MultimeterMode::Resistance;
    } else if (mode.startsWith(QLatin1String("dio"))) {
        settings.mode = MultimeterService::MultimeterMode::Diode;
    } else if (mode.startsWith(QLatin1String("cont"))) {
       settings.mode = MultimeterService::MultimeterMode::Continuity;
    } else if (mode.startsWith(QLatin1String("temp"))) {
       settings.mode = MultimeterService::MultimeterMode::Temperature;
    } else {
        errors.append(tr("Unknown meter mode: %1").arg(parser.value(QLatin1String("mode"))));
        return errors;
    }
    // Parse the interval (if any).
    if (parser.isSet(QLatin1String("interval"))) {
        const QString value = parser.value(QLatin1String("interval"));
        const quint32 interval = parseMilliseconds(value, 500);
        if (interval == 0) {
            errors.append(tr("Invalid interval: %1").arg(value));
        } else {
            settings.updateInterval = interval;
        }
    }
    /// \todo Parse the range.
    // Parse the samples.
    if (parser.isSet(QLatin1String("samples"))) {
        const QString value = parser.value(QLatin1String("samples"));
        QLocale locale; bool ok;
        const int samples = locale.toInt(value, &ok);
        if (!ok) {
            errors.append(tr("Invalid number of samples: %1").arg(value));
        } else {
            numberOfSamplesToRead = samples;
        }
    }
    return errors;
}
References MultimeterService::AcCurrent, MultimeterService::AcVoltage, MultimeterService::Continuity, MultimeterService::DcCurrent, MultimeterService::DcVoltage, MultimeterService::Diode, MultimeterService::Settings::mode, numberOfSamplesToRead, AbstractCommand::parseMilliseconds(), AbstractCommand::processOptions(), MultimeterService::Resistance, settings, MultimeterService::Temperature, and MultimeterService::Settings::updateInterval.
requiredOptions()
QStringList MultimeterCommand::requiredOptions () const override virtual
Returns a list of CLI option names required by this command.
The main console appication may use this list to output an eror (and exit) if any of the returned names are not found in the parsed CLI options.
This base implementation simply returns an empty list. Derived classes should override this function to include any required options.
Reimplemented from AbstractCommand.
Definition at line 46 of file multimetercommand.cpp.
{
    return DeviceCommand::requiredOptions() + QStringList{
        QLatin1String("mode"),
    };
}
References AbstractCommand::requiredOptions().
serviceDetailsDiscovered
void MultimeterCommand::serviceDetailsDiscovered () override protected slot
Handles service detail discovery events.
This override fetches the current device's status, and outputs it in the selected format.
Definition at line 148 of file multimetercommand.cpp.
{
    QString range = tr("N/A");
    switch (settings.mode) {
    case MultimeterService::MultimeterMode::Idle:        break;
    case MultimeterService::MultimeterMode::DcVoltage:
    case MultimeterService::MultimeterMode::AcVoltage:
        range = MultimeterService::toString(settings.range.voltageRange);
        break;
    case MultimeterService::MultimeterMode::DcCurrent:
    case MultimeterService::MultimeterMode::AcCurrent:
        range = MultimeterService::toString(settings.range.currentRange);
        break;
    case MultimeterService::MultimeterMode::Resistance:
        range = MultimeterService::toString(settings.range.resitanceRange);
        break;
    case MultimeterService::MultimeterMode::Diode:       break;
    case MultimeterService::MultimeterMode::Continuity:  break;
    case MultimeterService::MultimeterMode::Temperature: break;
    }
    DeviceCommand::serviceDetailsDiscovered(); // Just logs consistently.
    qCInfo(lc).noquote() << tr("Measuring %1, with range %2, every %L3ms.")
        .arg(MultimeterService::toString(settings.mode), range).arg(settings.updateInterval);
    service->setSettings(settings);
}
References MultimeterService::AcCurrent, MultimeterService::AcVoltage, MultimeterService::Continuity, MultimeterService::MultimeterRange::currentRange, MultimeterService::DcCurrent, MultimeterService::DcVoltage, MultimeterService::Diode, MultimeterService::Idle, MultimeterService::Settings::mode, MultimeterService::Settings::range, MultimeterService::Resistance, MultimeterService::MultimeterRange::resitanceRange, service, DeviceCommand::serviceDetailsDiscovered(), MultimeterService::setSettings(), settings, MultimeterService::Temperature, MultimeterService::toString(), MultimeterService::Settings::updateInterval, and MultimeterService::MultimeterRange::voltageRange.
settingsWritten
void MultimeterCommand::settingsWritten () private slot
Invoked when the multimeter settings have been written, to begin reading the meter values.
Definition at line 178 of file multimetercommand.cpp.
{
    qCDebug(lc).noquote() << tr("Settings written; starting meter readings...");
    connect(service, &MultimeterService::readingRead,
            this, &MultimeterCommand::outputReading);
    service->beginClientReadings();
}
References MultimeterService::beginClientReadings(), outputReading(), MultimeterService::readingRead(), and service.
Referenced by getService().
supportedOptions()
QStringList MultimeterCommand::supportedOptions () const override virtual
Returns a list of CLI option names supported by this command.
The main console appication may use this list to output a warning for any parsed CLI options not included in the returned list.
This base implementation simply returns requiredOptions(). Derived classes should override this function to include optional options, such as:
QStringList Derived::supportedOptions() const
{
    const QStringList list = AbstractCommand::supportedOptions() + QStringList{ ... };
    list.sort();
    list.removeDuplicates(); // Optional, recommended.
    return list;
}
Reimplemented from AbstractCommand.
Definition at line 53 of file multimetercommand.cpp.
{
    return DeviceCommand::supportedOptions() + QStringList{
        QLatin1String("interval"),
        QLatin1String("range"),
        QLatin1String("samples"),
    };
}
References AbstractCommand::supportedOptions().
Friends And Related Function Documentation
TestMultimeterCommand
friend class TestMultimeterCommand friend
Definition at line 50 of file multimetercommand.h.
Member Data Documentation
numberOfSamplesToRead
int MultimeterCommand::numberOfSamplesToRead private
Number of samples to read, if specified on the CLI.
Definition at line 44 of file multimetercommand.h.
Referenced by outputReading(), and processOptions().
service
MultimeterService* MultimeterCommand::service private
Bluetooth service this command interracts with.
Definition at line 42 of file multimetercommand.h.
Referenced by getService(), outputReading(), serviceDetailsDiscovered(), and settingsWritten().
settings
MultimeterService::Settings MultimeterCommand::settings private
Setting for the Pokit device's multimeter mode.
Definition at line 43 of file multimetercommand.h.
Referenced by processOptions(), and serviceDetailsDiscovered().
The documentation for this class was generated from the following files:
multimetercommand.h
multimetercommand.cpp