QtPokit: Informer Class Reference
Informer Class Reference
Simple class for experimenting with the Pokit device info service.
#include <informer.h>
Public Member Functions
Informer (QObject *const parent)
Detailed Description
Simple class for experimenting with the Pokit device info service.
This class will be signifantly refactored, or maybe replaced entirely soonish.
Definition at line 29 of file informer.h.
Constructor & Destructor Documentation
Informer()
Informer::Informer (QObject *const parent) explicit
<
Todo:
Exit gracefully.
Definition at line 35 of file informer.cpp.
                                         : QObject(parent)
{
    PokitDevice * device = new PokitDevice(QLatin1String("5C:02:72:09:AA:25"), this);
    qDebug() << device;
    StatusService * service = device->status();
    qDebug() << service;
    connect(device->controller(),
        #if (QT_VERSION < QT_VERSION_CHECK(6, 2, 0))
        QOverload<QLowEnergyController::Error>::of(&QLowEnergyController::error),
        #else
        &QLowEnergyController::errorOccurred,
        #endif
    [](QLowEnergyController::Error error) {
        qDebug() << error;
        ::exit(EXIT_FAILURE); ///< \todo Exit gracefully.
    });
    connect(service, &StatusService::serviceDetailsDiscovered,[service]() {
        qDebug() << "All ready to go! :)";
        service->deviceCharacteristics(); // Should be immediately (cached) available.
        service->flashLed(); // Should be fun :)
        //service->setDeviceName(QLatin1String("PokitPro")); // Yes, this works :D
        service->readCharacteristics(); // Can also fetch new values (results via signal).
    });
    device->controller()->connectToDevice();
}
References PokitDevice::controller(), StatusService::deviceCharacteristics(), StatusService::flashLed(), StatusService::readCharacteristics(), AbstractPokitService::serviceDetailsDiscovered(), and PokitDevice::status().
The documentation for this class was generated from the following files:
informer.h
informer.cpp