Dokit: ScanCommand Class Reference
ScanCommand Class Reference
The ScanCommand class implements the scan CLI command, by scanning for nearby Pokit Bluetooth devices.
Public Slots
QStringList processOptions (const QCommandLineParser &parser) override
Processes the relevant options from the command line parser.
bool start () override
Begins scanning for Pokit devices.
Public Slots inherited from AbstractCommand
virtual QStringList processOptions (const QCommandLineParser &parser)
Processes the relevant options from the command line parser.
virtual bool start ()=0
Begins the functionality of this command, and returns true if begun successfully, false otherwise.
Public Member Functions
ScanCommand (QObject *const parent=nullptr)
Construct a new ScanCommand object with parent.
QStringList requiredOptions (const QCommandLineParser &parser) const override
Returns a list of CLI option names required by this command.
QStringList supportedOptions (const QCommandLineParser &parser) const override
Returns a list of CLI option names supported by this command.
Public Member Functions inherited from AbstractCommand
AbstractCommand (QObject *const parent=nullptr)
Constructs a new command with parent.
virtual QStringList requiredOptions (const QCommandLineParser &parser) const
Returns a list of CLI option names required by this command.
virtual QStringList supportedOptions (const QCommandLineParser &parser) const
Returns a list of CLI option names supported by this command.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Protected Slots
void deviceDiscovered (const QBluetoothDeviceInfo &info) override
Handles discovered Pokit devices, writing info to stdout.
void deviceUpdated (const QBluetoothDeviceInfo &info, const QBluetoothDeviceInfo::Fields updatedFields)
Handles updated Pokit devices, writing info to stdout.
void deviceDiscoveryFinished () override
Handles the completion of device discovery.
Protected Slots inherited from AbstractCommand
virtual void deviceDiscovered (const QBluetoothDeviceInfo &info)=0
Handles PokitDiscoveryAgent::pokitDeviceDiscovered signal.
virtual void deviceDiscoveryFinished ()=0
Handles PokitDiscoveryAgent::deviceDiscoveryFinished signal.
Static Private Member Functions
static QJsonObject toJson (const QBluetoothDeviceInfo &info)
Returns info as a JSON object.
static QJsonArray toJson (const QBluetoothDeviceInfo::CoreConfigurations &configurations)
Returns configuration as a JSON array of strings.
static QJsonValue toJson (const QBluetoothDeviceInfo::MajorDeviceClass &majorClass)
Returns majorClass as a JSON value.
static QJsonValue toJson (const QBluetoothDeviceInfo::MajorDeviceClass &majorClass, const quint8 minorClass)
Returns minorClass as a JSON value.
static QJsonArray toJson (const QBluetoothDeviceInfo::ServiceClasses &classes)
Returns classes as a JSON array of strings.
static QJsonArray toJson (const QList< QBluetoothUuid > &uuids)
Returns uuids as a JSON array.
static QJsonObject toJson (const QMultiHash< quint16, QByteArray > &data)
Returns Bluetooth manufacturer data as a JSON object that maps the manufacturer IDs (unsigned integers as strings) to arrays of one or more values.
static QString toString (const QBluetoothDeviceInfo::MajorDeviceClass &majorClass)
Returns majorClass as a human-readable string, or a null QString if majorClass is not recognised.
static QString toString (const QBluetoothDeviceInfo::MajorDeviceClass &majorClass, const quint8 minorClass)
Returns minorClass as a human-readable string, or a null QString if minorClass is not recognised as a sub-class of majorClass.
Private Attributes
bool showCsvHeader { true }
Whether or not to show a header as the first line of CSV output.
Friends
class TestScanCommand
Additional Inherited Members
Public Types inherited from AbstractCommand
enum class OutputFormat { Csv , Json , Text }
Supported output formats.
Static Public Member Functions inherited from AbstractCommand
static QString escapeCsvField (const QString &field)
Returns an RFC 4180 compliant version of field.
static quint32 parseMicroValue (const QString &value, const QString &unit, const quint32 sensibleMinimum=0)
Returns value as a number of micros, such as microseconds, or microvolts.
static quint32 parseMilliValue (const QString &value, const QString &unit, const quint32 sensibleMinimum=0)
Returns value as a number of millis, such as milliseconds, or millivolts.
static quint32 parseWholeValue (const QString &value, const QString &unit)
Returns value as a number, with optional SI unit prefix, and optional unit suffix.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Static Protected Member Functions inherited from AbstractCommand
static Q_LOGGING_CATEGORY (lc, "dokit.cli.command", QtInfoMsg)
Logging category for UI commands.
Protected Attributes inherited from AbstractCommand
QString deviceToScanFor
Device (if any) that were passed to processOptions().
PokitDiscoveryAgent * discoveryAgent
Agent for Pokit device descovery.
OutputFormat format { OutputFormat::Text }
Selected output format.
Properties inherited from QObject
objectName
Detailed Description
The ScanCommand class implements the scan CLI command, by scanning for nearby Pokit Bluetooth devices.
When devices are found, they are logged to stdout in the chosen format.
Definition at line 6 of file scancommand.h.
Constructor & Destructor Documentation
ScanCommand()
ScanCommand::ScanCommand (QObject *const parent = nullptr) explicit
Construct a new ScanCommand object with parent.
Definition at line 25 of file scancommand.cpp.
                                               : AbstractCommand(parent)
{
    #if (QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)) // Required signal, and Fields, added in Qt 5.12.
    connect(discoveryAgent, &PokitDiscoveryAgent::pokitDeviceUpdated,
            this, &ScanCommand::deviceUpdated);
    #endif
}
References QObject::connect(), deviceUpdated(), AbstractCommand::discoveryAgent, and PokitDiscoveryAgent::pokitDeviceUpdated().
Member Function Documentation
deviceDiscovered
void ScanCommand::deviceDiscovered (const QBluetoothDeviceInfo & info) override protected slot
Handles discovered Pokit devices, writing info to stdout.
Definition at line 69 of file scancommand.cpp.
{
    switch (format) {
    case OutputFormat::Csv:
        for (; showCsvHeader; showCsvHeader = false) {
            std::cout << qUtf8Printable(tr("uuid,address,name,major_class,minor_class,signal_strength\n"));
        }
        std::cout << qUtf8Printable(QString::fromLatin1("%1,%2,%3,%4,%5,%6\n").arg(info.deviceUuid().toString(),
            info.address().toString(), escapeCsvField(info.name()), toString(info.majorDeviceClass()),
            toString(info.majorDeviceClass(), info.minorDeviceClass())).arg(info.rssi()));
        break;
    case OutputFormat::Json:
        std::cout << QJsonDocument(toJson(info)).toJson().toStdString();
        break;
    case OutputFormat::Text:
        std::cout << qUtf8Printable(tr("%1 %2 %3 %4\n").arg(info.deviceUuid().toString(),
            info.address().toString(), info.name()).arg(info.rssi()));
        break;
    }
}
References QBluetoothDeviceInfo::address(), QString::arg(), AbstractCommand::Csv, QBluetoothDeviceInfo::deviceUuid(), AbstractCommand::escapeCsvField(), AbstractCommand::format, QString::fromLatin1(), AbstractCommand::Json, QBluetoothDeviceInfo::majorDeviceClass(), QBluetoothDeviceInfo::minorDeviceClass(), QBluetoothDeviceInfo::name(), QBluetoothDeviceInfo::rssi(), showCsvHeader, AbstractCommand::Text, QJsonDocument::toJson(), toJson(), QByteArray::toStdString(), QBluetoothAddress::toString(), QUuid::toString(), toString(), and QObject::tr().
Referenced by deviceUpdated().
deviceDiscoveryFinished
void ScanCommand::deviceDiscoveryFinished () override protected slot
Handles the completion of device discovery.
In this override we simply exit, as the scan command is nothing more than logging of discovered devices.
Definition at line 106 of file scancommand.cpp.
{
    qCDebug(lc).noquote() << tr("Finished scanning for Pokit devices.");
    QCoreApplication::quit();
}
References QCoreApplication::quit(), and QObject::tr().
deviceUpdated
void ScanCommand::deviceUpdated (const QBluetoothDeviceInfo & info, const QBluetoothDeviceInfo::Fields updatedFields) protected slot
Handles updated Pokit devices, writing info to stdout.
Currently updatedFields us unused.
Definition at line 94 of file scancommand.cpp.
{
    Q_UNUSED(updatedFields)
    deviceDiscovered(info);
}
References deviceDiscovered().
Referenced by ScanCommand().
processOptions
QStringList ScanCommand::processOptions (const QCommandLineParser & parser) override slot
Processes the relevant options from the command line parser.
On success, returns an empty QStringList, otherwise returns a list of CLI errors that the caller should report appropriately before exiting.
This base implementations performs some common checks, such as ensuring that required options are present. Derived classes should override this function to perform further processing, typically inovking this base implementation as a first step, such as:
QStringList CustomCommand::processOptions(const QCommandLineParser &parser)
{
    QStringList errors = AbstractCommand::processOptions(parser);
    if (!errors.isEmpty()) {
        return errors;
    }
    // Do further procession of options.
    return errors;
}
Definition at line 45 of file scancommand.cpp.
{
    QStringList errors = AbstractCommand::processOptions(parser);
    if (!errors.isEmpty()) {
        return errors;
    }
    return errors;
}
References QList::isEmpty(), and AbstractCommand::processOptions().
requiredOptions()
QStringList ScanCommand::requiredOptions (const QCommandLineParser & parser) const override virtual
Returns a list of CLI option names required by this command.
The main console appication may use this list to output an eror (and exit) if any of the returned names are not found in the parsed CLI options.
The (already parsed) parser may be used adjust the returned required options depending on the value of other options. For example, the logger command only requires the --mode option if the --command option is start.
This base implementation simply returns an empty list. Derived classes should override this function to include any required options.
Reimplemented from AbstractCommand.
Definition at line 33 of file scancommand.cpp.
{
    return AbstractCommand::requiredOptions(parser);
}
References AbstractCommand::requiredOptions().
start
bool ScanCommand::start () override slot
Begins scanning for Pokit devices.
Definition at line 58 of file scancommand.cpp.
{
    Q_ASSERT(discoveryAgent);
    qCInfo(lc).noquote() << tr("Scanning for Pokit devices...");
    discoveryAgent->start();
    return true;
}
References AbstractCommand::discoveryAgent, PokitDiscoveryAgent::start(), and QObject::tr().
supportedOptions()
QStringList ScanCommand::supportedOptions (const QCommandLineParser & parser) const override virtual
Returns a list of CLI option names supported by this command.
The main console appication may use this list to output a warning for any parsed CLI options not included in the returned list.
The (already parsed) parser may be used adjust the returned supported options depending on the value of other options. For example, the logger command only supported the --timestamp option if the --command option is start.
This base implementation simply returns requiredOptions(). Derived classes should override this function to include optional options, such as:
QStringList Derived::supportedOptions(const QCommandLineParser &parser) const
{
    const QStringList list = AbstractCommand::supportedOptions(parser) + QStringList{ ... };
    list.sort();
    list.removeDuplicates(); // Optional, recommended.
    return list;
}
Reimplemented from AbstractCommand.
Definition at line 38 of file scancommand.cpp.
{
    return AbstractCommand::supportedOptions(parser) + QStringList{
    };
}
References AbstractCommand::supportedOptions().
toJson() [1/7]
QJsonObject ScanCommand::toJson (const QBluetoothDeviceInfo & info) static private
Returns info as a JSON object.
Definition at line 115 of file scancommand.cpp.
{
    if (!info.isValid()) {
        return QJsonObject();
    }
    QJsonObject json{
        { QLatin1String("address"), info.address().toString() },
        { QLatin1String("name"), info.name() },
        { QLatin1String("isCached"), info.isCached() },
        { QLatin1String("majorDeviceClass"), info.majorDeviceClass() },
        { QLatin1String("majorDeviceClass"), toJson(info.majorDeviceClass()) },
        { QLatin1String("minorDeviceClass"), toJson(info.majorDeviceClass(), info.minorDeviceClass()) },
        { QLatin1String("signalStrength"), info.rssi() },
    };
    if (info.coreConfigurations() != QBluetoothDeviceInfo::UnknownCoreConfiguration) {
        json.insert(QLatin1String("coreConfiguration"), toJson(info.coreConfigurations()));
    }
    if (!info.deviceUuid().isNull()) {
        json.insert(QLatin1String("deviceUuid"), info.deviceUuid().toString());
    }
    #if (QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)) // Added in Qt 5.12.
    if (!info.manufacturerData().isEmpty()) {
        json.insert(QLatin1String("manufacturerData"), toJson(info.manufacturerData()));
    }
    #endif
    if (info.serviceClasses() != QBluetoothDeviceInfo::NoService) {
        json.insert(QLatin1String("serviceClasses"), toJson(info.serviceClasses()));
    }
    if (!info.serviceUuids().isEmpty()) {
        json.insert(QLatin1String("serviceUuids"), toJson(info.serviceUuids()));
    }
    return json;
}
References QBluetoothDeviceInfo::address(), QBluetoothDeviceInfo::coreConfigurations(), QBluetoothDeviceInfo::deviceUuid(), QBluetoothDeviceInfo::isCached(), QByteArray::isEmpty(), QUuid::isNull(), QBluetoothDeviceInfo::isValid(), QBluetoothDeviceInfo::majorDeviceClass(), QBluetoothDeviceInfo::manufacturerData(), QBluetoothDeviceInfo::minorDeviceClass(), QBluetoothDeviceInfo::name(), QBluetoothDeviceInfo::NoService, QBluetoothDeviceInfo::rssi(), QBluetoothDeviceInfo::serviceClasses(), QBluetoothDeviceInfo::serviceUuids(), toJson(), QBluetoothAddress::toString(), QUuid::toString(), and QBluetoothDeviceInfo::UnknownCoreConfiguration.
Referenced by deviceDiscovered(), and toJson().
toJson() [2/7]
QJsonArray ScanCommand::toJson (const QBluetoothDeviceInfo::CoreConfigurations & configurations) static private
Returns configuration as a JSON array of strings.
Definition at line 152 of file scancommand.cpp.
{
    QJsonArray array;
    #define DOKIT_INTERNAL_IF_SET_THEN_APPEND(flag) \
        if (configurations.testFlag(QBluetoothDeviceInfo::flag)) \
            array.append(QLatin1String(#flag))
    DOKIT_INTERNAL_IF_SET_THEN_APPEND(UnknownCoreConfiguration);
    DOKIT_INTERNAL_IF_SET_THEN_APPEND(LowEnergyCoreConfiguration);
    DOKIT_INTERNAL_IF_SET_THEN_APPEND(BaseRateCoreConfiguration);
  //DOKIT_INTERNAL_IF_SET_THEN_APPEND(BaseRateAndLowEnergyCoreConfiguration); // Combination flag.
    #undef DOKIT_INTERNAL_IF_SET_THEN_APPEND
    return array;
}
toJson() [3/7]
QJsonValue ScanCommand::toJson (const QBluetoothDeviceInfo::MajorDeviceClass & majorClass) static private
Returns majorClass as a JSON value.
This is equivalent to toString, except that if toString does not recognise majorClass, then majorClass is returned as a JSON number (not a string).
See also
toString(const QBluetoothDeviceInfo::MajorDeviceClass &majorClass)
Definition at line 172 of file scancommand.cpp.
{
    const QString string = toString(majorClass);
    return (string.isNull() ? QJsonValue(majorClass) : QJsonValue(string));
}
References toString().
toJson() [4/7]
QJsonValue ScanCommand::toJson (const QBluetoothDeviceInfo::MajorDeviceClass & majorClass, const quint8 minorClass) static private
Returns minorClass as a JSON value.
This is equivalent to toString, except that if toString does not recognise minorClass as a sub-class of majorClass, then minorClass is returned as a JSON number (not a string).
See also
toString(const QBluetoothDeviceInfo::MajorDeviceClass &majorClass, const quint8 minorClass)
Definition at line 185 of file scancommand.cpp.
{
    const QString string = toString(majorClass, minorClass);
    return (string.isNull() ? QJsonValue(minorClass) : QJsonValue(string));
}
References toString().
toJson() [5/7]
QJsonArray ScanCommand::toJson (const QBluetoothDeviceInfo::ServiceClasses & classes) static private
Returns classes as a JSON array of strings.
Definition at line 194 of file scancommand.cpp.
{
    QJsonArray array;
    #define DOKIT_INTERNAL_IF_SET_THEN_APPEND(flag) \
        if (classes.testFlag(QBluetoothDeviceInfo::flag)) \
            array.append(QLatin1String(#flag))
    DOKIT_INTERNAL_IF_SET_THEN_APPEND(PositioningService);
    DOKIT_INTERNAL_IF_SET_THEN_APPEND(NetworkingService);
    DOKIT_INTERNAL_IF_SET_THEN_APPEND(RenderingService);
    DOKIT_INTERNAL_IF_SET_THEN_APPEND(CapturingService);
    DOKIT_INTERNAL_IF_SET_THEN_APPEND(ObjectTransferService);
    DOKIT_INTERNAL_IF_SET_THEN_APPEND(AudioService);
    DOKIT_INTERNAL_IF_SET_THEN_APPEND(TelephonyService);
    DOKIT_INTERNAL_IF_SET_THEN_APPEND(InformationService);
    #undef DOKIT_INTERNAL_IF_SET_THEN_APPEND
    return array;
}
toJson() [6/7]
QJsonArray ScanCommand::toJson (const QList< QBluetoothUuid > & uuids) static private
Returns uuids as a JSON array.
Definition at line 215 of file scancommand.cpp.
{
    QJsonArray array;
    for (const QBluetoothUuid &uuid: uuids) {
        array.append(uuid.toString());
    }
    return array;
}
References QJsonArray::append().
toJson() [7/7]
QJsonObject ScanCommand::toJson (const QMultiHash< quint16, QByteArray > & data) static private
Returns Bluetooth manufacturer data as a JSON object that maps the manufacturer IDs (unsigned integers as strings) to arrays of one or more values.
Definition at line 228 of file scancommand.cpp.
{
    QJsonObject object;
    QList<quint16> keys = data.uniqueKeys();
    std::sort(keys.begin(), keys.end());
    for (const quint16 key: keys) {
        // Convert the key's values to a JSON array, reversing the order, because QMultiHash
        // guarantees that the values are orderer "from the most recently inserted to the least
        // recently inserted", which is the oppoosit of what we want.
        QList<QByteArray> values = data.values(key);
        std::reverse(values.begin(), values.end());
        QJsonArray array;
        for (const QByteArray &value: values) {
            array.append(QLatin1String(value.toBase64()));
        }
        object.insert(QString::number(key), array);
    }
    return object;
}
References QJsonArray::append(), QList::begin(), QList::end(), QString::number(), QMultiHash::uniqueKeys(), and QMultiHash::values().
toString() [1/2]
QString ScanCommand::toString (const QBluetoothDeviceInfo::MajorDeviceClass & majorClass) static private
Returns majorClass as a human-readable string, or a null QString if majorClass is not recognised.
For example, if majorClass is QBluetoothDeviceInfo::ToyDevice, then the string ToyDevice is returned.
Definition at line 255 of file scancommand.cpp.
{
    #define DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(value) \
        if (majorClass == QBluetoothDeviceInfo::value) \
            return QLatin1String(#value)
    DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(MiscellaneousDevice);
    DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ComputerDevice);
    DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(PhoneDevice);
    #if (QT_VERSION < QT_VERSION_CHECK(5, 13, 0))
    DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(LANAccessDevice); // Deprecated since Qt 5.13.
    #else
    DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkDevice); // Added in Qt 5.13.
    #endif
    DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(AudioVideoDevice);
    DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(PeripheralDevice);
    DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ImagingDevice);
    DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WearableDevice);
    DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ToyDevice);
    DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HealthDevice);
    DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedDevice);
    #undef DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN
    qCDebug(lc).noquote() << tr("Unknown major class %1.").arg(majorClass);
    return QString(); // Null QString indicates unknown minor class.
}
References QString::arg(), and QObject::tr().
Referenced by deviceDiscovered(), and toJson().
toString() [2/2]
QString ScanCommand::toString (const QBluetoothDeviceInfo::MajorDeviceClass & majorClass, const quint8 minorClass) static private
Returns minorClass as a human-readable string, or a null QString if minorClass is not recognised as a sub-class of majorClass.
For example, if majorClass is QBluetoothDeviceInfo::ToyDevice, and minorClass is QBluetoothDeviceInfo::ToyRobot, then the string ToyRobot is returned.
Definition at line 287 of file scancommand.cpp.
{
    #define DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(value) \
        if (minorClass == QBluetoothDeviceInfo::value) \
            return QLatin1String(#value)
    switch (majorClass) {
    case QBluetoothDeviceInfo::MiscellaneousDevice:
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedMiscellaneous);
        break;
    case QBluetoothDeviceInfo::ComputerDevice:
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedComputer);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(DesktopComputer);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ServerComputer);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(LaptopComputer);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HandheldClamShellComputer);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HandheldComputer);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WearableComputer);
        break;
    case QBluetoothDeviceInfo::PhoneDevice:
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedPhone);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(CellularPhone);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(CordlessPhone);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(SmartPhone);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WiredModemOrVoiceGatewayPhone);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(CommonIsdnAccessPhone);
        break;
    #if (QT_VERSION < QT_VERSION_CHECK(5, 13, 0))
    case QBluetoothDeviceInfo::LANAccessDevice: // Deprecated since Qt 5.13.
    #else
    case QBluetoothDeviceInfo::NetworkDevice: // Added in Qt 5.13.
    #endif
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkFullService);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkLoadFactorOne);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkLoadFactorTwo);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkLoadFactorThree);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkLoadFactorFour);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkLoadFactorFive);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkLoadFactorSix);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkNoService);
        break;
    case QBluetoothDeviceInfo::AudioVideoDevice:
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedAudioVideoDevice);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WearableHeadsetDevice);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HandsFreeDevice);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(Microphone);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(Loudspeaker);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(Headphones);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(PortableAudioDevice);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(CarAudio);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(SetTopBox);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HiFiAudioDevice);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(Vcr);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(VideoCamera);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(Camcorder);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(VideoMonitor);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(VideoDisplayAndLoudspeaker);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(VideoConferencing);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(GamingDevice);
        break;
    case QBluetoothDeviceInfo::PeripheralDevice:
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedPeripheral);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(KeyboardPeripheral);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(PointingDevicePeripheral);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(KeyboardWithPointingDevicePeripheral);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(JoystickPeripheral);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(GamepadPeripheral);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(RemoteControlPeripheral);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(SensingDevicePeripheral);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(DigitizerTabletPeripheral);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(CardReaderPeripheral);
        break;
    case QBluetoothDeviceInfo::ImagingDevice:
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedImagingDevice);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ImageDisplay);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ImageCamera);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ImageScanner);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ImagePrinter);
        break;
    case QBluetoothDeviceInfo::WearableDevice:
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedWearableDevice);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WearableWristWatch);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WearablePager);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WearableJacket);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WearableHelmet);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WearableGlasses);
        break;
    case QBluetoothDeviceInfo::ToyDevice:
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedToy);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ToyRobot);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ToyVehicle);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ToyDoll);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ToyController);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ToyGame);
        break;
    case QBluetoothDeviceInfo::HealthDevice:
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedHealthDevice);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HealthBloodPressureMonitor);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HealthThermometer);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HealthWeightScale);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HealthGlucoseMeter);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HealthPulseOximeter);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HealthDataDisplay);
        DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HealthStepCounter);
        break;
    case QBluetoothDeviceInfo::UncategorizedDevice:
        // There are no minor classes defined (in Qt) for uncategorized devices.
        break;
    }
    #undef DOKIT_INTERNAL_IF_EQUAL_THEN_RETURN
    qCDebug(lc).noquote() << tr("Unknown minor class %1 for major class %2.")
        .arg(minorClass).arg(majorClass);
    return QString(); // Null QString indicates unknown minor class.
}
References QString::arg(), QBluetoothDeviceInfo::AudioVideoDevice, QBluetoothDeviceInfo::ComputerDevice, QBluetoothDeviceInfo::HealthDevice, QBluetoothDeviceInfo::ImagingDevice, QBluetoothDeviceInfo::LANAccessDevice, QBluetoothDeviceInfo::MiscellaneousDevice, QBluetoothDeviceInfo::NetworkDevice, QBluetoothDeviceInfo::PeripheralDevice, QBluetoothDeviceInfo::PhoneDevice, QBluetoothDeviceInfo::ToyDevice, QObject::tr(), QBluetoothDeviceInfo::UncategorizedDevice, and QBluetoothDeviceInfo::WearableDevice.
Friends And Related Function Documentation
TestScanCommand
friend class TestScanCommand friend
Definition at line 42 of file scancommand.h.
Member Data Documentation
showCsvHeader
bool ScanCommand::showCsvHeader { true } private
Whether or not to show a header as the first line of CSV output.
Definition at line 29 of file scancommand.h.
Referenced by deviceDiscovered().
The documentation for this class was generated from the following files:
scancommand.h
scancommand.cpp