QtPokit: PokitDevicePrivate Class Reference
PokitDevicePrivate Class Reference
The PokitDevicePrivate class provides private implementation for PokitDevice.
Public Slots
void connected ()
Handle connected signals.
void connectionUpdated (const QLowEnergyConnectionParameters &newParameters)
Handle connectionUpdated signals.
void disconnected ()
Handle disconnected signals.
void discoveryFinished ()
Handle discoveryFinished signals.
void errorOccurred (QLowEnergyController::Error newError)
Handle error signals.
void serviceDiscovered (const QBluetoothUuid &newService)
Handle serviceDiscovered signals.
void stateChanged (QLowEnergyController::ControllerState state)
Handle stateChanged signals.
Public Member Functions
PokitDevicePrivate (PokitDevice *const q)
Constructs a new PokitDevicePrivate object with public implementation q.
void setController (QLowEnergyController *newController)
Sets newController to be used for accessing Pokit devices.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
virtual void * qt_metacast (const char *)
virtual int qt_metacall (QMetaObject::Call, int, void **)
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Static Public Member Functions
static Q_LOGGING_CATEGORY (lc, "pokit.ble.controller", QtInfoMsg)
Logging category.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes
QLowEnergyController * controller
BLE controller for accessing the Pokit device.
CalibrationService * calibration
Calibration service for this Pokit device.
DataLoggerService * dataLogger
Data Logger service for this Pokit device.
DeviceInfoService * deviceInfo
Device Info service for this Pokit device.
DsoService * dso
DSO service for this Pokit device.
GenericAccessService * genericAccess
Generic Access service for this Pokit device.
MultimeterService * multimeter
Multimeter service for this Pokit device.
StatusService * status
Status service for this Pokit device.
QMutex calibrationMutex
Mutex for protecting access to calibration.
QMutex dataLoggerMutex
Mutex for protecting access to dataLogger.
QMutex deviceInfoMutex
Mutex for protecting access to deviceInfo.
QMutex dsoMutex
Mutex for protecting access to dso.
QMutex genericAccessMutex
Mutex for protecting access to genericAccess.
QMutex multimeterMutex
Mutex for protecting access to multimeter.
QMutex statusMutex
Mutex for protecting access to status.
Protected Attributes
PokitDevice * q_ptr
Internal q-pointer.
Friends
class TestPokitDevice
Additional Inherited Members
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
The PokitDevicePrivate class provides private implementation for PokitDevice.
Definition at line 48 of file pokitdevice_p.h.
Constructor & Destructor Documentation
PokitDevicePrivate()
PokitDevicePrivate::PokitDevicePrivate (PokitDevice *const q) explicit
Constructs a new PokitDevicePrivate object with public implementation q.
Definition at line 236 of file pokitdevice.cpp.
    : controller(nullptr), calibration(nullptr), dataLogger(nullptr), deviceInfo(nullptr),
      dso(nullptr), genericAccess(nullptr), multimeter(nullptr), status(nullptr), q_ptr(q)
{
}
Member Function Documentation
connected
void PokitDevicePrivate::connected () slot
Handle connected signals.
Definition at line 311 of file pokitdevice.cpp.
{
    qCDebug(lc).noquote() << tr("Connected to \"%1\" (%2) at (%3).").arg(
        controller->remoteName(), controller->remoteDeviceUuid().toString(),
        controller->remoteAddress().toString());
}
References QString::arg(), controller, QLowEnergyController::remoteAddress(), QLowEnergyController::remoteDeviceUuid(), QLowEnergyController::remoteName(), QBluetoothAddress::toString(), QUuid::toString(), and QObject::tr().
Referenced by setController().
connectionUpdated
void PokitDevicePrivate::connectionUpdated (const QLowEnergyConnectionParameters & newParameters) slot
Handle connectionUpdated signals.
Definition at line 321 of file pokitdevice.cpp.
{
    qCDebug(lc).noquote() << tr("Connection updated:") << newParameters.latency()
        << newParameters.minimumInterval() << newParameters.maximumInterval()
        << newParameters.supervisionTimeout();
}
References QLowEnergyConnectionParameters::latency(), QLowEnergyConnectionParameters::maximumInterval(), QLowEnergyConnectionParameters::minimumInterval(), QLowEnergyConnectionParameters::supervisionTimeout(), and QObject::tr().
Referenced by setController().
disconnected
void PokitDevicePrivate::disconnected () slot
Handle disconnected signals.
Definition at line 331 of file pokitdevice.cpp.
{
    qCDebug(lc).noquote() << tr("Device disconnected.");
}
References QObject::tr().
Referenced by setController().
discoveryFinished
void PokitDevicePrivate::discoveryFinished () slot
Handle discoveryFinished signals.
Definition at line 339 of file pokitdevice.cpp.
{
    qCDebug(lc).noquote() << tr("Service discovery finished.");
}
References QObject::tr().
Referenced by setController().
errorOccurred
void PokitDevicePrivate::errorOccurred (QLowEnergyController::Error newError) slot
Handle error signals.
Definition at line 347 of file pokitdevice.cpp.
{
    qCDebug(lc).noquote() << tr("Controller error:") << newError;
}
References QObject::tr().
Referenced by setController().
serviceDiscovered
void PokitDevicePrivate::serviceDiscovered (const QBluetoothUuid & newService) slot
Handle serviceDiscovered signals.
Definition at line 355 of file pokitdevice.cpp.
{
    qCDebug(lc).noquote() << tr("Service discovered:") << newService;
}
References QObject::tr().
Referenced by setController().
setController()
void PokitDevicePrivate::setController (QLowEnergyController * newController)
Sets newController to be used for accessing Pokit devices.
If a controller has already been set (and is not the same pointer), then the previous controller will be disconnected, and replaced with newController.
This function will not take ownership of the new controller. The caller is responsible for ensuring that newContorller remains valid for the lifetime of this instance, or until this function is used again to replace newController with another one (which may be a nullptr).
See also
controller
PokitDevice::controller()
Definition at line 256 of file pokitdevice.cpp.
{
    if (newController == this->controller) {
        qCDebug(lc).noquote() << tr("Controller already set to:") << newController;
        return;
    }
    if (this->controller) {
        qCDebug(lc).noquote() << tr("Disconnecting signals from previous controller:")
            << controller;
        disconnect(this->controller, nullptr, this, nullptr);
    }
    qCDebug(lc).noquote() << tr("Setting new controller:") << newController;
    this->controller = newController;
    if (!newController) {
        return; // Don't bother continuing to connect if new controller is null.
    }
    qCDebug(lc).noquote() << tr("Set new controller \"%1\" (%2) at (%3).").arg(
        controller->remoteName(), controller->remoteDeviceUuid().toString(),
        controller->remoteAddress().toString());
    connect(controller, &QLowEnergyController::connected,
            this, &PokitDevicePrivate::connected);
    connect(controller, &QLowEnergyController::connectionUpdated,
            this, &PokitDevicePrivate::connectionUpdated);
    connect(controller, &QLowEnergyController::disconnected,
            this, &PokitDevicePrivate::disconnected);
    connect(controller, &QLowEnergyController::discoveryFinished,
            this, &PokitDevicePrivate::discoveryFinished);
    connect(controller,
    #if (QT_VERSION < QT_VERSION_CHECK(6, 2, 0))
        QOverload<QLowEnergyController::Error>::of(&QLowEnergyController::error),
    #else
        &QLowEnergyController::errorOccurred,
    #endif
        this, &PokitDevicePrivate::errorOccurred);
    connect(controller, &QLowEnergyController::serviceDiscovered,
            this, &PokitDevicePrivate::serviceDiscovered);
    connect(controller, &QLowEnergyController::stateChanged,
            this, &PokitDevicePrivate::stateChanged);
}
References QString::arg(), QObject::connect(), connected(), QLowEnergyController::connected(), connectionUpdated(), QLowEnergyController::connectionUpdated(), controller, QObject::disconnect(), disconnected(), QLowEnergyController::disconnected(), discoveryFinished(), QLowEnergyController::discoveryFinished(), QLowEnergyController::error(), errorOccurred(), QLowEnergyController::remoteAddress(), QLowEnergyController::remoteDeviceUuid(), QLowEnergyController::remoteName(), serviceDiscovered(), QLowEnergyController::serviceDiscovered(), stateChanged(), QLowEnergyController::stateChanged(), QBluetoothAddress::toString(), QUuid::toString(), and QObject::tr().
stateChanged
void PokitDevicePrivate::stateChanged (QLowEnergyController::ControllerState state) slot
Handle stateChanged signals.
Definition at line 363 of file pokitdevice.cpp.
{
    qCDebug(lc).noquote() << tr("State changed to:") << state;
}
References QObject::tr().
Referenced by setController().
Friends And Related Function Documentation
TestPokitDevice
friend class TestPokitDevice friend
Definition at line 92 of file pokitdevice_p.h.
Member Data Documentation
calibration
CalibrationService* PokitDevicePrivate::calibration
Calibration service for this Pokit device.
Definition at line 57 of file pokitdevice_p.h.
calibrationMutex
QMutex PokitDevicePrivate::calibrationMutex
Mutex for protecting access to calibration.
Definition at line 65 of file pokitdevice_p.h.
controller
QLowEnergyController* PokitDevicePrivate::controller
BLE controller for accessing the Pokit device.
Definition at line 55 of file pokitdevice_p.h.
Referenced by connected(), and setController().
dataLogger
DataLoggerService* PokitDevicePrivate::dataLogger
Data Logger service for this Pokit device.
Definition at line 58 of file pokitdevice_p.h.
dataLoggerMutex
QMutex PokitDevicePrivate::dataLoggerMutex
Mutex for protecting access to dataLogger.
Definition at line 66 of file pokitdevice_p.h.
deviceInfo
DeviceInfoService* PokitDevicePrivate::deviceInfo
Device Info service for this Pokit device.
Definition at line 59 of file pokitdevice_p.h.
deviceInfoMutex
QMutex PokitDevicePrivate::deviceInfoMutex
Mutex for protecting access to deviceInfo.
Definition at line 67 of file pokitdevice_p.h.
dso
DsoService* PokitDevicePrivate::dso
DSO service for this Pokit device.
Definition at line 60 of file pokitdevice_p.h.
dsoMutex
QMutex PokitDevicePrivate::dsoMutex
Mutex for protecting access to dso.
Definition at line 68 of file pokitdevice_p.h.
genericAccess
GenericAccessService* PokitDevicePrivate::genericAccess
Generic Access service for this Pokit device.
Definition at line 61 of file pokitdevice_p.h.
genericAccessMutex
QMutex PokitDevicePrivate::genericAccessMutex
Mutex for protecting access to genericAccess.
Definition at line 69 of file pokitdevice_p.h.
multimeter
MultimeterService* PokitDevicePrivate::multimeter
Multimeter service for this Pokit device.
Definition at line 62 of file pokitdevice_p.h.
multimeterMutex
QMutex PokitDevicePrivate::multimeterMutex
Mutex for protecting access to multimeter.
Definition at line 70 of file pokitdevice_p.h.
q_ptr
PokitDevice* PokitDevicePrivate::q_ptr protected
Internal q-pointer.
Definition at line 87 of file pokitdevice_p.h.
status
StatusService* PokitDevicePrivate::status
Status service for this Pokit device.
Definition at line 63 of file pokitdevice_p.h.
statusMutex
QMutex PokitDevicePrivate::statusMutex
Mutex for protecting access to status.
Definition at line 71 of file pokitdevice_p.h.
The documentation for this class was generated from the following files:
pokitdevice_p.h
pokitdevice.cpp