QtPokit: PokitDiscoveryAgent Class Reference
PokitDiscoveryAgent Class Reference
The PokitDiscoveryAgent class discovers nearby Pokit devices.
Public Slots
void start (QBluetoothDeviceDiscoveryAgent::DiscoveryMethods methods)
Starts Pokit device discovery.
void start ()
Starts Pokit device discovery.
Signals
void pokitDeviceDiscovered (const QBluetoothDeviceInfo &info)
This signal is emitted when the Pokit device described by info is discovered.
void pokitDeviceUpdated (const QBluetoothDeviceInfo &info, QBluetoothDeviceInfo::Fields updatedFields)
This signal is emitted when the Pokit device described by info is updated.
Public Member Functions
PokitDiscoveryAgent (const QBluetoothAddress &deviceAdapter, QObject *parent=nullptr)
Constructs a new Pokit device discovery agent with parent, using deviceAdapter for the search device.
PokitDiscoveryAgent (QObject *parent=nullptr)
Constructs a new Pokit device discovery agent with parent.
virtual ~PokitDiscoveryAgent ()
Destroys this PokitDiscoveryAgent object.
Public Member Functions inherited from QBluetoothDeviceDiscoveryAgent
QBluetoothDeviceDiscoveryAgent (QObject *parent)
QBluetoothDeviceDiscoveryAgent (const QBluetoothAddress &deviceAdapter, QObject *parent)
QBluetoothDeviceDiscoveryAgent::InquiryType inquiryType () const const
void setInquiryType (QBluetoothDeviceDiscoveryAgent::InquiryType type)
bool isActive () const const
QBluetoothDeviceDiscoveryAgent::Error error () const const
QString errorString () const const
QList< QBluetoothDeviceInfo > discoveredDevices () const const
void setLowEnergyDiscoveryTimeout (int timeout)
int lowEnergyDiscoveryTimeout () const const
void start ()
void start (QBluetoothDeviceDiscoveryAgent::DiscoveryMethods methods)
void stop ()
void deviceDiscovered (const QBluetoothDeviceInfo &info)
void deviceUpdated (const QBluetoothDeviceInfo &info, QBluetoothDeviceInfo::Fields updatedFields)
void finished ()
void error (QBluetoothDeviceDiscoveryAgent::Error error)
void canceled ()
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Member Functions
static bool isPokitDevice (const QBluetoothDeviceInfo &info)
Returns true if info describes a Pokit device.
static bool isPokitMeter (const QBluetoothDeviceInfo &info)
Returns true if info describes a Pokit Meter device.
static bool isPokitPro (const QBluetoothDeviceInfo &info)
Returns true if info describes a Pokit Pro device.
Static Public Member Functions inherited from QBluetoothDeviceDiscoveryAgent
QBluetoothDeviceDiscoveryAgent::DiscoveryMethods supportedDiscoveryMethods ()
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Protected Member Functions
PokitDiscoveryAgent (PokitDiscoveryAgentPrivate *const d, const QBluetoothAddress &deviceAdapter, QObject *const parent)
Constructs a new Pokit device discovery agent with parent, using deviceAdapter for the search device, and private implementation d.
PokitDiscoveryAgent (PokitDiscoveryAgentPrivate *const d, QObject *const parent)
Constructs a new Pokit device discovery agent with parent, and private implementation d.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Attributes
PokitDiscoveryAgentPrivate * d_ptr
Internal d-pointer.
Friends
class TestPokitDiscoveryAgent
Additional Inherited Members
Public Types inherited from QBluetoothDeviceDiscoveryAgent
enum Error
enum InquiryType
enum DiscoveryMethod
Public Attributes inherited from QBluetoothDeviceDiscoveryAgent
typedef DiscoveryMethods
NoError
InputOutputError
PoweredOffError
InvalidBluetoothAdapterError
UnsupportedPlatformError
UnsupportedDiscoveryMethod
UnknownError
GeneralUnlimitedInquiry
LimitedInquiry
NoMethod
ClassicMethod
LowEnergyMethod
Public Attributes inherited from QObject
typedef QObjectList
Properties inherited from QBluetoothDeviceDiscoveryAgent
inquiryType
Properties inherited from QObject
objectName
Detailed Description
The PokitDiscoveryAgent class discovers nearby Pokit devices.
After constructing a PokitDiscoveryAgent object, and subscribing to the relevant signals, invoke start() to begin discovery.
Definition at line 20 of file pokitdiscoveryagent.h.
Constructor & Destructor Documentation
PokitDiscoveryAgent() [1/4]
PokitDiscoveryAgent::PokitDiscoveryAgent (const QBluetoothAddress & deviceAdapter, QObject * parent = nullptr) explicit
Constructs a new Pokit device discovery agent with parent, using deviceAdapter for the search device.
Definition at line 29 of file pokitdiscoveryagent.cpp.
    : QBluetoothDeviceDiscoveryAgent(deviceAdapter, parent),
      d_ptr(new PokitDiscoveryAgentPrivate(this))
{
}
PokitDiscoveryAgent() [2/4]
PokitDiscoveryAgent::PokitDiscoveryAgent (QObject * parent = nullptr)
Constructs a new Pokit device discovery agent with parent.
Definition at line 40 of file pokitdiscoveryagent.cpp.
    : QBluetoothDeviceDiscoveryAgent(parent),
      d_ptr(new PokitDiscoveryAgentPrivate(this))
{
}
~PokitDiscoveryAgent()
PokitDiscoveryAgent::~PokitDiscoveryAgent () virtual
Destroys this PokitDiscoveryAgent object.
Definition at line 74 of file pokitdiscoveryagent.cpp.
{
    delete d_ptr;
}
References d_ptr.
PokitDiscoveryAgent() [3/4]
PokitDiscoveryAgent::PokitDiscoveryAgent (PokitDiscoveryAgentPrivate *const d, const QBluetoothAddress & deviceAdapter, QObject *const parent) protected
Constructs a new Pokit device discovery agent with parent, using deviceAdapter for the search device, and private implementation d.
Definition at line 52 of file pokitdiscoveryagent.cpp.
    : QBluetoothDeviceDiscoveryAgent(deviceAdapter, parent), d_ptr(d)
{
}
PokitDiscoveryAgent() [4/4]
PokitDiscoveryAgent::PokitDiscoveryAgent (PokitDiscoveryAgentPrivate *const d, QObject *const parent) protected
Constructs a new Pokit device discovery agent with parent, and private implementation d.
Definition at line 63 of file pokitdiscoveryagent.cpp.
    : QBluetoothDeviceDiscoveryAgent(parent), d_ptr(d)
{
}
Member Function Documentation
isPokitDevice()
bool PokitDiscoveryAgent::isPokitDevice (const QBluetoothDeviceInfo & info) static
Returns true if info describes a Pokit device.
Currently, this is based on whether or not info's service UUIDs includes a known Pokit service, but this test criteria might be swapped for something else sometime.
Definition at line 85 of file pokitdiscoveryagent.cpp.
{
    return (isPokitMeter(info) || isPokitPro(info));
}
References isPokitMeter(), and isPokitPro().
isPokitMeter()
bool PokitDiscoveryAgent::isPokitMeter (const QBluetoothDeviceInfo & info) static
Returns true if info describes a Pokit Meter device.
Currently, this is based on whether or not info's service UUIDs includes a known Pokit service, but this test criteria might be swapped for something else sometime.
Definition at line 96 of file pokitdiscoveryagent.cpp.
{
    return info.serviceUuids().contains(StatusService::ServiceUuids::pokitMeter);
}
References StatusService::ServiceUuids::pokitMeter, and QBluetoothDeviceInfo::serviceUuids().
Referenced by isPokitDevice().
isPokitPro()
bool PokitDiscoveryAgent::isPokitPro (const QBluetoothDeviceInfo & info) static
Returns true if info describes a Pokit Pro device.
Currently, this is based on whether or not info's service UUIDs includes a known Pokit service, but this test criteria might be swapped for something else sometime.
Definition at line 107 of file pokitdiscoveryagent.cpp.
{
    return info.serviceUuids().contains(StatusService::ServiceUuids::pokitPro);
}
References StatusService::ServiceUuids::pokitPro, and QBluetoothDeviceInfo::serviceUuids().
Referenced by isPokitDevice().
pokitDeviceUpdated
void PokitDiscoveryAgent::pokitDeviceUpdated (const QBluetoothDeviceInfo & info, QBluetoothDeviceInfo::Fields updatedFields) signal
This signal is emitted when the Pokit device described by info is updated.
The updatedFields flags tell which information has been updated.
Referenced by ScanCommand::ScanCommand().
start [1/2]
void PokitDiscoveryAgent::start () slot
Starts Pokit device discovery.
Definition at line 129 of file pokitdiscoveryagent.cpp.
{
    Q_D(PokitDiscoveryAgent);
    qCDebug(d->lc).noquote() << tr("Scanning for Bluetooth Low Energy devices.");
    QBluetoothDeviceDiscoveryAgent::start(QBluetoothDeviceDiscoveryAgent::LowEnergyMethod);
}
References QBluetoothDeviceDiscoveryAgent::LowEnergyMethod, QBluetoothDeviceDiscoveryAgent::start(), and QObject::tr().
start [2/2]
void PokitDiscoveryAgent::start (QBluetoothDeviceDiscoveryAgent::DiscoveryMethods methods) slot
Starts Pokit device discovery.
This override simply enforces that method must be LowEnergyMethod, as all Pokit devices used Bluetooth Low Energy (BLE).
Definition at line 118 of file pokitdiscoveryagent.cpp.
{
    Q_D(PokitDiscoveryAgent);
    Q_ASSERT(methods == QBluetoothDeviceDiscoveryAgent::LowEnergyMethod);
    qCDebug(d->lc).noquote() << tr("Scanning for Bluetooth Low Energy devices.");
    QBluetoothDeviceDiscoveryAgent::start(QBluetoothDeviceDiscoveryAgent::LowEnergyMethod);
}
References QBluetoothDeviceDiscoveryAgent::LowEnergyMethod, QBluetoothDeviceDiscoveryAgent::start(), and QObject::tr().
Referenced by DeviceCommand::start(), and ScanCommand::start().
Friends And Related Function Documentation
TestPokitDiscoveryAgent
friend class TestPokitDiscoveryAgent friend
Definition at line 54 of file pokitdiscoveryagent.h.
Member Data Documentation
d_ptr
PokitDiscoveryAgentPrivate* PokitDiscoveryAgent::d_ptr protected
Internal d-pointer.
Definition at line 45 of file pokitdiscoveryagent.h.
Referenced by ~PokitDiscoveryAgent().
The documentation for this class was generated from the following files:
pokitdiscoveryagent.h
pokitdiscoveryagent.cpp