QtPokit: AbstractCommand Class Reference
AbstractCommand Class Reference abstract
The AbstractCommand class provides a consistent base for the classes that implement CLI commands.
Public Types
enum class OutputFormat { Csv , Json , Text }
Supported output formats.
Public Slots
virtual QStringList processOptions (const QCommandLineParser &parser)
Processes the relevant options from the command line parser.
virtual bool start ()=0
Begins the functionality of this command, and returns true if begun successfully, false otherwise.
Public Member Functions
AbstractCommand (QObject *const parent)
Constructs a new command with parent.
virtual QStringList requiredOptions (const QCommandLineParser &parser) const
Returns a list of CLI option names required by this command.
virtual QStringList supportedOptions (const QCommandLineParser &parser) const
Returns a list of CLI option names supported by this command.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
virtual void * qt_metacast (const char *)
virtual int qt_metacall (QMetaObject::Call, int, void **)
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Static Public Member Functions
static QString escapeCsvField (const QString &field)
Returns an RFC 4180 compliant version of field.
static quint32 parseMicroValue (const QString &value, const QString &unit, const quint32 sensibleMinimum=0)
Returns value as a number of micros, such as microseconds, or microvolts.
static quint32 parseMilliValue (const QString &value, const QString &unit, const quint32 sensibleMinimum=0)
Returns value as a number of millis, such as milliseconds, or millivolts.
static quint32 parseWholeValue (const QString &value, const QString &unit)
Returns value as a number, with optional SI unit prefix, and optional unit suffix.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Protected Member Functions
virtual void deviceDiscovered (const QBluetoothDeviceInfo &info)=0
Handles PokitDiscoveryAgent::pokitDeviceDiscovered signal.
virtual void deviceDiscoveryFinished ()=0
Handles PokitDiscoveryAgent::deviceDiscoveryFinished signal.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Static Protected Member Functions
static Q_LOGGING_CATEGORY (lc, "pokit.ui.command", QtInfoMsg)
Logging category for UI commands.
Protected Attributes
PokitDiscoveryAgent * discoveryAgent
Agent for Pokit device descovery.
OutputFormat format
Selected output format.
QString deviceToScanFor
Device (if any) that were passed to processOptions().
Friends
class TestAbstractCommand
Additional Inherited Members
Properties inherited from QObject
objectName
Detailed Description
The AbstractCommand class provides a consistent base for the classes that implement CLI commands.
Definition at line 30 of file abstractcommand.h.
Member Enumeration Documentation
OutputFormat
enum class AbstractCommand::OutputFormat strong
Supported output formats.
Enumerator
Csv
RFC 4180 compliant CSV text.
Json
RFC 8259 compliant JSON text.
Text
Plain unstructured text.
Definition at line 33 of file abstractcommand.h.
{
        Csv,  ///< RFC 4180 compliant CSV text.
        Json, ///< RFC 8259 compliant JSON text.
        Text, ///< Plain unstructured text.
    };
Constructor & Destructor Documentation
AbstractCommand()
AbstractCommand::AbstractCommand (QObject *const parent) explicit
Constructs a new command with parent.
Definition at line 39 of file abstractcommand.cpp.
                                                       : QObject(parent),
    discoveryAgent(new PokitDiscoveryAgent(this)), format(OutputFormat::Text)
{
    connect(discoveryAgent, &PokitDiscoveryAgent::pokitDeviceDiscovered,
            this, &AbstractCommand::deviceDiscovered);
    connect(discoveryAgent, &PokitDiscoveryAgent::finished,
            this, &AbstractCommand::deviceDiscoveryFinished);
    connect(discoveryAgent,
        #if (QT_VERSION < QT_VERSION_CHECK(6, 2, 0))
        QOverload<PokitDiscoveryAgent::Error>::of(&PokitDiscoveryAgent::error),
        #else
        &PokitDiscoveryAgent::errorOccurred,
        #endif
    [](const PokitDiscoveryAgent::Error &error) {
        qCWarning(lc).noquote() << tr("Bluetooth controller error:") << error;
        QCoreApplication::exit(EXIT_FAILURE);
    });
}
References QObject::connect(), deviceDiscovered(), deviceDiscoveryFinished(), discoveryAgent, QBluetoothDeviceDiscoveryAgent::error(), QCoreApplication::exit(), QBluetoothDeviceDiscoveryAgent::finished(), PokitDiscoveryAgent::pokitDeviceDiscovered(), and QObject::tr().
Member Function Documentation
deviceDiscovered()
void AbstractCommand::deviceDiscovered (const QBluetoothDeviceInfo & info) protected pure virtual
Handles PokitDiscoveryAgent::pokitDeviceDiscovered signal.
Derived classes must implement this slot to begin whatever actions are relevant when a Pokit device has been discovered. For example, the 'scan' command would simply output the info details, whereas most other commands would begin connecting if info is the device they're after.
Referenced by AbstractCommand().
deviceDiscoveryFinished()
void AbstractCommand::deviceDiscoveryFinished () protected pure virtual
Handles PokitDiscoveryAgent::deviceDiscoveryFinished signal.
Derived classes must implement this slot to perform whatever actions are appropraite when discovery is finished. For example, the 'scan' command would simply exit, whereas most other commands would verify that an appropriate device was found.
Referenced by AbstractCommand().
escapeCsvField()
QString AbstractCommand::escapeCsvField (const QString & field) static
Returns an RFC 4180 compliant version of field.
That is, if field contains any of the the below four characters, than any double quotes are escaped (by addition double-quotes), and the string itself surrounded in double-quotes. Otherwise, field is returned verbatim.
Some examples:
QCOMPARE(escapeCsvField("abc"), "abc");       // Returned unchanged.
QCOMPARE(escapeCsvField("a,c"), "\"a,c\"");   // Wrapped in double-quotes.
QCOMPARE(escapeCsvField("a\"c"), "\"a""c\""); // Existing double-quotes doubles, then wrapped.
Definition at line 119 of file abstractcommand.cpp.
{
    if (field.contains(QLatin1Char(','))||field.contains(QLatin1Char('\r'))||
        field.contains(QLatin1Char('"'))||field.contains(QLatin1Char('\n')))
    {
        return QString::fromLatin1("\"%1\"").arg(
            QString(field).replace(QLatin1Char('"'), QLatin1String("\"\"")));
    } else return field;
}
References QString::arg(), QString::contains(), and QString::fromLatin1().
Referenced by ScanCommand::deviceDiscovered(), MeterCommand::outputReading(), InfoCommand::serviceDetailsDiscovered(), and StatusCommand::serviceDetailsDiscovered().
parseMicroValue()
quint32 AbstractCommand::parseMicroValue (const QString & value, const QString & unit, const quint32 sensibleMinimum = 0) static
Returns value as a number of micros, such as microseconds, or microvolts.
The string value may end with the optional unit, such as V or s, which may also be preceded with a SI unit prefix such as m for milli. If value contains no SI unit prefix, then the result will be multiplied by 1,000 enough times to be greater than sensibleMinimum. This allows for convenient use like:
const quin32t timeout = parseMicroValue(parser.value("window"), 's', 500*1000);
So that an unqalified period like "300" will be assumed to be 300 milliseconds, and not 300 microseconds, while a period like "1000" will be assume to be 1 second.
If conversion fails for any reason, 0 is returned.
Definition at line 145 of file abstractcommand.cpp.
{
    // Remove the optional (whole) unit suffix.
    quint32 scale = 0;
    QString number = value.trimmed();
    if (number.endsWith(unit, Qt::CaseInsensitive)) {
        number.chop(unit.length());
        scale = 1000 * 1000;
    }
    // Parse, and remove, the optional SI unit prefix.
    if (number.endsWith(QLatin1String("m"))) {
        number.chop(1);
        scale = 1000;
    }
    // Parse, and remove, the optional SI unit prefix.
    if (number.endsWith(QLatin1String("u"))) {
        number.chop(1);
        scale = 1;
    }
    // Parse the number as an (unsigned) integer.
    QLocale locale; bool ok;
    const quint32 integer = locale.toUInt(number, &ok);
    if (ok) {
        if ((scale == 0) && (integer != 0)) {
            for (scale = 1; (integer * scale) < sensibleMinimum; scale *= 1000);
        }
        return integer * scale;
    }
    // Parse the number as a (double) floating point number.
    const double dbl = locale.toDouble(number, &ok);
    if (ok) {
        if ((scale == 0) && (dbl > 0.0)) {
            for (scale = 1; (dbl * scale) < sensibleMinimum; scale *= 1000);
        }
        return dbl * scale;
    }
    return 0; // Failed to parse as either integer, or float.
}
References QString::chop(), QString::endsWith(), QString::length(), QLocale::toDouble(), QLocale::toUInt(), and QString::trimmed().
Referenced by DsoCommand::processOptions().
parseMilliValue()
quint32 AbstractCommand::parseMilliValue (const QString & value, const QString & unit, const quint32 sensibleMinimum = 0) static
Returns value as a number of millis, such as milliseconds, or millivolts.
The string value may end with the optional unit, such as V or s, which may also be preceded with a SI unit prefix such as m for milli. If value contains no SI unit prefix, then the result will be multiplied by 1,000 enough times to be greater than sensibleMinimum. This allows for convenient use like:
const quin32t timeout = parseMilliValue(parser.value("timeout"), 's', 600);
So that an unqalified period like "300" will be assumed to be 300 seconds, and not 300 milliseconds, while a period like "1000" will be assume to be 1 second.
If conversion fails for any reason, 0 is returned.
Definition at line 206 of file abstractcommand.cpp.
{
    // Remove the optional (whole) unit suffix.
    quint32 scale = 0;
    QString number = value.trimmed();
    if (number.endsWith(unit, Qt::CaseInsensitive)) {
        number.chop(unit.length());
        scale = 1000;
    }
    // Parse, and remove, the optional SI unit prefix.
    if (number.endsWith(QLatin1String("m"))) {
        number.chop(1);
        scale = 1;
    }
    // Parse the number as an (unsigned) integer.
    QLocale locale; bool ok;
    const quint32 integer = locale.toUInt(number, &ok);
    if (ok) {
        if ((scale == 0) && (integer != 0)) {
            for (scale = 1; (integer * scale) < sensibleMinimum; scale *= 1000);
        }
        return integer * scale;
    }
    // Parse the number as a (double) floating point number.
    const double dbl = locale.toDouble(number, &ok);
    if (ok) {
        if ((scale == 0) && (dbl > 0.0)) {
            for (scale = 1; (dbl * scale) < sensibleMinimum; scale *= 1000);
        }
        return dbl * scale;
    }
    return 0; // Failed to parse as either integer, or float.
}
References QString::chop(), QString::endsWith(), QString::length(), QLocale::toDouble(), QLocale::toUInt(), and QString::trimmed().
Referenced by processOptions(), DsoCommand::processOptions(), LoggerStartCommand::processOptions(), and MeterCommand::processOptions().
parseWholeValue()
quint32 AbstractCommand::parseWholeValue (const QString & value, const QString & unit) static
Returns value as a number, with optional SI unit prefix, and optional unit suffix.
For example:
QCOMPARE(parseWholeValue("1.2Mohm", "ohm"), 1200000);
If conversion fails for any reason, 0 is returned.
Definition at line 255 of file abstractcommand.cpp.
{
    // Remove the optional unit suffix.
    QString number = value.trimmed();
    if (number.endsWith(unit, Qt::CaseInsensitive)) {
        number.chop(unit.length());
    }
    // Parse, and remove, the optional SI unit prefix.
    quint32 scale = 1;
    if (number.endsWith(QLatin1String("k"))) {
        number.chop(1);
        scale = 1000;
    } else if (number.endsWith(QLatin1String("M"))) {
        number.chop(1);
        scale = 1000 * 1000;
    }
    // Parse the number as an (unsigned) integer.
    QLocale locale; bool ok;
    const quint16 integer = locale.toUInt(number, &ok);
    if (ok) {
        return integer * scale;
    }
    // Parse the number as a (double) floating point number.
    const double dbl = locale.toDouble(number, &ok);
    if (ok) {
        return dbl * scale;
    }
    return 0; // Failed to parse as either integer, or float.
}
References QString::chop(), QString::endsWith(), QString::length(), QLocale::toDouble(), QLocale::toUInt(), and QString::trimmed().
Referenced by DsoCommand::processOptions(), and MeterCommand::processOptions().
processOptions
QStringList AbstractCommand::processOptions (const QCommandLineParser & parser) virtual slot
Processes the relevant options from the command line parser.
On success, returns an empty QStringList, otherwise returns a list of CLI errors that the caller should report appropriately before exiting.
This base implementations performs some common checks, such as ensuring that required options are present. Derived classes should override this function to perform further processing, typically inovking this base implementation as a first step, such as:
QStringList CustomCommand::processOptions(const QCommandLineParser &parser)
{
    QStringList errors = AbstractCommand::processOptions(parser);
    if (!errors.isEmpty()) {
        return errors;
    }
    // Do further procession of options.
    return errors;
}
Definition at line 313 of file abstractcommand.cpp.
{
    // Report any supplied options that are not supported by this command.
    const QStringList suppliedOptions = parser.optionNames();
    const QStringList supportedOptions = this->supportedOptions(parser);
    for (const QString &option: suppliedOptions) {
        if (!supportedOptions.contains(option)) {
            qCInfo(lc).noquote() << tr("Ignoring option: %1").arg(option);
        }
    }
    QStringList errors;
    // Parse the device (name/addr/uuid) option.
    if (parser.isSet(QLatin1String("device"))) {
        deviceToScanFor = parser.value(QLatin1String("device"));
    }
    // Parse the output format options (if supported, and supplied).
    if ((supportedOptions.contains(QLatin1String("output"))) && // Derived classes may have removed.
        (parser.isSet(QLatin1String("output"))))
    {
        const QString output = parser.value(QLatin1String("output")).toLower();
        if (output == QLatin1String("csv")) {
            format = OutputFormat::Csv;
        } else if (output == QLatin1String("json")) {
            format = OutputFormat::Json;
        } else if (output == QLatin1String("text")) {
            format = OutputFormat::Text;
        } else {
            errors.append(tr("Unknown output format: %1").arg(output));
        }
    }
    // Parse the device scan timeout option.
    if (parser.isSet(QLatin1String("timeout"))) {
        const quint32 timeout = parseMilliValue(parser.value(QLatin1String("timeout")),
                                                QLatin1String("s"), 500);
        if (timeout == 0) {
            errors.append(tr("Invalid timeout: %1").arg(parser.value(QLatin1String("timeout"))));
        } else {
            discoveryAgent->setLowEnergyDiscoveryTimeout(timeout);
            qCDebug(lc).noquote() << tr("Set scan timeout to %1").arg(
                discoveryAgent->lowEnergyDiscoveryTimeout());
        }
    }
    // Return errors for any required options that are absent.
    const QStringList requiredOptions = this->requiredOptions(parser);
    for (const QString &option: requiredOptions) {
        if (!parser.isSet(option)) {
            errors.append(tr("Missing required option: %1").arg(option));
        }
    }
    return errors;
}
References QList::append(), QString::arg(), QStringList::contains(), Csv, deviceToScanFor, discoveryAgent, format, QCommandLineParser::isSet(), Json, QBluetoothDeviceDiscoveryAgent::lowEnergyDiscoveryTimeout(), QCommandLineParser::optionNames(), parseMilliValue(), requiredOptions(), QBluetoothDeviceDiscoveryAgent::setLowEnergyDiscoveryTimeout(), supportedOptions(), Text, QString::toLower(), QObject::tr(), and QCommandLineParser::value().
Referenced by CalibrationCommand::processOptions(), DsoCommand::processOptions(), FlashLedCommand::processOptions(), InfoCommand::processOptions(), LoggerStartCommand::processOptions(), MeterCommand::processOptions(), ScanCommand::processOptions(), SetNameCommand::processOptions(), and StatusCommand::processOptions().
requiredOptions()
QStringList AbstractCommand::requiredOptions (const QCommandLineParser & parser) const virtual
Returns a list of CLI option names required by this command.
The main console appication may use this list to output an eror (and exit) if any of the returned names are not found in the parsed CLI options.
The (already parsed) parser may be used adjust the returned required options depending on the value of other options. For example, the logger command only requires the --mode option if the --command option is start.
This base implementation simply returns an empty list. Derived classes should override this function to include any required options.
Reimplemented in CalibrationCommand, DsoCommand, FlashLedCommand, InfoCommand, LoggerStartCommand, MeterCommand, ScanCommand, SetNameCommand, and StatusCommand.
Definition at line 70 of file abstractcommand.cpp.
{
    Q_UNUSED(parser);
    return QStringList();
}
Referenced by processOptions(), CalibrationCommand::requiredOptions(), DsoCommand::requiredOptions(), FlashLedCommand::requiredOptions(), InfoCommand::requiredOptions(), LoggerStartCommand::requiredOptions(), MeterCommand::requiredOptions(), ScanCommand::requiredOptions(), SetNameCommand::requiredOptions(), StatusCommand::requiredOptions(), and supportedOptions().
supportedOptions()
QStringList AbstractCommand::supportedOptions (const QCommandLineParser & parser) const virtual
Returns a list of CLI option names supported by this command.
The main console appication may use this list to output a warning for any parsed CLI options not included in the returned list.
The (already parsed) parser may be used adjust the returned supported options depending on the value of other options. For example, the logger command only supported the --timestamp option if the --command option is start.
This base implementation simply returns requiredOptions(). Derived classes should override this function to include optional options, such as:
QStringList Derived::supportedOptions(const QCommandLineParser &parser) const
{
    const QStringList list = AbstractCommand::supportedOptions(parser) + QStringList{ ... };
    list.sort();
    list.removeDuplicates(); // Optional, recommended.
    return list;
}
Reimplemented in CalibrationCommand, DsoCommand, FlashLedCommand, InfoCommand, LoggerStartCommand, MeterCommand, ScanCommand, SetNameCommand, and StatusCommand.
Definition at line 97 of file abstractcommand.cpp.
{
    return requiredOptions(parser) + QStringList{
        QLatin1String("debug"),
        QLatin1String("device"),
        QLatin1String("output"),
        QLatin1String("timeout"),
    };
}
References requiredOptions().
Referenced by processOptions(), CalibrationCommand::supportedOptions(), DsoCommand::supportedOptions(), FlashLedCommand::supportedOptions(), InfoCommand::supportedOptions(), LoggerStartCommand::supportedOptions(), MeterCommand::supportedOptions(), ScanCommand::supportedOptions(), SetNameCommand::supportedOptions(), and StatusCommand::supportedOptions().
Friends And Related Function Documentation
TestAbstractCommand
friend class TestAbstractCommand friend
Definition at line 65 of file abstractcommand.h.
Member Data Documentation
deviceToScanFor
QString AbstractCommand::deviceToScanFor protected
Device (if any) that were passed to processOptions().
Definition at line 61 of file abstractcommand.h.
Referenced by DeviceCommand::deviceDiscovered(), DeviceCommand::deviceDiscoveryFinished(), processOptions(), and DeviceCommand::start().
discoveryAgent
PokitDiscoveryAgent* AbstractCommand::discoveryAgent protected
Agent for Pokit device descovery.
Definition at line 56 of file abstractcommand.h.
Referenced by AbstractCommand(), DeviceCommand::deviceDiscovered(), processOptions(), ScanCommand::ScanCommand(), DeviceCommand::start(), and ScanCommand::start().
format
OutputFormat AbstractCommand::format protected
Selected output format.
Definition at line 57 of file abstractcommand.h.
Referenced by SetNameCommand::deivceNameWritten(), ScanCommand::deviceDiscovered(), FlashLedCommand::deviceLedFlashed(), MeterCommand::outputReading(), LoggerFetchCommand::outputSamples(), DsoCommand::outputSamples(), processOptions(), InfoCommand::serviceDetailsDiscovered(), StatusCommand::serviceDetailsDiscovered(), LoggerStartCommand::settingsWritten(), LoggerStopCommand::settingsWritten(), and CalibrationCommand::temperatureCalibrated().
The documentation for this class was generated from the following files:
abstractcommand.h
abstractcommand.cpp