Dokit: DsoServicePrivate Class Reference
DsoServicePrivate Class Reference
The DsoServicePrivate class provides private implementation for DsoService.
Public Member Functions
DsoServicePrivate (QLowEnergyController *controller, DsoService *const q)
Public Member Functions inherited from AbstractPokitServicePrivate
AbstractPokitServicePrivate (const QBluetoothUuid &serviceUuid, QLowEnergyController *controller, AbstractPokitService *const q)
bool createServiceObject ()
Creates an internal service object from the internal controller.
QLowEnergyCharacteristic getCharacteristic (const QBluetoothUuid &uuid) const
Get uuid characteristc from the underlying service.
bool readCharacteristic (const QBluetoothUuid &uuid)
Read the uuid characteristic.
bool enableCharacteristicNotificatons (const QBluetoothUuid &uuid)
Enables client (Pokit device) side notification for characteristic uuid.
bool disableCharacteristicNotificatons (const QBluetoothUuid &uuid)
Disables client (Pokit device) side notification for characteristic uuid.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Member Functions
static QByteArray encodeSettings (const DsoService::Settings &settings)
Returns settings in the format Pokit devices expect.
static DsoService::Metadata parseMetadata (const QByteArray &value)
Parses the Metadata value into a DsoService::Metatdata struct.
static DsoService::Samples parseSamples (const QByteArray &value)
Parses the Reading value into a DsoService::Samples vector.
Static Public Member Functions inherited from AbstractPokitServicePrivate
static Q_LOGGING_CATEGORY (lc, "pokit.ble.service", QtInfoMsg)
Logging category.
static bool checkSize (const QString &label, const QByteArray &data, const int minSize, const int maxSize=-1, const bool failOnMax=false)
Returns false if data is smaller than minSize, otherwise returns failOnMax if data is bigger than maxSize, otherwise returns true.
static QString toHexString (const QByteArray &data, const int maxSize=20)
Returns up to maxSize bytes of data as a human readable hexadecimal string.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Protected Member Functions
void characteristicRead (const QLowEnergyCharacteristic &characteristic, const QByteArray &value) override
Implements AbstractPokitServicePrivate::characteristicRead to parse value, then emit a specialised signal, for each supported characteristic.
void characteristicWritten (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue) override
Implements AbstractPokitServicePrivate::characteristicWritten to parse newValue, then emit a specialised signal, for each supported characteristic.
void characteristicChanged (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue) override
Implements AbstractPokitServicePrivate::characteristicChanged to parse newValue, then emit a specialised signal, for each supported characteristic.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Friends
class TestDsoService
Additional Inherited Members
Public Attributes inherited from AbstractPokitServicePrivate
bool autoDiscover
Whether autodiscovery is enabled or not.
QLowEnergyController * controller
BLE controller to fetch the service from.
QLowEnergyService * service
BLE service to read/write characteristics.
QBluetoothUuid serviceUuid
UUIDs for service.
Public Attributes inherited from QObject
typedef QObjectList
Protected Slots inherited from AbstractPokitServicePrivate
void connected ()
Handles QLowEnergyController::connected events.
void discoveryFinished ()
Handles QLowEnergyController::discoveryFinished events.
void errorOccurred (const QLowEnergyService::ServiceError newError)
Handles QLowEnergyController::errorOccurred events.
virtual void serviceDiscovered (const QBluetoothUuid &newService)
Handles QLowEnergyController::serviceDiscovered events.
void stateChanged (QLowEnergyService::ServiceState newState)
Handles QLowEnergyController::stateChanged events.
virtual void characteristicRead (const QLowEnergyCharacteristic &characteristic, const QByteArray &value)
Handles QLowEnergyService::characteristicRead events.
virtual void characteristicWritten (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue)
Handles QLowEnergyService::characteristicWritten events.
virtual void characteristicChanged (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue)
Handles QLowEnergyService::characteristicChanged events.
Protected Attributes inherited from AbstractPokitServicePrivate
AbstractPokitService * q_ptr
Internal q-pointer.
Properties inherited from QObject
objectName
Detailed Description
The DsoServicePrivate class provides private implementation for DsoService.
Definition at line 18 of file dsoservice_p.h.
Constructor & Destructor Documentation
DsoServicePrivate()
DsoServicePrivate::DsoServicePrivate (QLowEnergyController * controller, DsoService *const q) explicit
Constructs a new DsoServicePrivate object with public implementation q.
Definition at line 500 of file dsoservice.cpp.
    : AbstractPokitServicePrivate(DsoService::serviceUuid, controller, q)
{
}
Member Function Documentation
characteristicChanged()
void DsoServicePrivate::characteristicChanged (const QLowEnergyCharacteristic & characteristic, const QByteArray & newValue) override protected virtual
Implements AbstractPokitServicePrivate::characteristicChanged to parse newValue, then emit a specialised signal, for each supported characteristic.
Reimplemented from AbstractPokitServicePrivate.
Definition at line 641 of file dsoservice.cpp.
{
    AbstractPokitServicePrivate::characteristicChanged(characteristic, newValue);
    Q_Q(DsoService);
    if (characteristic.uuid() == DsoService::CharacteristicUuids::settings) {
        qCWarning(lc).noquote() << tr("Settings characteristic is write-only, but somehow updated")
            << serviceUuid << characteristic.name() << characteristic.uuid();
        return;
    }
    if (characteristic.uuid() == DsoService::CharacteristicUuids::metadata) {
        emit q->metadataRead(parseMetadata(newValue));
        return;
    }
    if (characteristic.uuid() == DsoService::CharacteristicUuids::reading) {
        emit q->samplesRead(parseSamples(newValue));
        return;
    }
    qCWarning(lc).noquote() << tr("Unknown characteristic notified for DSO service")
        << serviceUuid << characteristic.name() << characteristic.uuid();
}
References AbstractPokitServicePrivate::characteristicChanged(), DsoService::CharacteristicUuids::metadata, QLowEnergyCharacteristic::name(), parseMetadata(), parseSamples(), DsoService::CharacteristicUuids::reading, AbstractPokitServicePrivate::serviceUuid, DsoService::CharacteristicUuids::settings, QObject::tr(), and QLowEnergyCharacteristic::uuid().
characteristicRead()
void DsoServicePrivate::characteristicRead (const QLowEnergyCharacteristic & characteristic, const QByteArray & value) override protected virtual
Implements AbstractPokitServicePrivate::characteristicRead to parse value, then emit a specialised signal, for each supported characteristic.
Reimplemented from AbstractPokitServicePrivate.
Definition at line 579 of file dsoservice.cpp.
{
    AbstractPokitServicePrivate::characteristicRead(characteristic, value);
    if (characteristic.uuid() == DsoService::CharacteristicUuids::settings) {
        qCWarning(lc).noquote() << tr("Settings characteristic is write-only, but somehow read")
            << serviceUuid << characteristic.name() << characteristic.uuid();
        return;
    }
    Q_Q(DsoService);
    if (characteristic.uuid() == DsoService::CharacteristicUuids::metadata) {
        emit q->metadataRead(parseMetadata(value));
        return;
    }
    if (characteristic.uuid() == DsoService::CharacteristicUuids::reading) {
        qCWarning(lc).noquote() << tr("Reading characteristic is notify-only")
            << serviceUuid << characteristic.name() << characteristic.uuid();
        return;
    }
    qCWarning(lc).noquote() << tr("Unknown characteristic read for DSO service")
        << serviceUuid << characteristic.name() << characteristic.uuid();
}
References AbstractPokitServicePrivate::characteristicRead(), DsoService::CharacteristicUuids::metadata, QLowEnergyCharacteristic::name(), parseMetadata(), DsoService::CharacteristicUuids::reading, AbstractPokitServicePrivate::serviceUuid, DsoService::CharacteristicUuids::settings, QObject::tr(), and QLowEnergyCharacteristic::uuid().
characteristicWritten()
void DsoServicePrivate::characteristicWritten (const QLowEnergyCharacteristic & characteristic, const QByteArray & newValue) override protected virtual
Implements AbstractPokitServicePrivate::characteristicWritten to parse newValue, then emit a specialised signal, for each supported characteristic.
Reimplemented from AbstractPokitServicePrivate.
Definition at line 610 of file dsoservice.cpp.
{
    AbstractPokitServicePrivate::characteristicWritten(characteristic, newValue);
    Q_Q(DsoService);
    if (characteristic.uuid() == DsoService::CharacteristicUuids::settings) {
        emit q->settingsWritten();
        return;
    }
    if (characteristic.uuid() == DsoService::CharacteristicUuids::metadata) {
        qCWarning(lc).noquote() << tr("Metadata characteristic is read/notify, but somehow written")
            << serviceUuid << characteristic.name() << characteristic.uuid();
        return;
    }
    if (characteristic.uuid() == DsoService::CharacteristicUuids::reading) {
        qCWarning(lc).noquote() << tr("Reading characteristic is notify-only, but somehow written")
            << serviceUuid << characteristic.name() << characteristic.uuid();
        return;
    }
    qCWarning(lc).noquote() << tr("Unknown characteristic written for DSO service")
        << serviceUuid << characteristic.name() << characteristic.uuid();
}
References AbstractPokitServicePrivate::characteristicWritten(), DsoService::CharacteristicUuids::metadata, QLowEnergyCharacteristic::name(), DsoService::CharacteristicUuids::reading, AbstractPokitServicePrivate::serviceUuid, DsoService::CharacteristicUuids::settings, QObject::tr(), and QLowEnergyCharacteristic::uuid().
encodeSettings()
QByteArray DsoServicePrivate::encodeSettings (const DsoService::Settings & settings) static
Returns settings in the format Pokit devices expect.
Definition at line 510 of file dsoservice.cpp.
{
    static_assert(sizeof(settings.command)         == 1, "Expected to be 1 byte.");
    static_assert(sizeof(settings.triggerLevel)    == 4, "Expected to be 2 bytes.");
    static_assert(sizeof(settings.mode)            == 1, "Expected to be 1 byte.");
    static_assert(sizeof(settings.range)           == 1, "Expected to be 1 byte.");
    static_assert(sizeof(settings.samplingWindow)  == 4, "Expected to be 4 bytes.");
    static_assert(sizeof(settings.numberOfSamples) == 2, "Expected to be 2 bytes.");
    QByteArray value;
    QDataStream stream(&value, QIODevice::WriteOnly);
    stream.setByteOrder(QDataStream::LittleEndian);
    stream.setFloatingPointPrecision(QDataStream::SinglePrecision); // 32-bit floats, not 64-bit.
    stream << (quint8)settings.command << settings.triggerLevel << (quint8)settings.mode
           << (quint8)settings.range.voltageRange << settings.samplingWindow
           << settings.numberOfSamples;
    Q_ASSERT(value.size() == 13);
    return value;
}
References DsoService::Settings::command, QDataStream::LittleEndian, DsoService::Settings::mode, DsoService::Settings::numberOfSamples, DsoService::Settings::range, DsoService::Settings::samplingWindow, QDataStream::setByteOrder(), QDataStream::setFloatingPointPrecision(), QDataStream::SinglePrecision, QByteArray::size(), DsoService::Settings::triggerLevel, DsoService::Range::voltageRange, and QIODevice::WriteOnly.
parseMetadata()
DsoService::Metadata DsoServicePrivate::parseMetadata (const QByteArray & value) static
Parses the Metadata value into a DsoService::Metatdata struct.
Definition at line 534 of file dsoservice.cpp.
{
    DsoService::Metadata metadata{
        DsoService::DsoStatus::Error, std::numeric_limits<float>::quiet_NaN(),
        DsoService::Mode::Idle, DsoService::VoltageRange::_0_to_300mV,
        0, 0, 0
    };
    if (!checkSize(QLatin1String("Metadata"), value, 17, 17)) {
        return metadata;
    }
    metadata.status             = static_cast<DsoService::DsoStatus>(value.at(0));
    metadata.scale              = qFromLittleEndian<float>(value.mid(1,4));
    metadata.mode               = static_cast<DsoService::Mode>(value.at(5));
    metadata.range.voltageRange = static_cast<DsoService::VoltageRange>(value.at(6));
    metadata.samplingWindow     = qFromLittleEndian<quint32>(value.mid(7,4));
    metadata.numberOfSamples    = qFromLittleEndian<quint16>(value.mid(11,2));
    metadata.samplingRate       = qFromLittleEndian<quint32>(value.mid(13,4));
    return metadata;
}
References DsoService::_0_to_300mV, QByteArray::at(), AbstractPokitServicePrivate::checkSize(), DsoService::Error, DsoService::Idle, and QByteArray::mid().
Referenced by characteristicChanged(), characteristicRead(), and DsoService::metadata().
parseSamples()
DsoService::Samples DsoServicePrivate::parseSamples (const QByteArray & value) static
Parses the Reading value into a DsoService::Samples vector.
Definition at line 559 of file dsoservice.cpp.
{
    DsoService::Samples samples;
    if ((value.size()%2) != 0) {
        qCWarning(lc).noquote() << tr("Samples value has odd size %1 (should be even): %2")
            .arg(value.size()).arg(toHexString(value));
        return samples;
    }
    while ((samples.size()*2) < value.size()) {
        samples.append(qFromLittleEndian<qint16>(value.mid(samples.size()*2,2)));
    }
    qCDebug(lc).noquote() << tr("Read %1 samples from %2-bytes.")
        .arg(samples.size()).arg(value.size());
    return samples;
}
References QVector::append(), QString::arg(), QByteArray::mid(), QByteArray::size(), QVector::size(), AbstractPokitServicePrivate::toHexString(), and QObject::tr().
Referenced by characteristicChanged().
Friends And Related Function Documentation
TestDsoService
friend class TestDsoService friend
Definition at line 41 of file dsoservice_p.h.
The documentation for this class was generated from the following files:
dsoservice_p.h
dsoservice.cpp