QtPokit: InfoService Class Reference
InfoService Class Reference
The InfoService class accesses the Device Info service of Pokit devices.
Classes
struct CharacteristicUuids
Characteristics available via the Device Info service.
Signals
void manufacturerRead (const QString &name)
This signal is emitted when the Manufacturer Name characteristic has been read successfully.
void modelNumberRead (const QString &model)
This signal is emitted when the Model Number characteristic has been read successfully.
void firmwareRevisionRead (const QString &revision)
This signal is emitted when the Firmware Revision characteristic has been read successfully.
void hardwareRevisionRead (const QString &revision)
This signal is emitted when the Hardware Revision characteristic has been read successfully.
void softwareRevisionRead (const QString &revision)
This signal is emitted when the Software Revision characteristic has been read successfully.
Signals inherited from AbstractPokitService
void serviceDetailsDiscovered ()
This signal is emitted when the Pokit service details have been discovered.
void serviceErrorOccurred (QLowEnergyService::ServiceError newError)
This signal is emitted whenever an error occurs on the underlying QLowEnergyService.
Public Member Functions
InfoService (QLowEnergyController *const pokitDevice, QObject *parent=nullptr)
Constructs a new Pokit service with parent.
~InfoService () override
Destroys this InfoService object.
bool readCharacteristics () override
Read all characteristics.
bool readFirmwareRevisionCharacteristic ()
Read the Device Info service's Firmware Revision characteristic.
bool readHardwareRevisionCharacteristic ()
Read the Device Info service's Hardware Revision characteristic.
bool readManufacturerCharacteristics ()
Read the Device Info service's Manufacturer Name characteristic.
bool readModelNumberCharacteristic ()
Read the Device Info service's Model Number characteristic.
bool readSoftwareRevisionCharacteristic ()
Read the Device Info service's Software Revision characteristic.
QString manufacturer () const
Returns the most recent value of the Device Info service's Manufacturer Name characteristic.
QString modelNumber () const
Returns the most recent value of the Device Info service's Model Number characteristic.
QString firmwareRevision () const
Returns the most recent value of the Device Info service's Firmware Revision characteristic.
QString hardwareRevision () const
Returns the most recent value of the Device Info service's Hardware Revision characteristic.
QString softwareRevision () const
Returns the most recent value of the Device Info service's Software Revision characteristic.
Public Member Functions inherited from AbstractPokitService
virtual ~AbstractPokitService ()
Destroys this AbstractPokitService object.
virtual bool readCharacteristics ()=0
Read all characteristics.
bool autoDiscover () const
Returns true if autodiscovery of services and service details is enabled, false otherwise.
void setAutoDiscover (const bool discover=true)
If discover is true, autodiscovery will be attempted.
QLowEnergyService * service ()
Returns a non-const pointer to the internal service object, if any.
const QLowEnergyService * service () const
Returns a const pointer to the internal service object, if any.
Static Public Attributes
static const QBluetoothUuid serviceUuid
UUID of the "Device Info" service.
Protected Member Functions
InfoService (InfoServicePrivate *const d, QObject *const parent)
Constructs a new Pokit service with parent, and private implementation d.
Protected Member Functions inherited from AbstractPokitService
AbstractPokitService (AbstractPokitServicePrivate *const d, QObject *const parent)
Constructs a new Pokit service with parent, and private implementation d.
Friends
class TestInfoService
Additional Inherited Members
Protected Attributes inherited from AbstractPokitService
AbstractPokitServicePrivate * d_ptr
Internal d-pointer.
Detailed Description
The InfoService class accesses the Device Info service of Pokit devices.
Definition at line 38 of file infoservice.h.
Constructor & Destructor Documentation
InfoService() [1/2]
InfoService::InfoService (QLowEnergyController *const pokitDevice, QObject * parent = nullptr)
Constructs a new Pokit service with parent.
Definition at line 67 of file infoservice.cpp.
    : AbstractPokitService(new InfoServicePrivate(controller, this), parent)
{
}
~InfoService()
InfoService::~InfoService () override
Destroys this InfoService object.
Definition at line 88 of file infoservice.cpp.
{
    delete d_ptr;
}
References AbstractPokitService::d_ptr.
InfoService() [2/2]
InfoService::InfoService (InfoServicePrivate *const d, QObject *const parent) protected
Constructs a new Pokit service with parent, and private implementation d.
Definition at line 77 of file infoservice.cpp.
    : AbstractPokitService(d, parent)
{
}
Member Function Documentation
firmwareRevision()
QString InfoService::firmwareRevision () const
Returns the most recent value of the Device Info service's Firmware Revision characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then a null QString is returned.
Definition at line 260 of file infoservice.cpp.
{
    Q_D(const InfoService);
    if (!d->service) {
        qCDebug(pokitService).noquote() << tr("No device characteristics without a service object.");
        return QString();
    }
    const QLowEnergyCharacteristic characteristic =
        d->service->characteristic(CharacteristicUuids::firmwareRevision);
    if (!characteristic.isValid()) {
        qCDebug(pokitService).noquote() << tr("Firmware Revision characteristic not valid yet.");
        return QString();
    }
    return QString::fromUtf8(characteristic.value());
}
References InfoService::CharacteristicUuids::firmwareRevision.
firmwareRevisionRead
InfoService::firmwareRevisionRead (const QString & revision) signal
This signal is emitted when the Firmware Revision characteristic has been read successfully.
See also
readFirmwareRevisionCharacteristic
firmwareRevision
hardwareRevision()
QString InfoService::hardwareRevision () const
Returns the most recent value of the Device Info service's Hardware Revision characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then a null QString is returned.
Definition at line 235 of file infoservice.cpp.
{
    Q_D(const InfoService);
    if (!d->service) {
        qCDebug(pokitService).noquote() << tr("No device characteristics without a service object.");
        return QString();
    }
    const QLowEnergyCharacteristic characteristic =
        d->service->characteristic(CharacteristicUuids::hardwareRevision);
    if (!characteristic.isValid()) {
        qCDebug(pokitService).noquote() << tr("Hardware Revision characteristic not valid yet.");
        return QString();
    }
    return QString::fromUtf8(characteristic.value());
}
References InfoService::CharacteristicUuids::hardwareRevision.
hardwareRevisionRead
InfoService::hardwareRevisionRead (const QString & revision) signal
This signal is emitted when the Hardware Revision characteristic has been read successfully.
See also
readHardwareRevisionCharacteristic
hardwareRevision
manufacturer()
QString InfoService::manufacturer () const
Returns the most recent value of the Device Info service's Manufacturer Name characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then a null QString is returned.
Definition at line 185 of file infoservice.cpp.
{
    Q_D(const InfoService);
    if (!d->service) {
        qCDebug(pokitService).noquote() << tr("No device characteristics without a service object.");
        return QString();
    }
    const QLowEnergyCharacteristic characteristic =
        d->service->characteristic(CharacteristicUuids::manufacturerName);
    if (!characteristic.isValid()) {
        qCDebug(pokitService).noquote() << tr("Manufacturer Name characteristic not valid yet.");
        return QString();
    }
    return QString::fromUtf8(characteristic.value());
}
References InfoService::CharacteristicUuids::manufacturerName.
manufacturerRead
InfoService::manufacturerRead (const QString & name) signal
This signal is emitted when the Manufacturer Name characteristic has been read successfully.
See also
readManufacturerCharacteristic
manufacturer
modelNumber()
QString InfoService::modelNumber () const
Returns the most recent value of the Device Info service's Model Number characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then a null QString is returned.
Definition at line 210 of file infoservice.cpp.
{
    Q_D(const InfoService);
    if (!d->service) {
        qCDebug(pokitService).noquote() << tr("No device characteristics without a service object.");
        return QString();
    }
    const QLowEnergyCharacteristic characteristic =
        d->service->characteristic(CharacteristicUuids::modelNumber);
    if (!characteristic.isValid()) {
        qCDebug(pokitService).noquote() << tr("Model Number characteristic not valid yet.");
        return QString();
    }
    return QString::fromUtf8(characteristic.value());
}
References InfoService::CharacteristicUuids::modelNumber.
modelNumberRead
InfoService::modelNumberRead (const QString & model) signal
This signal is emitted when the Model Number characteristic has been read successfully.
See also
readModelNumberCharacteristic
modelNumber
readCharacteristics()
bool InfoService::readCharacteristics () override virtual
Read all characteristics.
This convenience function will queue refresh requests of all characteristics supported by this service.
Relevant *Service::*Read signals will be emitted by derived class objects as each characteristic is successfully read.
Implements AbstractPokitService.
Definition at line 93 of file infoservice.cpp.
{
    const bool r1 = readFirmwareRevisionCharacteristic();
    const bool r2 = readHardwareRevisionCharacteristic();
    const bool r3 = readSoftwareRevisionCharacteristic();
    const bool r4 = readManufacturerCharacteristics();
    const bool r5 = readModelNumberCharacteristic();
    return (r1 && r2 && r3 && r4 && r5);
}
References readFirmwareRevisionCharacteristic(), readHardwareRevisionCharacteristic(), readManufacturerCharacteristics(), readModelNumberCharacteristic(), and readSoftwareRevisionCharacteristic().
readFirmwareRevisionCharacteristic()
bool InfoService::readFirmwareRevisionCharacteristic ()
Read the Device Info service's Firmware Revision characteristic.
Returns true is the read request is succesfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits firmwareRevisionRead() if/when the characteristic has been read successfully.
Definition at line 112 of file infoservice.cpp.
{
    Q_D(InfoService);
    return d->readCharacteristic(CharacteristicUuids::firmwareRevision);
}
References InfoService::CharacteristicUuids::firmwareRevision.
Referenced by readCharacteristics().
readHardwareRevisionCharacteristic()
bool InfoService::readHardwareRevisionCharacteristic ()
Read the Device Info service's Hardware Revision characteristic.
Returns true is the read request is succesfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits hardwareRevisionRead() if/when the characteristic has been read successfully.
Definition at line 127 of file infoservice.cpp.
{
    Q_D(InfoService);
    return d->readCharacteristic(CharacteristicUuids::hardwareRevision);
}
References InfoService::CharacteristicUuids::hardwareRevision.
Referenced by readCharacteristics().
readManufacturerCharacteristics()
bool InfoService::readManufacturerCharacteristics ()
Read the Device Info service's Manufacturer Name characteristic.
Returns true is the read request is succesfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits manufacturerNameRead() if/when the characteristic has been read successfully.
Definition at line 142 of file infoservice.cpp.
{
    Q_D(InfoService);
    return d->readCharacteristic(CharacteristicUuids::manufacturerName);
}
References InfoService::CharacteristicUuids::manufacturerName.
Referenced by readCharacteristics().
readModelNumberCharacteristic()
bool InfoService::readModelNumberCharacteristic ()
Read the Device Info service's Model Number characteristic.
Returns true is the read request is succesfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits modelNumberRead() if/when the characteristic has been read successfully.
Definition at line 157 of file infoservice.cpp.
{
    Q_D(InfoService);
    return d->readCharacteristic(CharacteristicUuids::modelNumber);
}
References InfoService::CharacteristicUuids::modelNumber.
Referenced by readCharacteristics().
readSoftwareRevisionCharacteristic()
bool InfoService::readSoftwareRevisionCharacteristic ()
Read the Device Info service's Software Revision characteristic.
Returns true is the read request is succesfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits softwareRevisionRead() if/when the characteristic has been read successfully.
Definition at line 172 of file infoservice.cpp.
{
    Q_D(InfoService);
    return d->readCharacteristic(CharacteristicUuids::softwareRevision);
}
References InfoService::CharacteristicUuids::softwareRevision.
Referenced by readCharacteristics().
softwareRevision()
QString InfoService::softwareRevision () const
Returns the most recent value of the Device Info service's Software Revision characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then a null QString is returned.
Definition at line 285 of file infoservice.cpp.
{
    Q_D(const InfoService);
    if (!d->service) {
        qCDebug(pokitService).noquote() << tr("No device characteristics without a service object.");
        return QString();
    }
    const QLowEnergyCharacteristic characteristic =
        d->service->characteristic(CharacteristicUuids::softwareRevision);
    if (!characteristic.isValid()) {
        qCDebug(pokitService).noquote() << tr("Software Revision characteristic not valid yet.");
        return QString();
    }
    return QString::fromUtf8(characteristic.value());
}
References InfoService::CharacteristicUuids::softwareRevision.
softwareRevisionRead
InfoService::softwareRevisionRead (const QString & revision) signal
This signal is emitted when the Software Revision characteristic has been read successfully.
See also
readSoftwareRevisionCharacteristic
softwareRevision
Friends And Related Function Documentation
TestInfoService
friend class TestInfoService friend
Definition at line 85 of file infoservice.h.
Member Data Documentation
serviceUuid
const QBluetoothUuid InfoService::serviceUuid static
UUID of the "Device Info" service.
Definition at line 43 of file infoservice.h.
The documentation for this class was generated from the following files:
infoservice.h
infoservice.cpp