QtPokit: DataLoggerServicePrivate Class Reference
DataLoggerServicePrivate Class Reference
The DataLoggerServicePrivate class provides private implementation for DataLoggerService.
Public Member Functions
DataLoggerServicePrivate (QLowEnergyController *controller, DataLoggerService *const q)
Public Member Functions inherited from AbstractPokitServicePrivate
AbstractPokitServicePrivate (const QBluetoothUuid &serviceUuid, QLowEnergyController *controller, AbstractPokitService *const q)
bool createServiceObject ()
Creates an internal service object from the internal controller.
QLowEnergyCharacteristic getCharacteristic (const QBluetoothUuid &uuid) const
Get uuid characteristc from the underlying service.
bool readCharacteristic (const QBluetoothUuid &uuid)
Read the uuid characteristic.
bool enableCharacteristicNotificatons (const QBluetoothUuid &uuid)
Enables client (Pokit device) side notification for characteristic uuid.
bool disableCharacteristicNotificatons (const QBluetoothUuid &uuid)
Disables client (Pokit device) side notification for characteristic uuid.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Member Functions
static QByteArray encodeSettings (const DataLoggerService::Settings &settings, const bool updateIntervalIs32bit)
Returns settings in the format Pokit devices expect.
static DataLoggerService::Metadata parseMetadata (const QByteArray &value)
Parses the Metadata value into a DataLoggerService::Metatdata struct.
static DataLoggerService::Samples parseSamples (const QByteArray &value)
Parses the Reading value into a DataLoggerService::Samples vector.
Static Public Member Functions inherited from AbstractPokitServicePrivate
static Q_LOGGING_CATEGORY (lc, "pokit.ble.service", QtInfoMsg)
Logging category.
static bool checkSize (const QString &label, const QByteArray &data, const int minSize, const int maxSize=-1, const bool failOnMax=false)
Returns false if data is smaller than minSize, otherwise returns failOnMax if data is bigger than maxSize, otherwise returns true.
static QString toHexString (const QByteArray &data, const int maxSize=20)
Returns up to maxSize bytes of data as a human readable hexadecimal string.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Protected Member Functions
void characteristicRead (const QLowEnergyCharacteristic &characteristic, const QByteArray &value) override
Implements AbstractPokitServicePrivate::characteristicRead to parse value, then emit a specialised signal, for each supported characteristic.
void characteristicWritten (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue) override
Implements AbstractPokitServicePrivate::characteristicWritten to parse newValue, then emit a specialised signal, for each supported characteristic.
void characteristicChanged (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue) override
Implements AbstractPokitServicePrivate::characteristicChanged to parse newValue, then emit a specialised signal, for each supported characteristic.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Friends
class TestDataLoggerService
Additional Inherited Members
Public Attributes inherited from AbstractPokitServicePrivate
bool autoDiscover
Whether autodiscovery is enabled or not.
QLowEnergyController * controller
BLE controller to fetch the service from.
QLowEnergyService * service
BLE service to read/write characteristics.
QBluetoothUuid serviceUuid
UUIDs for service.
Public Attributes inherited from QObject
typedef QObjectList
Protected Slots inherited from AbstractPokitServicePrivate
void connected ()
Handles QLowEnergyController::connected events.
void discoveryFinished ()
Handles QLowEnergyController::discoveryFinished events.
void errorOccurred (const QLowEnergyService::ServiceError newError)
Handles QLowEnergyController::errorOccurred events.
virtual void serviceDiscovered (const QBluetoothUuid &newService)
Handles QLowEnergyController::serviceDiscovered events.
void stateChanged (QLowEnergyService::ServiceState newState)
Handles QLowEnergyController::stateChanged events.
virtual void characteristicRead (const QLowEnergyCharacteristic &characteristic, const QByteArray &value)
Handles QLowEnergyService::characteristicRead events.
virtual void characteristicWritten (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue)
Handles QLowEnergyService::characteristicWritten events.
virtual void characteristicChanged (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue)
Handles QLowEnergyService::characteristicChanged events.
Protected Attributes inherited from AbstractPokitServicePrivate
AbstractPokitService * q_ptr
Internal q-pointer.
Properties inherited from QObject
objectName
Detailed Description
The DataLoggerServicePrivate class provides private implementation for DataLoggerService.
Definition at line 18 of file dataloggerservice_p.h.
Constructor & Destructor Documentation
DataLoggerServicePrivate()
DataLoggerServicePrivate::DataLoggerServicePrivate (QLowEnergyController * controller, DataLoggerService *const q) explicit
Constructs a new DataLoggerServicePrivate object with public implementation q.
Definition at line 524 of file dataloggerservice.cpp.
    : AbstractPokitServicePrivate(DataLoggerService::serviceUuid, controller, q)
{
}
Member Function Documentation
characteristicChanged()
void DataLoggerServicePrivate::characteristicChanged (const QLowEnergyCharacteristic & characteristic, const QByteArray & newValue) override protected virtual
Implements AbstractPokitServicePrivate::characteristicChanged to parse newValue, then emit a specialised signal, for each supported characteristic.
Reimplemented from AbstractPokitServicePrivate.
Definition at line 701 of file dataloggerservice.cpp.
{
    AbstractPokitServicePrivate::characteristicChanged(characteristic, newValue);
    Q_Q(DataLoggerService);
    if (characteristic.uuid() == DataLoggerService::CharacteristicUuids::settings) {
        qCWarning(lc).noquote() << tr("Settings characteristic is write-only, but somehow updated")
            << serviceUuid << characteristic.name() << characteristic.uuid();
        return;
    }
    if (characteristic.uuid() == DataLoggerService::CharacteristicUuids::metadata) {
        emit q->metadataRead(parseMetadata(newValue));
        return;
    }
    if (characteristic.uuid() == DataLoggerService::CharacteristicUuids::reading) {
        emit q->samplesRead(parseSamples(newValue));
        return;
    }
    qCWarning(lc).noquote() << tr("Unknown characteristic notified for Data Logger service")
        << serviceUuid << characteristic.name() << characteristic.uuid();
}
References AbstractPokitServicePrivate::characteristicChanged(), DataLoggerService::CharacteristicUuids::metadata, QLowEnergyCharacteristic::name(), parseMetadata(), parseSamples(), DataLoggerService::CharacteristicUuids::reading, AbstractPokitServicePrivate::serviceUuid, DataLoggerService::CharacteristicUuids::settings, QObject::tr(), and QLowEnergyCharacteristic::uuid().
characteristicRead()
void DataLoggerServicePrivate::characteristicRead (const QLowEnergyCharacteristic & characteristic, const QByteArray & value) override protected virtual
Implements AbstractPokitServicePrivate::characteristicRead to parse value, then emit a specialised signal, for each supported characteristic.
Reimplemented from AbstractPokitServicePrivate.
Definition at line 639 of file dataloggerservice.cpp.
{
    AbstractPokitServicePrivate::characteristicRead(characteristic, value);
    if (characteristic.uuid() == DataLoggerService::CharacteristicUuids::settings) {
        qCWarning(lc).noquote() << tr("Settings characteristic is write-only, but somehow read")
            << serviceUuid << characteristic.name() << characteristic.uuid();
        return;
    }
    Q_Q(DataLoggerService);
    if (characteristic.uuid() == DataLoggerService::CharacteristicUuids::metadata) {
        emit q->metadataRead(parseMetadata(value));
        return;
    }
    if (characteristic.uuid() == DataLoggerService::CharacteristicUuids::reading) {
        qCWarning(lc).noquote() << tr("Reading characteristic is notify-only")
            << serviceUuid << characteristic.name() << characteristic.uuid();
        return;
    }
    qCWarning(lc).noquote() << tr("Unknown characteristic read for Data Logger service")
        << serviceUuid << characteristic.name() << characteristic.uuid();
}
References AbstractPokitServicePrivate::characteristicRead(), DataLoggerService::CharacteristicUuids::metadata, QLowEnergyCharacteristic::name(), parseMetadata(), DataLoggerService::CharacteristicUuids::reading, AbstractPokitServicePrivate::serviceUuid, DataLoggerService::CharacteristicUuids::settings, QObject::tr(), and QLowEnergyCharacteristic::uuid().
characteristicWritten()
void DataLoggerServicePrivate::characteristicWritten (const QLowEnergyCharacteristic & characteristic, const QByteArray & newValue) override protected virtual
Implements AbstractPokitServicePrivate::characteristicWritten to parse newValue, then emit a specialised signal, for each supported characteristic.
Reimplemented from AbstractPokitServicePrivate.
Definition at line 670 of file dataloggerservice.cpp.
{
    AbstractPokitServicePrivate::characteristicWritten(characteristic, newValue);
    Q_Q(DataLoggerService);
    if (characteristic.uuid() == DataLoggerService::CharacteristicUuids::settings) {
        emit q->settingsWritten();
        return;
    }
    if (characteristic.uuid() == DataLoggerService::CharacteristicUuids::metadata) {
        qCWarning(lc).noquote() << tr("Metadata characteristic is read/notify, but somehow written")
            << serviceUuid << characteristic.name() << characteristic.uuid();
        return;
    }
    if (characteristic.uuid() == DataLoggerService::CharacteristicUuids::reading) {
        qCWarning(lc).noquote() << tr("Reading characteristic is notify-only, but somehow written")
            << serviceUuid << characteristic.name() << characteristic.uuid();
        return;
    }
    qCWarning(lc).noquote() << tr("Unknown characteristic written for Data Logger service")
        << serviceUuid << characteristic.name() << characteristic.uuid();
}
References AbstractPokitServicePrivate::characteristicWritten(), DataLoggerService::CharacteristicUuids::metadata, QLowEnergyCharacteristic::name(), DataLoggerService::CharacteristicUuids::reading, AbstractPokitServicePrivate::serviceUuid, DataLoggerService::CharacteristicUuids::settings, QObject::tr(), and QLowEnergyCharacteristic::uuid().
encodeSettings()
QByteArray DataLoggerServicePrivate::encodeSettings (const DataLoggerService::Settings & settings, const bool updateIntervalIs32bit) static
Returns settings in the format Pokit devices expect.
If updateIntervalIs32bit is 32-bit then the Update Interval field will be encoded in 32-bit instead of 16.
Pokit Bluetooth API errata:
For Pokit Meter, updateInterval is uint16 seconds (as per the Pokit API 1.00), however for Pokit Pro it's uint32 milliseconds, even though that's not officially documented anywhere.
Definition at line 535 of file dataloggerservice.cpp.
{
    static_assert(sizeof(settings.command)        == 1, "Expected to be 1 byte.");
    static_assert(sizeof(settings.arguments)      == 2, "Expected to be 2 bytes.");
    static_assert(sizeof(settings.mode)           == 1, "Expected to be 1 byte.");
    static_assert(sizeof(settings.range)          == 1, "Expected to be 1 byte.");
    static_assert(sizeof(settings.updateInterval) == 4, "Expected to be 4 bytes.");
    static_assert(sizeof(settings.timestamp)      == 4, "Expected to be 4 bytes.");
    QByteArray value;
    QDataStream stream(&value, QIODevice::WriteOnly);
    stream.setByteOrder(QDataStream::LittleEndian);
    stream.setFloatingPointPrecision(QDataStream::SinglePrecision); // 32-bit floats, not 64-bit.
    stream << (quint8)settings.command << settings.arguments << (quint8)settings.mode
           << (quint8)settings.range.voltageRange;
    /*!
     * \pokitApi For Pokit Meter, `updateInterval` is `uint16` seconds (as per the Pokit API 1.00),
     * however for Pokit Pro it's `uint32` milliseconds, even though that's not officially
     * documented anywhere.
     */
    if (!updateIntervalIs32bit) {
        stream << (quint16)((settings.updateInterval+500)/1000) << settings.timestamp;
        Q_ASSERT(value.size() == 11); // According to Pokit API 1.00.
    } else {
        stream << (quint32)settings.updateInterval << settings.timestamp;
        Q_ASSERT(value.size() == 13); // According to testing / experimentation.
    }
//    default:
//        qCWarning(d->lc).noquote() << tr("Don't know how to construct settings value for this device");
//        return QByteArray();
    return value;
}
References DataLoggerService::Settings::arguments, DataLoggerService::Settings::command, QDataStream::LittleEndian, DataLoggerService::Settings::mode, DataLoggerService::Settings::range, QDataStream::setByteOrder(), QDataStream::setFloatingPointPrecision(), QDataStream::SinglePrecision, QByteArray::size(), DataLoggerService::Settings::timestamp, DataLoggerService::Settings::updateInterval, DataLoggerService::Range::voltageRange, and QIODevice::WriteOnly.
parseMetadata()
DataLoggerService::Metadata DataLoggerServicePrivate::parseMetadata (const QByteArray & value) static
Parses the Metadata value into a DataLoggerService::Metatdata struct.
Pokit Bluetooth API errata:
For Pokit Meter, updateInterval is uint16 (as per the Pokit API 1.00), however for Pokit Pro it's uint32, even though that's not officially documented anywhere. Also note, the doc claims 'microseconds' (ie 10^-6), but clearly the value is 'milliseconds' (ie 10^-3) for Pokit Pro, and whole seconds for Pokit Meter.
Definition at line 575 of file dataloggerservice.cpp.
{
    DataLoggerService::Metadata metadata{
        DataLoggerService::LoggerStatus::Error, std::numeric_limits<float>::quiet_NaN(),
        DataLoggerService::Mode::Idle, DataLoggerService::VoltageRange::_0_to_300mV,
        0, 0, 0
    };
    // Pokit Meter: 15 bytes, Pokit Pro: 23 bytes.
    if (!checkSize(QLatin1String("Metadata"), value, 15, 23)) {
        return metadata;
    }
    qCDebug(lc) << value.mid(7,12).toHex(',');
    metadata.status             = static_cast<DataLoggerService::LoggerStatus>(value.at(0));
    metadata.scale              = qFromLittleEndian<float>(value.mid(1,4));
    metadata.mode               = static_cast<DataLoggerService::Mode>(value.at(5));
    metadata.range.voltageRange = static_cast<DataLoggerService::VoltageRange>(value.at(6));
    /*!
     * \pokitApi For Pokit Meter, `updateInterval` is `uint16` (as per the Pokit API 1.00), however
     * for Pokit Pro it's `uint32`, even though that's not officially documented anywhere.
     * Also note, the doc claims 'microseconds' (ie 10^-6), but clearly the value is 'milliseconds'
     * (ie 10^-3) for Pokit Pro, and whole seconds for Pokit Meter.
     */
    if (value.size() == 15) {
        metadata.updateInterval  = qFromLittleEndian<quint16>(value.mid(7,2))*1000;
        metadata.numberOfSamples = qFromLittleEndian<quint16>(value.mid(9,2));
        metadata.timestamp       = qFromLittleEndian<quint32>(value.mid(11,4));
    } else if (value.size() == 23) {
        metadata.updateInterval  = qFromLittleEndian<quint32>(value.mid(7,4));
        metadata.numberOfSamples = qFromLittleEndian<quint32>(value.mid(11,4));
        metadata.timestamp       = qFromLittleEndian<quint32>(value.mid(19,4));
    } else {
        qCWarning(lc).noquote() << tr("Cannot decode metadata of %1 bytes: %2").arg(value.size())
            .arg(toHexString(value));
    }
    return metadata;
}
References DataLoggerService::_0_to_300mV, QString::arg(), QByteArray::at(), AbstractPokitServicePrivate::checkSize(), DataLoggerService::Error, DataLoggerService::Idle, QByteArray::mid(), QByteArray::size(), QByteArray::toHex(), AbstractPokitServicePrivate::toHexString(), and QObject::tr().
Referenced by characteristicChanged(), characteristicRead(), and DataLoggerService::metadata().
parseSamples()
DataLoggerService::Samples DataLoggerServicePrivate::parseSamples (const QByteArray & value) static
Parses the Reading value into a DataLoggerService::Samples vector.
Definition at line 619 of file dataloggerservice.cpp.
{
    DataLoggerService::Samples samples;
    if ((value.size()%2) != 0) {
        qCWarning(lc).noquote() << tr("Samples value has odd size %1 (should be even): %2")
            .arg(value.size()).arg(toHexString(value));
        return samples;
    }
    for (; (samples.size()*2) < value.size();) {
        samples.append(qFromLittleEndian<qint16>(value.mid(samples.size()*2,2)));
    }
    qCDebug(lc).noquote() << tr("Read %1 samples from %2-bytes.")
        .arg(samples.size()).arg(value.size());
    return samples;
}
References QVector::append(), QString::arg(), QByteArray::mid(), QByteArray::size(), QVector::size(), AbstractPokitServicePrivate::toHexString(), and QObject::tr().
Referenced by characteristicChanged().
Friends And Related Function Documentation
TestDataLoggerService
friend class TestDataLoggerService friend
Definition at line 42 of file dataloggerservice_p.h.
The documentation for this class was generated from the following files:
dataloggerservice_p.h
dataloggerservice.cpp