Dokit: AbstractPokitServicePrivate Class Reference
AbstractPokitServicePrivate Class Reference
The AbstractPokitServicePrivate class provides private implementation for AbstractPokitService.
Public Member Functions
AbstractPokitServicePrivate (const QBluetoothUuid &serviceUuid, QLowEnergyController *controller, AbstractPokitService *const q)
bool createServiceObject ()
Creates an internal service object from the internal controller.
QLowEnergyCharacteristic getCharacteristic (const QBluetoothUuid &uuid) const
Get uuid characteristic from the underlying service.
bool readCharacteristic (const QBluetoothUuid &uuid)
Read the uuid characteristic.
bool enableCharacteristicNotificatons (const QBluetoothUuid &uuid)
Enables client (Pokit device) side notification for characteristic uuid.
bool disableCharacteristicNotificatons (const QBluetoothUuid &uuid)
Disables client (Pokit device) side notification for characteristic uuid.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Member Functions
static Q_LOGGING_CATEGORY (lc, "pokit.ble.service", QtInfoMsg)
Logging category.
static bool checkSize (const QString &label, const QByteArray &data, const int minSize, const int maxSize=-1, const bool failOnMax=false)
Returns false if data is smaller than minSize, otherwise returns failOnMax if data is bigger than maxSize, otherwise returns true.
static QString toHexString (const QByteArray &data, const int maxSize=20)
Returns up to maxSize bytes of data as a human readable hexadecimal string.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes
bool autoDiscover { true }
Whether autodiscovery is enabled or not.
QLowEnergyController * controller { nullptr }
BLE controller to fetch the service from.
std::optional< PokitProduct > pokitProduct
The Pokit product controller is connected to.
QLowEnergyService * service { nullptr }
BLE service to read/write characteristics.
QBluetoothUuid serviceUuid
UUIDs for service.
Public Attributes inherited from QObject
typedef QObjectList
Protected Slots
void connected ()
Handles QLowEnergyController::connected events.
void discoveryFinished ()
Handles QLowEnergyController::discoveryFinished events.
void errorOccurred (const QLowEnergyService::ServiceError newError)
Handles QLowEnergyController::errorOccurred events.
virtual void serviceDiscovered (const QBluetoothUuid &newService)
Handles QLowEnergyController::serviceDiscovered events.
void stateChanged (QLowEnergyService::ServiceState newState)
Handles QLowEnergyController::stateChanged events.
virtual void characteristicRead (const QLowEnergyCharacteristic &characteristic, const QByteArray &value)
Handles QLowEnergyService::characteristicRead events.
virtual void characteristicWritten (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue)
Handles QLowEnergyService::characteristicWritten events.
virtual void characteristicChanged (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue)
Handles QLowEnergyService::characteristicChanged events.
Protected Attributes
AbstractPokitService * q_ptr
Internal q-pointer.
Additional Inherited Members
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
The AbstractPokitServicePrivate class provides private implementation for AbstractPokitService.
Definition at line 25 of file abstractpokitservice_p.h.
Constructor & Destructor Documentation
AbstractPokitServicePrivate()
AbstractPokitServicePrivate::AbstractPokitServicePrivate (const QBluetoothUuid & serviceUuid, QLowEnergyController * controller, AbstractPokitService *const q)
Constructs a new AbstractPokitServicePrivate object with public implementation q.
Note, typically the serviceUuid should be set validly, however, in the rare case that a service's UUID can vary (ie the Status Service), serviceUuid may be set to a null QBluetoothUuid here, and updated when the correct service UUID is known.
See also
StatusService::ServiceUuids
StatusServicePrivate::serviceDiscovered
Definition at line 172 of file abstractpokitservice.cpp.
    : controller(controller), serviceUuid(serviceUuid), q_ptr(q)
{
    if (controller) {
        connect(controller, &QLowEnergyController::connected,
                this, &AbstractPokitServicePrivate::connected);
        connect(controller, &QLowEnergyController::discoveryFinished,
                this, &AbstractPokitServicePrivate::discoveryFinished);
        connect(controller, &QLowEnergyController::serviceDiscovered,
                this, &AbstractPokitServicePrivate::serviceDiscovered);
        createServiceObject();
    }
}
References QObject::connect(), connected(), QLowEnergyController::connected(), controller, createServiceObject(), discoveryFinished(), QLowEnergyController::discoveryFinished(), q_ptr, serviceDiscovered(), QLowEnergyController::serviceDiscovered(), and serviceUuid.
Referenced by CalibrationServicePrivate::CalibrationServicePrivate(), DataLoggerServicePrivate::DataLoggerServicePrivate(), DeviceInfoServicePrivate::DeviceInfoServicePrivate(), DsoServicePrivate::DsoServicePrivate(), MultimeterServicePrivate::MultimeterServicePrivate(), and StatusServicePrivate::StatusServicePrivate().
Member Function Documentation
characteristicChanged
void AbstractPokitServicePrivate::characteristicChanged (const QLowEnergyCharacteristic & characteristic, const QByteArray & newValue) protected virtual slot
Handles QLowEnergyService::characteristicChanged events.
This base implementation simply debug logs the event.
If derived classes support characteristics with client-side notification (ie Notify, as opposed to Read or Write operations), they should implement this function to handle the successful reads of characteristic, typically by parsing value, then emitting a specialised signal.
Reimplemented in DataLoggerServicePrivate, DsoServicePrivate, and MultimeterServicePrivate.
Definition at line 594 of file abstractpokitservice.cpp.
{
    qCDebug(lc).noquote() << tr(R"(Characteristic %1 "%2" changed to %Ln byte/s: %3)", nullptr, newValue.size())
        .arg(characteristic.uuid().toString(), PokitDevice::charcteristicToString(characteristic.uuid()), toHexString(newValue));
}
References QString::arg(), PokitDevice::charcteristicToString(), QByteArray::size(), toHexString(), QUuid::toString(), QObject::tr(), and QLowEnergyCharacteristic::uuid().
Referenced by DataLoggerServicePrivate::characteristicChanged(), DsoServicePrivate::characteristicChanged(), MultimeterServicePrivate::characteristicChanged(), and createServiceObject().
characteristicRead
void AbstractPokitServicePrivate::characteristicRead (const QLowEnergyCharacteristic & characteristic, const QByteArray & value) protected virtual slot
Handles QLowEnergyService::characteristicRead events.
This base implementation simply debug logs the event.
Derived classes should implement this function to handle the successful reads of characteristic, typically by parsing value, then emitting a specialised signal.
Reimplemented in DataLoggerServicePrivate, DeviceInfoServicePrivate, DsoServicePrivate, MultimeterServicePrivate, and StatusServicePrivate.
Definition at line 565 of file abstractpokitservice.cpp.
{
    qCDebug(lc).noquote() << tr(R"(Characteristic %1 "%2" read %n byte/s: %3)", nullptr, value.size()).arg(
        characteristic.uuid().toString(), PokitDevice::charcteristicToString(characteristic.uuid()), toHexString(value));
}
References QString::arg(), PokitDevice::charcteristicToString(), QByteArray::size(), toHexString(), QUuid::toString(), QObject::tr(), and QLowEnergyCharacteristic::uuid().
Referenced by DataLoggerServicePrivate::characteristicRead(), DeviceInfoServicePrivate::characteristicRead(), DsoServicePrivate::characteristicRead(), MultimeterServicePrivate::characteristicRead(), StatusServicePrivate::characteristicRead(), and createServiceObject().
characteristicWritten
void AbstractPokitServicePrivate::characteristicWritten (const QLowEnergyCharacteristic & characteristic, const QByteArray & newValue) protected virtual slot
Handles QLowEnergyService::characteristicWritten events.
This base implementation simply debug logs the event.
Derived classes should implement this function to handle the successful writes of characteristic, typically by parsing newValue, then emitting a specialised signal.
Reimplemented in CalibrationServicePrivate, DataLoggerServicePrivate, DsoServicePrivate, MultimeterServicePrivate, and StatusServicePrivate.
Definition at line 579 of file abstractpokitservice.cpp.
{
    qCDebug(lc).noquote() << tr(R"(Characteristic %1 "%2" written with %Ln byte/s: %3)", nullptr, newValue.size())
        .arg(characteristic.uuid().toString(), PokitDevice::charcteristicToString(characteristic.uuid()), toHexString(newValue));
}
References QString::arg(), PokitDevice::charcteristicToString(), QByteArray::size(), toHexString(), QUuid::toString(), QObject::tr(), and QLowEnergyCharacteristic::uuid().
Referenced by CalibrationServicePrivate::characteristicWritten(), DataLoggerServicePrivate::characteristicWritten(), DsoServicePrivate::characteristicWritten(), MultimeterServicePrivate::characteristicWritten(), StatusServicePrivate::characteristicWritten(), and createServiceObject().
checkSize()
bool AbstractPokitServicePrivate::checkSize (const QString & label, const QByteArray & data, const int minSize, const int maxSize = -1, const bool failOnMax = false) static
Returns false if data is smaller than minSize, otherwise returns failOnMax if data is bigger than maxSize, otherwise returns true.
A warning is logged if either minSize or maxSize is violated, regardless of the returned value; ie this funcion can be used to simply warn if data is too big, or it can be used to failed (return false) in that case.
Definition at line 403 of file abstractpokitservice.cpp.
{
    if (data.size() < minSize) {
        qCWarning(lc).noquote() << tr("%1 requires %n byte/s, but only %2 present: %3", nullptr, minSize)
            .arg(label).arg(data.size()).arg(toHexString(data));
        return false;
    }
    if ((maxSize >= 0) && (data.size() > maxSize)) {
        qCWarning(lc).noquote() << tr("%1 has %n extraneous byte/s: %2", nullptr, data.size()-maxSize)
            .arg(label, toHexString(data.mid(maxSize)));
        return (!failOnMax);
    }
    return true;
}
References QString::arg(), QByteArray::mid(), QByteArray::size(), toHexString(), and QObject::tr().
Referenced by StatusServicePrivate::characteristicRead(), StatusServicePrivate::parseButtonPress(), StatusServicePrivate::parseDeviceCharacteristics(), DataLoggerServicePrivate::parseMetadata(), DsoServicePrivate::parseMetadata(), MultimeterServicePrivate::parseReading(), StatusServicePrivate::parseStatus(), and StatusServicePrivate::parseTorchStatus().
connected
void AbstractPokitServicePrivate::connected () protected slot
Handles QLowEnergyController::connected events.
If autoDiscover is enabled, this will begin service discovery on the newly connected controller.
See also
AbstractPokitService::autoDiscover()
Definition at line 444 of file abstractpokitservice.cpp.
{
    if (!controller) {
        qCWarning(lc).noquote() << tr("Connected with no controller set") << sender();
        return;
    }
    qCDebug(lc).noquote() << tr(R"(Connected to "%1" (%2) at %3.)").arg(
        controller->remoteName(), controller->remoteDeviceUuid().toString(),
        controller->remoteAddress().toString());
    if (autoDiscover) {
        controller->discoverServices();
    }
}
References QString::arg(), autoDiscover, controller, QObject::sender(), and QObject::tr().
Referenced by AbstractPokitServicePrivate().
createServiceObject()
bool AbstractPokitServicePrivate::createServiceObject ()
Creates an internal service object from the internal controller.
Any existing service object will not be replaced.
Returns true if a service was created successfully, either now, or sometime previously.
Definition at line 197 of file abstractpokitservice.cpp.
{
    if (!controller) {
        return false;
    }
    if (service) {
        qCDebug(lc).noquote() << tr("Already have service object:") << service;
        return true;
    }
    if (serviceUuid.isNull()) {
        qCDebug(lc).noquote() << tr("Service UUID not assigned yet.");
        return false;
    }
    service = controller->createServiceObject(serviceUuid, this);
    if (!service) {
        return false;
    }
    qCDebug(lc).noquote() << tr("Service object created for %1 device:").arg(toString(*this->pokitProduct)) << service;
    connect(service, &QLowEnergyService::stateChanged,
            this, &AbstractPokitServicePrivate::stateChanged);
    connect(service, &QLowEnergyService::characteristicRead,
            this, &AbstractPokitServicePrivate::characteristicRead);
    connect(service, &QLowEnergyService::characteristicWritten,
            this, &AbstractPokitServicePrivate::characteristicWritten);
    connect(service, &QLowEnergyService::characteristicChanged,
            this, &AbstractPokitServicePrivate::characteristicChanged);
    connect(service, &QLowEnergyService::descriptorRead, this,
        [](const QLowEnergyDescriptor &descriptor, const QByteArray &value){
            qCDebug(lc).noquote() << tr(R"(Descriptor "%1" (%2) read.)")
                .arg(descriptor.name(), descriptor.uuid().toString());
            Q_UNUSED(value)
        });
    connect(service, &QLowEnergyService::descriptorWritten, this,
        [](const QLowEnergyDescriptor &descriptor, const QByteArray &newValue){
            qCDebug(lc).noquote() << tr(R"(Descriptor "%1" (%2) written.)")
                .arg(descriptor.name(), descriptor.uuid().toString());
            Q_UNUSED(newValue)
        });
    connect(service,
    #if (QT_VERSION < QT_VERSION_CHECK(6, 2, 0))
        QOverload<QLowEnergyService::ServiceError>::of(&QLowEnergyService::error),
    #else
        &QLowEnergyService::errorOccurred,
    #endif
        this, &AbstractPokitServicePrivate::errorOccurred);
    if (autoDiscover) {
        service->discoverDetails();
    }
    return true;
}
References QString::arg(), autoDiscover, characteristicChanged(), QLowEnergyService::characteristicChanged(), characteristicRead(), QLowEnergyService::characteristicRead(), characteristicWritten(), QLowEnergyService::characteristicWritten(), QObject::connect(), controller, QLowEnergyService::descriptorRead(), QLowEnergyService::descriptorWritten(), QLowEnergyService::error(), errorOccurred(), QLowEnergyDescriptor::name(), pokitProduct, service, serviceUuid, stateChanged(), QLowEnergyService::stateChanged(), QUuid::toString(), toString(), QObject::tr(), and QLowEnergyDescriptor::uuid().
Referenced by AbstractPokitServicePrivate(), discoveryFinished(), and serviceDiscovered().
disableCharacteristicNotificatons()
bool AbstractPokitServicePrivate::disableCharacteristicNotificatons (const QBluetoothUuid & uuid)
Disables client (Pokit device) side notification for characteristic uuid.
Returns true if the notification disable request was successfully queued, false otherwise.
See also
AbstractPokitServicePrivate::characteristicChanged
AbstractPokitServicePrivate::enableCharacteristicNotificatons
Definition at line 368 of file abstractpokitservice.cpp.
{
    qCDebug(lc).noquote() << tr(R"(Disabling CCCD for characteristic %1 "%2".)")
        .arg(uuid.toString(), PokitDevice::charcteristicToString(uuid));
    QLowEnergyCharacteristic characteristic = getCharacteristic(uuid);
    if (!characteristic.isValid()) {
        return false;
    }
    QLowEnergyDescriptor descriptor = characteristic.descriptor(
        QBluetoothUuid::DescriptorType::ClientCharacteristicConfiguration); // 0x2902
    if (!descriptor.isValid()) {
        qCWarning(lc).noquote() << tr(R"(Characteristic %1 "%2" has no client configuration descriptor.)")
            .arg(uuid.toString(), PokitDevice::charcteristicToString(uuid));
        return false;
    }
    service->writeDescriptor(descriptor,
        #if (QT_VERSION >= QT_VERSION_CHECK(6, 2, 0))
        QLowEnergyCharacteristic::CCCDDisable
        #else
        QByteArray::fromHex("0000") // See Qt6's QLowEnergyCharacteristic::CCCDDisable.
        #endif
    );
    return true;
}
References QString::arg(), PokitDevice::charcteristicToString(), QLowEnergyCharacteristic::descriptor(), QByteArray::fromHex(), getCharacteristic(), QLowEnergyCharacteristic::isValid(), QLowEnergyDescriptor::isValid(), service, QUuid::toString(), and QObject::tr().
discoveryFinished
void AbstractPokitServicePrivate::discoveryFinished () protected slot
Handles QLowEnergyController::discoveryFinished events.
As this event indicates that the controller has finished discovering services, this function will invoke createServiceObject() to create the internal service object (if not already created).
Definition at line 465 of file abstractpokitservice.cpp.
{
    if (!controller) {
        qCWarning(lc).noquote() << tr("Discovery finished with no controller set") << sender();
        return;
    }
    qCDebug(lc).noquote() << tr(R"(Discovery finished for "%1" (%2) at %3.)").arg(
        controller->remoteName(), controller->remoteDeviceUuid().toString(),
        controller->remoteAddress().toString());
    if (!createServiceObject()) {
        qCWarning(lc).noquote() << tr("Discovery finished, but service not found.");
        Q_Q(AbstractPokitService);
        Q_EMIT q->serviceErrorOccurred(QLowEnergyService::ServiceError::UnknownError);
    }
}
References QString::arg(), controller, createServiceObject(), QObject::Q_EMIT(), QObject::sender(), and QObject::tr().
Referenced by AbstractPokitServicePrivate().
enableCharacteristicNotificatons()
bool AbstractPokitServicePrivate::enableCharacteristicNotificatons (const QBluetoothUuid & uuid)
Enables client (Pokit device) side notification for characteristic uuid.
Returns true if the notification enable request was successfully queued, false otherwise.
See also
AbstractPokitServicePrivate::characteristicChanged
AbstractPokitServicePrivate::disableCharacteristicNotificatons
Definition at line 333 of file abstractpokitservice.cpp.
{
    qCDebug(lc).noquote() << tr(R"(Enabling CCCD for characteristic %1 "%2".)")
        .arg(uuid.toString(), PokitDevice::charcteristicToString(uuid));
    QLowEnergyCharacteristic characteristic = getCharacteristic(uuid);
    if (!characteristic.isValid()) {
        return false;
    }
    QLowEnergyDescriptor descriptor = characteristic.descriptor(
        QBluetoothUuid::DescriptorType::ClientCharacteristicConfiguration); // 0x2902
    if (!descriptor.isValid()) {
        qCWarning(lc).noquote() << tr(R"(Characteristic %1 "%2" has no client configuration descriptor.)")
            .arg(uuid.toString(), PokitDevice::charcteristicToString(uuid));
        return false;
    }
    service->writeDescriptor(descriptor,
        #if (QT_VERSION >= QT_VERSION_CHECK(6, 2, 0))
        QLowEnergyCharacteristic::CCCDEnableNotification
        #else
        QByteArray::fromHex("0100") // See Qt6's QLowEnergyCharacteristic::CCCDEnableNotification.
        #endif
    );
    return true;
}
References QString::arg(), PokitDevice::charcteristicToString(), QLowEnergyCharacteristic::descriptor(), QByteArray::fromHex(), getCharacteristic(), QLowEnergyCharacteristic::isValid(), QLowEnergyDescriptor::isValid(), service, QUuid::toString(), and QObject::tr().
errorOccurred
void AbstractPokitServicePrivate::errorOccurred (const QLowEnergyService::ServiceError newError) protected slot
Handles QLowEnergyController::errorOccurred events.
This function simply re-emits newError as AbstractPokitService::serviceErrorOccurred.
Definition at line 488 of file abstractpokitservice.cpp.
{
    Q_Q(AbstractPokitService);
    qCDebug(lc).noquote() << tr("Service error") << newError;
    Q_EMIT q->serviceErrorOccurred(newError);
}
References QObject::Q_EMIT(), and QObject::tr().
Referenced by createServiceObject().
getCharacteristic()
QLowEnergyCharacteristic AbstractPokitServicePrivate::getCharacteristic (const QBluetoothUuid & uuid) const
Get uuid characteristic from the underlying service.
This helper function is equivalent to
return service->characteristic(uuid);
except that it performs some sanity checks, such as checking the service object pointer has been assigned first, and also logs failures in a consistent manner.
Parameters
uuid
Returns
Definition at line 269 of file abstractpokitservice.cpp.
{
    if (!service) {
        qCDebug(lc).noquote() << tr(R"(Characteristic %1 "%2" requested before service assigned.)")
            .arg(uuid.toString(), PokitDevice::charcteristicToString(uuid));
        return QLowEnergyCharacteristic();
    }
    if (const QLowEnergyCharacteristic characteristic = service->characteristic(uuid); characteristic.isValid()) {
        return characteristic;
    }
    if (service->state() != QLowEnergyService::
        #if (QT_VERSION < QT_VERSION_CHECK(6, 0, 0))
        ServiceDiscovered
        #else
        RemoteServiceDiscovered
        #endif
    ) {
        qCWarning(lc).noquote() << tr(R"(Characteristic %1 "%2" requested before service %3 "%4" discovered.)")
            .arg(uuid.toString(), PokitDevice::charcteristicToString(uuid),
            service->serviceUuid().toString(), PokitDevice::serviceToString(service->serviceUuid()));
        qCInfo(lc).noquote() << tr("Current service state:") << service->state();
        return QLowEnergyCharacteristic();
    }
    qCWarning(lc).noquote() << tr(R"(Characteristic %1 "%2" not found in service %3 "%4".)")
        .arg(uuid.toString(), PokitDevice::charcteristicToString(uuid),
        service->serviceUuid().toString(), PokitDevice::serviceToString(service->serviceUuid()));
    return QLowEnergyCharacteristic();
}
References QString::arg(), PokitDevice::charcteristicToString(), service, PokitDevice::serviceToString(), QUuid::toString(), and QObject::tr().
Referenced by disableCharacteristicNotificatons(), enableCharacteristicNotificatons(), and readCharacteristic().
readCharacteristic()
bool AbstractPokitServicePrivate::readCharacteristic (const QBluetoothUuid & uuid)
Read the uuid characteristic.
If successful, the QLowEnergyService::characteristicRead signal will be emitted by the internal service object. For convenience, derived classes should implement the characteristicRead() virtual function to handle the read value.
Returns true if the characteristic read request was successfully queued, false otherwise.
See also
AbstractPokitService::readCharacteristics()
AbstractPokitServicePrivate::characteristicRead()
Definition at line 313 of file abstractpokitservice.cpp.
{
    const QLowEnergyCharacteristic characteristic = getCharacteristic(uuid);
    if (!characteristic.isValid()) {
        return false;
    }
    qCDebug(lc).noquote() << tr(R"(Reading characteristic %1 "%2".)")
        .arg(uuid.toString(), PokitDevice::charcteristicToString(uuid));
    service->readCharacteristic(characteristic);
    return true;
}
References QString::arg(), PokitDevice::charcteristicToString(), getCharacteristic(), QLowEnergyCharacteristic::isValid(), service, QUuid::toString(), and QObject::tr().
serviceDiscovered
void AbstractPokitServicePrivate::serviceDiscovered (const QBluetoothUuid & newService) protected virtual slot
Handles QLowEnergyController::serviceDiscovered events.
If the discovered service is the one this (or rather the derived) class wraps, then createServiceObject() will be invoked immediately (otherwise it will be invoked after full service discovery has completed, ie in discoveryFinished()).
Reimplemented in StatusServicePrivate.
Definition at line 502 of file abstractpokitservice.cpp.
{
    if ((!service) && (newService == serviceUuid)) {
        qCDebug(lc).noquote() << tr("Service discovered") << newService;
        createServiceObject();
    }
}
References createServiceObject(), service, serviceUuid, and QObject::tr().
Referenced by AbstractPokitServicePrivate(), and StatusServicePrivate::serviceDiscovered().
stateChanged
void AbstractPokitServicePrivate::stateChanged (QLowEnergyService::ServiceState newState) protected slot
Handles QLowEnergyController::stateChanged events.
If newState indicates that service details have now been discovered, then AbstractPokitService::serviceDetailsDiscovered will be emitted.
See also
AbstractPokitService::autoDiscover()
Definition at line 518 of file abstractpokitservice.cpp.
{
    qCDebug(lc).noquote() << tr("State changed to") << newState;
    if (lc().isDebugEnabled()) {
        for (const auto &characteristic: service->characteristics()) {
            QStringList properties;
            /// \cond no-doxygen
            #define QTPOKIT_INTERNAL_TEST_AND_APPEND(property) \
            if (characteristic.properties().testFlag(QLowEnergyCharacteristic::property)) { \
                properties.append(QStringLiteral(#property).toLower());\
            }
            /// \endcond
            QTPOKIT_INTERNAL_TEST_AND_APPEND(Broadcasting)
            QTPOKIT_INTERNAL_TEST_AND_APPEND(Read)
            QTPOKIT_INTERNAL_TEST_AND_APPEND(WriteNoResponse)
            QTPOKIT_INTERNAL_TEST_AND_APPEND(Write)
            QTPOKIT_INTERNAL_TEST_AND_APPEND(Notify)
            QTPOKIT_INTERNAL_TEST_AND_APPEND(Indicate)
            QTPOKIT_INTERNAL_TEST_AND_APPEND(WriteSigned)
            QTPOKIT_INTERNAL_TEST_AND_APPEND(ExtendedProperty)
            #undef QTPOKIT_INTERNAL_TEST_AND_APPEND
            qCDebug(lc).noquote() << tr(R"(Characteristic %1 "%2" supports %3.)").arg(characteristic.uuid().toString(),
                PokitDevice::charcteristicToString(characteristic.uuid()), properties.join(u", "_s));
        }
    }
    if (newState == QLowEnergyService::
            #if (QT_VERSION < QT_VERSION_CHECK(6, 0, 0))
            ServiceDiscovered
            #else
            RemoteServiceDiscovered
            #endif
        ) {
        Q_Q(AbstractPokitService);
        qCDebug(lc).noquote() << tr("Service details discovered.");
        Q_EMIT q->serviceDetailsDiscovered();
    }
}
References QString::arg(), PokitDevice::charcteristicToString(), QStringList::join(), QObject::Q_EMIT(), service, and QObject::tr().
Referenced by createServiceObject().
toHexString()
QString AbstractPokitServicePrivate::toHexString (const QByteArray & data, const int maxSize = 20) static
Returns up to maxSize bytes of data as a human readable hexadecimal string.
If data exceeds maxSize, then data is elided in the middle. For example:
toHex(QBytArray("\x1\x2\x3\x4\x5\x6", 4); // "0x01,02,...,05,06"
Definition at line 428 of file abstractpokitservice.cpp.
{
    return (data.size() <= maxSize)
        ? QString::fromLatin1("0x%1").arg(QLatin1String(data.toHex(',')))
        : QString::fromLatin1("0x%1,...,%2").arg(
            QLatin1String(data.left(maxSize/2-1).toHex(',')),
            QLatin1String(data.right(maxSize/2-1).toHex(',')));
}
References QString::arg(), QString::fromLatin1(), QByteArray::left(), QByteArray::right(), QByteArray::size(), and QByteArray::toHex().
Referenced by characteristicChanged(), characteristicRead(), characteristicWritten(), checkSize(), DataLoggerServicePrivate::parseMetadata(), DataLoggerServicePrivate::parseSamples(), and DsoServicePrivate::parseSamples().
Member Data Documentation
autoDiscover
bool AbstractPokitServicePrivate::autoDiscover { true }
Whether autodiscovery is enabled or not.
Definition at line 32 of file abstractpokitservice_p.h.
{ true };                    ///< Whether autodiscovery is enabled or not.
Referenced by connected(), and createServiceObject().
controller
QLowEnergyController* AbstractPokitServicePrivate::controller { nullptr }
BLE controller to fetch the service from.
Definition at line 33 of file abstractpokitservice_p.h.
{ nullptr }; ///< BLE controller to fetch the service from.
Referenced by AbstractPokitServicePrivate(), CalibrationServicePrivate::CalibrationServicePrivate(), connected(), createServiceObject(), DataLoggerServicePrivate::DataLoggerServicePrivate(), DeviceInfoServicePrivate::DeviceInfoServicePrivate(), discoveryFinished(), DsoServicePrivate::DsoServicePrivate(), MultimeterServicePrivate::MultimeterServicePrivate(), and StatusServicePrivate::StatusServicePrivate().
pokitProduct
std::optional<PokitProduct> AbstractPokitServicePrivate::pokitProduct
The Pokit product controller is connected to.
Definition at line 34 of file abstractpokitservice_p.h.
Referenced by createServiceObject().
q_ptr
AbstractPokitService* AbstractPokitServicePrivate::q_ptr protected
Internal q-pointer.
Definition at line 55 of file abstractpokitservice_p.h.
Referenced by AbstractPokitServicePrivate().
service
QLowEnergyService* AbstractPokitServicePrivate::service { nullptr }
BLE service to read/write characteristics.
Definition at line 35 of file abstractpokitservice_p.h.
{ nullptr };       ///< BLE service to read/write characteristics.
Referenced by createServiceObject(), disableCharacteristicNotificatons(), enableCharacteristicNotificatons(), getCharacteristic(), readCharacteristic(), serviceDiscovered(), and stateChanged().
serviceUuid
QBluetoothUuid AbstractPokitServicePrivate::serviceUuid
UUIDs for service.
Definition at line 36 of file abstractpokitservice_p.h.
Referenced by AbstractPokitServicePrivate(), CalibrationServicePrivate::CalibrationServicePrivate(), DataLoggerServicePrivate::characteristicChanged(), DsoServicePrivate::characteristicChanged(), MultimeterServicePrivate::characteristicChanged(), DataLoggerServicePrivate::characteristicRead(), DeviceInfoServicePrivate::characteristicRead(), DsoServicePrivate::characteristicRead(), MultimeterServicePrivate::characteristicRead(), StatusServicePrivate::characteristicRead(), CalibrationServicePrivate::characteristicWritten(), DataLoggerServicePrivate::characteristicWritten(), DsoServicePrivate::characteristicWritten(), MultimeterServicePrivate::characteristicWritten(), StatusServicePrivate::characteristicWritten(), createServiceObject(), DataLoggerServicePrivate::DataLoggerServicePrivate(), DeviceInfoServicePrivate::DeviceInfoServicePrivate(), DsoServicePrivate::DsoServicePrivate(), MultimeterServicePrivate::MultimeterServicePrivate(), serviceDiscovered(), and StatusServicePrivate::serviceDiscovered().
The documentation for this class was generated from the following files:
abstractpokitservice_p.h
abstractpokitservice.cpp