QtPokit: PokitDeviceDiscoveryAgent Class Reference
PokitDeviceDiscoveryAgent Class Reference
The PokitDeviceDiscoveryAgent class discovers nearby Pokit devices.
#include <pokitdevicedisoveryagent.h>
Public Slots
void start (QBluetoothDeviceDiscoveryAgent::DiscoveryMethods methods)
Starts Pokit device discovery.
void start ()
Starts Pokit device discovery.
Signals
void pokitDeviceDiscovered (const QBluetoothDeviceInfo &info)
This signal is emitted when the Pokit device described by info is discovered.
void pokitDeviceUpdated (const QBluetoothDeviceInfo &info, QBluetoothDeviceInfo::Fields updatedFields)
This signal is emitted when the Pokit device described by info is updated.
Public Member Functions
PokitDeviceDiscoveryAgent (const QBluetoothAddress &deviceAdapter, QObject *parent=nullptr)
Constructs a new Pokit device discovery agent with parent, using deviceAdapter for the search device.
PokitDeviceDiscoveryAgent (QObject *parent=nullptr)
Constructs a new Pokit device discovery agent with parent.
Static Public Member Functions
static bool isPokitDevice (const QBluetoothDeviceInfo &info)
Returns true if info describes a Pokit device.
Private Slots
void onDeviceDiscovered (const QBluetoothDeviceInfo &info)
Handle deviceDiscovered signals.
void onDeviceUpdated (const QBluetoothDeviceInfo &info, QBluetoothDeviceInfo::Fields updatedFields)
Handle deviceUpdated signals.
Detailed Description
The PokitDeviceDiscoveryAgent class discovers nearby Pokit devices.
After constructing a PokitDeviceDiscoveryAgent object, and subscribing to the relevant signals, invoke start() to begin discovery.
Definition at line 37 of file pokitdevicedisoveryagent.h.
Constructor & Destructor Documentation
PokitDeviceDiscoveryAgent() [1/2]
PokitDeviceDiscoveryAgent::PokitDeviceDiscoveryAgent (const QBluetoothAddress & deviceAdapter, QObject * parent = nullptr) explicit
Constructs a new Pokit device discovery agent with parent, using deviceAdapter for the search device.
Definition at line 39 of file pokitdevicedisoveryagent.cpp.
    : QBluetoothDeviceDiscoveryAgent(deviceAdapter, parent)
{
    connect(this, &QBluetoothDeviceDiscoveryAgent::deviceDiscovered,
            this, &PokitDeviceDiscoveryAgent::onDeviceDiscovered);
    #if (QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)) // Signal added in Qt 5.12.
    connect(this, &QBluetoothDeviceDiscoveryAgent::deviceUpdated,
            this, &PokitDeviceDiscoveryAgent::onDeviceUpdated);
    #endif
}
References onDeviceDiscovered(), and onDeviceUpdated().
PokitDeviceDiscoveryAgent() [2/2]
PokitDeviceDiscoveryAgent::PokitDeviceDiscoveryAgent (QObject * parent = nullptr)
Constructs a new Pokit device discovery agent with parent.
Definition at line 55 of file pokitdevicedisoveryagent.cpp.
    : QBluetoothDeviceDiscoveryAgent(parent)
{
    connect(this, &QBluetoothDeviceDiscoveryAgent::deviceDiscovered,
            this, &PokitDeviceDiscoveryAgent::onDeviceDiscovered);
    #if (QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)) // Signal added in Qt 5.12.
    connect(this, &QBluetoothDeviceDiscoveryAgent::deviceUpdated,
            this, &PokitDeviceDiscoveryAgent::onDeviceUpdated);
    #endif
}
References onDeviceDiscovered(), and onDeviceUpdated().
Member Function Documentation
isPokitDevice()
bool PokitDeviceDiscoveryAgent::isPokitDevice (const QBluetoothDeviceInfo & info) static
Returns true if info describes a Pokit device.
Currently, this is based on whether or not info's service UUIDs includes a known Pokit service, but this test criteria might be swapped for something more explicity sometime.
Definition at line 73 of file pokitdevicedisoveryagent.cpp.
{
    return info.serviceUuids().contains(QBluetoothUuid(QStringLiteral(POKIT_SERVICE_STATUS)));
}
References POKIT_SERVICE_STATUS.
Referenced by onDeviceDiscovered(), and onDeviceUpdated().
onDeviceDiscovered
void PokitDeviceDiscoveryAgent::onDeviceDiscovered (const QBluetoothDeviceInfo & info) private slot
Handle deviceDiscovered signals.
Here we simply check if info describes a Pokit device, and if so, emit pokitDeviceDiscovered().
Definition at line 116 of file pokitdevicedisoveryagent.cpp.
{
    if (!isPokitDevice(info)) return;
    qCDebug(pokitDiscovery) << "Discovered Pokit device" << info.name() << info.address();
    emit pokitDeviceDiscovered(info);
}
References isPokitDevice(), and pokitDeviceDiscovered().
Referenced by PokitDeviceDiscoveryAgent().
onDeviceUpdated
void PokitDeviceDiscoveryAgent::onDeviceUpdated (const QBluetoothDeviceInfo & info, QBluetoothDeviceInfo::Fields updatedFields) private slot
Handle deviceUpdated signals.
Here we simply check if info describes a Pokit device, and if so, emit pokitDeviceUpdated().
Since
Qt 5.12.0
Definition at line 131 of file pokitdevicedisoveryagent.cpp.
{
    if (!isPokitDevice(info)) return;
    qCDebug(pokitDiscovery) << "Updated Pokit device" << info.name() << info.address() << info.rssi();
    emit pokitDeviceUpdated(info, updatedFields);
}
References isPokitDevice(), and pokitDeviceUpdated().
Referenced by PokitDeviceDiscoveryAgent().
pokitDeviceUpdated
void PokitDeviceDiscoveryAgent::pokitDeviceUpdated (const QBluetoothDeviceInfo & info, QBluetoothDeviceInfo::Fields updatedFields) signal
This signal is emitted when the Pokit device described by info is updated.
The updatedFields flags tell which information has been updated.
Referenced by onDeviceUpdated().
start [1/2]
void PokitDeviceDiscoveryAgent::start () slot
Starts Pokit device discovery.
Definition at line 93 of file pokitdevicedisoveryagent.cpp.
{
    QBluetoothDeviceDiscoveryAgent::start(QBluetoothDeviceDiscoveryAgent::LowEnergyMethod);
}
start [2/2]
void PokitDeviceDiscoveryAgent::start (QBluetoothDeviceDiscoveryAgent::DiscoveryMethods methods) slot
Starts Pokit device discovery.
This override simply enforces that method must be LowEnergyMethod, as all Pokit devices used Bluetooth Low Energy (BLE).
Definition at line 84 of file pokitdevicedisoveryagent.cpp.
{
    Q_ASSERT(methods == QBluetoothDeviceDiscoveryAgent::LowEnergyMethod);
    QBluetoothDeviceDiscoveryAgent::start(QBluetoothDeviceDiscoveryAgent::LowEnergyMethod);
}
Referenced by Scanner::start().
The documentation for this class was generated from the following files:
pokitdevicedisoveryagent.h
pokitdevicedisoveryagent.cpp