Dokit: DeviceInfoService Class Reference
DeviceInfoService Class Reference
The DeviceInfoService class accesses the Device Info service of Pokit devices.
Classes
struct CharacteristicUuids
Characteristics available via the Device Info service.
Signals
void manufacturerRead (const QString &name)
This signal is emitted when the Manufacturer Name characteristic has been read successfully.
void modelNumberRead (const QString &model)
This signal is emitted when the Model Number characteristic has been read successfully.
void hardwareRevisionRead (const QString &revision)
This signal is emitted when the Hardware Revision characteristic has been read successfully.
void firmwareRevisionRead (const QString &revision)
This signal is emitted when the Firmware Revision characteristic has been read successfully.
void softwareRevisionRead (const QString &revision)
This signal is emitted when the Software Revision characteristic has been read successfully.
void serialNumberRead (const QString &serialNumber)
This signal is emitted when the Serial Number characteristic has been read successfully.
Signals inherited from AbstractPokitService
void serviceDetailsDiscovered ()
This signal is emitted when the Pokit service details have been discovered.
void serviceErrorOccurred (QLowEnergyService::ServiceError newError)
This signal is emitted whenever an error occurs on the underlying QLowEnergyService.
Public Member Functions
DeviceInfoService (QLowEnergyController *const pokitDevice, QObject *parent=nullptr)
Constructs a new Pokit service with parent.
bool readCharacteristics () override
Read all characteristics.
bool readFirmwareRevisionCharacteristic ()
Read the Device Info service's Firmware Revision characteristic.
bool readHardwareRevisionCharacteristic ()
Read the Device Info service's Hardware Revision characteristic.
bool readManufacturerCharacteristics ()
Read the Device Info service's Manufacturer Name characteristic.
bool readModelNumberCharacteristic ()
Read the Device Info service's Model Number characteristic.
bool readSoftwareRevisionCharacteristic ()
Read the Device Info service's Software Revision characteristic.
bool readSerialNumberCharacteristic ()
Read the Device Info service's (undocumented) Serial Number characteristic.
QString manufacturer () const
Returns the most recent value of the Device Info service's Manufacturer Name characteristic.
QString modelNumber () const
Returns the most recent value of the Device Info service's Model Number characteristic.
QString hardwareRevision () const
Returns the most recent value of the Device Info service's Hardware Revision characteristic.
QString firmwareRevision () const
Returns the most recent value of the Device Info service's Firmware Revision characteristic.
QString softwareRevision () const
Returns the most recent value of the Device Info service's Software Revision characteristic.
QString serialNumber () const
Returns the most recent value of the Device Info service's (undocumented) Serial Number characteristic.
Public Member Functions inherited from AbstractPokitService
virtual ~AbstractPokitService ()
Destroys this AbstractPokitService object.
bool autoDiscover () const
Returns true if autodiscovery of services and service details is enabled, false otherwise.
void setAutoDiscover (const bool discover=true)
If discover is true, autodiscovery will be attempted.
std::optional< PokitProduct > pokitProduct () const
Returns the Pokit product this service is attached to.
void setPokitProduct (const PokitProduct product)
Sets the current Pokit product.
QLowEnergyService * service ()
Returns a non-const pointer to the internal service object, if any.
const QLowEnergyService * service () const
Returns a const pointer to the internal service object, if any.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Attributes
static const QBluetoothUuid serviceUuid { QBluetoothUuid::ServiceClassUuid::DeviceInformation }
UUID of the "Device Info" service.
Protected Member Functions
DeviceInfoService (DeviceInfoServicePrivate *const d, QObject *const parent)
Constructs a new Pokit service with parent, and private implementation d.
Protected Member Functions inherited from AbstractPokitService
AbstractPokitService (AbstractPokitServicePrivate *const d, QObject *const parent)
Constructs a new Pokit service with parent, and private implementation d.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Additional Inherited Members
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Protected Attributes inherited from AbstractPokitService
AbstractPokitServicePrivate * d_ptr
Internal d-pointer.
Properties inherited from QObject
objectName
Detailed Description
The DeviceInfoService class accesses the Device Info service of Pokit devices.
Definition at line 22 of file deviceinfoservice.h.
Constructor & Destructor Documentation
DeviceInfoService() [1/2]
DeviceInfoService::DeviceInfoService (QLowEnergyController *const pokitDevice, QObject * parent = nullptr)
Constructs a new Pokit service with parent.
Definition at line 27 of file deviceinfoservice.cpp.
    : AbstractPokitService(new DeviceInfoServicePrivate(controller, this), parent)
{
}
References QObject::parent(), and QObject::QObject().
Referenced by firmwareRevision(), hardwareRevision(), manufacturer(), modelNumber(), readFirmwareRevisionCharacteristic(), readHardwareRevisionCharacteristic(), readManufacturerCharacteristics(), readModelNumberCharacteristic(), readSerialNumberCharacteristic(), readSoftwareRevisionCharacteristic(), serialNumber(), serialNumberRead(), and softwareRevision().
DeviceInfoService() [2/2]
DeviceInfoService::DeviceInfoService (DeviceInfoServicePrivate *const d, QObject *const parent) protected
Constructs a new Pokit service with parent, and private implementation d.
Definition at line 37 of file deviceinfoservice.cpp.
    : AbstractPokitService(d, parent)
{
}
References QObject::parent(), and QObject::QObject().
Member Function Documentation
firmwareRevision()
QString DeviceInfoService::firmwareRevision () const
Returns the most recent value of the Device Info service's Firmware Revision characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then a null QString is returned.
Definition at line 199 of file deviceinfoservice.cpp.
{
    Q_D(const DeviceInfoService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::firmwareRevision);
    return (characteristic.isValid()) ? QString::fromUtf8(characteristic.value()) : QString();
}
References DeviceInfoService(), DeviceInfoService::CharacteristicUuids::firmwareRevision, QString::fromUtf8(), QLowEnergyCharacteristic::isValid(), and QLowEnergyCharacteristic::value().
firmwareRevisionRead
void DeviceInfoService::firmwareRevisionRead (const QString & revision) signal
This signal is emitted when the Firmware Revision characteristic has been read successfully.
See also
readFirmwareRevisionCharacteristic
firmwareRevision
hardwareRevision()
QString DeviceInfoService::hardwareRevision () const
Returns the most recent value of the Device Info service's Hardware Revision characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then a null QString is returned.
Definition at line 184 of file deviceinfoservice.cpp.
{
    Q_D(const DeviceInfoService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::hardwareRevision);
    return (characteristic.isValid()) ? QString::fromUtf8(characteristic.value()) : QString();
}
References DeviceInfoService(), QString::fromUtf8(), DeviceInfoService::CharacteristicUuids::hardwareRevision, QLowEnergyCharacteristic::isValid(), and QLowEnergyCharacteristic::value().
hardwareRevisionRead
void DeviceInfoService::hardwareRevisionRead (const QString & revision) signal
This signal is emitted when the Hardware Revision characteristic has been read successfully.
See also
readHardwareRevisionCharacteristic
hardwareRevision
manufacturer()
QString DeviceInfoService::manufacturer () const
Returns the most recent value of the Device Info service's Manufacturer Name characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then a null QString is returned.
Definition at line 154 of file deviceinfoservice.cpp.
{
    Q_D(const DeviceInfoService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::manufacturerName);
    return (characteristic.isValid()) ? QString::fromUtf8(characteristic.value()) : QString();
}
References DeviceInfoService(), QString::fromUtf8(), QLowEnergyCharacteristic::isValid(), DeviceInfoService::CharacteristicUuids::manufacturerName, and QLowEnergyCharacteristic::value().
manufacturerRead
void DeviceInfoService::manufacturerRead (const QString & name) signal
This signal is emitted when the Manufacturer Name characteristic has been read successfully.
See also
readManufacturerCharacteristic
manufacturer
modelNumber()
QString DeviceInfoService::modelNumber () const
Returns the most recent value of the Device Info service's Model Number characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then a null QString is returned.
Definition at line 169 of file deviceinfoservice.cpp.
{
    Q_D(const DeviceInfoService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::modelNumber);
    return (characteristic.isValid()) ? QString::fromUtf8(characteristic.value()) : QString();
}
References DeviceInfoService(), QString::fromUtf8(), QLowEnergyCharacteristic::isValid(), DeviceInfoService::CharacteristicUuids::modelNumber, and QLowEnergyCharacteristic::value().
modelNumberRead
void DeviceInfoService::modelNumberRead (const QString & model) signal
This signal is emitted when the Model Number characteristic has been read successfully.
See also
readModelNumberCharacteristic
modelNumber
readCharacteristics()
bool DeviceInfoService::readCharacteristics () override virtual
Read all characteristics.
This convenience function will queue refresh requests of all characteristics supported by this service.
Relevant *Service::*Read signals will be emitted by derived class objects as each characteristic is successfully read.
Implements AbstractPokitService.
Definition at line 45 of file deviceinfoservice.cpp.
{
    const bool r1 = readFirmwareRevisionCharacteristic();
    const bool r2 = readHardwareRevisionCharacteristic();
    const bool r3 = readSoftwareRevisionCharacteristic();
    const bool r4 = readManufacturerCharacteristics();
    const bool r5 = readModelNumberCharacteristic();
    const bool r6 = ((service() != nullptr) && (service()->characteristic(CharacteristicUuids::serialNumber).isValid()))
        ? readSerialNumberCharacteristic() : true;
    return (r1 && r2 && r3 && r4 && r5 && r6);
}
References QLowEnergyService::characteristic(), QLowEnergyCharacteristic::isValid(), readFirmwareRevisionCharacteristic(), readHardwareRevisionCharacteristic(), readManufacturerCharacteristics(), readModelNumberCharacteristic(), readSerialNumberCharacteristic(), readSoftwareRevisionCharacteristic(), DeviceInfoService::CharacteristicUuids::serialNumber, and AbstractPokitService::service().
readFirmwareRevisionCharacteristic()
bool DeviceInfoService::readFirmwareRevisionCharacteristic ()
Read the Device Info service's Firmware Revision characteristic.
Returns true is the read request is successfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits firmwareRevisionRead() if/when the characteristic has been read successfully.
Definition at line 66 of file deviceinfoservice.cpp.
{
    Q_D(DeviceInfoService);
    return d->readCharacteristic(CharacteristicUuids::firmwareRevision);
}
References DeviceInfoService(), and DeviceInfoService::CharacteristicUuids::firmwareRevision.
Referenced by readCharacteristics().
readHardwareRevisionCharacteristic()
bool DeviceInfoService::readHardwareRevisionCharacteristic ()
Read the Device Info service's Hardware Revision characteristic.
Returns true is the read request is successfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits hardwareRevisionRead() if/when the characteristic has been read successfully.
Definition at line 81 of file deviceinfoservice.cpp.
{
    Q_D(DeviceInfoService);
    return d->readCharacteristic(CharacteristicUuids::hardwareRevision);
}
References DeviceInfoService(), and DeviceInfoService::CharacteristicUuids::hardwareRevision.
Referenced by readCharacteristics().
readManufacturerCharacteristics()
bool DeviceInfoService::readManufacturerCharacteristics ()
Read the Device Info service's Manufacturer Name characteristic.
Returns true is the read request is successfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits manufacturerNameRead() if/when the characteristic has been read successfully.
Definition at line 96 of file deviceinfoservice.cpp.
{
    Q_D(DeviceInfoService);
    return d->readCharacteristic(CharacteristicUuids::manufacturerName);
}
References DeviceInfoService(), and DeviceInfoService::CharacteristicUuids::manufacturerName.
Referenced by readCharacteristics().
readModelNumberCharacteristic()
bool DeviceInfoService::readModelNumberCharacteristic ()
Read the Device Info service's Model Number characteristic.
Returns true is the read request is successfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits modelNumberRead() if/when the characteristic has been read successfully.
Definition at line 111 of file deviceinfoservice.cpp.
{
    Q_D(DeviceInfoService);
    return d->readCharacteristic(CharacteristicUuids::modelNumber);
}
References DeviceInfoService(), and DeviceInfoService::CharacteristicUuids::modelNumber.
Referenced by readCharacteristics().
readSerialNumberCharacteristic()
bool DeviceInfoService::readSerialNumberCharacteristic ()
Read the Device Info service's (undocumented) Serial Number characteristic.
Returns true is the read request is successfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits serialNumberRead() if/when the characteristic has been read successfully.
Definition at line 141 of file deviceinfoservice.cpp.
{
    Q_D(DeviceInfoService);
    return d->readCharacteristic(CharacteristicUuids::serialNumber);
}
References DeviceInfoService(), and DeviceInfoService::CharacteristicUuids::serialNumber.
Referenced by readCharacteristics().
readSoftwareRevisionCharacteristic()
bool DeviceInfoService::readSoftwareRevisionCharacteristic ()
Read the Device Info service's Software Revision characteristic.
Returns true is the read request is successfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits softwareRevisionRead() if/when the characteristic has been read successfully.
Definition at line 126 of file deviceinfoservice.cpp.
{
    Q_D(DeviceInfoService);
    return d->readCharacteristic(CharacteristicUuids::softwareRevision);
}
References DeviceInfoService(), and DeviceInfoService::CharacteristicUuids::softwareRevision.
Referenced by readCharacteristics().
serialNumber()
QString DeviceInfoService::serialNumber () const
Returns the most recent value of the Device Info service's (undocumented) Serial Number characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then a null QString is returned.
Pokit Bluetooth API errata
Unlike other string characteristics, Pokit (Pro) devices always appear to add a trailing null byte to serial number strings. So here we strip any that are present.
Definition at line 230 of file deviceinfoservice.cpp.
{
    Q_D(const DeviceInfoService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::serialNumber);
    /*!
     * \cond internal
     * \pokitApi Unlike other string characteristics, Pokit (Pro) devices always appear to add a trailing
     * `null` byte to serial number strings. So here we strip any that are present.
     * \endcond
     */
    return (characteristic.isValid()) ? QString::fromUtf8(characteristic.value()).remove('\0'_L1) : QString();
}
References DeviceInfoService(), QString::fromUtf8(), QLowEnergyCharacteristic::isValid(), QString::remove(), DeviceInfoService::CharacteristicUuids::serialNumber, and QLowEnergyCharacteristic::value().
Referenced by serialNumberRead().
serialNumberRead
void DeviceInfoService::serialNumberRead (const QString & serialNumber) signal
This signal is emitted when the Serial Number characteristic has been read successfully.
See also
readSerialNumberCharacteristic
serialNumber
References DeviceInfoService(), QObject::parent(), QObject::QObject(), and serialNumber().
softwareRevision()
QString DeviceInfoService::softwareRevision () const
Returns the most recent value of the Device Info service's Software Revision characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then a null QString is returned.
Definition at line 214 of file deviceinfoservice.cpp.
{
    Q_D(const DeviceInfoService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::softwareRevision);
    return (characteristic.isValid()) ? QString::fromUtf8(characteristic.value()) : QString();
}
References DeviceInfoService(), QString::fromUtf8(), QLowEnergyCharacteristic::isValid(), DeviceInfoService::CharacteristicUuids::softwareRevision, and QLowEnergyCharacteristic::value().
softwareRevisionRead
void DeviceInfoService::softwareRevisionRead (const QString & revision) signal
This signal is emitted when the Software Revision characteristic has been read successfully.
See also
readSoftwareRevisionCharacteristic
softwareRevision
Member Data Documentation
serviceUuid
const QBluetoothUuid DeviceInfoService::serviceUuid { QBluetoothUuid::ServiceClassUuid::DeviceInformation } inline static
UUID of the "Device Info" service.
Definition at line 28 of file deviceinfoservice.h.
{ QBluetoothUuid::ServiceClassUuid::DeviceInformation }; // 0x180a
Referenced by PokitDevice::serviceToString().
The documentation for this class was generated from the following files:
deviceinfoservice.h
deviceinfoservice.cpp