Dokit: StatusServicePrivate Class Reference
StatusServicePrivate Class Reference
The StatusServicePrivate class provides private implementation for StatusService.
Public Member Functions
StatusServicePrivate (QLowEnergyController *controller, StatusService *const q)
Public Member Functions inherited from AbstractPokitServicePrivate
AbstractPokitServicePrivate (const QBluetoothUuid &serviceUuid, QLowEnergyController *controller, AbstractPokitService *const q)
bool createServiceObject ()
Creates an internal service object from the internal controller.
QLowEnergyCharacteristic getCharacteristic (const QBluetoothUuid &uuid) const
Get uuid characteristic from the underlying service.
bool readCharacteristic (const QBluetoothUuid &uuid)
Read the uuid characteristic.
bool enableCharacteristicNotificatons (const QBluetoothUuid &uuid)
Enables client (Pokit device) side notification for characteristic uuid.
bool disableCharacteristicNotificatons (const QBluetoothUuid &uuid)
Disables client (Pokit device) side notification for characteristic uuid.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Member Functions
static StatusService::DeviceCharacteristics parseDeviceCharacteristics (const QByteArray &value)
Parses the Device Characteristics value into a DeviceCharacteristics struct.
static StatusService::Status parseStatus (const QByteArray &value)
Parses the Status value into a Status struct.
static std::optional< StatusService::TorchStatus > parseTorchStatus (const QByteArray &value)
Parses the torch status value, and returns the corresponding TorchStatus.
static std::optional< StatusService::ButtonStatus > parseButtonPress (const QByteArray &value)
Parses the button press value, and returns the corresponding ButtonStatus.
Static Public Member Functions inherited from AbstractPokitServicePrivate
static Q_LOGGING_CATEGORY (lc, "pokit.ble.service", QtInfoMsg)
Logging category.
static bool checkSize (const QString &label, const QByteArray &data, const int minSize, const int maxSize=-1, const bool failOnMax=false)
Returns false if data is smaller than minSize, otherwise returns failOnMax if data is bigger than maxSize, otherwise returns true.
static QString toHexString (const QByteArray &data, const int maxSize=20)
Returns up to maxSize bytes of data as a human readable hexadecimal string.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Protected Member Functions
void serviceDiscovered (const QBluetoothUuid &newService) override
Handles QLowEnergyController::serviceDiscovered events.
void characteristicRead (const QLowEnergyCharacteristic &characteristic, const QByteArray &value) override
Implements AbstractPokitServicePrivate::characteristicRead to parse value, then emit a specialised signal, for each supported characteristic.
void characteristicWritten (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue) override
Implements AbstractPokitServicePrivate::characteristicWritten to parse newValue, then emit a specialised signal, for each supported characteristic.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Additional Inherited Members
Public Attributes inherited from AbstractPokitServicePrivate
bool autoDiscover { true }
Whether autodiscovery is enabled or not.
QLowEnergyController * controller { nullptr }
BLE controller to fetch the service from.
std::optional< PokitProduct > pokitProduct
The Pokit product controller is connected to.
QLowEnergyService * service { nullptr }
BLE service to read/write characteristics.
QBluetoothUuid serviceUuid
UUIDs for service.
Public Attributes inherited from QObject
typedef QObjectList
Protected Slots inherited from AbstractPokitServicePrivate
void connected ()
Handles QLowEnergyController::connected events.
void discoveryFinished ()
Handles QLowEnergyController::discoveryFinished events.
void errorOccurred (const QLowEnergyService::ServiceError newError)
Handles QLowEnergyController::errorOccurred events.
void stateChanged (QLowEnergyService::ServiceState newState)
Handles QLowEnergyController::stateChanged events.
virtual void characteristicChanged (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue)
Handles QLowEnergyService::characteristicChanged events.
Protected Attributes inherited from AbstractPokitServicePrivate
AbstractPokitService * q_ptr
Internal q-pointer.
Properties inherited from QObject
objectName
Detailed Description
The StatusServicePrivate class provides private implementation for StatusService.
Definition at line 18 of file statusservice_p.h.
Constructor & Destructor Documentation
StatusServicePrivate()
StatusServicePrivate::StatusServicePrivate (QLowEnergyController * controller, StatusService *const q) explicit
Constructs a new StatusServicePrivate object with public implementation q.
Definition at line 570 of file statusservice.cpp.
    : AbstractPokitServicePrivate(QBluetoothUuid(), controller, q)
{
}
References AbstractPokitServicePrivate::AbstractPokitServicePrivate(), and AbstractPokitServicePrivate::controller.
Member Function Documentation
characteristicRead()
void StatusServicePrivate::characteristicRead (const QLowEnergyCharacteristic & characteristic, const QByteArray & value) override protected virtual
Implements AbstractPokitServicePrivate::characteristicRead to parse value, then emit a specialised signal, for each supported characteristic.
Reimplemented from AbstractPokitServicePrivate.
Definition at line 731 of file statusservice.cpp.
{
    AbstractPokitServicePrivate::characteristicRead(characteristic, value);
    Q_Q(StatusService);
    if (characteristic.uuid() == StatusService::CharacteristicUuids::deviceCharacteristics) {
        Q_EMIT q->deviceCharacteristicsRead(parseDeviceCharacteristics(value));
        return;
    }
    if (characteristic.uuid() == StatusService::CharacteristicUuids::status) {
        Q_EMIT q->deviceStatusRead(parseStatus(value));
        return;
    }
    if (characteristic.uuid() == StatusService::CharacteristicUuids::name) {
        const QString deviceName = QString::fromUtf8(value);
        qCDebug(lc).noquote() << tr(R"(Device name: "%1")").arg(deviceName);
        Q_EMIT q->deviceNameRead(deviceName);
        return;
    }
    if (characteristic.uuid() == StatusService::CharacteristicUuids::flashLed) {
        qCWarning(lc).noquote() << tr("Flash LED characteristic is write-only, but somehow read")
            << serviceUuid << characteristic.name() << characteristic.uuid();
        return;
    }
    if (characteristic.uuid() == StatusService::CharacteristicUuids::torch) {
        if (!checkSize(u"Torch"_s, value, 1, 1)) {
            return;
        }
        const StatusService::TorchStatus status = static_cast<StatusService::TorchStatus>(value.at(0));
        qCDebug(lc).noquote() << tr("Torch status:  %1 (%2)").arg((quint8)status).arg(StatusService::toString(status));
        Q_EMIT q->torchStatusRead(status);
        return;
    }
    if (characteristic.uuid() == StatusService::CharacteristicUuids::buttonPress) {
        if (!checkSize(u"Torch"_s, value, 2, 2)) {
            return;
        }
        const StatusService::ButtonStatus status = static_cast<StatusService::ButtonStatus>(value.at(1));
        qCDebug(lc).noquote() << tr("Button status:  %1 (%2)").arg((quint8)status).arg(StatusService::toString(status));
        Q_EMIT q->buttonPressRead(value.at(0), status);
        return;
    }
    qCWarning(lc).noquote() << tr("Unknown characteristic read for Status service")
        << serviceUuid << characteristic.name() << characteristic.uuid();
}
References QString::arg(), QByteArray::at(), StatusService::CharacteristicUuids::buttonPress, AbstractPokitServicePrivate::characteristicRead(), AbstractPokitServicePrivate::checkSize(), StatusService::CharacteristicUuids::deviceCharacteristics, StatusService::CharacteristicUuids::flashLed, QString::fromUtf8(), QLowEnergyCharacteristic::name(), StatusService::CharacteristicUuids::name, parseDeviceCharacteristics(), parseStatus(), QObject::Q_EMIT(), AbstractPokitServicePrivate::serviceUuid, StatusService::CharacteristicUuids::status, StatusService::CharacteristicUuids::torch, StatusService::toString(), QObject::tr(), and QLowEnergyCharacteristic::uuid().
characteristicWritten()
void StatusServicePrivate::characteristicWritten (const QLowEnergyCharacteristic & characteristic, const QByteArray & newValue) override protected virtual
Implements AbstractPokitServicePrivate::characteristicWritten to parse newValue, then emit a specialised signal, for each supported characteristic.
Reimplemented from AbstractPokitServicePrivate.
Definition at line 788 of file statusservice.cpp.
{
    AbstractPokitServicePrivate::characteristicWritten(characteristic, newValue);
    Q_Q(StatusService);
    if (characteristic.uuid() == StatusService::CharacteristicUuids::deviceCharacteristics) {
        qCWarning(lc).noquote() << tr("Device Characteristics is read-only, but somehow written")
            << serviceUuid << characteristic.name() << characteristic.uuid();
        return;
    }
    if (characteristic.uuid() == StatusService::CharacteristicUuids::status) {
        qCWarning(lc).noquote() << tr("Status characteristic is read-only, but somehow written")
            << serviceUuid << characteristic.name() << characteristic.uuid();
        return;
    }
    if (characteristic.uuid() == StatusService::CharacteristicUuids::name) {
        Q_EMIT q->deviceNameWritten();
        return;
    }
    if (characteristic.uuid() == StatusService::CharacteristicUuids::flashLed) {
        Q_EMIT q->deviceLedFlashed();
        return;
    }
    if (characteristic.uuid() == StatusService::CharacteristicUuids::torch) {
        Q_EMIT q->torchStatusWritten();
        return;
    }
    qCWarning(lc).noquote() << tr("Unknown characteristic written for Status service")
        << serviceUuid << characteristic.name() << characteristic.uuid();
}
References AbstractPokitServicePrivate::characteristicWritten(), StatusService::CharacteristicUuids::deviceCharacteristics, StatusService::CharacteristicUuids::flashLed, QLowEnergyCharacteristic::name(), StatusService::CharacteristicUuids::name, QObject::Q_EMIT(), AbstractPokitServicePrivate::serviceUuid, StatusService::CharacteristicUuids::status, StatusService::CharacteristicUuids::torch, QObject::tr(), and QLowEnergyCharacteristic::uuid().
parseButtonPress()
std::optional< StatusService::ButtonStatus > StatusServicePrivate::parseButtonPress (const QByteArray & value) static
Parses the button press value, and returns the corresponding ButtonStatus.
Pokit Bluetooth API errata
The button event is the second byte, but no idea what the first byte is. In all examples I've see it's always 0x02. It appears that the Pokit Android app only ever looks at bytes[1].
Pokit Bluetooth API errata
Note, we can actually write to the Button Press characteristic too. If we do, then whatever we set as the first byte persists, and (unsurprisingly) the second byte reverts to the current button state. So still no idea what that first byte is for.
Definition at line 689 of file statusservice.cpp.
{
    if (!checkSize(u"Torch"_s, value, 2, 2)) {
        return std::nullopt;
    }
    /*!
     * \pokitApi The button event is the second byte, but no idea what the first byte is. In all examples
     * I've see it's always `0x02`. It appears that the Pokit Android app only ever looks at `bytes[1]`.
     *
     * \pokitApi Note, we can actually write to the Button Press characteristic too. If we do, then whatever
     * we set as the first byte persists, and (unsurprisingly) the second byte reverts to the current
     * button state. So still no idea what that first byte is for.
     */
    const StatusService::ButtonStatus status = static_cast<StatusService::ButtonStatus>(value.at(1));
    qCDebug(lc).noquote() << tr("Button: %1 (%2)").arg((quint8)status).arg(StatusService::toString(status));
    return status;
}
References QString::arg(), QByteArray::at(), AbstractPokitServicePrivate::checkSize(), StatusService::toString(), and QObject::tr().
Referenced by StatusService::buttonPress().
parseDeviceCharacteristics()
StatusService::DeviceCharacteristics StatusServicePrivate::parseDeviceCharacteristics (const QByteArray & value) static
Parses the Device Characteristics value into a DeviceCharacteristics struct.
Definition at line 580 of file statusservice.cpp.
{
    StatusService::DeviceCharacteristics characteristics{
        QVersionNumber(), 0, 0, 0, 0, 0, 0, QBluetoothAddress()
    };
    Q_ASSERT(characteristics.firmwareVersion.isNull());  // How we indicate failure.
    if (!checkSize(u"Device Characteristics"_s, value, 20, 20)) {
        return characteristics;
    }
    characteristics.firmwareVersion = QVersionNumber(
                                          qFromLittleEndian<quint8 >(value.mid(0,1).constData()),
                                          qFromLittleEndian<quint8 >(value.mid(1,1).constData()));
    characteristics.maximumVoltage      = qFromLittleEndian<quint16>(value.mid(2,2).constData());
    characteristics.maximumCurrent      = qFromLittleEndian<quint16>(value.mid(4,2).constData());
    characteristics.maximumResistance   = qFromLittleEndian<quint16>(value.mid(6,2).constData());
    characteristics.maximumSamplingRate = qFromLittleEndian<quint16>(value.mid(8,2).constData());
    characteristics.samplingBufferSize  = qFromLittleEndian<quint16>(value.mid(10,2).constData());
    characteristics.capabilityMask      = qFromLittleEndian<quint16>(value.mid(12,2).constData());
    characteristics.macAddress = QBluetoothAddress(qFromBigEndian<quint64>
                                                   ((QByteArray(2, '\0') + value.mid(14,6)).constData()));
    qCDebug(lc).noquote() << tr("Firmware version:     ") << characteristics.firmwareVersion;
    qCDebug(lc).noquote() << tr("Maximum voltage:      ") << characteristics.maximumVoltage;
    qCDebug(lc).noquote() << tr("Maximum current:      ") << characteristics.maximumCurrent;
    qCDebug(lc).noquote() << tr("Maximum resistance:   ") << characteristics.maximumResistance;
    qCDebug(lc).noquote() << tr("Maximum sampling rate:") << characteristics.maximumSamplingRate;
    qCDebug(lc).noquote() << tr("Sampling buffer size: ") << characteristics.samplingBufferSize;
    qCDebug(lc).noquote() << tr("Capability mask:      ") << characteristics.capabilityMask;
    qCDebug(lc).noquote() << tr("MAC address:          ") << characteristics.macAddress;
    Q_ASSERT(!characteristics.firmwareVersion.isNull()); // How we indicate success.
    return characteristics;
}
References StatusService::DeviceCharacteristics::capabilityMask, AbstractPokitServicePrivate::checkSize(), QByteArray::constData(), StatusService::DeviceCharacteristics::firmwareVersion, QVersionNumber::isNull(), StatusService::DeviceCharacteristics::macAddress, StatusService::DeviceCharacteristics::maximumCurrent, StatusService::DeviceCharacteristics::maximumResistance, StatusService::DeviceCharacteristics::maximumSamplingRate, StatusService::DeviceCharacteristics::maximumVoltage, QByteArray::mid(), StatusService::DeviceCharacteristics::samplingBufferSize, and QObject::tr().
Referenced by characteristicRead(), and StatusService::deviceCharacteristics().
parseStatus()
StatusService::Status StatusServicePrivate::parseStatus (const QByteArray & value) static
Parses the Status value into a Status struct.
Note, not all Pokit devices support all members in Status. Specifically, the batteryStatus member is not usually set by Pokit Meter devices, so will be an invalid BatteryStatus enum value (255) in that case.
Pokit Bluetooth API errata
Pokit API 0.02 says the Status characteristic is 5 bytes. API 1.00 then added an additional byte for Battery Status, for 6 bytes in total. However, Pokit Pro devices return 8 bytes here. It appears that the first of those 2 extra bytes (ie the 7th byte) is used to indicate the physical switch position, while the other extra byte (ie the 8th byte) indicates the device's current charging status.
Definition at line 622 of file statusservice.cpp.
{
    StatusService::Status status{
        static_cast<StatusService::DeviceStatus>
            (std::numeric_limits<std::underlying_type_t<StatusService::DeviceStatus>>::max()),
        std::numeric_limits<float>::quiet_NaN(),
        static_cast<StatusService::BatteryStatus>
            (std::numeric_limits<std::underlying_type_t<StatusService::BatteryStatus>>::max()),
        std::nullopt, std::nullopt,
    };
    /*!
     * \pokitApi Pokit API 0.02 says the `Status` characteristic is 5 bytes. API 1.00 then added an
     * additional byte for `Battery Status`, for 6 bytes in total. However, Pokit Pro devices return
     * 8 bytes here. It appears that the first of those 2 extra bytes (ie the 7th byte) is used to
     * indicate the physical switch position, while the other extra byte (ie the 8th byte) indicates
     * the device's current charging status.
     */
    if (!checkSize(u"Status"_s, value, 5, 8)) {
        return status;
    }
    status.deviceStatus = static_cast<StatusService::DeviceStatus>(value.at(0));
    status.batteryVoltage = qFromLittleEndian<float>(value.mid(1,4).constData());
    if (value.size() >= 6) { // Battery Status added to Pokit API docs v1.00.
        status.batteryStatus = static_cast<StatusService::BatteryStatus>(value.at(5));
    }
    if (value.size() >= 7) { // Switch Position - as yet, undocumented by Pokit Innovations.
        status.switchPosition = static_cast<StatusService::SwitchPosition>(value.at(6));
    }
    if (value.size() >= 8) { // Charging Status - as yet, undocumented by Pokit Innovations.
        status.chargingStatus = static_cast<StatusService::ChargingStatus>(value.at(7));
    }
    qCDebug(lc).noquote() << tr("Device status:   %1 (%2)")
        .arg((quint8)status.deviceStatus).arg(StatusService::toString(status.deviceStatus));
    qCDebug(lc).noquote() << tr("Battery voltage: %1 volts").arg(status.batteryVoltage);
    qCDebug(lc).noquote() << tr("Battery status:  %1 (%2)")
        .arg((quint8)status.batteryStatus).arg(StatusService::toString(status.batteryStatus));
    if (status.switchPosition) {
        qCDebug(lc).noquote() << tr("Switch position: %1 (%2)")
            .arg((quint8)*status.switchPosition).arg(StatusService::toString(*status.switchPosition));
    }
    if (status.chargingStatus) {
        qCDebug(lc).noquote() << tr("Charging status: %1 (%2)")
        .arg((quint8)*status.chargingStatus).arg(StatusService::toString(*status.chargingStatus));
    }
    return status;
}
References QString::arg(), QByteArray::at(), StatusService::Status::batteryStatus, StatusService::Status::batteryVoltage, StatusService::Status::chargingStatus, AbstractPokitServicePrivate::checkSize(), QByteArray::constData(), StatusService::Status::deviceStatus, QByteArray::mid(), QByteArray::size(), StatusService::Status::switchPosition, StatusService::toString(), and QObject::tr().
Referenced by characteristicRead(), and StatusService::status().
parseTorchStatus()
std::optional< StatusService::TorchStatus > StatusServicePrivate::parseTorchStatus (const QByteArray & value) static
Parses the torch status value, and returns the corresponding TorchStatus.
Definition at line 675 of file statusservice.cpp.
{
    if (!checkSize(u"Torch"_s, value, 1, 1)) {
        return std::nullopt;
    }
    const StatusService::TorchStatus status = static_cast<StatusService::TorchStatus>(value.at(0));
    qCDebug(lc).noquote() << tr("Torch status: %1 (%2)").arg((quint8)status).arg(StatusService::toString(status));
    return status;
}
References QString::arg(), QByteArray::at(), AbstractPokitServicePrivate::checkSize(), StatusService::toString(), and QObject::tr().
Referenced by StatusService::torchStatus().
serviceDiscovered()
void StatusServicePrivate::serviceDiscovered (const QBluetoothUuid & newService) override protected virtual
Handles QLowEnergyController::serviceDiscovered events.
Here we override the base implementation to detect if we're looking at a Pokit Meter, or Pokit Pro device, as the two devices have very slightly different Status Service UUIDs.
Reimplemented from AbstractPokitServicePrivate.
Definition at line 715 of file statusservice.cpp.
{
    if (newService == StatusService::ServiceUuids::pokitMeter) {
        qCDebug(lc).noquote() << tr("Found Status Service for a Pokit Meter device.");
        serviceUuid = StatusService::ServiceUuids::pokitMeter;
    } else if (newService == StatusService::ServiceUuids::pokitPro) {
        qCDebug(lc).noquote() << tr("Found Status Service for a Pokit Pro device.");
        serviceUuid = StatusService::ServiceUuids::pokitPro;
    }
    AbstractPokitServicePrivate::serviceDiscovered(newService);
}
References StatusService::ServiceUuids::pokitMeter, StatusService::ServiceUuids::pokitPro, AbstractPokitServicePrivate::serviceDiscovered(), AbstractPokitServicePrivate::serviceUuid, and QObject::tr().
The documentation for this class was generated from the following files:
statusservice_p.h
statusservice.cpp