QtPokit: DeviceInfoServicePrivate Class Reference
DeviceInfoServicePrivate Class Reference
The DeviceInfoServicePrivate class provides private implementation for DeviceInfoService.
Public Member Functions
DeviceInfoServicePrivate (QLowEnergyController *controller, DeviceInfoService *const q)
Public Member Functions inherited from AbstractPokitServicePrivate
AbstractPokitServicePrivate (const QBluetoothUuid &serviceUuid, QLowEnergyController *controller, AbstractPokitService *const q)
bool createServiceObject ()
Creates an internal service object from the internal controller.
QLowEnergyCharacteristic getCharacteristic (const QBluetoothUuid &uuid) const
Get uuid characteristc from the underlying service.
bool readCharacteristic (const QBluetoothUuid &uuid)
Read the uuid characteristic.
bool enableCharacteristicNotificatons (const QBluetoothUuid &uuid)
Enables client (Pokit device) side notification for characteristic uuid.
bool disableCharacteristicNotificatons (const QBluetoothUuid &uuid)
Disables client (Pokit device) side notification for characteristic uuid.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Protected Member Functions
void characteristicRead (const QLowEnergyCharacteristic &characteristic, const QByteArray &value) override
Implements AbstractPokitServicePrivate::characteristicRead to parse value, then emit a specialised signal, for each supported characteristic.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Friends
class TestDeviceInfoService
Additional Inherited Members
Static Public Member Functions inherited from AbstractPokitServicePrivate
static Q_LOGGING_CATEGORY (lc, "pokit.ble.service", QtInfoMsg)
Logging category.
static bool checkSize (const QString &label, const QByteArray &data, const int minSize, const int maxSize=-1, const bool failOnMax=false)
Returns false if data is smaller than minSize, otherwise returns failOnMax if data is bigger than maxSize, otherwise returns true.
static QString toHexString (const QByteArray &data, const int maxSize=20)
Returns up to maxSize bytes of data as a human readable hexadecimal string.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from AbstractPokitServicePrivate
bool autoDiscover
Whether autodiscovery is enabled or not.
QLowEnergyController * controller
BLE controller to fetch the service from.
QLowEnergyService * service
BLE service to read/write characteristics.
QBluetoothUuid serviceUuid
UUIDs for service.
Public Attributes inherited from QObject
typedef QObjectList
Protected Slots inherited from AbstractPokitServicePrivate
void connected ()
Handles QLowEnergyController::connected events.
void discoveryFinished ()
Handles QLowEnergyController::discoveryFinished events.
void errorOccurred (const QLowEnergyService::ServiceError newError)
Handles QLowEnergyController::errorOccurred events.
virtual void serviceDiscovered (const QBluetoothUuid &newService)
Handles QLowEnergyController::serviceDiscovered events.
void stateChanged (QLowEnergyService::ServiceState newState)
Handles QLowEnergyController::stateChanged events.
virtual void characteristicRead (const QLowEnergyCharacteristic &characteristic, const QByteArray &value)
Handles QLowEnergyService::characteristicRead events.
virtual void characteristicWritten (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue)
Handles QLowEnergyService::characteristicWritten events.
virtual void characteristicChanged (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue)
Handles QLowEnergyService::characteristicChanged events.
Protected Attributes inherited from AbstractPokitServicePrivate
AbstractPokitService * q_ptr
Internal q-pointer.
Properties inherited from QObject
objectName
Detailed Description
The DeviceInfoServicePrivate class provides private implementation for DeviceInfoService.
Definition at line 18 of file deviceinfoservice_p.h.
Constructor & Destructor Documentation
DeviceInfoServicePrivate()
DeviceInfoServicePrivate::DeviceInfoServicePrivate (QLowEnergyController * controller, DeviceInfoService *const q) explicit
Constructs a new DeviceInfoServicePrivate object with public implementation q.
Definition at line 292 of file deviceinfoservice.cpp.
    : AbstractPokitServicePrivate(DeviceInfoService::serviceUuid, controller, q)
{
}
Member Function Documentation
characteristicRead()
void DeviceInfoServicePrivate::characteristicRead (const QLowEnergyCharacteristic & characteristic, const QByteArray & value) override protected virtual
Implements AbstractPokitServicePrivate::characteristicRead to parse value, then emit a specialised signal, for each supported characteristic.
Reimplemented from AbstractPokitServicePrivate.
Definition at line 303 of file deviceinfoservice.cpp.
{
    AbstractPokitServicePrivate::characteristicRead(characteristic, value);
    Q_Q(DeviceInfoService);
    if (characteristic.uuid() == DeviceInfoService::CharacteristicUuids::manufacturerName) {
        const QString name = QString::fromUtf8(value);
        qCDebug(lc).noquote() << tr("Manufacturer name: \"%1\"").arg(name);
        emit q->manufacturerRead(name);
        return;
    }
    if (characteristic.uuid() == DeviceInfoService::CharacteristicUuids::modelNumber) {
        const QString model = QString::fromUtf8(value);
        qCDebug(lc).noquote() << tr("Model number: \"%1\"").arg(model);
        emit q->modelNumberRead(model);
        return;
    }
    if (characteristic.uuid() == DeviceInfoService::CharacteristicUuids::hardwareRevision) {
        const QString revision = QString::fromUtf8(value);
        qCDebug(lc).noquote() << tr("Hardware revision: \"%1\"").arg(revision);
        emit q->hardwareRevisionRead(revision);
        return;
    }
    if (characteristic.uuid() == DeviceInfoService::CharacteristicUuids::firmwareRevision) {
        const QString revision = QString::fromUtf8(value);
        qCDebug(lc).noquote() << tr("Firmware revision: \"%1\"").arg(revision);
        emit q->firmwareRevisionRead(revision);
        return;
    }
    if (characteristic.uuid() == DeviceInfoService::CharacteristicUuids::softwareRevision) {
        const QString revision = QString::fromUtf8(value);
        qCDebug(lc).noquote() << tr("Software revision: \"%1\"").arg(revision);
        emit q->softwareRevisionRead(revision);
        return;
    }
    qCWarning(lc).noquote() << tr("Unknown characteristic read for Device Info service")
        << serviceUuid << characteristic.name() << characteristic.uuid();
}
References QString::arg(), AbstractPokitServicePrivate::characteristicRead(), DeviceInfoService::CharacteristicUuids::firmwareRevision, QString::fromUtf8(), DeviceInfoService::CharacteristicUuids::hardwareRevision, DeviceInfoService::CharacteristicUuids::manufacturerName, DeviceInfoService::CharacteristicUuids::modelNumber, QLowEnergyCharacteristic::name(), AbstractPokitServicePrivate::serviceUuid, DeviceInfoService::CharacteristicUuids::softwareRevision, QObject::tr(), and QLowEnergyCharacteristic::uuid().
Friends And Related Function Documentation
TestDeviceInfoService
friend class TestDeviceInfoService friend
Definition at line 32 of file deviceinfoservice_p.h.
The documentation for this class was generated from the following files:
deviceinfoservice_p.h
deviceinfoservice.cpp