QtPokit: LoggerStartCommand Class Reference
LoggerStartCommand Class Reference
The LoggerStartCommand class implements the logger CLI command.
Public Slots
QStringList processOptions (const QCommandLineParser &parser) override
Processes the relevant options from the command line parser.
Public Slots inherited from DeviceCommand
bool start () override
Begins scanning for the Pokit device.
Public Slots inherited from AbstractCommand
virtual QStringList processOptions (const QCommandLineParser &parser)
Processes the relevant options from the command line parser.
virtual bool start ()=0
Begins the functionality of this command, and returns true if begun successfully, false otherwise.
Public Member Functions
LoggerStartCommand (QObject *const parent)
Construct a new LoggerStartCommand object with parent.
QStringList requiredOptions (const QCommandLineParser &parser) const override
Returns a list of CLI option names required by this command.
QStringList supportedOptions (const QCommandLineParser &parser) const override
Returns a list of CLI option names supported by this command.
Public Member Functions inherited from DeviceCommand
DeviceCommand (QObject *const parent)
Construct a new DeviceCommand object with parent.
Public Member Functions inherited from AbstractCommand
AbstractCommand (QObject *const parent)
Constructs a new command with parent.
virtual QStringList requiredOptions (const QCommandLineParser &parser) const
Returns a list of CLI option names required by this command.
virtual QStringList supportedOptions (const QCommandLineParser &parser) const
Returns a list of CLI option names supported by this command.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
virtual void * qt_metacast (const char *)
virtual int qt_metacall (QMetaObject::Call, int, void **)
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Protected Slots
void serviceDetailsDiscovered () override
Handles service detail discovery events.
Protected Slots inherited from DeviceCommand
virtual void controllerError (const QLowEnergyController::Error error)
Handles controller error events.
virtual void deviceDisconnected ()
Handles devics disconnection events.
virtual void serviceError (const QLowEnergyService::ServiceError error)
Handles service error events.
virtual void serviceDetailsDiscovered ()
Handles service detail discovery events.
Protected Slots inherited from AbstractCommand
virtual void deviceDiscovered (const QBluetoothDeviceInfo &info)=0
Handles PokitDiscoveryAgent::pokitDeviceDiscovered signal.
virtual void deviceDiscoveryFinished ()=0
Handles PokitDiscoveryAgent::deviceDiscoveryFinished signal.
Protected Member Functions
AbstractPokitService * getService () override
Returns a Pokit service object for the derived command class.
Protected Member Functions inherited from DeviceCommand
void disconnect (int exitCode=EXIT_SUCCESS)
Disconnects the underlying Pokit device, and sets exitCode to be return to the OS once the disconnection has taken place.
virtual AbstractPokitService * getService ()=0
Returns a Pokit service object for the derived command class.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Private Slots
void settingsWritten ()
Invoked when the data logger settings have been written.
Static Private Member Functions
static DataLoggerService::Range lowestRange (const DataLoggerService::Mode mode, const quint32 desiredMax)
Returns the lowest mode range that can measure at least up to desired max, or AutoRange if no such range is available.
static DataLoggerService::CurrentRange lowestCurrentRange (const quint32 desiredMax)
Returns the lowest current range that can measure at least up to desired max, or AutoRange if no such range is available.
static DataLoggerService::VoltageRange lowestVoltageRange (const quint32 desiredMax)
Returns the lowest voltage range that can measure at least up to desired max, or AutoRange if no such range is available.
Private Attributes
DataLoggerService * service
Bluetooth service this command interracts with.
DataLoggerService::Settings settings
Settings for the Pokit device's data logger mode.
Friends
class TestLoggerStartCommand
Additional Inherited Members
Public Types inherited from AbstractCommand
enum class OutputFormat { Csv , Json , Text }
Supported output formats.
Static Public Member Functions inherited from AbstractCommand
static QString escapeCsvField (const QString &field)
Returns an RFC 4180 compliant version of field.
static quint32 parseMicroValue (const QString &value, const QString &unit, const quint32 sensibleMinimum=0)
Returns value as a number of micros, such as microseconds, or microvolts.
static quint32 parseMilliValue (const QString &value, const QString &unit, const quint32 sensibleMinimum=0)
Returns value as a number of millis, such as milliseconds, or millivolts.
static quint32 parseWholeValue (const QString &value, const QString &unit)
Returns value as a number, with optional SI unit prefix, and optional unit suffix.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Static Protected Member Functions inherited from AbstractCommand
static Q_LOGGING_CATEGORY (lc, "pokit.ui.command", QtInfoMsg)
Logging category for UI commands.
Protected Attributes inherited from DeviceCommand
PokitDevice * device
Pokit Bluetooth device (if any) this command inerracts with.
int exitCodeOnDisconnect
Exit code to return on device disconnection.
Protected Attributes inherited from AbstractCommand
QString deviceToScanFor
Device (if any) that were passed to processOptions().
PokitDiscoveryAgent * discoveryAgent
Agent for Pokit device descovery.
OutputFormat format
Selected output format.
Properties inherited from QObject
objectName
Detailed Description
The LoggerStartCommand class implements the logger CLI command.
Definition at line 8 of file loggerstartcommand.h.
Constructor & Destructor Documentation
LoggerStartCommand()
LoggerStartCommand::LoggerStartCommand (QObject *const parent) explicit
Construct a new LoggerStartCommand object with parent.
Definition at line 23 of file loggerstartcommand.cpp.
                                                             : DeviceCommand(parent),
    service(nullptr), settings{
        DataLoggerService::Command::Start, 0, DataLoggerService::Mode::DcVoltage,
        DataLoggerService::VoltageRange::_30V_to_60V, 60000, 0}
{
}
Member Function Documentation
getService()
AbstractPokitService * LoggerStartCommand::getService () override protected virtual
Returns a Pokit service object for the derived command class.
This override returns a pointer to a DataLoggerService object.
Implements DeviceCommand.
Definition at line 135 of file loggerstartcommand.cpp.
{
    Q_ASSERT(device);
    if (!service) {
        service = device->dataLogger();
        Q_ASSERT(service);
        connect(service, &DataLoggerService::settingsWritten,
                this, &LoggerStartCommand::settingsWritten);
    }
    return service;
}
References QObject::connect(), PokitDevice::dataLogger(), DeviceCommand::device, service, DataLoggerService::settingsWritten(), and settingsWritten().
lowestCurrentRange()
DataLoggerService::CurrentRange LoggerStartCommand::lowestCurrentRange (const quint32 desiredMax) static private
Returns the lowest current range that can measure at least up to desired max, or AutoRange if no such range is available.
Definition at line 196 of file loggerstartcommand.cpp.
{
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, CurrentRange::_0_to_10mA)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, CurrentRange::_10mA_to_30mA)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, CurrentRange::_30mA_to_150mA)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, CurrentRange::_150mA_to_300mA)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, CurrentRange::_300mA_to_3A)
    return DataLoggerService::CurrentRange::_300mA_to_3A; // Out of range, so go with the biggest.
}
References DataLoggerService::_300mA_to_3A.
Referenced by lowestRange().
lowestRange()
DataLoggerService::Range LoggerStartCommand::lowestRange (const DataLoggerService::Mode mode, const quint32 desiredMax) static private
Returns the lowest mode range that can measure at least up to desired max, or AutoRange if no such range is available.
Definition at line 166 of file loggerstartcommand.cpp.
{
    switch (mode) {
    case DataLoggerService::Mode::Idle:
        qCWarning(lc).noquote() << tr("Idle has no defined ranges.");
        Q_ASSERT(false); // Should never have been called with this Idle mode.
        break;
    case DataLoggerService::Mode::DcVoltage:
    case DataLoggerService::Mode::AcVoltage:
        return lowestVoltageRange(desiredMax);
    case DataLoggerService::Mode::DcCurrent:
    case DataLoggerService::Mode::AcCurrent:
        return lowestCurrentRange(desiredMax);
    default:
        qCWarning(lc).noquote() << tr("No defined ranges for mode %1.").arg((quint8)mode);
        Q_ASSERT(false); // Should never have been called with this invalid mode.
    }
    return DataLoggerService::Range();
}
References DataLoggerService::AcCurrent, DataLoggerService::AcVoltage, QString::arg(), DataLoggerService::DcCurrent, DataLoggerService::DcVoltage, DataLoggerService::Idle, lowestCurrentRange(), lowestVoltageRange(), and QObject::tr().
Referenced by processOptions().
lowestVoltageRange()
DataLoggerService::VoltageRange LoggerStartCommand::lowestVoltageRange (const quint32 desiredMax) static private
Returns the lowest voltage range that can measure at least up to desired max, or AutoRange if no such range is available.
Definition at line 210 of file loggerstartcommand.cpp.
{
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_0_to_300mV)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_300mV_to_2V)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_2V_to_6V)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_6V_to_12V)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_12V_to_30V)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_30V_to_60V)
    return DataLoggerService::VoltageRange::_30V_to_60V; // Out of range, so go with the biggest.
}
References DataLoggerService::_30V_to_60V.
Referenced by lowestRange().
processOptions
QStringList LoggerStartCommand::processOptions (const QCommandLineParser & parser) override slot
Processes the relevant options from the command line parser.
This implementation extends DeviceCommand::processOptions to process additional CLI options supported (or required) by this command.
Definition at line 53 of file loggerstartcommand.cpp.
{
    QStringList errors = DeviceCommand::processOptions(parser);
    if (!errors.isEmpty()) {
        return errors;
    }
    // Parse the (required) mode option.
    const QString mode = parser.value(QLatin1String("mode")).trimmed().toLower();
    if (mode.startsWith(QLatin1String("ac v")) || mode.startsWith(QLatin1String("vac"))) {
        settings.mode = DataLoggerService::Mode::AcVoltage;
    } else if (mode.startsWith(QLatin1String("dc v")) || mode.startsWith(QLatin1String("vdc"))) {
        settings.mode = DataLoggerService::Mode::DcVoltage;
    } else if (mode.startsWith(QLatin1String("ac c")) || mode.startsWith(QLatin1String("aac"))) {
        settings.mode = DataLoggerService::Mode::AcCurrent;
    } else if (mode.startsWith(QLatin1String("dc c")) || mode.startsWith(QLatin1String("adc"))) {
        settings.mode = DataLoggerService::Mode::DcCurrent;
    } else {
        errors.append(tr("Unknown logger mode: %1").arg(parser.value(QLatin1String("mode"))));
        return errors;
    }
    // Parse the (required) range option.
    {
        const QString value = parser.value(QLatin1String("range"));
        QString unit; quint32 sensibleMinimum = 0;
        switch (settings.mode) {
        case DataLoggerService::Mode::Idle:
            Q_ASSERT(false); // Not possible, since the mode parsing above never allows Idle.
            break;
        case DataLoggerService::Mode::DcVoltage:
        case DataLoggerService::Mode::AcVoltage:
            unit = QLatin1String("V");
            sensibleMinimum = 50; // mV.
            break;
        case DataLoggerService::Mode::DcCurrent:
        case DataLoggerService::Mode::AcCurrent:
            unit = QLatin1String("A");
            sensibleMinimum = 5; // mA.
            break;
        }
        Q_ASSERT(!unit.isEmpty());
        const quint32 rangeMax = parseMilliValue(value, unit, sensibleMinimum);
        if (rangeMax == 0) {
            errors.append(tr("Invalid range value: %1").arg(value));
        } else {
            settings.range = lowestRange(settings.mode, rangeMax);
        }
    }
    // Parse the interval option.
    if (parser.isSet(QLatin1String("interval"))) {
        const QString value = parser.value(QLatin1String("interval"));
        const quint32 interval = parseMilliValue(value, QLatin1String("s"), 500);
        if (interval == 0) {
            errors.append(tr("Invalid interval value: %1").arg(value));
        } else {
            settings.updateInterval = interval;
        }
    }
    // Parse the timestamp option.
    settings.timestamp = QDateTime::currentSecsSinceEpoch(); // Note, subject to Y2038 epochalypse.
    if (parser.isSet(QLatin1String("timestamp"))) {
        const QString value = parser.value(QLatin1String("timestamp"));
        QLocale locale; bool ok;
        static_assert(sizeof(uint) == sizeof(settings.timestamp), "QLocale has no toUint32().");
        const int timestamp = locale.toUInt(value, &ok);
        if (!ok) {
            errors.append(tr("Invalid timestamp value: %1").arg(value));
        } else {
            settings.timestamp = timestamp;
        }
    }
    return errors;
}
References DataLoggerService::AcCurrent, DataLoggerService::AcVoltage, QList::append(), QString::arg(), QDateTime::currentSecsSinceEpoch(), DataLoggerService::DcCurrent, DataLoggerService::DcVoltage, DataLoggerService::Idle, QString::isEmpty(), QList::isEmpty(), QCommandLineParser::isSet(), lowestRange(), DataLoggerService::Settings::mode, AbstractCommand::parseMilliValue(), AbstractCommand::processOptions(), DataLoggerService::Settings::range, settings, QString::startsWith(), DataLoggerService::Settings::timestamp, QString::toLower(), QLocale::toUInt(), QObject::tr(), QString::trimmed(), DataLoggerService::Settings::updateInterval, and QCommandLineParser::value().
requiredOptions()
QStringList LoggerStartCommand::requiredOptions (const QCommandLineParser & parser) const override virtual
Returns a list of CLI option names required by this command.
The main console appication may use this list to output an eror (and exit) if any of the returned names are not found in the parsed CLI options.
The (already parsed) parser may be used adjust the returned required options depending on the value of other options. For example, the logger command only requires the --mode option if the --command option is start.
This base implementation simply returns an empty list. Derived classes should override this function to include any required options.
Reimplemented from AbstractCommand.
Definition at line 31 of file loggerstartcommand.cpp.
{
    return DeviceCommand::requiredOptions(parser) + QStringList{
        QLatin1String("mode"),
        QLatin1String("range"),
    };
}
References AbstractCommand::requiredOptions().
serviceDetailsDiscovered
void LoggerStartCommand::serviceDetailsDiscovered () override protected slot
Handles service detail discovery events.
This override fetches the current device's status, and outputs it in the selected format.
Definition at line 152 of file loggerstartcommand.cpp.
{
    DeviceCommand::serviceDetailsDiscovered(); // Just logs consistently.
    const QString range = DataLoggerService::toString(settings.range, settings.mode);
    qCInfo(lc).noquote() << tr("Logging %1, with range %2, every %L3ms.").arg(
        DataLoggerService::toString(settings.mode),
        (range.isNull()) ? QString::fromLatin1("N/A") : range).arg(settings.updateInterval);
    service->setSettings(settings);
}
References QString::arg(), QString::fromLatin1(), QString::isNull(), DataLoggerService::Settings::mode, DataLoggerService::Settings::range, service, DeviceCommand::serviceDetailsDiscovered(), DataLoggerService::setSettings(), settings, DataLoggerService::toString(), QObject::tr(), and DataLoggerService::Settings::updateInterval.
settingsWritten
void LoggerStartCommand::settingsWritten () private slot
Invoked when the data logger settings have been written.
Definition at line 226 of file loggerstartcommand.cpp.
{
    qCDebug(lc).noquote() << tr("Settings written; data logger has started.");
    switch (format) {
    case OutputFormat::Csv:
        std::cout << qUtf8Printable(tr("logger_start_result\nsuccess\n"));
        break;
    case OutputFormat::Json:
        std::cout << qUtf8Printable(QLatin1String("true\n"));
        break;
    case OutputFormat::Text:
        std::cout << qUtf8Printable(tr("Done.\n"));
        break;
    }
    if (device) disconnect(); // Will exit the application once disconnected.
}
References AbstractCommand::Csv, DeviceCommand::device, DeviceCommand::disconnect(), AbstractCommand::format, AbstractCommand::Json, AbstractCommand::Text, and QObject::tr().
Referenced by getService().
supportedOptions()
QStringList LoggerStartCommand::supportedOptions (const QCommandLineParser & parser) const override virtual
Returns a list of CLI option names supported by this command.
The main console appication may use this list to output a warning for any parsed CLI options not included in the returned list.
The (already parsed) parser may be used adjust the returned supported options depending on the value of other options. For example, the logger command only supported the --timestamp option if the --command option is start.
This base implementation simply returns requiredOptions(). Derived classes should override this function to include optional options, such as:
QStringList Derived::supportedOptions(const QCommandLineParser &parser) const
{
    const QStringList list = AbstractCommand::supportedOptions(parser) + QStringList{ ... };
    list.sort();
    list.removeDuplicates(); // Optional, recommended.
    return list;
}
Reimplemented from AbstractCommand.
Definition at line 39 of file loggerstartcommand.cpp.
{
    return DeviceCommand::supportedOptions(parser) + QStringList{
        QLatin1String("interval"),
        QLatin1String("timestamp"),
    };
}
References AbstractCommand::supportedOptions().
Friends And Related Function Documentation
TestLoggerStartCommand
friend class TestLoggerStartCommand friend
Definition at line 37 of file loggerstartcommand.h.
Member Data Documentation
service
DataLoggerService* LoggerStartCommand::service private
Bluetooth service this command interracts with.
Definition at line 26 of file loggerstartcommand.h.
Referenced by getService(), and serviceDetailsDiscovered().
settings
DataLoggerService::Settings LoggerStartCommand::settings private
Settings for the Pokit device's data logger mode.
Definition at line 27 of file loggerstartcommand.h.
Referenced by processOptions(), and serviceDetailsDiscovered().
The documentation for this class was generated from the following files:
loggerstartcommand.h
loggerstartcommand.cpp