Dokit: StatusCommand Class Reference
StatusCommand Class Reference
The StatusCommand class implements the status CLI command.
Public Slots
QStringList processOptions (const QCommandLineParser &parser) override
Processes the relevant options from the command line parser.
Public Slots inherited from DeviceCommand
bool start () override
Begins scanning for the Pokit device.
Public Slots inherited from AbstractCommand
virtual QStringList processOptions (const QCommandLineParser &parser)
Processes the relevant options from the command line parser.
virtual bool start ()=0
Begins the functionality of this command, and returns true if begun successfully, false otherwise.
Public Member Functions
StatusCommand (QObject *const parent=nullptr)
Construct a new StatusCommand object with parent.
QStringList requiredOptions (const QCommandLineParser &parser) const override
Returns a list of CLI option names required by this command.
QStringList supportedOptions (const QCommandLineParser &parser) const override
Returns a list of CLI option names supported by this command.
Public Member Functions inherited from DeviceCommand
DeviceCommand (QObject *const parent=nullptr)
Construct a new DeviceCommand object with parent.
Public Member Functions inherited from AbstractCommand
AbstractCommand (QObject *const parent=nullptr)
Constructs a new command with parent.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Protected Slots
void serviceDetailsDiscovered () override
Handles service detail discovery events.
Protected Slots inherited from DeviceCommand
virtual void controllerError (const QLowEnergyController::Error error)
Handles controller error events.
virtual void deviceDisconnected ()
Handles device disconnection events.
virtual void serviceError (const QLowEnergyService::ServiceError error)
Handles service error events.
virtual void serviceDetailsDiscovered ()
Handles service detail discovery events.
Protected Slots inherited from AbstractCommand
virtual void deviceDiscovered (const QBluetoothDeviceInfo &info)=0
Handles PokitDiscoveryAgent::pokitDeviceDiscovered signal.
virtual void deviceDiscoveryFinished ()=0
Handles PokitDiscoveryAgent::deviceDiscoveryFinished signal.
Protected Member Functions
AbstractPokitService * getService () override
Returns a Pokit service object for the derived command class.
Protected Member Functions inherited from DeviceCommand
void disconnect (int exitCode=EXIT_SUCCESS)
Disconnects the underlying Pokit device, and sets exitCode to be return to the OS once the disconnection has taken place.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Private Member Functions
void outputDeviceStatus (const StatusService::DeviceCharacteristics &chrs)
Outputs the Pokit device's details, including chrs, in the selected format.
Private Attributes
StatusService * service { nullptr }
Bluetooth service this command interacts with.
Additional Inherited Members
Public Types inherited from AbstractCommand
enum class OutputFormat { Csv , Json , Text }
Supported output formats.
Static Public Member Functions inherited from AbstractCommand
static QString escapeCsvField (const QString &field)
Returns an RFC 4180 compliant version of field.
template<typename R>
static quint32 parseNumber (const QString &value, const QString &unit, const quint32 sensibleMinimum=0)
Returns value as an integer multiple of the ratio R.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Static Protected Member Functions inherited from DeviceCommand
template<typename T>
static T minRange (const quint32 maxValue)
static quint8 minCapacitanceRange (const PokitProduct product, const quint32 maxValue)
Returns the product's lowest capacitance range that can measure at least up to maxValue (nF), or AutoRange if no such range is available.
static quint8 minCurrentRange (const PokitProduct product, const quint32 maxValue)
Returns the product's lowest current range that can measure at least up to maxValue (A), or AutoRange if no such range is available.
static quint8 minResistanceRange (const PokitProduct product, const quint32 maxValue)
Returns the product's lowest resistance range that can measure at least up to maxValue (), or AutoRange if no such range is available.
static quint8 minVoltageRange (const PokitProduct product, const quint32 maxValue)
t Returns the product's lowest voltage range that can measure at least up to maxValue (mV), or AutoRange if no such range is available.
Static Protected Member Functions inherited from AbstractCommand
static Q_LOGGING_CATEGORY (lc, "dokit.cli.command", QtInfoMsg)
Logging category for UI commands.
Protected Attributes inherited from DeviceCommand
PokitDevice * device { nullptr }
Pokit Bluetooth device (if any) this command interacts with.
int exitCodeOnDisconnect { EXIT_FAILURE }
Exit code to return on device disconnection.
Protected Attributes inherited from AbstractCommand
QString deviceToScanFor
Device (if any) that were passed to processOptions().
PokitDiscoveryAgent * discoveryAgent
Agent for Pokit device discovery.
OutputFormat format { OutputFormat::Text }
Selected output format.
Properties inherited from QObject
objectName
Detailed Description
The StatusCommand class implements the status CLI command.
Definition at line 8 of file statuscommand.h.
Constructor & Destructor Documentation
StatusCommand()
StatusCommand::StatusCommand (QObject *const parent = nullptr) explicit
Construct a new StatusCommand object with parent.
Definition at line 25 of file statuscommand.cpp.
                                                   : DeviceCommand(parent)
{
}
References DeviceCommand::DeviceCommand(), QObject::parent(), and QObject::QObject().
Member Function Documentation
getService()
AbstractPokitService * StatusCommand::getService () override protected virtual
Returns a Pokit service object for the derived command class.
This override returns a pointer to a StatusService object.
Implements DeviceCommand.
Definition at line 62 of file statuscommand.cpp.
{
    Q_ASSERT(device);
    if (!service) {
        service = device->status();
        Q_ASSERT(service);
    }
    return service;
}
References DeviceCommand::device, and service.
outputDeviceStatus()
void StatusCommand::outputDeviceStatus (const StatusService::DeviceCharacteristics & chrs) private
Outputs the Pokit device's details, including chrs, in the selected format.
Definition at line 92 of file statuscommand.cpp.
{
    const QString deviceName = service->deviceName();
    const StatusService::Status status = service->status();
    const std::optional<StatusService::TorchStatus> torchStatus = service->torchStatus();
    const std::optional<StatusService::ButtonStatus> buttonStatus = service->buttonPress();
    const QString statusLabel = StatusService::toString(status.deviceStatus);
    const QString batteryLabel = StatusService::toString(status.batteryStatus);
    const QString switchLabel = status.switchPosition ? StatusService::toString(*status.switchPosition) : QString();
    const QString chargingLabel = status.chargingStatus ? StatusService::toString(*status.chargingStatus) : QString();
    const QString torchLabel = (torchStatus) ? StatusService::toString(*torchStatus) : QString();
    const QString buttonLabel = (buttonStatus) ? StatusService::toString(*buttonStatus) : QString();
    switch (format) {
    case OutputFormat::Csv:
        std::cout << qUtf8Printable(tr("device_name,device_status,firmware_version,maximum_voltage,"
                            "maximum_current,maximum_resistance,maximum_sampling_rate,"
                            "sampling_buffer_size,capability_mask,mac_address,battery_voltage,"
                            "battery_status,torch_status,button_status,switch_position,charging_status\n"));
        std::cout << qUtf8Printable(QString::fromLatin1("%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15,%16\n")
            .arg(escapeCsvField(deviceName),statusLabel.toLower(),chrs.firmwareVersion.toString())
            .arg(chrs.maximumVoltage).arg(chrs.maximumCurrent).arg(chrs.maximumResistance)
            .arg(chrs.maximumSamplingRate).arg(chrs.samplingBufferSize).arg(chrs.capabilityMask)
            .arg(chrs.macAddress.toString()).arg(status.batteryVoltage)
            .arg(batteryLabel.toLower(), torchLabel.toLower(), buttonLabel.toLower(), switchLabel.toLower(),
                 chargingLabel.toLower()));
        break;
    case OutputFormat::Json: {
        QJsonObject battery{
            { u"level"_s,  status.batteryVoltage },
        };
        if (!batteryLabel.isNull()) {
            battery.insert(u"status"_s, batteryLabel);
        }
        QJsonObject object{
                { u"deviceName"_s,   deviceName },
                { u"firmwareVersion"_s, QJsonObject{
                      { u"major"_s, chrs.firmwareVersion.majorVersion() },
                      { u"minor"_s, chrs.firmwareVersion.minorVersion() },
                }},
                { u"maximumVoltage"_s,      chrs.maximumVoltage },
                { u"maximumCurrent"_s,      chrs.maximumCurrent },
                { u"maximumResistance"_s,   chrs.maximumResistance },
                { u"maximumSamplingRate"_s, chrs.maximumSamplingRate },
                { u"samplingBufferSize"_s,  chrs.samplingBufferSize },
                { u"capabilityMask"_s,      chrs.capabilityMask },
                { u"macAddress"_s,          chrs.macAddress.toString() },
                { u"deviceStatus"_s, QJsonObject{
                      { u"code"_s, (quint8)status.deviceStatus },
                      { u"label"_s, statusLabel },
                }},
                { u"battery"_s, battery },
            };
        if (torchStatus) {
            object.insert(u"torchStatus"_s, QJsonObject{
                { u"code"_s, (quint8)*torchStatus },
                { u"label"_s, torchLabel },
            });
        }
        if (buttonStatus) {
            object.insert(u"buttonStatus"_s, QJsonObject{
                { u"code"_s, (quint8)*buttonStatus },
                { u"label"_s, buttonLabel },
            });
        }
        if (status.switchPosition) {
            object.insert(u"switchStatus"_s, QJsonObject{
                { u"code"_s, (quint8)*status.switchPosition },
                { u"label"_s, switchLabel },
            });
        }
        if (status.chargingStatus) {
            object.insert(u"chargingStatus"_s, QJsonObject{
                { u"code"_s, (quint8)*status.chargingStatus },
                { u"label"_s, chargingLabel },
            });
        }
        std::cout << QJsonDocument(object).toJson().toStdString();
    }   break;
    case OutputFormat::Text:
        std::cout << qUtf8Printable(tr("Device name:           %1\n").arg(deviceName));
        std::cout << qUtf8Printable(tr("Firmware version:      %1\n").arg(chrs.firmwareVersion.toString()));
        std::cout << qUtf8Printable(tr("Maximum voltage:       %1\n").arg(chrs.maximumVoltage));
        std::cout << qUtf8Printable(tr("Maximum current:       %1\n").arg(chrs.maximumCurrent));
        std::cout << qUtf8Printable(tr("Maximum resistance:    %1\n").arg(chrs.maximumResistance));
        std::cout << qUtf8Printable(tr("Maximum sampling rate: %1\n").arg(chrs.maximumSamplingRate));
        std::cout << qUtf8Printable(tr("Sampling buffer size:  %1\n").arg(chrs.samplingBufferSize));
        std::cout << qUtf8Printable(tr("Capability mask:       %1\n").arg(chrs.capabilityMask));
        std::cout << qUtf8Printable(tr("MAC address:           %1\n").arg(chrs.macAddress.toString()));
        std::cout << qUtf8Printable(tr("Device status:         %1 (%2)\n").arg(statusLabel)
            .arg((quint8)status.deviceStatus));
        std::cout << qUtf8Printable(tr("Battery voltage:       %1\n").arg(status.batteryVoltage));
        std::cout << qUtf8Printable(tr("Battery status:        %1 (%2)\n")
            .arg(batteryLabel.isNull() ? QString::fromLatin1("N/A") : batteryLabel)
            .arg((quint8)status.batteryStatus));
        if (status.switchPosition) {
            std::cout << qUtf8Printable(tr("Switch position:       %1 (%2)\n")
                .arg(switchLabel).arg((quint8)*status.switchPosition));
        }
        if (status.chargingStatus) {
            std::cout << qUtf8Printable(tr("Charging status:       %1 (%2)\n")
                .arg(chargingLabel).arg((quint8)*status.chargingStatus));
        }
        break;
    }
    if (device) disconnect(); // Will exit the application once disconnected.
}
References QString::arg(), StatusService::Status::batteryStatus, StatusService::Status::batteryVoltage, StatusService::DeviceCharacteristics::capabilityMask, StatusService::Status::chargingStatus, AbstractCommand::Csv, DeviceCommand::device, StatusService::Status::deviceStatus, DeviceCommand::disconnect(), AbstractCommand::escapeCsvField(), StatusService::DeviceCharacteristics::firmwareVersion, AbstractCommand::format, QString::fromLatin1(), QJsonObject::insert(), QString::isNull(), AbstractCommand::Json, StatusService::DeviceCharacteristics::macAddress, QVersionNumber::majorVersion(), StatusService::DeviceCharacteristics::maximumCurrent, StatusService::DeviceCharacteristics::maximumResistance, StatusService::DeviceCharacteristics::maximumSamplingRate, StatusService::DeviceCharacteristics::maximumVoltage, QVersionNumber::minorVersion(), StatusService::DeviceCharacteristics::samplingBufferSize, service, StatusService::Status::switchPosition, AbstractCommand::Text, QJsonDocument::toJson(), QString::toLower(), QByteArray::toStdString(), QBluetoothAddress::toString(), QVersionNumber::toString(), StatusService::toString(), and QObject::tr().
Referenced by serviceDetailsDiscovered().
processOptions
QStringList StatusCommand::processOptions (const QCommandLineParser & parser) override slot
Processes the relevant options from the command line parser.
This implementation extends DeviceCommand::processOptions to process additional CLI options supported (or required) by this command.
Definition at line 47 of file statuscommand.cpp.
{
    QStringList errors = DeviceCommand::processOptions(parser);
    if (!errors.isEmpty()) {
        return errors;
    }
    return errors;
}
References QList::isEmpty(), and AbstractCommand::processOptions().
requiredOptions()
QStringList StatusCommand::requiredOptions (const QCommandLineParser & parser) const override virtual
Returns a list of CLI option names required by this command.
The main console appication may use this list to output an error (and exit) if any of the returned names are not found in the parsed CLI options.
The (already parsed) parser may be used adjust the returned required options depending on the value of other options. For example, the logger command only requires the --mode option if the --command option is start.
This base implementation simply returns an empty list. Derived classes should override this function to include any required options.
Reimplemented from AbstractCommand.
Definition at line 30 of file statuscommand.cpp.
{
    return DeviceCommand::requiredOptions(parser) + QStringList{
    };
}
References AbstractCommand::requiredOptions().
serviceDetailsDiscovered
void StatusCommand::serviceDetailsDiscovered () override protected slot
Handles service detail discovery events.
This override fetches the current device's status, and outputs it in the selected format.
Definition at line 77 of file statuscommand.cpp.
{
    DeviceCommand::serviceDetailsDiscovered(); // Just logs consistently.
    const StatusService::DeviceCharacteristics chrs = service->deviceCharacteristics();
    if (chrs.firmwareVersion.isNull()) {
        qCWarning(lc).noquote() << tr("Failed to parse device information");
        QCoreApplication::exit(EXIT_FAILURE);
        return;
    }
    outputDeviceStatus(chrs);
}
References QCoreApplication::exit(), StatusService::DeviceCharacteristics::firmwareVersion, QVersionNumber::isNull(), outputDeviceStatus(), service, DeviceCommand::serviceDetailsDiscovered(), and QObject::tr().
supportedOptions()
QStringList StatusCommand::supportedOptions (const QCommandLineParser & parser) const override virtual
Returns a list of CLI option names supported by this command.
The main console appication may use this list to output a warning for any parsed CLI options not included in the returned list.
The (already parsed) parser may be used adjust the returned supported options depending on the value of other options. For example, the logger command only supported the --timestamp option if the --command option is start.
This base implementation simply returns requiredOptions(). Derived classes should override this function to include optional options, such as:
QStringList Derived::supportedOptions(const QCommandLineParser &parser) const
{
    const QStringList list = AbstractCommand::supportedOptions(parser) + QStringList{ ... };
    list.sort();
    list.removeDuplicates(); // Optional, recommended.
    return list;
}
Reimplemented from AbstractCommand.
Definition at line 36 of file statuscommand.cpp.
{
    return DeviceCommand::supportedOptions(parser);
}
References AbstractCommand::supportedOptions().
Member Data Documentation
service
StatusService* StatusCommand::service { nullptr } private
Bluetooth service this command interacts with.
Definition at line 28 of file statuscommand.h.
{ nullptr }; ///< Bluetooth service this command interacts with.
Referenced by getService(), outputDeviceStatus(), and serviceDetailsDiscovered().
The documentation for this class was generated from the following files:
statuscommand.h
statuscommand.cpp