Dokit: MultimeterServicePrivate Class Reference
MultimeterServicePrivate Class Reference
The MultimeterServicePrivate class provides private implementation for MultimeterService.
Public Member Functions
MultimeterServicePrivate (QLowEnergyController *controller, MultimeterService *const q)
Public Member Functions inherited from AbstractPokitServicePrivate
AbstractPokitServicePrivate (const QBluetoothUuid &serviceUuid, QLowEnergyController *controller, AbstractPokitService *const q)
bool createServiceObject ()
Creates an internal service object from the internal controller.
QLowEnergyCharacteristic getCharacteristic (const QBluetoothUuid &uuid) const
Get uuid characteristc from the underlying service.
bool readCharacteristic (const QBluetoothUuid &uuid)
Read the uuid characteristic.
bool enableCharacteristicNotificatons (const QBluetoothUuid &uuid)
Enables client (Pokit device) side notification for characteristic uuid.
bool disableCharacteristicNotificatons (const QBluetoothUuid &uuid)
Disables client (Pokit device) side notification for characteristic uuid.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Member Functions
static QByteArray encodeSettings (const MultimeterService::Settings &settings)
Returns settings in the format Pokit devices expect.
static MultimeterService::Reading parseReading (const QByteArray &value)
Parses the Reading value into a MultimeterService::Reading struct.
Static Public Member Functions inherited from AbstractPokitServicePrivate
static Q_LOGGING_CATEGORY (lc, "pokit.ble.service", QtInfoMsg)
Logging category.
static bool checkSize (const QString &label, const QByteArray &data, const int minSize, const int maxSize=-1, const bool failOnMax=false)
Returns false if data is smaller than minSize, otherwise returns failOnMax if data is bigger than maxSize, otherwise returns true.
static QString toHexString (const QByteArray &data, const int maxSize=20)
Returns up to maxSize bytes of data as a human readable hexadecimal string.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Protected Member Functions
void characteristicRead (const QLowEnergyCharacteristic &characteristic, const QByteArray &value) override
Implements AbstractPokitServicePrivate::characteristicRead to parse value, then emit a specialised signal, for each supported characteristic.
void characteristicWritten (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue) override
Implements AbstractPokitServicePrivate::characteristicWritten to parse newValue, then emit a specialised signal, for each supported characteristic.
void characteristicChanged (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue) override
Implements AbstractPokitServicePrivate::characteristicChanged to parse newValue, then emit a specialised signal, for each supported characteristic.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Friends
class TestMultimeterService
Additional Inherited Members
Public Attributes inherited from AbstractPokitServicePrivate
bool autoDiscover { true }
Whether autodiscovery is enabled or not.
QLowEnergyController * controller { nullptr }
PokitProduct pokitProduct { static_cast<PokitProduct>(255) }
The Pokit product controller is connected to.
QLowEnergyService * service { nullptr }
BLE service to read/write characteristics.
QBluetoothUuid serviceUuid
UUIDs for service.
Public Attributes inherited from QObject
typedef QObjectList
Protected Slots inherited from AbstractPokitServicePrivate
void connected ()
Handles QLowEnergyController::connected events.
void discoveryFinished ()
Handles QLowEnergyController::discoveryFinished events.
void errorOccurred (const QLowEnergyService::ServiceError newError)
Handles QLowEnergyController::errorOccurred events.
virtual void serviceDiscovered (const QBluetoothUuid &newService)
Handles QLowEnergyController::serviceDiscovered events.
void stateChanged (QLowEnergyService::ServiceState newState)
Handles QLowEnergyController::stateChanged events.
virtual void characteristicRead (const QLowEnergyCharacteristic &characteristic, const QByteArray &value)
Handles QLowEnergyService::characteristicRead events.
virtual void characteristicWritten (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue)
Handles QLowEnergyService::characteristicWritten events.
virtual void characteristicChanged (const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue)
Handles QLowEnergyService::characteristicChanged events.
Protected Attributes inherited from AbstractPokitServicePrivate
AbstractPokitService * q_ptr
Internal q-pointer.
Properties inherited from QObject
objectName
Detailed Description
The MultimeterServicePrivate class provides private implementation for MultimeterService.
Definition at line 18 of file multimeterservice_p.h.
Constructor & Destructor Documentation
MultimeterServicePrivate()
MultimeterServicePrivate::MultimeterServicePrivate (QLowEnergyController * controller, MultimeterService *const q) explicit
Constructs a new MultimeterServicePrivate object with public implementation q.
Definition at line 305 of file multimeterservice.cpp.
    : AbstractPokitServicePrivate(MultimeterService::serviceUuid, controller, q)
{
}
Member Function Documentation
characteristicChanged()
void MultimeterServicePrivate::characteristicChanged (const QLowEnergyCharacteristic & characteristic, const QByteArray & newValue) override protected virtual
Implements AbstractPokitServicePrivate::characteristicChanged to parse newValue, then emit a specialised signal, for each supported characteristic.
Reimplemented from AbstractPokitServicePrivate.
Definition at line 407 of file multimeterservice.cpp.
{
    AbstractPokitServicePrivate::characteristicChanged(characteristic, newValue);
    Q_Q(MultimeterService);
    if (characteristic.uuid() == MultimeterService::CharacteristicUuids::settings) {
        qCWarning(lc).noquote() << tr("Settings characteristic is write-only, but somehow updated")
            << serviceUuid << characteristic.name() << characteristic.uuid();
        return;
    }
    if (characteristic.uuid() == MultimeterService::CharacteristicUuids::reading) {
        emit q->readingRead(parseReading(newValue));
        return;
    }
    qCWarning(lc).noquote() << tr("Unknown characteristic notified for Multimeter service")
        << serviceUuid << characteristic.name() << characteristic.uuid();
}
References AbstractPokitServicePrivate::characteristicChanged(), QLowEnergyCharacteristic::name(), parseReading(), MultimeterService::CharacteristicUuids::reading, AbstractPokitServicePrivate::serviceUuid, MultimeterService::CharacteristicUuids::settings, QObject::tr(), and QLowEnergyCharacteristic::uuid().
characteristicRead()
void MultimeterServicePrivate::characteristicRead (const QLowEnergyCharacteristic & characteristic, const QByteArray & value) override protected virtual
Implements AbstractPokitServicePrivate::characteristicRead to parse value, then emit a specialised signal, for each supported characteristic.
Reimplemented from AbstractPokitServicePrivate.
Definition at line 357 of file multimeterservice.cpp.
{
    AbstractPokitServicePrivate::characteristicRead(characteristic, value);
    Q_Q(MultimeterService);
    if (characteristic.uuid() == MultimeterService::CharacteristicUuids::reading) {
        emit q->readingRead(parseReading(value));
        return;
    }
    if (characteristic.uuid() == MultimeterService::CharacteristicUuids::settings) {
        qCWarning(lc).noquote() << tr("Settings characteristic is write-only, but somehow read")
            << serviceUuid << characteristic.name() << characteristic.uuid();
        return;
    }
    qCWarning(lc).noquote() << tr("Unknown characteristic read for Multimeter service")
        << serviceUuid << characteristic.name() << characteristic.uuid();
}
References AbstractPokitServicePrivate::characteristicRead(), QLowEnergyCharacteristic::name(), parseReading(), MultimeterService::CharacteristicUuids::reading, AbstractPokitServicePrivate::serviceUuid, MultimeterService::CharacteristicUuids::settings, QObject::tr(), and QLowEnergyCharacteristic::uuid().
characteristicWritten()
void MultimeterServicePrivate::characteristicWritten (const QLowEnergyCharacteristic & characteristic, const QByteArray & newValue) override protected virtual
Implements AbstractPokitServicePrivate::characteristicWritten to parse newValue, then emit a specialised signal, for each supported characteristic.
Reimplemented from AbstractPokitServicePrivate.
Definition at line 382 of file multimeterservice.cpp.
{
    AbstractPokitServicePrivate::characteristicWritten(characteristic, newValue);
    Q_Q(MultimeterService);
    if (characteristic.uuid() == MultimeterService::CharacteristicUuids::settings) {
        emit q->settingsWritten();
        return;
    }
    if (characteristic.uuid() == MultimeterService::CharacteristicUuids::reading) {
        qCWarning(lc).noquote() << tr("Reading characteristic is read/notify, but somehow written")
            << serviceUuid << characteristic.name() << characteristic.uuid();
        return;
    }
    qCWarning(lc).noquote() << tr("Unknown characteristic written for Multimeter service")
        << serviceUuid << characteristic.name() << characteristic.uuid();
}
References AbstractPokitServicePrivate::characteristicWritten(), QLowEnergyCharacteristic::name(), MultimeterService::CharacteristicUuids::reading, AbstractPokitServicePrivate::serviceUuid, MultimeterService::CharacteristicUuids::settings, QObject::tr(), and QLowEnergyCharacteristic::uuid().
encodeSettings()
QByteArray MultimeterServicePrivate::encodeSettings (const MultimeterService::Settings & settings) static
Returns settings in the format Pokit devices expect.
Definition at line 315 of file multimeterservice.cpp.
{
    static_assert(sizeof(settings.mode)           == 1, "Expected to be 1 byte.");
    static_assert(sizeof(settings.range)          == 1, "Expected to be 1 byte.");
    static_assert(sizeof(settings.updateInterval) == 4, "Expected to be 4 bytes.");
    QByteArray value;
    QDataStream stream(&value, QIODevice::WriteOnly);
    stream.setByteOrder(QDataStream::LittleEndian);
    stream.setFloatingPointPrecision(QDataStream::SinglePrecision); // 32-bit floats, not 64-bit.
    stream << (quint8)settings.mode << settings.range << settings.updateInterval;
    Q_ASSERT(value.size() == 6);
    return value;
}
References QDataStream::LittleEndian, MultimeterService::Settings::mode, MultimeterService::Settings::range, QDataStream::setByteOrder(), QDataStream::setFloatingPointPrecision(), QDataStream::SinglePrecision, QByteArray::size(), MultimeterService::Settings::updateInterval, and QIODevice::WriteOnly.
Referenced by MultimeterService::setSettings().
parseReading()
MultimeterService::Reading MultimeterServicePrivate::parseReading (const QByteArray & value) static
Parses the Reading value into a MultimeterService::Reading struct.
Definition at line 334 of file multimeterservice.cpp.
{
    MultimeterService::Reading reading{
        MultimeterService::MeterStatus::Error,
        std::numeric_limits<float>::quiet_NaN(),
        MultimeterService::Mode::Idle, 0
    };
    if (!checkSize(QLatin1String("Reading"), value, 7, 7)) {
        return reading;
    }
    reading.status = MultimeterService::MeterStatus(value.at(0));
    reading.value  = qFromLittleEndian<float>(value.mid(1,4));
    reading.mode   = static_cast<MultimeterService::Mode>(value.at(5));
    reading.range  = static_cast<quint8>(value.at(6));
    return reading;
}
References QByteArray::at(), AbstractPokitServicePrivate::checkSize(), MultimeterService::Error, MultimeterService::Idle, and QByteArray::mid().
Referenced by characteristicChanged(), characteristicRead(), and MultimeterService::reading().
Friends And Related Symbol Documentation
TestMultimeterService
friend class TestMultimeterService friend
Definition at line 40 of file multimeterservice_p.h.
The documentation for this class was generated from the following files:
multimeterservice_p.h
multimeterservice.cpp