Dokit: MultimeterService Class Reference
MultimeterService Class Reference
The MultimeterService class accesses the Multimeter service of Pokit devices.
Classes
struct CharacteristicUuids
Characteristics available via the Multimeter service.
union Range
Values supported by the Range attribute of the Settings characteristic.
struct Reading
Attributes included in the Reading characterstic.
struct Settings
Attributes included in the Settings characterstic.
Public Types
enum class Mode : quint8 {
Idle = 0 , DcVoltage = 1 , AcVoltage = 2 , DcCurrent = 3 ,
AcCurrent = 4 , Resistance = 5 , Diode = 6 , Continuity = 7 ,
Temperature = 8
}
Values supported by the Mode attribute of the Settings and Reading characteristics.
enum class VoltageRange : quint8 {
_0_to_300mV = 0 , _300mV_to_2V = 1 , _2V_to_6V = 2 , _6V_to_12V = 3 ,
_12V_to_30V = 4 , _30V_to_60V = 5 , AutoRange = 255
}
Values supported by the Range attribute of the Settings and Reading characteristics, when Mode is AC or DC voltage.
enum class CurrentRange : quint8 {
_0_to_10mA = 0 , _10mA_to_30mA = 1 , _30mA_to_150mA = 2 , _150mA_to_300mA = 3 ,
_300mA_to_3A = 4 , AutoRange = 255
}
Values supported by the Range attribute of the Settings and Reading characteristics, when Mode is AC or DC current.
enum class ResistanceRange : quint8 {
_0_to_160 = 0 , _160_to_330 = 1 , _330_to_890 = 2 , _890_to_1K5 = 3 ,
_1K5_to_10K = 4 , _10K_to_100K = 5 , _100K_to_470K = 6 , _470K_to_1M = 7 ,
AutoRange = 255
}
Values supported by the Range attribute of the Settings and Reading characteristics, when Mode is resistance.
enum class MeterStatus : quint8 {
AutoRangeOff = 0 , AutoRangeOn = 1 , NoContinuity = 0 , Continuity = 1 ,
Ok = 0 , Error = 255
}
Values supported by the Status attribute of the Settings characteristic.
Signals
void settingsWritten ()
This signal is emitted when the Settings characteristic has been written successfully.
void readingRead (const MultimeterService::Reading &reading)
This signal is emitted when the Reading characteristic has been read successfully.
Signals inherited from AbstractPokitService
void serviceDetailsDiscovered ()
This signal is emitted when the Pokit service details have been discovered.
void serviceErrorOccurred (QLowEnergyService::ServiceError newError)
This signal is emitted whenever an error occurs on the underlying QLowEnergyService.
Public Member Functions
MultimeterService (QLowEnergyController *const pokitDevice, QObject *parent=nullptr)
Constructs a new Pokit service with parent.
~MultimeterService () override
Destroys this MultimeterService object.
bool readCharacteristics () override
Read all characteristics.
bool readReadingCharacteristic ()
Read the Multimeter service's Reading characteristic.
bool setSettings (const Settings &settings)
Configures the Pokit device's multimeter mode.
Reading reading () const
Returns the most recent value of the Multimeter service's Reading characteristic.
bool enableReadingNotifications ()
Enables client-side notifications of meter readings.
bool disableReadingNotifications ()
Disables client-side notifications of meter readings.
Public Member Functions inherited from AbstractPokitService
virtual ~AbstractPokitService ()
Destroys this AbstractPokitService object.
virtual bool readCharacteristics ()=0
Read all characteristics.
bool autoDiscover () const
Returns true if autodiscovery of services and service details is enabled, false otherwise.
void setAutoDiscover (const bool discover=true)
If discover is true, autodiscovery will be attempted.
QLowEnergyService * service ()
Returns a non-const pointer to the internal service object, if any.
const QLowEnergyService * service () const
Returns a const pointer to the internal service object, if any.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Member Functions
static QString toString (const Mode &mode)
Returns mode as a user-friendly string.
static QString toString (const VoltageRange &range)
Returns range as a user-friendly string.
static QVariant minValue (const VoltageRange &range)
Returns the minimum value for range in (integer) millivolts, or the string "Auto".
static QVariant maxValue (const VoltageRange &range)
Returns the maximum value for range in (integer) millivolts, or the string "Auto".
static QString toString (const CurrentRange &range)
Returns range as a user-friendly string.
static QVariant minValue (const CurrentRange &range)
Returns the minimum value for range in (integer) milliamps, or the string "Auto".
static QVariant maxValue (const CurrentRange &range)
Returns the maximum value for range in (integer) milliamps, or the string "Auto".
static QString toString (const ResistanceRange &range)
Returns range as a user-friendly string.
static QVariant minValue (const ResistanceRange &range)
Returns the minimum value for range in (integer) ohms, or the string "Auto".
static QVariant maxValue (const ResistanceRange &range)
Returns the maximum value for range in (integer) ohms, or the string "Auto".
static QString toString (const Range &range, const Mode &mode)
Returns range as a user-friendly string, or a null QString if mode has no ranges.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Static Public Attributes
static const QBluetoothUuid serviceUuid
UUID of the "Multimeter" service.
Protected Member Functions
MultimeterService (MultimeterServicePrivate *const d, QObject *const parent)
Constructs a new Pokit service with parent, and private implementation d.
Protected Member Functions inherited from AbstractPokitService
AbstractPokitService (AbstractPokitServicePrivate *const d, QObject *const parent)
Constructs a new Pokit service with parent, and private implementation d.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Friends
class TestMultimeterService
Additional Inherited Members
Public Attributes inherited from QObject
typedef QObjectList
Protected Attributes inherited from AbstractPokitService
AbstractPokitServicePrivate * d_ptr
Internal d-pointer.
Properties inherited from QObject
objectName
Detailed Description
The MultimeterService class accesses the Multimeter service of Pokit devices.
Definition at line 22 of file multimeterservice.h.
Member Enumeration Documentation
CurrentRange
enum class MultimeterService::CurrentRange : quint8 strong
Values supported by the Range attribute of the Settings and Reading characteristics, when Mode is AC or DC current.
Enumerator
_0_to_10mA
0 to 10mA.
_10mA_to_30mA
10mA to 30mA.
_30mA_to_150mA
30mA to 150mA.
_150mA_to_300mA
150mA to 300mA.
_300mA_to_3A
300mA to 3A.
AutoRange
Auto-range.
Todo:
Pokit Pro supports up to 10A.
Definition at line 62 of file multimeterservice.h.
                            : quint8 {
        _0_to_10mA      = 0,  ///< 0 to 10mA.
        _10mA_to_30mA   = 1,  ///< 10mA to 30mA.
        _30mA_to_150mA  = 2,  ///< 30mA to 150mA.
        _150mA_to_300mA = 3,  ///< 150mA to 300mA.
        _300mA_to_3A    = 4,  ///< 300mA to 3A.
        /// \todo Pokit Pro supports up to 10A.
        AutoRange       = 255 ///< Auto-range.
    };
MeterStatus
enum class MultimeterService::MeterStatus : quint8 strong
Values supported by the Status attribute of the Settings characteristic.
Enumerator
AutoRangeOff
Auto-range is disabled (voltage, current and resistance modes only).
AutoRangeOn
Auto-range is enabled (voltage, current and resistance modes only).
NoContinuity
No continuity (continuity mode only).
Continuity
Continuity (continuity mode only).
Ok
Ok (temperature and diode modes only).
Error
Error (all modes).
Definition at line 108 of file multimeterservice.h.
                           : quint8 {
        AutoRangeOff = 0,  ///< Auto-range is disabled (voltage, current and resistance modes only).
        AutoRangeOn  = 1,  ///< Auto-range is enabled (voltage, current and resistance modes only).
        NoContinuity = 0,  ///< No continuity (continuity mode only).
        Continuity   = 1,  ///< Continuity (continuity mode only).
        Ok           = 0,  ///< Ok (temperature and diode modes only).
        Error        = 255 ///< Error (all modes).
    };
Mode
enum class MultimeterService::Mode : quint8 strong
Values supported by the Mode attribute of the Settings and Reading characteristics.
Enumerator
Idle
Make device idle.
DcVoltage
Measure DC voltage.
AcVoltage
Measure AC voltage.
DcCurrent
Measure DC current.
AcCurrent
Measure AC current.
Resistance
Measure resistance.
Diode
Measure diode.
Continuity
Measure continuity.
Temperature
Measure temperature.
Definition at line 34 of file multimeterservice.h.
                    : quint8 {
        Idle        = 0, ///< Make device idle.
        DcVoltage   = 1, ///< Measure DC voltage.
        AcVoltage   = 2, ///< Measure AC voltage.
        DcCurrent   = 3, ///< Measure DC current.
        AcCurrent   = 4, ///< Measure AC current.
        Resistance  = 5, ///< Measure resistance.
        Diode       = 6, ///< Measure diode.
        Continuity  = 7, ///< Measure continuity.
        Temperature = 8, ///< Measure temperature.
        /// \todo Pokit Pro supports capacitance too.
    };
ResistanceRange
enum class MultimeterService::ResistanceRange : quint8 strong
Values supported by the Range attribute of the Settings and Reading characteristics, when Mode is resistance.
Enumerator
_0_to_160
0 to 160 ohms.
_160_to_330
160 to 330 ohms.
_330_to_890
330 to 890 ohms.
_890_to_1K5
890 to 1.5K ohms.
_1K5_to_10K
1.5K to 10K ohms.
_10K_to_100K
10K to 100K ohms.
_100K_to_470K
100K to 470K ohms.
_470K_to_1M
470K to 1M ohms.
AutoRange
Auto-range.
Todo:
Pokit Pro supports up to 3M ohms.
Definition at line 75 of file multimeterservice.h.
                               : quint8 {
        _0_to_160     = 0,  ///< 0 to 160 ohms.
        _160_to_330   = 1,  ///< 160 to 330 ohms.
        _330_to_890   = 2,  ///< 330 to 890 ohms.
        _890_to_1K5   = 3,  ///< 890 to 1.5K ohms.
        _1K5_to_10K   = 4,  ///< 1.5K to 10K ohms.
        _10K_to_100K  = 5,  ///< 10K to 100K ohms.
        _100K_to_470K = 6,  ///< 100K to 470K ohms.
        _470K_to_1M   = 7,  ///< 470K to 1M ohms.
        /// \todo Pokit Pro supports up to 3M ohms.
        AutoRange     = 255 ///< Auto-range.
    };
VoltageRange
enum class MultimeterService::VoltageRange : quint8 strong
Values supported by the Range attribute of the Settings and Reading characteristics, when Mode is AC or DC voltage.
Enumerator
_0_to_300mV
0 to 300mV.
_300mV_to_2V
300mV to 2V.
_2V_to_6V
2V to 6V.
_6V_to_12V
6V to 12V.
_12V_to_30V
12V to 30V.
_30V_to_60V
30V to 60V.
AutoRange
Auto-range.
Todo:
Pokit Pro supports up to 600V.
Definition at line 48 of file multimeterservice.h.
                            : quint8 {
        _0_to_300mV  = 0,  ///< 0 to 300mV.
        _300mV_to_2V = 1,  ///< 300mV to 2V.
        _2V_to_6V    = 2,  ///< 2V to 6V.
        _6V_to_12V   = 3,  ///< 6V to 12V.
        _12V_to_30V  = 4,  ///< 12V to 30V.
        _30V_to_60V  = 5,  ///< 30V to 60V.
        /// \todo Pokit Pro supports up to 600V.
        AutoRange    = 255 ///< Auto-range.
    };
Constructor & Destructor Documentation
MultimeterService() [1/2]
MultimeterService::MultimeterService (QLowEnergyController *const pokitDevice, QObject * parent = nullptr)
Constructs a new Pokit service with parent.
Definition at line 335 of file multimeterservice.cpp.
    : AbstractPokitService(new MultimeterServicePrivate(controller, this), parent)
{
}
~MultimeterService()
MultimeterService::~MultimeterService () override
Destroys this MultimeterService object.
Definition at line 356 of file multimeterservice.cpp.
{
}
MultimeterService() [2/2]
MultimeterService::MultimeterService (MultimeterServicePrivate *const d, QObject *const parent) protected
Constructs a new Pokit service with parent, and private implementation d.
Definition at line 345 of file multimeterservice.cpp.
    : AbstractPokitService(d, parent)
{
}
Member Function Documentation
disableReadingNotifications()
bool MultimeterService::disableReadingNotifications ()
Disables client-side notifications of meter readings.
Instantaneous reads can still be fetched by readReadingCharacteristic().
Returns true is the request was successfully submited to the device queue, false otherwise.
Definition at line 452 of file multimeterservice.cpp.
{
    Q_D(MultimeterService);
    return d->disableCharacteristicNotificatons(CharacteristicUuids::reading);
}
References MultimeterService::CharacteristicUuids::reading.
enableReadingNotifications()
bool MultimeterService::enableReadingNotifications ()
Enables client-side notifications of meter readings.
This is an alternative to manually requesting individual reads via readReadingCharacteristic().
Returns true is the request was successfully submited to the device queue, false otherwise.
Successfully read values (if any) will be emitted via the readingRead() signal.
Definition at line 439 of file multimeterservice.cpp.
{
    Q_D(MultimeterService);
    return d->enableCharacteristicNotificatons(CharacteristicUuids::reading);
}
References MultimeterService::CharacteristicUuids::reading.
Referenced by MeterCommand::settingsWritten().
maxValue() [1/3]
QVariant MultimeterService::maxValue (const CurrentRange & range) static
Returns the maximum value for range in (integer) milliamps, or the string "Auto".
If range is not known valid value, then an null QVariant is returned.
Definition at line 161 of file multimeterservice.cpp.
{
    switch (range) {
    case CurrentRange::_0_to_10mA:      return   10;
    case CurrentRange::_10mA_to_30mA:   return   30;
    case CurrentRange::_30mA_to_150mA:  return  150;
    case CurrentRange::_150mA_to_300mA: return  300;
    case CurrentRange::_300mA_to_3A:    return 3000;
    case CurrentRange::AutoRange:       return tr("Auto");
    default:                            return QVariant();
    }
}
References _0_to_10mA, _10mA_to_30mA, _150mA_to_300mA, _300mA_to_3A, _30mA_to_150mA, AutoRange, and QObject::tr().
maxValue() [2/3]
QVariant MultimeterService::maxValue (const ResistanceRange & range) static
Returns the maximum value for range in (integer) ohms, or the string "Auto".
If range is not known valid value, then an null QVariant is returned.
Definition at line 219 of file multimeterservice.cpp.
{
    switch (range) {
    case ResistanceRange::_0_to_160:     return     160;
    case ResistanceRange::_160_to_330:   return     330;
    case ResistanceRange::_330_to_890:   return     890;
    case ResistanceRange::_890_to_1K5:   return    1500;
    case ResistanceRange::_1K5_to_10K:   return   10000;
    case ResistanceRange::_10K_to_100K:  return  100000;
    case ResistanceRange::_100K_to_470K: return  470000;
    case ResistanceRange::_470K_to_1M:   return 1000000;
    case ResistanceRange::AutoRange:     return tr("Auto");
    default:                             return QVariant();
    }
}
References _0_to_160, _100K_to_470K, _10K_to_100K, _160_to_330, _1K5_to_10K, _330_to_890, _470K_to_1M, _890_to_1K5, AutoRange, and QObject::tr().
maxValue() [3/3]
QVariant MultimeterService::maxValue (const VoltageRange & range) static
Returns the maximum value for range in (integer) millivolts, or the string "Auto".
If range is not known valid value, then an null QVariant is returned.
Definition at line 103 of file multimeterservice.cpp.
{
    switch (range) {
    case VoltageRange::_0_to_300mV:  return   300;
    case VoltageRange::_300mV_to_2V: return  2000;
    case VoltageRange::_2V_to_6V:    return  6000;
    case VoltageRange::_6V_to_12V:   return 12000;
    case VoltageRange::_12V_to_30V:  return 30000;
    case VoltageRange::_30V_to_60V:  return 60000;
    case VoltageRange::AutoRange:    return tr("Auto");
    default:                         return QVariant();
    }
}
References _0_to_300mV, _12V_to_30V, _2V_to_6V, _300mV_to_2V, _30V_to_60V, _6V_to_12V, AutoRange, and QObject::tr().
Referenced by MeterCommand::outputReading().
minValue() [1/3]
QVariant MultimeterService::minValue (const CurrentRange & range) static
Returns the minimum value for range in (integer) milliamps, or the string "Auto".
If range is not known valid value, then an null QVariant is returned.
Note, this is an absolute minimum. That is, the true range for DC measurements is from -maxValue(range) to +maxValue(range). In this sense, minValue(range) indicates the magnitude (ignore signs) that can be measured accurately for the given range. As AC current can never be negative, this is relevant for DC current only.
Definition at line 144 of file multimeterservice.cpp.
{
    switch (range) {
    case CurrentRange::_0_to_10mA:      return   0;
    case CurrentRange::_10mA_to_30mA:   return  10;
    case CurrentRange::_30mA_to_150mA:  return  30;
    case CurrentRange::_150mA_to_300mA: return 150;
    case CurrentRange::_300mA_to_3A:    return 300;
    case CurrentRange::AutoRange:       return tr("Auto");
    default:                            return QVariant();
    }
}
References _0_to_10mA, _10mA_to_30mA, _150mA_to_300mA, _300mA_to_3A, _30mA_to_150mA, AutoRange, and QObject::tr().
minValue() [2/3]
QVariant MultimeterService::minValue (const ResistanceRange & range) static
Returns the minimum value for range in (integer) ohms, or the string "Auto".
If range is not known valid value, then an null QVariant is returned.
Definition at line 199 of file multimeterservice.cpp.
{
    switch (range) {
    case ResistanceRange::_0_to_160:     return      0;
    case ResistanceRange::_160_to_330:   return    160;
    case ResistanceRange::_330_to_890:   return    330;
    case ResistanceRange::_890_to_1K5:   return    890;
    case ResistanceRange::_1K5_to_10K:   return   1500;
    case ResistanceRange::_10K_to_100K:  return  10000;
    case ResistanceRange::_100K_to_470K: return 100000;
    case ResistanceRange::_470K_to_1M:   return 470000;
    case ResistanceRange::AutoRange:     return tr("Auto");
    default:                             return QVariant();
    }
}
References _0_to_160, _100K_to_470K, _10K_to_100K, _160_to_330, _1K5_to_10K, _330_to_890, _470K_to_1M, _890_to_1K5, AutoRange, and QObject::tr().
minValue() [3/3]
QVariant MultimeterService::minValue (const VoltageRange & range) static
Returns the minimum value for range in (integer) millivolts, or the string "Auto".
If range is not known valid value, then an null QVariant is returned.
Note, this is an absolute minimum. That is, the true range for DC measurements is from -maxValue(range) to +maxValue(range). In this sense, minValue(range) indicates the magnitude (ignore signs) that can be measured accurately for the given range. As AC voltage can never be negative, this is relevant for DC voltage only.
Definition at line 85 of file multimeterservice.cpp.
{
    switch (range) {
    case VoltageRange::_0_to_300mV:  return     0;
    case VoltageRange::_300mV_to_2V: return   300;
    case VoltageRange::_2V_to_6V:    return  2000;
    case VoltageRange::_6V_to_12V:   return  6000;
    case VoltageRange::_12V_to_30V:  return 12000;
    case VoltageRange::_30V_to_60V:  return 30000;
    case VoltageRange::AutoRange:    return tr("Auto");
    default:                         return QVariant();
    }
}
References _0_to_300mV, _12V_to_30V, _2V_to_6V, _300mV_to_2V, _30V_to_60V, _6V_to_12V, AutoRange, and QObject::tr().
Referenced by MeterCommand::outputReading().
readCharacteristics()
bool MultimeterService::readCharacteristics () override virtual
Read all characteristics.
This convenience function will queue refresh requests of all characteristics supported by this service.
Relevant *Service::*Read signals will be emitted by derived class objects as each characteristic is successfully read.
Implements AbstractPokitService.
Definition at line 361 of file multimeterservice.cpp.
{
    return readReadingCharacteristic();
}
References readReadingCharacteristic().
reading()
MultimeterService::Reading MultimeterService::reading () const
Returns the most recent value of the Multimeter service's Reading characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then the returned MultimeterService::Reading::value member will be a quiet NaN, which can be checked like:
const MultimeterService::Reading reading = multimeterService->reading();
if (qIsNaN(reading.value)) {
    // Handle failure.
}
Definition at line 420 of file multimeterservice.cpp.
{
    Q_D(const MultimeterService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::reading);
    return (characteristic.isValid()) ? MultimeterServicePrivate::parseReading(characteristic.value())
        : Reading{ MeterStatus::Error, std::numeric_limits<float>::quiet_NaN(),
                   Mode::Idle, VoltageRange::AutoRange };
}
References AutoRange, Error, Idle, QLowEnergyCharacteristic::isValid(), MultimeterServicePrivate::parseReading(), MultimeterService::CharacteristicUuids::reading, and QLowEnergyCharacteristic::value().
readingRead
MultimeterService::readingRead (const MultimeterService::Reading & reading) signal
This signal is emitted when the Reading characteristic has been read successfully.
See also
readReadingCharacteristic
Referenced by MeterCommand::settingsWritten().
readReadingCharacteristic()
bool MultimeterService::readReadingCharacteristic ()
Read the Multimeter service's Reading characteristic.
Returns true is the read request is succesfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits readingRead() if/when the characteristic has been read successfully.
Definition at line 375 of file multimeterservice.cpp.
{
    Q_D(MultimeterService);
    return d->readCharacteristic(CharacteristicUuids::reading);
}
References MultimeterService::CharacteristicUuids::reading.
Referenced by readCharacteristics().
setSettings()
bool MultimeterService::setSettings (const Settings & settings)
Configures the Pokit device's multimeter mode.
Returns true if the write request was successfully queued, false otherwise.
Emits settingsWritten() if/when the settings have been writtem successfully.
Definition at line 388 of file multimeterservice.cpp.
{
    Q_D(const MultimeterService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::settings);
    if (!characteristic.isValid()) {
        return false;
    }
    const QByteArray value = d->encodeSettings(settings);
    if (value.isNull()) {
        return false;
    }
    d->service->writeCharacteristic(characteristic, value);
    return (d->service->error() != QLowEnergyService::ServiceError::CharacteristicWriteError);
}
References QByteArray::isNull(), QLowEnergyCharacteristic::isValid(), and MultimeterService::CharacteristicUuids::settings.
Referenced by MeterCommand::serviceDetailsDiscovered().
settingsWritten
MultimeterService::settingsWritten () signal
This signal is emitted when the Settings characteristic has been written successfully.
See also
setSettings
Referenced by MeterCommand::getService().
toString() [1/5]
QString MultimeterService::toString (const CurrentRange & range) static
Returns range as a user-friendly string.
Definition at line 122 of file multimeterservice.cpp.
{
    switch (range) {
    case CurrentRange::_0_to_10mA:      return tr("0 to 10mA");
    case CurrentRange::_10mA_to_30mA:   return tr("10mA to 30mA");
    case CurrentRange::_30mA_to_150mA:  return tr("30mA to 150mA");
    case CurrentRange::_150mA_to_300mA: return tr("150mA to 300mA");
    case CurrentRange::_300mA_to_3A:    return tr("300mA to 3A");
    case CurrentRange::AutoRange:       return tr("Auto-range");
    default:                            return QString();
    }
}
References _0_to_10mA, _10mA_to_30mA, _150mA_to_300mA, _300mA_to_3A, _30mA_to_150mA, AutoRange, and QObject::tr().
toString() [2/5]
QString MultimeterService::toString (const Mode & mode) static
Returns mode as a user-friendly string.
Definition at line 41 of file multimeterservice.cpp.
{
    switch (mode) {
    case Mode::Idle:        return tr("Idle");
    case Mode::DcVoltage:   return tr("DC voltage");
    case Mode::AcVoltage:   return tr("AC voltage");
    case Mode::DcCurrent:   return tr("DC current");
    case Mode::AcCurrent:   return tr("AC current");
    case Mode::Resistance:  return tr("Resistance");
    case Mode::Diode:       return tr("Diode");
    case Mode::Continuity:  return tr("Continuity");
    case Mode::Temperature: return tr("Temperature");
    default:                return QString();
    }
}
References AcCurrent, AcVoltage, Continuity, DcCurrent, DcVoltage, Diode, Idle, Resistance, Temperature, and QObject::tr().
Referenced by MeterCommand::outputReading(), MeterCommand::serviceDetailsDiscovered(), and toString().
toString() [3/5]
QString MultimeterService::toString (const Range & range, const Mode & mode) static
Returns range as a user-friendly string, or a null QString if mode has no ranges.
Definition at line 267 of file multimeterservice.cpp.
{
    switch (mode) {
    case Mode::DcVoltage:
    case Mode::AcVoltage:
        return toString(range.voltageRange);
    case Mode::DcCurrent:
    case Mode::AcCurrent:
        return toString(range.currentRange);
    default:
        return QString();
    }
}
References AcCurrent, AcVoltage, MultimeterService::Range::currentRange, DcCurrent, DcVoltage, toString(), and MultimeterService::Range::voltageRange.
toString() [4/5]
QString MultimeterService::toString (const ResistanceRange & range) static
Returns range as a user-friendly string.
Definition at line 179 of file multimeterservice.cpp.
{
    switch (range) {
    case ResistanceRange::_0_to_160:     return tr("0 to 160 ohms");
    case ResistanceRange::_160_to_330:   return tr("160 to 330 ohms");
    case ResistanceRange::_330_to_890:   return tr("330 to 890 ohms");
    case ResistanceRange::_890_to_1K5:   return tr("890 to 1.5K ohms");
    case ResistanceRange::_1K5_to_10K:   return tr("1.5K to 10K ohms");
    case ResistanceRange::_10K_to_100K:  return tr("10K to 100K ohms");
    case ResistanceRange::_100K_to_470K: return tr("100K to 470K ohms");
    case ResistanceRange::_470K_to_1M:   return tr("470K to 1M ohms");
    case ResistanceRange::AutoRange:     return tr("Auto-range");
    default:                             return QString();
    }
}
References _0_to_160, _100K_to_470K, _10K_to_100K, _160_to_330, _1K5_to_10K, _330_to_890, _470K_to_1M, _890_to_1K5, AutoRange, and QObject::tr().
toString() [5/5]
QString MultimeterService::toString (const VoltageRange & range) static
Returns range as a user-friendly string.
Definition at line 62 of file multimeterservice.cpp.
{
    switch (range) {
    case VoltageRange::_0_to_300mV:  return tr("0 to 300mV");
    case VoltageRange::_300mV_to_2V: return tr("300mV to 2V");
    case VoltageRange::_2V_to_6V:    return tr("2V to 6V");
    case VoltageRange::_6V_to_12V:   return tr("6V to 12V");
    case VoltageRange::_12V_to_30V:  return tr("12V to 30V");
    case VoltageRange::_30V_to_60V:  return tr("30V to 60V");
    case VoltageRange::AutoRange:    return tr("Auto-range");
    default:                         return QString();
    }
}
References _0_to_300mV, _12V_to_30V, _2V_to_6V, _300mV_to_2V, _30V_to_60V, _6V_to_12V, AutoRange, and QObject::tr().
Friends And Related Function Documentation
TestMultimeterService
friend class TestMultimeterService friend
Definition at line 150 of file multimeterservice.h.
Member Data Documentation
serviceUuid
const QBluetoothUuid MultimeterService::serviceUuid static
UUID of the "Multimeter" service.
Definition at line 27 of file multimeterservice.h.
Referenced by PokitDevice::serviceToString().
The documentation for this class was generated from the following files:
multimeterservice.h
multimeterservice.cpp