QtPokit: Scanner Class Reference
Scanner Class Reference
Scans for nearby Pokit devices.
#include <scanner.h>
Public Slots
void start (const int timeout=0)
Begins scanning for Pokit devices, with timeout, in milliseconds.
Public Member Functions
Scanner (QObject *const parent)
Construct a new scanner object with parent.
Private Slots
void deviceDiscovered (const QBluetoothDeviceInfo &info)
Handles discovered Pokit devices, writing info to stdout.
Private Attributes
PokitDeviceDiscoveryAgent * discoveryAgent
Agent for Pokit device descovery.
Detailed Description
Scans for nearby Pokit devices.
When devices are found, they are logged to stdout in the chosen format.
Definition at line 30 of file scanner.h.
Constructor & Destructor Documentation
Scanner()
Scanner::Scanner (QObject *const parent) explicit
Construct a new scanner object with parent.
Definition at line 35 of file scanner.cpp.
                                       : QObject(parent)
{
    discoveryAgent = new PokitDeviceDiscoveryAgent(this);
    connect(discoveryAgent, &PokitDeviceDiscoveryAgent::pokitDeviceDiscovered,
            this, &Scanner::deviceDiscovered);
    connect(discoveryAgent, &PokitDeviceDiscoveryAgent::finished, this, []() {
        qCDebug(pokitScanner) << "Finished scanning for Pokit devices.";
        QCoreApplication::quit();
    });
}
References deviceDiscovered(), discoveryAgent, and PokitDeviceDiscoveryAgent::pokitDeviceDiscovered().
Member Function Documentation
deviceDiscovered
void Scanner::deviceDiscovered (const QBluetoothDeviceInfo & info) private slot
Handles discovered Pokit devices, writing info to stdout.
Todo:
Support alternative output formats: text, json, other?
Definition at line 66 of file scanner.cpp.
{
    fputs(QJsonDocument(toJson(info)).toJson(), stdout);
}
References toJson().
Referenced by Scanner().
start
void Scanner::start (const int timeout = 0) slot
Begins scanning for Pokit devices, with timeout, in milliseconds.
Definition at line 51 of file scanner.cpp.
{
    Q_ASSERT(discoveryAgent);
    qCDebug(pokitScanner).noquote().nospace() << "Scanning for Pokit devices (with "
        << (timeout ? QLocale().toString(timeout)+QLatin1String("ms") : QLatin1String("no"))
        << " timeout).";
    discoveryAgent->setLowEnergyDiscoveryTimeout(timeout);
    discoveryAgent->start();
}
References discoveryAgent, and PokitDeviceDiscoveryAgent::start().
Member Data Documentation
discoveryAgent
PokitDeviceDiscoveryAgent* Scanner::discoveryAgent private
Agent for Pokit device descovery.
Definition at line 39 of file scanner.h.
Referenced by Scanner(), and start().
The documentation for this class was generated from the following files:
scanner.h
scanner.cpp