Dokit: DeviceCommand Class Reference
DeviceCommand Class Reference abstract
The AbstractCommand class extends AbstractCommand to add a PokitDevice instance.
Public Slots
bool start () override
Begins scanning for the Pokit device.
Public Slots inherited from AbstractCommand
virtual QStringList processOptions (const QCommandLineParser &parser)
Processes the relevant options from the command line parser.
virtual bool start ()=0
Begins the functionality of this command, and returns true if begun successfully, false otherwise.
Public Member Functions
DeviceCommand (QObject *const parent=nullptr)
Construct a new DeviceCommand object with parent.
Public Member Functions inherited from AbstractCommand
AbstractCommand (QObject *const parent=nullptr)
Constructs a new command with parent.
virtual QStringList requiredOptions (const QCommandLineParser &parser) const
Returns a list of CLI option names required by this command.
virtual QStringList supportedOptions (const QCommandLineParser &parser) const
Returns a list of CLI option names supported by this command.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Protected Slots
virtual void controllerError (const QLowEnergyController::Error error)
Handles controller error events.
virtual void deviceDisconnected ()
Handles device disconnection events.
virtual void serviceError (const QLowEnergyService::ServiceError error)
Handles service error events.
virtual void serviceDetailsDiscovered ()
Handles service detail discovery events.
Protected Slots inherited from AbstractCommand
virtual void deviceDiscovered (const QBluetoothDeviceInfo &info)=0
Handles PokitDiscoveryAgent::pokitDeviceDiscovered signal.
virtual void deviceDiscoveryFinished ()=0
Handles PokitDiscoveryAgent::deviceDiscoveryFinished signal.
Protected Member Functions
void disconnect (int exitCode=EXIT_SUCCESS)
Disconnects the underlying Pokit device, and sets exitCode to be return to the OS once the disconnection has taken place.
virtual AbstractPokitService * getService ()=0
Returns a Pokit service object for the derived command class.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Static Protected Member Functions
template<typename T>
static T minRange (const quint32 maxValue)
static quint8 minCapacitanceRange (const PokitProduct product, const quint32 maxValue)
Returns the product's lowest capacitance range that can measure at least up to maxValue (nF), or AutoRange if no such range is available.
static quint8 minCurrentRange (const PokitProduct product, const quint32 maxValue)
Returns the product's lowest current range that can measure at least up to maxValue (A), or AutoRange if no such range is available.
static quint8 minResistanceRange (const PokitProduct product, const quint32 maxValue)
Returns the product's lowest resistance range that can measure at least up to maxValue (), or AutoRange if no such range is available.
static quint8 minVoltageRange (const PokitProduct product, const quint32 maxValue)
t Returns the product's lowest voltage range that can measure at least up to maxValue (mV), or AutoRange if no such range is available.
Static Protected Member Functions inherited from AbstractCommand
static Q_LOGGING_CATEGORY (lc, "dokit.cli.command", QtInfoMsg)
Logging category for UI commands.
Protected Attributes
PokitDevice * device { nullptr }
Pokit Bluetooth device (if any) this command interacts with.
int exitCodeOnDisconnect { EXIT_FAILURE }
Exit code to return on device disconnection.
Protected Attributes inherited from AbstractCommand
QString deviceToScanFor
Device (if any) that were passed to processOptions().
PokitDiscoveryAgent * discoveryAgent
Agent for Pokit device discovery.
OutputFormat format { OutputFormat::Text }
Selected output format.
Private Slots
void deviceDiscovered (const QBluetoothDeviceInfo &info) override
Checks if info is the device (if any) we're looking for, and if so, create a controller and service, and begins connecting to the device.
void deviceDiscoveryFinished () override
Checks that the requested device was discovered, and if not, reports and error and exits.
Additional Inherited Members
Public Types inherited from AbstractCommand
enum class OutputFormat { Csv , Json , Text }
Supported output formats.
Static Public Member Functions inherited from AbstractCommand
static QString escapeCsvField (const QString &field)
Returns an RFC 4180 compliant version of field.
template<typename R>
static quint32 parseNumber (const QString &value, const QString &unit, const quint32 sensibleMinimum=0)
Returns value as an integer multiple of the ratio R.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Properties inherited from QObject
objectName
Detailed Description
The AbstractCommand class extends AbstractCommand to add a PokitDevice instance.
Definition at line 16 of file devicecommand.h.
Constructor & Destructor Documentation
DeviceCommand()
DeviceCommand::DeviceCommand (QObject *const parent = nullptr) explicit
Construct a new DeviceCommand object with parent.
Definition at line 21 of file devicecommand.cpp.
                                                   : AbstractCommand(parent)
{
}
References AbstractCommand::AbstractCommand(), QObject::parent(), and QObject::QObject().
Referenced by CalibrateCommand::CalibrateCommand(), DsoCommand::DsoCommand(), FlashLedCommand::FlashLedCommand(), InfoCommand::InfoCommand(), LoggerFetchCommand::LoggerFetchCommand(), LoggerStartCommand::LoggerStartCommand(), LoggerStopCommand::LoggerStopCommand(), MeterCommand::MeterCommand(), minRange(), SetNameCommand::SetNameCommand(), SetTorchCommand::SetTorchCommand(), and StatusCommand::StatusCommand().
Member Function Documentation
controllerError
void DeviceCommand::controllerError (const QLowEnergyController::Error error) protected virtual slot
Handles controller error events.
This base implementation simply logs error and then exits with EXIT_FAILURE. Derived classes may override this slot to implement their own error handing if desired.
Definition at line 292 of file devicecommand.cpp.
{
    qCWarning(lc).noquote() << tr("Bluetooth controller error:") << error;
    QCoreApplication::exit(EXIT_FAILURE);
}
References QCoreApplication::exit(), and QObject::tr().
Referenced by deviceDiscovered().
deviceDisconnected
void DeviceCommand::deviceDisconnected () protected virtual slot
Handles device disconnection events.
This base implementation simply logs and exits the application (via QCoreApplication::exit) with the current exitCodeOnDisconnect value, which is initialise to EXIT_FAILURE in the constructor, but should be set to EXIT_SUCESS if/when the derived command class has completed its actions and requested the disconnection (as opposed to a spontaneous disconnection on error).
Definition at line 305 of file devicecommand.cpp.
{
    qCDebug(lc).noquote() << tr("Pokit device disconnected. Exiting with code %1.")
        .arg(exitCodeOnDisconnect);
    QCoreApplication::exit(exitCodeOnDisconnect);
}
References QString::arg(), QCoreApplication::exit(), exitCodeOnDisconnect, and QObject::tr().
Referenced by deviceDiscovered().
deviceDiscovered
void DeviceCommand::deviceDiscovered (const QBluetoothDeviceInfo & info) override private slot
Checks if info is the device (if any) we're looking for, and if so, create a controller and service, and begins connecting to the device.
Definition at line 340 of file devicecommand.cpp.
{
    Q_ASSERT(isPokitProduct(info));
    if (device) {
        qCDebug(lc).noquote() << tr(R"(Ignoring additional Pokit device "%1" (%2) at (%3).)")
            .arg(info.name(), info.deviceUuid().toString(), info.address().toString());
        return;
    }
    if ((deviceToScanFor.isEmpty()) || (deviceToScanFor == info.name()) ||
        ((!info.address().isNull()) && (info.address() == QBluetoothAddress(deviceToScanFor))) ||
        ((!info.deviceUuid().isNull()) && (info.deviceUuid() == QBluetoothUuid(deviceToScanFor))))
    {
        qCDebug(lc).noquote() << tr(R"(Found Pokit device "%1" (%2) at (%3).)")
            .arg(info.name(), info.deviceUuid().toString(), info.address().toString());
        discoveryAgent->stop();
        device = new PokitDevice(info, this);
        connect(device->controller(), &QLowEnergyController::disconnected,
                this, &DeviceCommand::deviceDisconnected);
        connect(device->controller(),
            #if (QT_VERSION < QT_VERSION_CHECK(6, 2, 0))
            QOverload<QLowEnergyController::Error>::of(&QLowEnergyController::error),
            #else
            &QLowEnergyController::errorOccurred,
            #endif
            this, &DeviceCommand::controllerError, Qt::QueuedConnection);
        AbstractPokitService * const service = getService();
        service->setPokitProduct(pokitProduct(info));
        Q_ASSERT(service);
        connect(service, &AbstractPokitService::serviceDetailsDiscovered,
                this, &DeviceCommand::serviceDetailsDiscovered);
        connect(service, &AbstractPokitService::serviceErrorOccurred,
                this, &DeviceCommand::serviceError);
        qCDebug(lc).noquote() << tr(R"(Connecting to %1 device "%2" (%3) at (%4).)").arg(
            toString(*service->pokitProduct()), info.name(), info.deviceUuid().toString(), info.address().toString());
        device->controller()->connectToDevice();
        return;
    }
    qCDebug(lc).noquote() << tr(R"(Ignoring non-matching Pokit device "%1" (%2) at (%3).)")
        .arg(info.name(), info.deviceUuid().toString(), info.address().toString());
    return;
}
References QBluetoothDeviceInfo::address(), QString::arg(), QObject::connect(), controllerError(), device, deviceDisconnected(), AbstractCommand::deviceToScanFor, QBluetoothDeviceInfo::deviceUuid(), QLowEnergyController::disconnected(), AbstractCommand::discoveryAgent, QLowEnergyController::error(), getService(), QBluetoothAddress::isNull(), QUuid::isNull(), isPokitProduct(), QBluetoothDeviceInfo::name(), AbstractPokitService::pokitProduct(), pokitProduct(), Qt::QueuedConnection, AbstractPokitService::serviceDetailsDiscovered(), serviceDetailsDiscovered(), serviceError(), AbstractPokitService::serviceErrorOccurred(), AbstractPokitService::setPokitProduct(), QBluetoothAddress::toString(), QUuid::toString(), toString(), and QObject::tr().
deviceDiscoveryFinished
void DeviceCommand::deviceDiscoveryFinished () override private slot
Checks that the requested device was discovered, and if not, reports and error and exits.
Definition at line 392 of file devicecommand.cpp.
{
    if (!device) {
        qCWarning(lc).noquote() << ((deviceToScanFor.isNull())
            ? tr("Failed to find any Pokit device.")
            : tr(R"(Failed to find device "%1".)").arg(deviceToScanFor));
        QCoreApplication::exit(EXIT_FAILURE);
    }
}
References device, AbstractCommand::deviceToScanFor, QCoreApplication::exit(), and QObject::tr().
disconnect()
void DeviceCommand::disconnect (int exitCode = EXIT_SUCCESS) protected
Disconnects the underlying Pokit device, and sets exitCode to be return to the OS once the disconnection has taken place.
Definition at line 42 of file devicecommand.cpp.
{
    qCDebug(lc).noquote() << tr("Disconnecting Pokit device...");
    Q_ASSERT(device);
    Q_ASSERT(device->controller());
    exitCodeOnDisconnect = exitCode;
    device->controller()->disconnectFromDevice();
}
References device, exitCodeOnDisconnect, and QObject::tr().
Referenced by FlashLedCommand::deviceLedFlashed(), SetNameCommand::deviceNameWritten(), StatusCommand::outputDeviceStatus(), MeterCommand::outputReading(), DsoCommand::outputSamples(), LoggerFetchCommand::outputSamples(), InfoCommand::serviceDetailsDiscovered(), LoggerStartCommand::settingsWritten(), LoggerStopCommand::settingsWritten(), CalibrateCommand::temperatureCalibrated(), and SetTorchCommand::torchStatusWritten().
getService()
virtual AbstractPokitService * DeviceCommand::getService () protected pure virtual
Returns a Pokit service object for the derived command class.
This will be called by deviceDiscovered() when the requested Pokit device has been found, after which deviceDiscovered() will connect the returned service's common signals, and kick off the device's connection process.
Implemented in CalibrateCommand, DsoCommand, FlashLedCommand, InfoCommand, LoggerFetchCommand, LoggerStartCommand, LoggerStopCommand, MeterCommand, SetNameCommand, SetTorchCommand, and StatusCommand.
Referenced by deviceDiscovered().
minCapacitanceRange()
quint8 DeviceCommand::minCapacitanceRange (const PokitProduct product, const quint32 maxValue) static protected
Returns the product's lowest capacitance range that can measure at least up to maxValue (nF), or AutoRange if no such range is available.
Note
Since Pokit Meters do not support capacitance measurement, product should not be PokitProduct::PokitMeter.
See also
minRange<PokitPro::CapacitanceRange>
Definition at line 213 of file devicecommand.cpp.
{
    switch (product) {
    case PokitProduct::PokitMeter:
        Q_ASSERT_X(false, "DeviceCommand::minCapacitanceRange", "Pokit Meter has no capacitance support.");
        return 255;
    case PokitProduct::PokitPro:
        return +minRange<PokitPro::CapacitanceRange>(maxValue);
    }
    Q_ASSERT_X(false, "DeviceCommand::minCapacitanceRange", "Unknown PokitProduct enum value");
    return 255;
}
References minRange(), PokitMeter, and PokitPro.
Referenced by MeterCommand::processOptions().
minCurrentRange()
quint8 DeviceCommand::minCurrentRange (const PokitProduct product, const quint32 maxValue) static protected
Returns the product's lowest current range that can measure at least up to maxValue (A), or AutoRange if no such range is available.
See also
DeviceCommand::minRange<PokitMeter::CurrentRange>(const quint32 maxValue)
minRange<PokitPro::CurrentRange>(const quint32 maxValue)
Definition at line 233 of file devicecommand.cpp.
{
    switch (product) {
    case PokitProduct::PokitMeter:
        return +minRange<PokitMeter::CurrentRange>(maxValue);
    case PokitProduct::PokitPro:
        return +minRange<PokitPro::CurrentRange>(maxValue);
    }
    Q_ASSERT_X(false, "DeviceCommand::minCurrentRange", "Unknown PokitProduct enum value");
    return 255;
}
References minRange(), PokitMeter, and PokitPro.
Referenced by DsoCommand::processOptions(), LoggerStartCommand::processOptions(), and MeterCommand::processOptions().
minRange()
template<typename T> static T DeviceCommand::minRange (const quint32 maxValue) static protected
Returns the lowest T range that can measure at least up to maxValue, or AutoRange if no such range is available.
Template Parameters
T Range enumerator to evaluate ranges for. Must be one of:
PokitMeter::CurrentRange
PokitMeter::ResistanceRange
PokitMeter::VoltageRange
PokitPro::CapacitanceRange
PokitPro::CurrentRange
PokitPro::ResistanceRange
PokitPro::VoltageRange
References DeviceCommand().
Referenced by minCapacitanceRange(), minCurrentRange(), minResistanceRange(), and minVoltageRange().
minResistanceRange()
quint8 DeviceCommand::minResistanceRange (const PokitProduct product, const quint32 maxValue) static protected
Returns the product's lowest resistance range that can measure at least up to maxValue (), or AutoRange if no such range is available.
See also
DeviceCommand::minRange<PokitMeter::ResistanceRange>(const quint32 maxValue)
minRange<PokitPro::ResistanceRange>(const quint32 maxValue)
Definition at line 252 of file devicecommand.cpp.
{
    switch (product) {
    case PokitProduct::PokitMeter:
        return +minRange<PokitMeter::ResistanceRange>(maxValue);
    case PokitProduct::PokitPro:
        return +minRange<PokitPro::ResistanceRange>(maxValue);
    }
    Q_ASSERT_X(false, "DeviceCommand::minResistanceRange", "Unknown PokitProduct enum value");
    return 255;
}
References minRange(), PokitMeter, and PokitPro.
Referenced by MeterCommand::processOptions().
minVoltageRange()
quint8 DeviceCommand::minVoltageRange (const PokitProduct product, const quint32 maxValue) static protected
t Returns the product's lowest voltage range that can measure at least up to maxValue (mV), or AutoRange if no such range is available.
See also
DeviceCommand::minRange<PokitMeter::VoltageRange>(const quint32 maxValue)
minRange<PokitPro::VoltageRange>(const quint32 maxValue)
Definition at line 272 of file devicecommand.cpp.
{
    switch (product) {
    case PokitProduct::PokitMeter:
        return +minRange<PokitMeter::VoltageRange>(maxValue);
    case PokitProduct::PokitPro:
        return +minRange<PokitPro::VoltageRange>(maxValue);
    }
    Q_ASSERT_X(false, "DeviceCommand::minVoltageRange", "Unknown PokitProduct enum value");
    return 255;
}
References minRange(), PokitMeter, and PokitPro.
Referenced by DsoCommand::processOptions(), LoggerStartCommand::processOptions(), and MeterCommand::processOptions().
serviceDetailsDiscovered
void DeviceCommand::serviceDetailsDiscovered () protected virtual slot
Handles service detail discovery events.
This base implementation simply logs the event, and nothing more. Derived classes may (usually do) override this slot to provide their own processing when a services details have been discovered.
Definition at line 331 of file devicecommand.cpp.
{
    qCDebug(lc).noquote() << tr("Service details discovered.");
}
References QObject::tr().
Referenced by deviceDiscovered(), CalibrateCommand::serviceDetailsDiscovered(), DsoCommand::serviceDetailsDiscovered(), FlashLedCommand::serviceDetailsDiscovered(), InfoCommand::serviceDetailsDiscovered(), LoggerFetchCommand::serviceDetailsDiscovered(), LoggerStartCommand::serviceDetailsDiscovered(), LoggerStopCommand::serviceDetailsDiscovered(), MeterCommand::serviceDetailsDiscovered(), and StatusCommand::serviceDetailsDiscovered().
serviceError
void DeviceCommand::serviceError (const QLowEnergyService::ServiceError error) protected virtual slot
Handles service error events.
This base implementation simply logs error and then exits with EXIT_FAILURE. Derived classes may override this slot to implement their own error handing if desired.
Note
As this base class does not construct services (derived classed do), its up to the derived classed to connect this slot to the relevant service's error signal if desired.
Definition at line 320 of file devicecommand.cpp.
{
    qCWarning(lc).noquote() << tr("Bluetooth service error:") << error;
    QCoreApplication::exit(EXIT_FAILURE);
}
References QCoreApplication::exit(), and QObject::tr().
Referenced by deviceDiscovered().
start
bool DeviceCommand::start () override slot
Begins scanning for the Pokit device.
Definition at line 29 of file devicecommand.cpp.
{
    qCInfo(lc).noquote() << ((deviceToScanFor.isNull())
        ? tr("Looking for first available Pokit device...")
        : tr(R"(Looking for device "%1"...)").arg(deviceToScanFor));
    discoveryAgent->start();
    return true;
}
References AbstractCommand::deviceToScanFor, AbstractCommand::discoveryAgent, and QObject::tr().
Member Data Documentation
device
PokitDevice* DeviceCommand::device { nullptr } protected
Pokit Bluetooth device (if any) this command interacts with.
Definition at line 27 of file devicecommand.h.
{ nullptr }; ///< Pokit Bluetooth device (if any) this command interacts with.
Referenced by deviceDiscovered(), deviceDiscoveryFinished(), FlashLedCommand::deviceLedFlashed(), SetNameCommand::deviceNameWritten(), disconnect(), CalibrateCommand::getService(), DsoCommand::getService(), FlashLedCommand::getService(), InfoCommand::getService(), LoggerFetchCommand::getService(), LoggerStartCommand::getService(), LoggerStopCommand::getService(), MeterCommand::getService(), SetNameCommand::getService(), SetTorchCommand::getService(), StatusCommand::getService(), StatusCommand::outputDeviceStatus(), MeterCommand::outputReading(), DsoCommand::outputSamples(), LoggerFetchCommand::outputSamples(), InfoCommand::serviceDetailsDiscovered(), LoggerStartCommand::settingsWritten(), LoggerStopCommand::settingsWritten(), CalibrateCommand::temperatureCalibrated(), and SetTorchCommand::torchStatusWritten().
exitCodeOnDisconnect
int DeviceCommand::exitCodeOnDisconnect { EXIT_FAILURE } protected
Exit code to return on device disconnection.
Definition at line 28 of file devicecommand.h.
{ EXIT_FAILURE }; ///< Exit code to return on device disconnection.
Referenced by deviceDisconnected(), and disconnect().
The documentation for this class was generated from the following files:
devicecommand.h
devicecommand.cpp