QtPokit: MeterCommand Class Reference
MeterCommand Class Reference
The MeterCommand class implements the meter CLI command.
Public Slots
QStringList processOptions (const QCommandLineParser &parser) override
Processes the relevant options from the command line parser.
Public Slots inherited from DeviceCommand
bool start () override
Begins scanning for the Pokit device.
Public Slots inherited from AbstractCommand
virtual QStringList processOptions (const QCommandLineParser &parser)
Processes the relevant options from the command line parser.
virtual bool start ()=0
Begins the functionality of this command, and returns true if begun successfully, false otherwise.
Public Member Functions
MeterCommand (QObject *const parent)
Construct a new MeterCommand object with parent.
QStringList requiredOptions (const QCommandLineParser &parser) const override
Returns a list of CLI option names required by this command.
QStringList supportedOptions (const QCommandLineParser &parser) const override
Returns a list of CLI option names supported by this command.
Public Member Functions inherited from DeviceCommand
DeviceCommand (QObject *const parent)
Construct a new DeviceCommand object with parent.
Public Member Functions inherited from AbstractCommand
AbstractCommand (QObject *const parent)
Constructs a new command with parent.
virtual QStringList requiredOptions (const QCommandLineParser &parser) const
Returns a list of CLI option names required by this command.
virtual QStringList supportedOptions (const QCommandLineParser &parser) const
Returns a list of CLI option names supported by this command.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
virtual void * qt_metacast (const char *)
virtual int qt_metacall (QMetaObject::Call, int, void **)
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Protected Slots
void serviceDetailsDiscovered () override
Handles service detail discovery events.
Protected Slots inherited from DeviceCommand
virtual void controllerError (const QLowEnergyController::Error error)
Handles controller error events.
virtual void deviceDisconnected ()
Handles devics disconnection events.
virtual void serviceError (const QLowEnergyService::ServiceError error)
Handles service error events.
virtual void serviceDetailsDiscovered ()
Handles service detail discovery events.
Protected Slots inherited from AbstractCommand
virtual void deviceDiscovered (const QBluetoothDeviceInfo &info)=0
Handles PokitDiscoveryAgent::pokitDeviceDiscovered signal.
virtual void deviceDiscoveryFinished ()=0
Handles PokitDiscoveryAgent::deviceDiscoveryFinished signal.
Protected Member Functions
AbstractPokitService * getService () override
Returns a Pokit service object for the derived command class.
Protected Member Functions inherited from DeviceCommand
void disconnect (int exitCode=EXIT_SUCCESS)
Disconnects the underlying Pokit device, and sets exitCode to be return to the OS once the disconnection has taken place.
virtual AbstractPokitService * getService ()=0
Returns a Pokit service object for the derived command class.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Private Slots
void settingsWritten ()
Invoked when the multimeter settings have been written, to begin reading the meter values.
void outputReading (const MultimeterService::Reading &reading)
Outputs meter reading in the selected ouput format.
Static Private Member Functions
static MultimeterService::Range lowestRange (const MultimeterService::Mode mode, const quint32 desiredMax)
Returns the lowest mode range that can measure at least up to desired max, or AutoRange if no such range is available.
static MultimeterService::CurrentRange lowestCurrentRange (const quint32 desiredMax)
Returns the lowest current range that can measure at least up to desired max, or AutoRange if no such range is available.
static MultimeterService::ResistanceRange lowestResistanceRange (const quint32 desiredMax)
Returns the lowest resistance range that can measure at least up to desired max, or AutoRange if no such range is available.
static MultimeterService::VoltageRange lowestVoltageRange (const quint32 desiredMax)
Returns the lowest voltage range that can measure at least up to desired max, or AutoRange if no such range is available.
Private Attributes
MultimeterService * service
Bluetooth service this command interracts with.
MultimeterService::Settings settings
Settings for the Pokit device's multimeter mode.
int samplesToGo
Number of samples to read, if specified on the CLI.
Friends
class TestMeterCommand
Additional Inherited Members
Public Types inherited from AbstractCommand
enum class OutputFormat { Csv , Json , Text }
Supported output formats.
Static Public Member Functions inherited from AbstractCommand
static QString escapeCsvField (const QString &field)
Returns an RFC 4180 compliant version of field.
static quint32 parseMicroValue (const QString &value, const QString &unit, const quint32 sensibleMinimum=0)
Returns value as a number of micros, such as microseconds, or microvolts.
static quint32 parseMilliValue (const QString &value, const QString &unit, const quint32 sensibleMinimum=0)
Returns value as a number of millis, such as milliseconds, or millivolts.
static quint32 parseWholeValue (const QString &value, const QString &unit)
Returns value as a number, with optional SI unit prefix, and optional unit suffix.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Static Protected Member Functions inherited from AbstractCommand
static Q_LOGGING_CATEGORY (lc, "pokit.ui.command", QtInfoMsg)
Logging category for UI commands.
Protected Attributes inherited from DeviceCommand
PokitDevice * device
Pokit Bluetooth device (if any) this command inerracts with.
int exitCodeOnDisconnect
Exit code to return on device disconnection.
Protected Attributes inherited from AbstractCommand
QString deviceToScanFor
Device (if any) that were passed to processOptions().
PokitDiscoveryAgent * discoveryAgent
Agent for Pokit device descovery.
OutputFormat format
Selected output format.
Properties inherited from QObject
objectName
Detailed Description
The MeterCommand class implements the meter CLI command.
Definition at line 8 of file metercommand.h.
Constructor & Destructor Documentation
MeterCommand()
MeterCommand::MeterCommand (QObject *const parent) explicit
Construct a new MeterCommand object with parent.
Definition at line 20 of file metercommand.cpp.
                                                 : DeviceCommand(parent),
    service(nullptr), settings{
        MultimeterService::Mode::DcVoltage,
        { MultimeterService::VoltageRange::AutoRange },
        1000
    }, samplesToGo(-1)
{
}
References MultimeterService::AutoRange.
Member Function Documentation
getService()
AbstractPokitService * MeterCommand::getService () override protected virtual
Returns a Pokit service object for the derived command class.
This override returns a pointer to a MultimeterService object.
Implements DeviceCommand.
Definition at line 154 of file metercommand.cpp.
{
    Q_ASSERT(device);
    if (!service) {
        service = device->multimeter();
        Q_ASSERT(service);
        connect(service, &MultimeterService::settingsWritten,
                this, &MeterCommand::settingsWritten);
    }
    return service;
}
References QObject::connect(), DeviceCommand::device, PokitDevice::multimeter(), service, MultimeterService::settingsWritten(), and settingsWritten().
lowestCurrentRange()
MultimeterService::CurrentRange MeterCommand::lowestCurrentRange (const quint32 desiredMax) static private
Returns the lowest current range that can measure at least up to desired max, or AutoRange if no such range is available.
Definition at line 217 of file metercommand.cpp.
{
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, CurrentRange::_0_to_10mA)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, CurrentRange::_10mA_to_30mA)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, CurrentRange::_30mA_to_150mA)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, CurrentRange::_150mA_to_300mA)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, CurrentRange::_300mA_to_3A)
    return MultimeterService::CurrentRange::AutoRange;
}
References MultimeterService::AutoRange.
Referenced by lowestRange().
lowestRange()
MultimeterService::Range MeterCommand::lowestRange (const MultimeterService::Mode mode, const quint32 desiredMax) static private
Returns the lowest mode range that can measure at least up to desired max, or AutoRange if no such range is available.
Definition at line 185 of file metercommand.cpp.
{
    MultimeterService::Range range;
    switch (mode) {
    case MultimeterService::Mode::DcVoltage:
    case MultimeterService::Mode::AcVoltage:
        range.voltageRange = lowestVoltageRange(desiredMax);
        break;
    case MultimeterService::Mode::DcCurrent:
    case MultimeterService::Mode::AcCurrent:
        range.currentRange = lowestCurrentRange(desiredMax);
        break;
    case MultimeterService::Mode::Resistance:
        range.resistanceRange = lowestResistanceRange(desiredMax);
        break;
    default:
        qCWarning(lc).noquote() << tr("Mode does not support range.");
        range.voltageRange = MultimeterService::VoltageRange::AutoRange;
    }
    return range;
}
References MultimeterService::AcCurrent, MultimeterService::AcVoltage, MultimeterService::AutoRange, MultimeterService::Range::currentRange, MultimeterService::DcCurrent, MultimeterService::DcVoltage, lowestCurrentRange(), lowestResistanceRange(), lowestVoltageRange(), MultimeterService::Resistance, MultimeterService::Range::resistanceRange, QObject::tr(), and MultimeterService::Range::voltageRange.
Referenced by processOptions().
lowestResistanceRange()
MultimeterService::ResistanceRange MeterCommand::lowestResistanceRange (const quint32 desiredMax) static private
Returns the lowest resistance range that can measure at least up to desired max, or AutoRange if no such range is available.
Definition at line 231 of file metercommand.cpp.
{
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, ResistanceRange::_0_to_160)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, ResistanceRange::_160_to_330)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, ResistanceRange::_330_to_890)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, ResistanceRange::_890_to_1K5)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, ResistanceRange::_1K5_to_10K)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, ResistanceRange::_10K_to_100K)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, ResistanceRange::_100K_to_470K)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, ResistanceRange::_470K_to_1M)
    return MultimeterService::ResistanceRange::AutoRange;
}
References MultimeterService::AutoRange.
Referenced by lowestRange().
lowestVoltageRange()
MultimeterService::VoltageRange MeterCommand::lowestVoltageRange (const quint32 desiredMax) static private
Returns the lowest voltage range that can measure at least up to desired max, or AutoRange if no such range is available.
Definition at line 248 of file metercommand.cpp.
{
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_0_to_300mV)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_300mV_to_2V)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_2V_to_6V)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_6V_to_12V)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_12V_to_30V)
    POKIT_APP_IF_LESS_THAN_RETURN(desiredMax, VoltageRange::_30V_to_60V)
    return MultimeterService::VoltageRange::AutoRange;
}
References MultimeterService::AutoRange.
Referenced by lowestRange().
outputReading
void MeterCommand::outputReading (const MultimeterService::Reading & reading) private slot
Outputs meter reading in the selected ouput format.
Definition at line 275 of file metercommand.cpp.
{
    QString status;
    if (reading.status == MultimeterService::MeterStatus::Error) {
        status = QLatin1String("Error");
    } else switch (reading.mode) {
    case MultimeterService::Mode::Idle:
        break;
    case MultimeterService::Mode::DcVoltage:
    case MultimeterService::Mode::AcVoltage:
    case MultimeterService::Mode::DcCurrent:
    case MultimeterService::Mode::AcCurrent:
    case MultimeterService::Mode::Resistance:
        status = (reading.status == MultimeterService::MeterStatus::AutoRangeOn)
            ? tr("Auto Range On") : tr("Auto Range Off");
        break;
    case MultimeterService::Mode::Continuity:
        status = (reading.status == MultimeterService::MeterStatus::Continuity)
            ? tr("Continuity") : tr("No continuity");
        break;
    case MultimeterService::Mode::Temperature:
    case MultimeterService::Mode::Diode:
        status = tr("Ok");
        break;
    }
    QString units;
    switch (reading.mode) {
    case MultimeterService::Mode::Idle:        break;
    case MultimeterService::Mode::DcVoltage:   units = QLatin1String("Vdc"); break;
    case MultimeterService::Mode::AcVoltage:   units = QLatin1String("Vac"); break;
    case MultimeterService::Mode::DcCurrent:   units = QLatin1String("Adc"); break;
    case MultimeterService::Mode::AcCurrent:   units = QLatin1String("Aac"); break;
    case MultimeterService::Mode::Resistance:  units = QString::fromUtf8(""); break;
    case MultimeterService::Mode::Diode:       break;
    case MultimeterService::Mode::Continuity:  break;
    case MultimeterService::Mode::Temperature: units = QString::fromUtf8("C"); break;
    }
    QString range;
    QVariant rangeMin, rangeMax;
    switch (reading.mode) {
    case MultimeterService::Mode::Idle:        break;
    case MultimeterService::Mode::DcVoltage:
    case MultimeterService::Mode::AcVoltage:
        range = MultimeterService::toString(reading.range.voltageRange);
        rangeMin = MultimeterService::minValue(reading.range.voltageRange);
        rangeMax = MultimeterService::maxValue(reading.range.voltageRange);
        break;
    case MultimeterService::Mode::DcCurrent:
    case MultimeterService::Mode::AcCurrent:
        range = MultimeterService::toString(reading.range.currentRange);
        rangeMin = MultimeterService::minValue(reading.range.currentRange);
        rangeMax = MultimeterService::maxValue(reading.range.currentRange);
        break;
    case MultimeterService::Mode::Resistance:
        range = MultimeterService::toString(reading.range.resistanceRange);
        rangeMin = MultimeterService::minValue(reading.range.resistanceRange);
        rangeMax = MultimeterService::maxValue(reading.range.resistanceRange);
        break;
    case MultimeterService::Mode::Diode:       break;
    case MultimeterService::Mode::Continuity:  break;
    case MultimeterService::Mode::Temperature: break;
    }
    switch (format) {
    case OutputFormat::Csv:
        for (static bool firstTime = true; firstTime; firstTime = false) {
            fputs(qPrintable(tr("mode,value,units,status,range_min_milli,range_max_milli\n")), stdout);
        }
        fputs(qPrintable(QString::fromLatin1("%1,%2,%3,%4,%5,%6\n")
            .arg(escapeCsvField(MultimeterService::toString(reading.mode)))
            .arg(reading.value, 0, 'f').arg(units, status, rangeMin.toString(), rangeMax.toString())
            ), stdout);
        break;
    case OutputFormat::Json: {
        QJsonObject jsonObject{
            { QLatin1String("status"), status },
            { QLatin1String("value"), qIsInf(reading.value) ?
                QJsonValue(tr("Infinity")) : QJsonValue(reading.value) },
            { QLatin1String("mode"),   MultimeterService::toString(reading.mode) },
        };
        if ((!rangeMin.isNull()) || (!rangeMax.isNull())) {
            jsonObject.insert(QLatin1String("range"), QJsonObject{
                { QLatin1String("min"),
                    #if (QT_VERSION >= QT_VERSION_CHECK(6, 0, 0))
                    (rangeMin.typeId() == QMetaType::Int)
                    #else
                    (rangeMin.type() == QVariant::Int)
                    #endif
                    ? QJsonValue(rangeMin.toInt()/1000.0) : rangeMin.toJsonValue() },
                { QLatin1String("max"),
                    #if (QT_VERSION >= QT_VERSION_CHECK(6, 0, 0))
                    (rangeMax.typeId() == QMetaType::Int) ?
                    #else
                    (rangeMax.type() == QVariant::Int) ?
                    #endif
                    QJsonValue(rangeMax.toInt()/1000.0) : rangeMax.toJsonValue() },
            });
        }
        fputs(QJsonDocument(jsonObject).toJson(), stdout);
    }   break;
    case OutputFormat::Text:
        fputs(qPrintable(tr("Mode:   %1 (0x%2)\n").arg(MultimeterService::toString(reading.mode))
            .arg((quint8)reading.mode,2,16,QLatin1Char('0'))), stdout);
        fputs(qPrintable(tr("Value:  %1 %2\n").arg(reading.value,0,'f').arg(units)), stdout);
        fputs(qPrintable(tr("Status: %1 (0x%2)\n").arg(status)
            .arg((quint8)reading.status,2,16,QLatin1Char('0'))), stdout);
        fputs(qPrintable(tr("Range:  %1 (0x%2)\n").arg(range)
            .arg((quint8)reading.range.voltageRange,2,16,QLatin1Char('0'))), stdout);
        break;
    }
    if ((samplesToGo > 0) && (--samplesToGo == 0)) {
        disconnect(); // Will exit the application once disconnected.
    }
}
References MultimeterService::AcCurrent, MultimeterService::AcVoltage, QString::arg(), MultimeterService::AutoRangeOn, MultimeterService::Continuity, AbstractCommand::Csv, MultimeterService::Range::currentRange, MultimeterService::DcCurrent, MultimeterService::DcVoltage, MultimeterService::Diode, DeviceCommand::disconnect(), MultimeterService::Error, AbstractCommand::escapeCsvField(), AbstractCommand::format, QString::fromLatin1(), QString::fromUtf8(), MultimeterService::Idle, QString::insert(), QVariant::isNull(), AbstractCommand::Json, MultimeterService::maxValue(), MultimeterService::minValue(), MultimeterService::Reading::mode, MultimeterService::Reading::range, MultimeterService::Resistance, MultimeterService::Range::resistanceRange, samplesToGo, MultimeterService::Reading::status, MultimeterService::Temperature, AbstractCommand::Text, QVariant::toInt(), QVariant::toJsonValue(), QVariant::toString(), MultimeterService::toString(), QObject::tr(), QVariant::type(), MultimeterService::Reading::value, and MultimeterService::Range::voltageRange.
Referenced by settingsWritten().
processOptions
QStringList MeterCommand::processOptions (const QCommandLineParser & parser) override slot
Processes the relevant options from the command line parser.
This implementation extends DeviceCommand::processOptions to process additional CLI options supported (or required) by this command.
Definition at line 52 of file metercommand.cpp.
{
    QStringList errors = DeviceCommand::processOptions(parser);
    if (!errors.isEmpty()) {
        return errors;
    }
    // Parse the (required) mode option.
    const QString mode = parser.value(QLatin1String("mode")).trimmed().toLower();
    if (mode.startsWith(QLatin1String("ac v")) || mode.startsWith(QLatin1String("vac"))) {
        settings.mode = MultimeterService::Mode::AcVoltage;
    } else if (mode.startsWith(QLatin1String("dc v")) || mode.startsWith(QLatin1String("vdc"))) {
        settings.mode = MultimeterService::Mode::DcVoltage;
    } else if (mode.startsWith(QLatin1String("ac c")) || mode.startsWith(QLatin1String("aac"))) {
        settings.mode = MultimeterService::Mode::AcCurrent;
    } else if (mode.startsWith(QLatin1String("dc c")) || mode.startsWith(QLatin1String("adc"))) {
        settings.mode = MultimeterService::Mode::DcCurrent;
    } else if (mode.startsWith(QLatin1String("res"))) {
        settings.mode = MultimeterService::Mode::Resistance;
    } else if (mode.startsWith(QLatin1String("dio"))) {
        settings.mode = MultimeterService::Mode::Diode;
    } else if (mode.startsWith(QLatin1String("cont"))) {
       settings.mode = MultimeterService::Mode::Continuity;
    } else if (mode.startsWith(QLatin1String("temp"))) {
       settings.mode = MultimeterService::Mode::Temperature;
    } else {
        errors.append(tr("Unknown meter mode: %1").arg(parser.value(QLatin1String("mode"))));
        return errors;
    }
    // Parse the interval option.
    if (parser.isSet(QLatin1String("interval"))) {
        const QString value = parser.value(QLatin1String("interval"));
        const quint32 interval = parseMilliValue(value, QLatin1String("s"), 500);
        if (interval == 0) {
            errors.append(tr("Invalid interval value: %1").arg(value));
        } else {
            settings.updateInterval = interval;
        }
    }
    // Parse the range option.
    if (parser.isSet(QLatin1String("range"))) {
        const QString value = parser.value(QLatin1String("range"));
        const bool isAuto = (value.trimmed().compare(QLatin1String("auto"), Qt::CaseInsensitive) == 0);
        QString unit; quint32 sensibleMinimum = 0;
        switch (settings.mode) {
        case MultimeterService::Mode::DcVoltage:
        case MultimeterService::Mode::AcVoltage:
            if (isAuto) {
                settings.range.voltageRange = MultimeterService::VoltageRange::AutoRange;
            }
            unit = QLatin1String("V");
            sensibleMinimum = 50; // mV.
            break;
        case MultimeterService::Mode::DcCurrent:
        case MultimeterService::Mode::AcCurrent:
            if (isAuto) {
                settings.range.currentRange = MultimeterService::CurrentRange::AutoRange;
            }
            unit = QLatin1String("A");
            sensibleMinimum = 5; // mA.
            break;
        case MultimeterService::Mode::Resistance:
            if (isAuto) {
                settings.range.resistanceRange = MultimeterService::ResistanceRange::AutoRange;
            }
            unit = QLatin1String("ohms");
            sensibleMinimum = 0; // Unused.
            break;
        default:
            qCInfo(lc).noquote() << tr("Ignoring range value: %1").arg(value);
        }
        if ((!unit.isEmpty()) && (!isAuto)) { // isEmpty indicates a mode that has no range option.
            const quint32 rangeMax = (sensibleMinimum == 0)
                ? parseWholeValue(value, unit) : parseMilliValue(value, unit, sensibleMinimum);
            if (rangeMax == 0) {
                errors.append(tr("Invalid range value: %1").arg(value));
            } else {
                settings.range = lowestRange(settings.mode, rangeMax);
            }
        }
    }
    // Parse the samples option.
    if (parser.isSet(QLatin1String("samples"))) {
        const QString value = parser.value(QLatin1String("samples"));
        const quint32 samples = parseWholeValue(value, QLatin1String("S"));
        if (samples == 0) {
            errors.append(tr("Invalid samples value: %1").arg(value));
        } else {
            samplesToGo = samples;
        }
    }
    return errors;
}
References MultimeterService::AcCurrent, MultimeterService::AcVoltage, QList::append(), QString::arg(), MultimeterService::AutoRange, QString::compare(), MultimeterService::Continuity, MultimeterService::Range::currentRange, MultimeterService::DcCurrent, MultimeterService::DcVoltage, MultimeterService::Diode, QString::isEmpty(), QList::isEmpty(), QCommandLineParser::isSet(), lowestRange(), MultimeterService::Settings::mode, AbstractCommand::parseMilliValue(), AbstractCommand::parseWholeValue(), AbstractCommand::processOptions(), MultimeterService::Settings::range, MultimeterService::Resistance, MultimeterService::Range::resistanceRange, samplesToGo, settings, QString::startsWith(), MultimeterService::Temperature, QString::toLower(), QObject::tr(), QString::trimmed(), MultimeterService::Settings::updateInterval, QCommandLineParser::value(), and MultimeterService::Range::voltageRange.
requiredOptions()
QStringList MeterCommand::requiredOptions (const QCommandLineParser & parser) const override virtual
Returns a list of CLI option names required by this command.
The main console appication may use this list to output an eror (and exit) if any of the returned names are not found in the parsed CLI options.
The (already parsed) parser may be used adjust the returned required options depending on the value of other options. For example, the logger command only requires the --mode option if the --command option is start.
This base implementation simply returns an empty list. Derived classes should override this function to include any required options.
Reimplemented from AbstractCommand.
Definition at line 30 of file metercommand.cpp.
{
    return DeviceCommand::requiredOptions(parser) + QStringList{
        QLatin1String("mode"),
    };
}
References AbstractCommand::requiredOptions().
serviceDetailsDiscovered
void MeterCommand::serviceDetailsDiscovered () override protected slot
Handles service detail discovery events.
This override fetches the current device's status, and outputs it in the selected format.
Definition at line 171 of file metercommand.cpp.
{
    DeviceCommand::serviceDetailsDiscovered(); // Just logs consistently.
    const QString range = MultimeterService::toString(settings.range, settings.mode);
    qCInfo(lc).noquote() << tr("Measuring %1, with range %2, every %L3ms.").arg(
        MultimeterService::toString(settings.mode),
        (range.isNull()) ? QString::fromLatin1("N/A") : range).arg(settings.updateInterval);
    service->setSettings(settings);
}
References QString::arg(), QString::fromLatin1(), QString::isNull(), MultimeterService::Settings::mode, MultimeterService::Settings::range, service, DeviceCommand::serviceDetailsDiscovered(), MultimeterService::setSettings(), settings, MultimeterService::toString(), QObject::tr(), and MultimeterService::Settings::updateInterval.
settingsWritten
void MeterCommand::settingsWritten () private slot
Invoked when the multimeter settings have been written, to begin reading the meter values.
Definition at line 264 of file metercommand.cpp.
{
    qCDebug(lc).noquote() << tr("Settings written; starting meter readings...");
    connect(service, &MultimeterService::readingRead,
            this, &MeterCommand::outputReading);
    service->enableReadingNotifications();
}
References QObject::connect(), MultimeterService::enableReadingNotifications(), outputReading(), MultimeterService::readingRead(), service, and QObject::tr().
Referenced by getService().
supportedOptions()
QStringList MeterCommand::supportedOptions (const QCommandLineParser & parser) const override virtual
Returns a list of CLI option names supported by this command.
The main console appication may use this list to output a warning for any parsed CLI options not included in the returned list.
The (already parsed) parser may be used adjust the returned supported options depending on the value of other options. For example, the logger command only supported the --timestamp option if the --command option is start.
This base implementation simply returns requiredOptions(). Derived classes should override this function to include optional options, such as:
QStringList Derived::supportedOptions(const QCommandLineParser &parser) const
{
    const QStringList list = AbstractCommand::supportedOptions(parser) + QStringList{ ... };
    list.sort();
    list.removeDuplicates(); // Optional, recommended.
    return list;
}
Reimplemented from AbstractCommand.
Definition at line 37 of file metercommand.cpp.
{
    return DeviceCommand::supportedOptions(parser) + QStringList{
        QLatin1String("interval"),
        QLatin1String("range"),
        QLatin1String("samples"),
    };
}
References AbstractCommand::supportedOptions().
Friends And Related Function Documentation
TestMeterCommand
friend class TestMeterCommand friend
Definition at line 39 of file metercommand.h.
Member Data Documentation
samplesToGo
int MeterCommand::samplesToGo private
Number of samples to read, if specified on the CLI.
Definition at line 28 of file metercommand.h.
Referenced by outputReading(), and processOptions().
service
MultimeterService* MeterCommand::service private
Bluetooth service this command interracts with.
Definition at line 26 of file metercommand.h.
Referenced by getService(), serviceDetailsDiscovered(), and settingsWritten().
settings
MultimeterService::Settings MeterCommand::settings private
Settings for the Pokit device's multimeter mode.
Definition at line 27 of file metercommand.h.
Referenced by processOptions(), and serviceDetailsDiscovered().
The documentation for this class was generated from the following files:
metercommand.h
metercommand.cpp