QtPokit: PokitDeviceDiscoveryAgentPrivate Class Reference
PokitDeviceDiscoveryAgentPrivate Class Reference
The PokitDeviceDiscoveryAgentPrivate class provides private implementation for PokitDeviceDiscoveryAgent.
Public Slots
void deviceDiscovered (const QBluetoothDeviceInfo &info)
Handle deviceDiscovered signals.
void deviceUpdated (const QBluetoothDeviceInfo &info, QBluetoothDeviceInfo::Fields updatedFields)
Handle deviceUpdated signals.
Public Member Functions
PokitDeviceDiscoveryAgentPrivate (PokitDeviceDiscoveryAgent *const q)
Protected Attributes
PokitDeviceDiscoveryAgent * q_ptr
Internal q-pointer.
Friends
class TestPokitDeviceDiscoveryAgent
Detailed Description
The PokitDeviceDiscoveryAgentPrivate class provides private implementation for PokitDeviceDiscoveryAgent.
Definition at line 34 of file pokitdevicedisoveryagent_p.h.
Constructor & Destructor Documentation
PokitDeviceDiscoveryAgentPrivate()
PokitDeviceDiscoveryAgentPrivate::PokitDeviceDiscoveryAgentPrivate (PokitDeviceDiscoveryAgent *const q) explicit
Constructs a new PokitDeviceDiscoveryAgentPrivate object with public implementation q.
Definition at line 154 of file pokitdevicedisoveryagent.cpp.
    : q_ptr(q)
{
    connect(q, &QBluetoothDeviceDiscoveryAgent::deviceDiscovered,
            this, &PokitDeviceDiscoveryAgentPrivate::deviceDiscovered);
    #if (QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)) // Signal added in Qt 5.12.
    connect(q, &QBluetoothDeviceDiscoveryAgent::deviceUpdated,
            this, &PokitDeviceDiscoveryAgentPrivate::deviceUpdated);
    #endif
}
References deviceDiscovered(), and deviceUpdated().
Member Function Documentation
deviceDiscovered
void PokitDeviceDiscoveryAgentPrivate::deviceDiscovered (const QBluetoothDeviceInfo & info) slot
Handle deviceDiscovered signals.
Here we simply check if info describes a Pokit device, and if so, emit pokitDeviceDiscovered().
Definition at line 171 of file pokitdevicedisoveryagent.cpp.
{
    Q_Q(PokitDeviceDiscoveryAgent);
    if (!q->isPokitDevice(info)) return;
    qCDebug(pokitDiscovery) << "Discovered Pokit device" << info.name() << info.address();
    emit q->pokitDeviceDiscovered(info);
}
Referenced by PokitDeviceDiscoveryAgentPrivate().
deviceUpdated
void PokitDeviceDiscoveryAgentPrivate::deviceUpdated (const QBluetoothDeviceInfo & info, QBluetoothDeviceInfo::Fields updatedFields) slot
Handle deviceUpdated signals.
Here we simply check if info describes a Pokit device, and if so, emit pokitDeviceUpdated().
Since
Qt 5.12.0
Definition at line 187 of file pokitdevicedisoveryagent.cpp.
{
    Q_Q(PokitDeviceDiscoveryAgent);
    if (!q->isPokitDevice(info)) return;
    qCDebug(pokitDiscovery) << "Updated Pokit device" << info.name() << info.address() << info.rssi();
    emit q->pokitDeviceUpdated(info, updatedFields);
}
Referenced by PokitDeviceDiscoveryAgentPrivate().
Friends And Related Function Documentation
TestPokitDeviceDiscoveryAgent
friend class TestPokitDeviceDiscoveryAgent friend
Definition at line 53 of file pokitdevicedisoveryagent_p.h.
Member Data Documentation
q_ptr
PokitDeviceDiscoveryAgent* PokitDeviceDiscoveryAgentPrivate::q_ptr protected
Internal q-pointer.
Definition at line 48 of file pokitdevicedisoveryagent_p.h.
The documentation for this class was generated from the following files:
pokitdevicedisoveryagent_p.h
pokitdevicedisoveryagent.cpp