QtPokit: DataLoggerService Class Reference
DataLoggerService Class Reference
The DataLoggerService class accesses the Pokit Status service of Pokit devices.
Classes
struct CharacteristicUuids
Characteristics available via the DataLogger service.
struct Metadata
Attributes included in the Metadata characterstic.
union Range
Values supported by the Range attribute of the Settings and Metadata characteristics.
struct Settings
Attributes included in the Settings characterstic.
Public Types
enum class Command : quint8 { Start = 0 , Stop = 1 , Refresh = 2 }
Values supported by the Command attribute of the Settings characteristic.
enum class Mode : quint8 {
Idle = 0 , DcVoltage = 1 , AcVoltage = 2 , DcCurrent = 3 ,
AcCurrent = 4
}
Values supported by the Mode attribute of the Settings and Metadata characteristics.
enum class VoltageRange : quint8 {
_0_to_300mV = 0 , _300mV_to_2V = 1 , _2V_to_6V = 2 , _6V_to_12V = 3 ,
_12V_to_30V = 4 , _30V_to_60V = 5
}
Values supported by the Range attribute of the Settings and Metadata characteristics, when Mode is AC or DC voltage.
enum class CurrentRange : quint8 {
_0_to_10mA = 0 , _10mA_to_30mA = 1 , _30mA_to_150mA = 2 , _150mA_to_300mA = 3 ,
_300mA_to_3A = 4
}
Values supported by the Range attribute of the Settings and Metadata characteristics, when Mode is AC or DC current.
enum class LoggerStatus : quint8 { Done = 0 , Sampling = 1 , BufferFull = 2 , Error = 255 }
Values supported by the Status attribute of the Metadata characteristic.
typedef QVector< qint16 > Samples
Raw samples from the Reading characteristic.
Signals
void settingsWritten ()
This signal is emitted when the Settings characteristic has been written successfully.
void metadataRead (const DataLoggerService::Metadata &meta)
This signal is emitted when the Metadata characteristic has been read successfully.
void samplesRead (const DataLoggerService::Samples &samples)
This signal is emitted when the Reading characteristic has been notified.
Signals inherited from AbstractPokitService
void serviceDetailsDiscovered ()
This signal is emitted when the Pokit service details have been discovered.
void serviceErrorOccurred (QLowEnergyService::ServiceError newError)
This signal is emitted whenever an error occurs on the underlying QLowEnergyService.
Public Member Functions
DataLoggerService (QLowEnergyController *const pokitDevice, QObject *parent=nullptr)
Constructs a new Pokit service with parent.
~DataLoggerService () override
Destroys this DataLoggerService object.
bool readCharacteristics () override
Read all characteristics.
bool readMetadataCharacteristic ()
Reads the DataLogger service's Metadata characteristic.
bool setSettings (const Settings &settings)
Configures the Pokit device's data logger mode.
bool startLogger (const Settings &settings)
Start the data logger with settings.
bool stopLogger ()
Stop the data logger.
bool fetchSamples ()
Start the data logger.
Metadata metadata () const
Returns the most recent value of the DataLogger service's Metadata characteristic.
bool enableMetadataNotifications ()
Enables client-side notifications of Data Logger metadata changes.
bool disableMetadataNotifications ()
Disables client-side notifications of Data Logger metadata changes.
bool enableReadingNotifications ()
Enables client-side notifications of Data Logger readings.
bool disableReadingNotifications ()
Disables client-side notifications of Data Logger readings.
Public Member Functions inherited from AbstractPokitService
virtual ~AbstractPokitService ()
Destroys this AbstractPokitService object.
virtual bool readCharacteristics ()=0
Read all characteristics.
bool autoDiscover () const
Returns true if autodiscovery of services and service details is enabled, false otherwise.
void setAutoDiscover (const bool discover=true)
If discover is true, autodiscovery will be attempted.
QLowEnergyService * service ()
Returns a non-const pointer to the internal service object, if any.
const QLowEnergyService * service () const
Returns a const pointer to the internal service object, if any.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
virtual void * qt_metacast (const char *)
virtual int qt_metacall (QMetaObject::Call, int, void **)
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Static Public Member Functions
static QString toString (const Mode &mode)
Returns mode as a user-friendly string.
static QString toString (const VoltageRange &range)
Returns range as a user-friendly string.
static QVariant minValue (const VoltageRange &range)
Returns the minimum value for range in (integer) millivolts, or null QVariant if range is not valid.
static QVariant maxValue (const VoltageRange &range)
Returns the maximum value for range in (integer) millivolts, or null QVariant if range is not valid.
static QString toString (const CurrentRange &range)
Returns range as a user-friendly string.
static QVariant minValue (const CurrentRange &range)
Returns the minimum value for range in (integer) milliamps, or null QVariant if range is not valid.
static QVariant maxValue (const CurrentRange &range)
Returns the maximum value for range in (integer) milliamps, or null QVariant if range is not valid.
static QString toString (const Range &range, const Mode &mode)
Returns range as a user-friendly string, or a null QString if mode has no ranges.
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Static Public Attributes
static const QBluetoothUuid serviceUuid
UUID of the "DataLogger" service.
Protected Member Functions
DataLoggerService (DataLoggerServicePrivate *const d, QObject *const parent)
Constructs a new Pokit service with parent, and private implementation d.
Protected Member Functions inherited from AbstractPokitService
AbstractPokitService (AbstractPokitServicePrivate *const d, QObject *const parent)
Constructs a new Pokit service with parent, and private implementation d.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Friends
class TestDataLoggerService
Additional Inherited Members
Protected Attributes inherited from AbstractPokitService
AbstractPokitServicePrivate * d_ptr
Internal d-pointer.
Properties inherited from QObject
objectName
Detailed Description
The DataLoggerService class accesses the Pokit Status service of Pokit devices.
Definition at line 22 of file dataloggerservice.h.
Member Typedef Documentation
Samples
DataLoggerService::Samples
Raw samples from the Reading characteristic.
These raw samples are (supposedly) within the range -2048 to +2047, and need to be multiplied by the Metadata::scale value from the Metadata characteristc to get the true values.
Also supposedly, there should be no more than 10 samples at a time, according to Pokit's current API docs. There is not artificial limitation imposed by QtPokit, so devices may begin batching more samples in future. Specifically, the Pokit Pro seems to send 88 samples (in 176 bytes) at a time.
Definition at line 111 of file dataloggerservice.h.
Member Enumeration Documentation
Command
enum class DataLoggerService::Command : quint8 strong
Values supported by the Command attribute of the Settings characteristic.
Definition at line 35 of file dataloggerservice.h.
                       : quint8 {
        Start   = 0,
        Stop    = 1,
        Refresh = 2,
    };
CurrentRange
enum class DataLoggerService::CurrentRange : quint8 strong
Values supported by the Range attribute of the Settings and Metadata characteristics, when Mode is AC or DC current.
Enumerator
_0_to_10mA
0 to 10mA.
_10mA_to_30mA
10mA to 30mA.
_30mA_to_150mA
30mA to 150mA.
_150mA_to_300mA
150mA to 300mA.
_300mA_to_3A
300mA to 3A.
Definition at line 64 of file dataloggerservice.h.
                            : quint8 {
        _0_to_10mA      = 0,  ///< 0 to 10mA.
        _10mA_to_30mA   = 1,  ///< 10mA to 30mA.
        _30mA_to_150mA  = 2,  ///< 30mA to 150mA.
        _150mA_to_300mA = 3,  ///< 150mA to 300mA.
        _300mA_to_3A    = 4,  ///< 300mA to 3A.
        /// \todo Pokit Pro supports up to 10A.
    };
LoggerStatus
enum class DataLoggerService::LoggerStatus : quint8 strong
Values supported by the Status attribute of the Metadata characteristic.
Definition at line 94 of file dataloggerservice.h.
                            : quint8 {
        Done       = 0,
        Sampling   = 1,
        BufferFull = 2,
        Error      = 255
    };
Mode
enum class DataLoggerService::Mode : quint8 strong
Values supported by the Mode attribute of the Settings and Metadata characteristics.
Enumerator
Idle
Make device idle.
DcVoltage
Measure DC voltage.
AcVoltage
Measure AC voltage.
DcCurrent
Measure DC current.
AcCurrent
Measure AC current.
Definition at line 41 of file dataloggerservice.h.
                    : quint8 {
        Idle        = 0, ///< Make device idle.
        DcVoltage   = 1, ///< Measure DC voltage.
        AcVoltage   = 2, ///< Measure AC voltage.
        DcCurrent   = 3, ///< Measure DC current.
        AcCurrent   = 4, ///< Measure AC current.
        /// \todo Pokit Pro supports temperature in logger mode too.
    };
VoltageRange
enum class DataLoggerService::VoltageRange : quint8 strong
Values supported by the Range attribute of the Settings and Metadata characteristics, when Mode is AC or DC voltage.
Enumerator
_0_to_300mV
0 to 300mV.
_300mV_to_2V
300mV to 2V.
_2V_to_6V
2V to 6V.
_6V_to_12V
6V to 12V.
_12V_to_30V
12V to 30V.
_30V_to_60V
30V to 60V.
Definition at line 51 of file dataloggerservice.h.
                            : quint8 {
        _0_to_300mV  = 0,  ///< 0 to 300mV.
        _300mV_to_2V = 1,  ///< 300mV to 2V.
        _2V_to_6V    = 2,  ///< 2V to 6V.
        _6V_to_12V   = 3,  ///< 6V to 12V.
        _12V_to_30V  = 4,  ///< 12V to 30V.
        _30V_to_60V  = 5,  ///< 30V to 60V.
        /// \todo Pokit Pro supports up to 600V, which are enum 6 and 7 via Android app.
    };
Constructor & Destructor Documentation
DataLoggerService() [1/2]
DataLoggerService::DataLoggerService (QLowEnergyController *const pokitDevice, QObject * parent = nullptr)
Constructs a new Pokit service with parent.
Definition at line 281 of file dataloggerservice.cpp.
    : AbstractPokitService(new DataLoggerServicePrivate(controller, this), parent)
{
}
~DataLoggerService()
DataLoggerService::~DataLoggerService () override
Destroys this DataLoggerService object.
Definition at line 302 of file dataloggerservice.cpp.
{
}
DataLoggerService() [2/2]
DataLoggerService::DataLoggerService (DataLoggerServicePrivate *const d, QObject *const parent) protected
Constructs a new Pokit service with parent, and private implementation d.
Definition at line 291 of file dataloggerservice.cpp.
    : AbstractPokitService(d, parent)
{
}
Member Function Documentation
disableMetadataNotifications()
bool DataLoggerService::disableMetadataNotifications ()
Disables client-side notifications of Data Logger metadata changes.
Instantaneous reads can still be fetched by readMetadataCharacteristic().
Returns true is the request was successfully submited to the device queue, false otherwise.
Definition at line 457 of file dataloggerservice.cpp.
{
    Q_D(DataLoggerService);
    return d->disableCharacteristicNotificatons(CharacteristicUuids::metadata);
}
References DataLoggerService::CharacteristicUuids::metadata.
disableReadingNotifications()
bool DataLoggerService::disableReadingNotifications ()
Disables client-side notifications of Data Logger readings.
Returns true is the request was successfully submited to the device queue, false otherwise.
Definition at line 481 of file dataloggerservice.cpp.
{
    Q_D(DataLoggerService);
    return d->disableCharacteristicNotificatons(CharacteristicUuids::reading);
}
References DataLoggerService::CharacteristicUuids::reading.
enableMetadataNotifications()
bool DataLoggerService::enableMetadataNotifications ()
Enables client-side notifications of Data Logger metadata changes.
This is an alternative to manually requesting individual reads via readMetadataCharacteristic().
Returns true is the request was successfully submited to the device queue, false otherwise.
Successfully read values (if any) will be emitted via the metadataRead() signal.
Definition at line 444 of file dataloggerservice.cpp.
{
    Q_D(DataLoggerService);
    return d->enableCharacteristicNotificatons(CharacteristicUuids::metadata);
}
References DataLoggerService::CharacteristicUuids::metadata.
Referenced by LoggerFetchCommand::serviceDetailsDiscovered().
enableReadingNotifications()
bool DataLoggerService::enableReadingNotifications ()
Enables client-side notifications of Data Logger readings.
Returns true is the request was successfully submited to the device queue, false otherwise.
Successfully read samples (if any) will be emitted via the samplesRead() signal.
Definition at line 470 of file dataloggerservice.cpp.
{
    Q_D(DataLoggerService);
    return d->enableCharacteristicNotificatons(CharacteristicUuids::reading);
}
References DataLoggerService::CharacteristicUuids::reading.
Referenced by LoggerFetchCommand::serviceDetailsDiscovered().
fetchSamples()
bool DataLoggerService::fetchSamples ()
Start the data logger.
This is just a convenience function equivalent to calling setSettings() with the command set to DataLoggerService::Command::Refresh.
Once the Pokit device has processed this request succesffully, the device will begin notifying the Metadata and Reading characteristic, resulting in emits of metadataRead and samplesRead respectively.
Definition at line 399 of file dataloggerservice.cpp.
{
    // Note, only the Settings::command member need be set, since the others are all ignored by the
    // Pokit device when the command is Refresh. However, we still explicitly initialise all other
    // members just to ensure we're never exposing uninitialised RAM to an external device.
    return setSettings({
        DataLoggerService::Command::Refresh,
        0, DataLoggerService::Mode::Idle,
        DataLoggerService::VoltageRange::_0_to_300mV, 0, 0
    });
}
References _0_to_300mV, Idle, and setSettings().
Referenced by LoggerFetchCommand::serviceDetailsDiscovered().
maxValue() [1/2]
QVariant DataLoggerService::maxValue (const CurrentRange & range) static
Returns the maximum value for range in (integer) milliamps, or null QVariant if range is not valid.
Definition at line 162 of file dataloggerservice.cpp.
{
    switch (range) {
    case CurrentRange::_0_to_10mA:      return   10;
    case CurrentRange::_10mA_to_30mA:   return   30;
    case CurrentRange::_30mA_to_150mA:  return  150;
    case CurrentRange::_150mA_to_300mA: return  300;
    case CurrentRange::_300mA_to_3A:    return 3000;
    default:                            return QVariant();
    }
}
References _0_to_10mA, _10mA_to_30mA, _150mA_to_300mA, _300mA_to_3A, and _30mA_to_150mA.
maxValue() [2/2]
QVariant DataLoggerService::maxValue (const VoltageRange & range) static
Returns the maximum value for range in (integer) millivolts, or null QVariant if range is not valid.
Definition at line 107 of file dataloggerservice.cpp.
{
    switch (range) {
    case VoltageRange::_0_to_300mV:  return   300;
    case VoltageRange::_300mV_to_2V: return  2000;
    case VoltageRange::_2V_to_6V:    return  6000;
    case VoltageRange::_6V_to_12V:   return 12000;
    case VoltageRange::_12V_to_30V:  return 30000;
    case VoltageRange::_30V_to_60V:  return 60000;
    default:                         return QVariant();
    }
}
References _0_to_300mV, _12V_to_30V, _2V_to_6V, _300mV_to_2V, _30V_to_60V, and _6V_to_12V.
metadata()
DataLoggerService::Metadata DataLoggerService::metadata () const
Returns the most recent value of the DataLogger service's Metadata characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then the returned DataLoggerService::Metadata::scale member will be a quiet NaN, which can be checked like:
const DataLoggerService::Metadata metadata = multimeterService->metadata();
if (qIsNaN(metadata.scale)) {
    // Handle failure.
}
Definition at line 425 of file dataloggerservice.cpp.
{
    Q_D(const DataLoggerService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::metadata);
    return (characteristic.isValid()) ? DataLoggerServicePrivate::parseMetadata(characteristic.value())
        : Metadata{ LoggerStatus::Error, std::numeric_limits<float>::quiet_NaN(),
                    Mode::Idle, VoltageRange::_0_to_300mV, 0, 0, 0 };
}
References _0_to_300mV, Idle, QLowEnergyCharacteristic::isValid(), DataLoggerService::CharacteristicUuids::metadata, DataLoggerServicePrivate::parseMetadata(), and QLowEnergyCharacteristic::value().
metadataRead
DataLoggerService::metadataRead (const DataLoggerService::Metadata & meta) signal
This signal is emitted when the Metadata characteristic has been read successfully.
See also
readMetadataCharacteristic
Referenced by LoggerFetchCommand::getService().
minValue() [1/2]
QVariant DataLoggerService::minValue (const CurrentRange & range) static
Returns the minimum value for range in (integer) milliamps, or null QVariant if range is not valid.
Note, this is an absolute minimum. That is, the true range for DC measurements is from -maxValue(range) to +maxValue(range). In this sense, minValue(range) indicates the magnitude (ignore signs) that can be measured accurately for the given range. As AC current can never be negative, this is relevant for DC current only.
Definition at line 146 of file dataloggerservice.cpp.
{
    switch (range) {
    case CurrentRange::_0_to_10mA:      return   0;
    case CurrentRange::_10mA_to_30mA:   return  10;
    case CurrentRange::_30mA_to_150mA:  return  30;
    case CurrentRange::_150mA_to_300mA: return 150;
    case CurrentRange::_300mA_to_3A:    return 300;
    default:                            return QVariant();
    }
}
References _0_to_10mA, _10mA_to_30mA, _150mA_to_300mA, _300mA_to_3A, and _30mA_to_150mA.
minValue() [2/2]
QVariant DataLoggerService::minValue (const VoltageRange & range) static
Returns the minimum value for range in (integer) millivolts, or null QVariant if range is not valid.
Note, this is an absolute minimum. That is, the true range for DC measurements is from -maxValue(range) to +maxValue(range). In this sense, minValue(range) indicates the magnitude (ignore signs) that can be measured accurately for the given range. As AC voltage can never be negative, this is relevant for DC voltage only.
Definition at line 90 of file dataloggerservice.cpp.
{
    switch (range) {
    case VoltageRange::_0_to_300mV:  return     0;
    case VoltageRange::_300mV_to_2V: return   300;
    case VoltageRange::_2V_to_6V:    return  2000;
    case VoltageRange::_6V_to_12V:   return  6000;
    case VoltageRange::_12V_to_30V:  return 12000;
    case VoltageRange::_30V_to_60V:  return 30000;
    default:                         return QVariant();
    }
}
References _0_to_300mV, _12V_to_30V, _2V_to_6V, _300mV_to_2V, _30V_to_60V, and _6V_to_12V.
readCharacteristics()
bool DataLoggerService::readCharacteristics () override virtual
Read all characteristics.
This convenience function will queue refresh requests of all characteristics supported by this service.
Relevant *Service::*Read signals will be emitted by derived class objects as each characteristic is successfully read.
Implements AbstractPokitService.
Definition at line 307 of file dataloggerservice.cpp.
{
    return readMetadataCharacteristic();
}
References readMetadataCharacteristic().
readMetadataCharacteristic()
bool DataLoggerService::readMetadataCharacteristic ()
Reads the DataLogger service's Metadata characteristic.
Returns true is the read request is succesfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits metadataRead() if/when the characteristic has been read successfully.
Definition at line 321 of file dataloggerservice.cpp.
{
    Q_D(DataLoggerService);
    return d->readCharacteristic(CharacteristicUuids::metadata);
}
References DataLoggerService::CharacteristicUuids::metadata.
Referenced by readCharacteristics().
samplesRead
DataLoggerService::samplesRead (const DataLoggerService::Samples & samples) signal
This signal is emitted when the Reading characteristic has been notified.
See also
beginSampling
stopSampling
Referenced by LoggerFetchCommand::getService().
setSettings()
bool DataLoggerService::setSettings (const Settings & settings)
Configures the Pokit device's data logger mode.
Returns true if the write request was successfully queued, false otherwise.
Emits settingsWritten() if/when the settings have been writtem successfully.
Definition at line 334 of file dataloggerservice.cpp.
{
    Q_D(const DataLoggerService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::settings);
    if (!characteristic.isValid()) {
        return false;
    }
    const bool updateIntervalIs32bit =
        (d->getCharacteristic(CharacteristicUuids::metadata).value().size() >= 23);
    const QByteArray value = d->encodeSettings(settings, updateIntervalIs32bit);
    if (value.isNull()) {
        return false;
    }
    d->service->writeCharacteristic(characteristic, value);
    return (d->service->error() != QLowEnergyService::ServiceError::CharacteristicWriteError);
}
References QByteArray::isNull(), QLowEnergyCharacteristic::isValid(), DataLoggerService::CharacteristicUuids::metadata, and DataLoggerService::CharacteristicUuids::settings.
Referenced by fetchSamples(), LoggerStartCommand::serviceDetailsDiscovered(), startLogger(), and stopLogger().
settingsWritten
DataLoggerService::settingsWritten () signal
This signal is emitted when the Settings characteristic has been written successfully.
See also
setSettings
Referenced by LoggerStartCommand::getService(), and LoggerStopCommand::getService().
startLogger()
bool DataLoggerService::startLogger (const Settings & settings)
Start the data logger with settings.
This is just a synonym for setSettings() except makes the caller's intention more explicit, and sanity-checks that the settings's command is DataLoggerService::Command::Start.
Definition at line 360 of file dataloggerservice.cpp.
{
    Q_D(const DataLoggerService);
    Q_ASSERT(settings.command == DataLoggerService::Command::Start);
    if (settings.command != DataLoggerService::Command::Start) {
        qCWarning(d->lc).noquote() << tr("Settings command must be 'Start'.");
        return false;
    }
    return setSettings(settings);
}
References DataLoggerService::Settings::command, setSettings(), and QObject::tr().
stopLogger()
bool DataLoggerService::stopLogger ()
Stop the data logger.
This is just a convenience function equivalent to calling setSettings() with the command set to DataLoggerService::Command::Stop.
Definition at line 377 of file dataloggerservice.cpp.
{
    // Note, only the Settings::command member need be set, since the others are all ignored by the
    // Pokit device when the command is Stop. However, we still explicitly initialise all other
    // members just to ensure we're never exposing uninitialised RAM to an external device.
    return setSettings({
        DataLoggerService::Command::Stop,
        0, DataLoggerService::Mode::Idle,
        DataLoggerService::VoltageRange::_0_to_300mV, 0, 0
    });
}
References _0_to_300mV, Idle, and setSettings().
Referenced by LoggerStopCommand::serviceDetailsDiscovered().
toString() [1/4]
QString DataLoggerService::toString (const CurrentRange & range) static
Returns range as a user-friendly string.
Definition at line 125 of file dataloggerservice.cpp.
{
    switch (range) {
    case CurrentRange::_0_to_10mA:      return tr("0 to 10mA");
    case CurrentRange::_10mA_to_30mA:   return tr("10mA to 30mA");
    case CurrentRange::_30mA_to_150mA:  return tr("30mA to 150mA");
    case CurrentRange::_150mA_to_300mA: return tr("150mA to 300mA");
    case CurrentRange::_300mA_to_3A:    return tr("300mA to 3A");
    default:                            return QString();
    }
}
References _0_to_10mA, _10mA_to_30mA, _150mA_to_300mA, _300mA_to_3A, _30mA_to_150mA, and QObject::tr().
toString() [2/4]
QString DataLoggerService::toString (const Mode & mode) static
Returns mode as a user-friendly string.
Definition at line 51 of file dataloggerservice.cpp.
{
    switch (mode) {
    case Mode::Idle:        return tr("Idle");
    case Mode::DcVoltage:   return tr("DC voltage");
    case Mode::AcVoltage:   return tr("AC voltage");
    case Mode::DcCurrent:   return tr("DC current");
    case Mode::AcCurrent:   return tr("AC current");
    default:                return QString();
    }
}
References AcCurrent, AcVoltage, DcCurrent, DcVoltage, Idle, and QObject::tr().
Referenced by LoggerFetchCommand::metadataRead(), LoggerFetchCommand::outputSamples(), LoggerStartCommand::serviceDetailsDiscovered(), and toString().
toString() [3/4]
QString DataLoggerService::toString (const Range & range, const Mode & mode) static
Returns range as a user-friendly string, or a null QString if mode has no ranges.
Definition at line 200 of file dataloggerservice.cpp.
{
    switch (mode) {
    case Mode::DcVoltage:
    case Mode::AcVoltage:
        return toString(range.voltageRange);
    case Mode::DcCurrent:
    case Mode::AcCurrent:
        return toString(range.currentRange);
    default:
        return QString();
    }
}
References AcCurrent, AcVoltage, DataLoggerService::Range::currentRange, DcCurrent, DcVoltage, toString(), and DataLoggerService::Range::voltageRange.
toString() [4/4]
QString DataLoggerService::toString (const VoltageRange & range) static
Returns range as a user-friendly string.
Definition at line 68 of file dataloggerservice.cpp.
{
    switch (range) {
    case VoltageRange::_0_to_300mV:  return tr("0 to 300mV");
    case VoltageRange::_300mV_to_2V: return tr("300mV to 2V");
    case VoltageRange::_2V_to_6V:    return tr("2V to 6V");
    case VoltageRange::_6V_to_12V:   return tr("6V to 12V");
    case VoltageRange::_12V_to_30V:  return tr("12V to 30V");
    case VoltageRange::_30V_to_60V:  return tr("30V to 60V");
    default:                         return QString();
    }
}
References _0_to_300mV, _12V_to_30V, _2V_to_6V, _300mV_to_2V, _30V_to_60V, _6V_to_12V, and QObject::tr().
Friends And Related Function Documentation
TestDataLoggerService
friend class TestDataLoggerService friend
Definition at line 147 of file dataloggerservice.h.
Member Data Documentation
serviceUuid
const QBluetoothUuid DataLoggerService::serviceUuid static
UUID of the "DataLogger" service.
Definition at line 27 of file dataloggerservice.h.
Referenced by PokitDevice::serviceToString().
The documentation for this class was generated from the following files:
dataloggerservice.h
dataloggerservice.cpp