Dokit: GenericAccessService Class Reference
GenericAccessService Class Reference
The GenericAccessService class accesses the Generic Access service of Pokit devices.
Classes
struct CharacteristicUuids
Characteristics available via the Generic Access service.
Signals
void appearanceRead (const quint16 appearance)
This signal is emitted when the Appearance characteristic has been read successfully.
void deviceNameRead (const QString &deviceName)
This signal is emitted when the Device Name characteristic has been read successfully.
void deviceNameWritten ()
This signal is emitted when the Device Name characteristic has been written successfully.
Signals inherited from AbstractPokitService
void serviceDetailsDiscovered ()
This signal is emitted when the Pokit service details have been discovered.
void serviceErrorOccurred (QLowEnergyService::ServiceError newError)
This signal is emitted whenever an error occurs on the underlying QLowEnergyService.
Public Member Functions
GenericAccessService (QLowEnergyController *const pokitDevice, QObject *parent=nullptr)
Constructs a new Pokit service with parent.
~GenericAccessService () override
Destroys this GenericAccessService object.
bool readCharacteristics () override
Read all characteristics.
bool readAppearanceCharacteristic ()
Read the Generic Access service's Appearance characteristic.
bool readDeviceNameCharacteristic ()
Read the Generic Access service's Device Name characteristic.
quint16 appearance () const
Returns the most recent value of the Generic Access services's Appearance characteristic.
QString deviceName () const
Returns the most recent value of the Generic Access services's Device Name characteristic.
bool setDeviceName (const QString &name)
Set's the Pokit device's name to name.
Public Member Functions inherited from AbstractPokitService
virtual ~AbstractPokitService ()
Destroys this AbstractPokitService object.
virtual bool readCharacteristics ()=0
Read all characteristics.
bool autoDiscover () const
Returns true if autodiscovery of services and service details is enabled, false otherwise.
void setAutoDiscover (const bool discover=true)
If discover is true, autodiscovery will be attempted.
PokitProduct pokitProduct () const
Returns the Pokit product this service is attached to.
void setPokitProduct (const PokitProduct product)
Sets the current Pokit product.
QLowEnergyService * service ()
Returns a non-const pointer to the internal service object, if any.
const QLowEnergyService * service () const
Returns a const pointer to the internal service object, if any.
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Attributes
static const QBluetoothUuid serviceUuid
UUID of the "Generic Access" service.
Protected Member Functions
GenericAccessService (GenericAccessServicePrivate *const d, QObject *const parent)
Constructs a new Pokit service with parent, and private implementation d.
Protected Member Functions inherited from AbstractPokitService
AbstractPokitService (AbstractPokitServicePrivate *const d, QObject *const parent)
Constructs a new Pokit service with parent, and private implementation d.
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Friends
class TestGenericAccessService
Additional Inherited Members
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Protected Attributes inherited from AbstractPokitService
AbstractPokitServicePrivate * d_ptr
Internal d-pointer.
Properties inherited from QObject
objectName
Detailed Description
The GenericAccessService class accesses the Generic Access service of Pokit devices.
Pokit Bluetooth API errata:
Pokit API 1.00 (and 0.02) claims support for the Generic Access (0x1800) service, however the neither the Pokit Meter, nor the Pokit Pro eport any support for this service, but both report support for an undocumented Generic Attribute (0x1801) service instead.
Definition at line 22 of file genericaccessservice.h.
Constructor & Destructor Documentation
GenericAccessService() [1/2]
GenericAccessService::GenericAccessService (QLowEnergyController *const pokitDevice, QObject * parent = nullptr)
Constructs a new Pokit service with parent.
Definition at line 44 of file genericaccessservice.cpp.
    : AbstractPokitService(new GenericAccessServicePrivate(controller, this), parent)
{
}
~GenericAccessService()
GenericAccessService::~GenericAccessService () override
Destroys this GenericAccessService object.
Definition at line 65 of file genericaccessservice.cpp.
{
}
GenericAccessService() [2/2]
GenericAccessService::GenericAccessService (GenericAccessServicePrivate *const d, QObject *const parent) protected
Constructs a new Pokit service with parent, and private implementation d.
Definition at line 54 of file genericaccessservice.cpp.
    : AbstractPokitService(d, parent)
{
}
Member Function Documentation
appearance()
quint16 GenericAccessService::appearance () const
Returns the most recent value of the Generic Access services's Appearance characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), 0xFFFF is returned.
Note
Pokit's Bluetooth API suggests the device's Appearance will always be 0 aka "Unknown Appearance", so this is probably not a very useful characteristic if you already know you are dealing with a Pokit device.
Definition at line 118 of file genericaccessservice.cpp.
{
    Q_D(const GenericAccessService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::appearance);
    return (characteristic.isValid()) ? GenericAccessServicePrivate::parseAppearance(characteristic.value())
        : std::numeric_limits<quint16>::max();
}
References GenericAccessService::CharacteristicUuids::appearance, QLowEnergyCharacteristic::isValid(), GenericAccessServicePrivate::parseAppearance(), and QLowEnergyCharacteristic::value().
appearanceRead
GenericAccessService::appearanceRead (const quint16 appearance) signal
This signal is emitted when the Appearance characteristic has been read successfully.
See also
readAppearanceCharacteristic
appearance
deviceName()
QString GenericAccessService::deviceName () const
Returns the most recent value of the Generic Access services's Device Name characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then a null QString is returned.
Definition at line 134 of file genericaccessservice.cpp.
{
    Q_D(const GenericAccessService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::deviceName);
    return (characteristic.isValid()) ? QString::fromUtf8(characteristic.value()) : QString();
}
References GenericAccessService::CharacteristicUuids::deviceName, QString::fromUtf8(), QLowEnergyCharacteristic::isValid(), and QLowEnergyCharacteristic::value().
deviceNameRead
GenericAccessService::deviceNameRead (const QString & deviceName) signal
This signal is emitted when the Device Name characteristic has been read successfully.
See also
readDeviceName
deviceNameWritten
GenericAccessService::deviceNameWritten () signal
This signal is emitted when the Device Name characteristic has been written successfully.
See also
setDeviceName
readAppearanceCharacteristic()
bool GenericAccessService::readAppearanceCharacteristic ()
Read the Generic Access service's Appearance characteristic.
Returns true if the read request is succesfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits appearanceRead() if/when the characteristic has been read successfully.
Definition at line 86 of file genericaccessservice.cpp.
{
    Q_D(GenericAccessService);
    return d->readCharacteristic(CharacteristicUuids::appearance);
}
References GenericAccessService::CharacteristicUuids::appearance.
Referenced by readCharacteristics().
readCharacteristics()
bool GenericAccessService::readCharacteristics () override virtual
Read all characteristics.
This convenience function will queue refresh requests of all characteristics supported by this service.
Relevant *Service::*Read signals will be emitted by derived class objects as each characteristic is successfully read.
Implements AbstractPokitService.
Definition at line 70 of file genericaccessservice.cpp.
{
    const bool r1 = readDeviceNameCharacteristic();
    const bool r2 = readAppearanceCharacteristic();
    return (r1 && r2);
}
References readAppearanceCharacteristic(), and readDeviceNameCharacteristic().
readDeviceNameCharacteristic()
bool GenericAccessService::readDeviceNameCharacteristic ()
Read the Generic Access service's Device Name characteristic.
Returns true if the read request is succesfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered).
Emits deviceNameRead() if/when the characteristic has been read successfully.
Definition at line 101 of file genericaccessservice.cpp.
{
    Q_D(GenericAccessService);
    return d->readCharacteristic(CharacteristicUuids::deviceName);
}
References GenericAccessService::CharacteristicUuids::deviceName.
Referenced by readCharacteristics().
setDeviceName()
bool GenericAccessService::setDeviceName (const QString & name)
Set's the Pokit device's name to name.
Returns true if the write request was successfully queued, false otherwise.
Emits deviceNameWritten() if/when the name has been set.
Definition at line 149 of file genericaccessservice.cpp.
{
    Q_D(const GenericAccessService);
    const QLowEnergyCharacteristic characteristic =
        d->getCharacteristic(CharacteristicUuids::deviceName);
    if (!characteristic.isValid()) {
        return false;
    }
    const QByteArray value = name.toUtf8();
    if (value.length() > 11) {
        qCWarning(d->lc).noquote() << tr(R"(Device name "%1" is too long (%2 > 11 bytes): 0x%3)")
            .arg(name).arg(value.length()).arg(QLatin1String(value.toHex()));
        return false;
    }
    d->service->writeCharacteristic(characteristic, value);
    return (d->service->error() != QLowEnergyService::ServiceError::CharacteristicWriteError);
}
References QString::arg(), GenericAccessService::CharacteristicUuids::deviceName, QLowEnergyCharacteristic::isValid(), QByteArray::length(), QByteArray::toHex(), QString::toUtf8(), and QObject::tr().
Friends And Related Symbol Documentation
TestGenericAccessService
friend class TestGenericAccessService friend
Definition at line 61 of file genericaccessservice.h.
Member Data Documentation
serviceUuid
const QBluetoothUuid GenericAccessService::serviceUuid static
UUID of the "Generic Access" service.
Definition at line 27 of file genericaccessservice.h.
Referenced by PokitDevice::serviceToString().
The documentation for this class was generated from the following files:
genericaccessservice.h
genericaccessservice.cpp