Dokit: ResistanceRange Namespace Reference
ResistanceRange Namespace Reference
Encapsulates convenience functions for working with resistance ranges.
Functions
QString toString (const PokitProduct product, const quint8 range)
Returns product's current range as a human-friendly string.
QVariant maxValue (const PokitProduct product, const quint8 range)
Returns the maximum value for product's range in (integer) ohms, or the string "Auto".
Detailed Description
Encapsulates convenience functions for working with resistance ranges.
Function Documentation
maxValue()
QTPOKIT_EXPORT QVariant ResistanceRange::maxValue (const PokitProduct product, const quint8 range)
Returns the maximum value for product's range in (integer) ohms, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned.
See also
PokitMeter::maxValue(const PokitMeter::ResistanceRange &range)
PokitPro::maxValue(const PokitPro::ResistanceRange &range)
Definition at line 247 of file pokitproducts.cpp.
{
    switch (product) {
    case PokitProduct::PokitMeter:
        return PokitMeter::maxValue(static_cast<PokitMeter::ResistanceRange>(range));
    case PokitProduct::PokitPro:
        return PokitPro::maxValue(static_cast<PokitPro::ResistanceRange>(range));
    }
    qCWarning(lc).noquote() << QCoreApplication::translate("ResistanceRange",
        "Unknown PokitProduct value: %1", "maxValue").arg((int)product);
    return QVariant();
}
References QString::arg(), PokitMeter::maxValue(), PokitPro::maxValue(), PokitMeter, PokitPro, and QCoreApplication::translate().
Referenced by MultimeterService::maxValue().
toString()
QTPOKIT_EXPORT QString ResistanceRange::toString (const PokitProduct product, const quint8 range)
Returns product's current range as a human-friendly string.
See also
PokitMeter::toString(const PokitMeter::ResistanceRange &range)
PokitPro::toString(const PokitPro::ResistanceRange &range)
Definition at line 227 of file pokitproducts.cpp.
{
    switch (product) {
    case PokitProduct::PokitMeter:
        return PokitMeter::toString(static_cast<PokitMeter::ResistanceRange>(range));
    case PokitProduct::PokitPro:
        return PokitPro::toString(static_cast<PokitPro::ResistanceRange>(range));
    }
    qCWarning(lc).noquote() << QCoreApplication::translate("ResistanceRange",
        "Unknown PokitProduct value: %1", "toString").arg((int)product);
    return QString();
}
References QString::arg(), PokitMeter, PokitPro, PokitMeter::toString(), PokitPro::toString(), and QCoreApplication::translate().
Referenced by MultimeterService::toString().