Dokit: PokitPro Namespace Reference
PokitPro Namespace Reference
Encapsulates details specific to Pokit Pro devices.
Enumerations
enum class CapacitanceRange : quint8 { _100nF = 0 , _10uF = 1 , _1mF = 2 , AutoRange = 255 }
Values supported by the Pokit Pro's Range attributes in Capacitance mode.
enum class CurrentRange : quint8 {
_500uA = 0 , _2mA = 1 , _10mA = 2 , _125mA = 3 ,
_300mA = 4 , _3A = 5 , _10A = 6 , AutoRange = 255
}
Values supported by the Pokit Pro's Range attributes in *Current modes.
enum class ResistanceRange : quint8 {
_30 = 0 , _75 = 1 , _400 = 2 , _5K = 3 ,
_10K = 4 , _15K = 5 , _40K = 6 , _500K = 7 ,
_700K = 8 , _1M = 9 , _3M = 10 , AutoRange = 255
}
Values supported by the Pokit Pro's Range attributes in Resistance mode.
enum class VoltageRange : quint8 {
_250mV = 0 , _2V = 1 , _10V = 2 , _30V = 3 ,
_60V = 4 , _125V = 5 , _400V = 6 , _600V = 7 ,
AutoRange = 255
}
Values supported by the Pokit Pro's Range attributes in *Voltage modes.
Functions
QTPOKIT_EXPORT QString toString (const CapacitanceRange &range)
Returns range as a user-friendly string.
QTPOKIT_EXPORT QVariant maxValue (const CapacitanceRange &range)
Returns the maximum value for range in (integer) nanofarads, or the string "Auto".
QTPOKIT_EXPORT QString toString (const CurrentRange &range)
Returns range as a user-friendly string.
QTPOKIT_EXPORT QVariant maxValue (const CurrentRange &range)
Returns the maximum value for range in (integer) microamps, or the string "Auto".
QTPOKIT_EXPORT QString toString (const ResistanceRange &range)
Returns range as a user-friendly string.
QTPOKIT_EXPORT QVariant maxValue (const ResistanceRange &range)
Returns the maximum value for range in (integer) ohms, or the string "Auto".
QTPOKIT_EXPORT QString toString (const VoltageRange &range)
Returns range as a user-friendly string.
QTPOKIT_EXPORT QVariant maxValue (const VoltageRange &range)
Returns the maximum value for range in (integer) millivolts, or the string "Auto".
Detailed Description
Encapsulates details specific to Pokit Pro devices.
Enumeration Type Documentation
CapacitanceRange
enum class PokitPro::CapacitanceRange : quint8 strong
Values supported by the Pokit Pro's Range attributes in Capacitance mode.
Pokit Bluetooth API errata:
These Pokit Pro enumeration values are as-yet undocumented by Pokit Innovations. @pcolby reverse-engineered them as part of the dokit project.
Enumerator
_100nF
Up 100nF.
_10uF
Up 10μF.
_1mF
Up 1mF.
AutoRange
Auto-range.
Definition at line 22 of file pokitpro.h.
                                : quint8 {
        _100nF    = 0,  ///< Up 100nF.
        _10uF     = 1,  ///< Up 10μF.
        _1mF      = 2,  ///< Up 1mF.
        AutoRange = 255 ///< Auto-range.
    };
CurrentRange
enum class PokitPro::CurrentRange : quint8 strong
Values supported by the Pokit Pro's Range attributes in *Current modes.
Pokit Bluetooth API errata:
These Pokit Pro enumeration values are as-yet undocumented by Pokit Innovations. @pcolby reverse-engineered them as part of the dokit project.
Enumerator
_500uA
Up to 5µA.
_2mA
Up to 2mA.
_10mA
Up to 10mA.
_125mA
Up to 125mA.
_300mA
Up to 300mA.
_3A
Up to 3A.
_10A
Up to 10A.
AutoRange
Auto-range.
Definition at line 33 of file pokitpro.h.
                            : quint8 {
        _500uA    = 0,  ///< Up to 5µA.
        _2mA      = 1,  ///< Up to 2mA.
        _10mA     = 2,  ///< Up to 10mA.
        _125mA    = 3,  ///< Up to 125mA.
        _300mA    = 4,  ///< Up to 300mA.
        _3A       = 5,  ///< Up to 3A.
        _10A      = 6,  ///< Up to 10A.
        AutoRange = 255 ///< Auto-range.
    };
ResistanceRange
enum class PokitPro::ResistanceRange : quint8 strong
Values supported by the Pokit Pro's Range attributes in Resistance mode.
Pokit Bluetooth API errata:
These Pokit Pro enumeration values are as-yet undocumented by Pokit Innovations. @pcolby reverse-engineered them as part of the dokit project.
Enumerator
_30
Up to 30Ω.
_75
Up to 75Ω.
_400
Up to 400Ω.
_5K
Up to 5KΩ.
_10K
Up to 10KΩ.
_15K
Up to 15KΩ.
_40K
Up to 40KΩ.
_500K
Up to 500KΩ.
_700K
Up to 700KΩ.
_1M
Up to 1MΩ.
_3M
Up to 3MΩ.
AutoRange
Auto-range.
Definition at line 47 of file pokitpro.h.
                               : quint8 {
        _30       = 0,  ///< Up to 30Ω.
        _75       = 1,  ///< Up to 75Ω.
        _400      = 2,  ///< Up to 400Ω.
        _5K       = 3,  ///< Up to 5KΩ.
        _10K      = 4,  ///< Up to 10KΩ.
        _15K      = 5,  ///< Up to 15KΩ.
        _40K      = 6,  ///< Up to 40KΩ.
        _500K     = 7,  ///< Up to 500KΩ.
        _700K     = 8,  ///< Up to 700KΩ.
        _1M       = 9,  ///< Up to 1MΩ.
        _3M       = 10, ///< Up to 3MΩ.
        AutoRange = 255 ///< Auto-range.
    };
VoltageRange
enum class PokitPro::VoltageRange : quint8 strong
Values supported by the Pokit Pro's Range attributes in *Voltage modes.
Pokit Bluetooth API errata:
These Pokit Pro enumeration values are as-yet undocumented by Pokit Innovations. @pcolby reverse-engineered them as part of the dokit project.
Enumerator
_250mV
Up to 250mV.
_2V
Up to 2V.
_10V
Up to 10V.
_30V
Up to 30V.
_60V
Up to 60V.
_125V
Up to 125V.
_400V
Up to 400V.
_600V
Up to 600V.
AutoRange
Auto-range.
Definition at line 65 of file pokitpro.h.
                            : quint8 {
        _250mV    = 0,  ///< Up to 250mV.
        _2V       = 1,  ///< Up to 2V.
        _10V      = 2,  ///< Up to 10V.
        _30V      = 3,  ///< Up to 30V.
        _60V      = 4,  ///< Up to 60V.
        _125V     = 5,  ///< Up to 125V.
        _400V     = 6,  ///< Up to 400V.
        _600V     = 7,  ///< Up to 600V.
        AutoRange = 255 ///< Auto-range.
    };
Function Documentation
maxValue() [1/4]
QVariant PokitPro::maxValue (const CapacitanceRange & range)
Returns the maximum value for range in (integer) nanofarads, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned.
Definition at line 40 of file pokitpro.cpp.
{
    switch (range) {
    case CapacitanceRange::_100nF:    return       100;
    case CapacitanceRange::_10uF:     return    10'000;
    case CapacitanceRange::_1mF:      return 1'000'000;
    case CapacitanceRange::AutoRange: return QCoreApplication::translate("PokitPro", "Auto", "CapacitanceRange");
    default:                          return QVariant();
    }
}
References _100nF, _10uF, _1mF, AutoRange, and QCoreApplication::translate().
Referenced by CapacitanceRange::maxValue(), CurrentRange::maxValue(), ResistanceRange::maxValue(), and VoltageRange::maxValue().
maxValue() [2/4]
QVariant PokitPro::maxValue (const CurrentRange & range)
Returns the maximum value for range in (integer) microamps, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned.
Definition at line 80 of file pokitpro.cpp.
{
    switch (range) {
    case CurrentRange::_500uA:    return        500;
    case CurrentRange::_2mA:      return      2'000;
    case CurrentRange::_10mA:     return     10'000;
    case CurrentRange::_125mA:    return    125'000;
    case CurrentRange::_300mA:    return    300'000;
    case CurrentRange::_3A:       return  3'000'000;
    case CurrentRange::_10A:      return 10'000'000;
    case CurrentRange::AutoRange: return QCoreApplication::translate("PokitPro", "Auto", "CurrentRange");
    default:                      return QVariant();
    }
}
References _10A, _10mA, _125mA, _2mA, _300mA, _3A, _500uA, AutoRange, and QCoreApplication::translate().
maxValue() [3/4]
QVariant PokitPro::maxValue (const ResistanceRange & range)
Returns the maximum value for range in (integer) ohms, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned.
Definition at line 128 of file pokitpro.cpp.
{
    switch (range) {
    case ResistanceRange::_30:       return        30;
    case ResistanceRange::_75:       return        75;
    case ResistanceRange::_400:      return       400;
    case ResistanceRange::_5K:       return     5'000;
    case ResistanceRange::_10K:      return    10'000;
    case ResistanceRange::_15K:      return    15'000;
    case ResistanceRange::_40K:      return    40'000;
    case ResistanceRange::_500K:     return   500'000;
    case ResistanceRange::_700K:     return   700'000;
    case ResistanceRange::_1M:       return 1'000'000;
    case ResistanceRange::_3M:       return 3'000'000;
    case ResistanceRange::AutoRange: return QCoreApplication::translate("PokitPro", "Auto", "ResistanceRange");
    default:                         return QVariant();
    }
}
References _10K, _15K, _1M, _30, _3M, _400, _40K, _500K, _5K, _700K, _75, AutoRange, and QCoreApplication::translate().
maxValue() [4/4]
QVariant PokitPro::maxValue (const VoltageRange & range)
Returns the maximum value for range in (integer) millivolts, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned.
Definition at line 177 of file pokitpro.cpp.
{
    switch (range) {
    case VoltageRange::_250mV:    return     250;
    case VoltageRange::_2V:       return   2'000;
    case VoltageRange::_10V:      return  10'000;
    case VoltageRange::_30V:      return  30'000;
    case VoltageRange::_60V:      return  60'000;
    case VoltageRange::_125V:     return 125'000;
    case VoltageRange::_400V:     return 400'000;
    case VoltageRange::_600V:     return 600'000;
    case VoltageRange::AutoRange: return QCoreApplication::translate("PokitPro", "Auto", "VoltageRange");
    default:                      return QVariant();
    }
}
References _10V, _125V, _250mV, _2V, _30V, _400V, _600V, _60V, AutoRange, and QCoreApplication::translate().
toString() [1/4]
QString PokitPro::toString (const CapacitanceRange & range)
Returns range as a user-friendly string.
Definition at line 25 of file pokitpro.cpp.
{
    switch (range) {
    case CapacitanceRange::_100nF:    return QCoreApplication::translate("PokitPro", "Up to 100nF", "CapacitanceRange");
    case CapacitanceRange::_10uF:     return QCoreApplication::translate("PokitPro", "Up to 10μF",  "CapacitanceRange");
    case CapacitanceRange::_1mF:      return QCoreApplication::translate("PokitPro", "Up to 1mF",   "CapacitanceRange");
    case CapacitanceRange::AutoRange: return QCoreApplication::translate("PokitPro", "Auto-range",  "CapacitanceRange");
    default:                          return QString();
    }
}
References _100nF, _10uF, _1mF, AutoRange, and QCoreApplication::translate().
Referenced by CapacitanceRange::toString(), CurrentRange::toString(), ResistanceRange::toString(), and VoltageRange::toString().
toString() [2/4]
QString PokitPro::toString (const CurrentRange & range)
Returns range as a user-friendly string.
Definition at line 61 of file pokitpro.cpp.
{
    switch (range) {
    case CurrentRange::_500uA:    return QCoreApplication::translate("PokitPro", "Up to 500μA", "CurrentRange");
    case CurrentRange::_2mA:      return QCoreApplication::translate("PokitPro", "Up to 2mA",   "CurrentRange");
    case CurrentRange::_10mA:     return QCoreApplication::translate("PokitPro", "Up to 10mA",  "CurrentRange");
    case CurrentRange::_125mA:    return QCoreApplication::translate("PokitPro", "Up to 125mA", "CurrentRange");
    case CurrentRange::_300mA:    return QCoreApplication::translate("PokitPro", "Up to 300mA", "CurrentRange");
    case CurrentRange::_3A:       return QCoreApplication::translate("PokitPro", "Up to 3A",    "CurrentRange");
    case CurrentRange::_10A:      return QCoreApplication::translate("PokitPro", "Up to 10A",   "CurrentRange");
    case CurrentRange::AutoRange: return QCoreApplication::translate("PokitPro", "Auto-range",  "CurrentRange");
    default:                      return QString();
    }
}
References _10A, _10mA, _125mA, _2mA, _300mA, _3A, _500uA, AutoRange, and QCoreApplication::translate().
toString() [3/4]
QString PokitPro::toString (const ResistanceRange & range)
Returns range as a user-friendly string.
Definition at line 105 of file pokitpro.cpp.
{
    switch (range) {
    case ResistanceRange::_30:       return QCoreApplication::translate("PokitPro", "Up to 30Ω",   "ResistanceRange");
    case ResistanceRange::_75:       return QCoreApplication::translate("PokitPro", "Up to 75Ω",   "ResistanceRange");
    case ResistanceRange::_400:      return QCoreApplication::translate("PokitPro", "Up to 400Ω",  "ResistanceRange");
    case ResistanceRange::_5K:       return QCoreApplication::translate("PokitPro", "Up to 5KΩ",   "ResistanceRange");
    case ResistanceRange::_10K:      return QCoreApplication::translate("PokitPro", "Up to 10KΩ",  "ResistanceRange");
    case ResistanceRange::_15K:      return QCoreApplication::translate("PokitPro", "Up to 15KΩ",  "ResistanceRange");
    case ResistanceRange::_40K:      return QCoreApplication::translate("PokitPro", "Up to 40KΩ",  "ResistanceRange");
    case ResistanceRange::_500K:     return QCoreApplication::translate("PokitPro", "Up to 500KΩ", "ResistanceRange");
    case ResistanceRange::_700K:     return QCoreApplication::translate("PokitPro", "Up to 700KΩ", "ResistanceRange");
    case ResistanceRange::_1M:       return QCoreApplication::translate("PokitPro", "Up to 1MΩ",   "ResistanceRange");
    case ResistanceRange::_3M:       return QCoreApplication::translate("PokitPro", "Up to 3MΩ",   "ResistanceRange");
    case ResistanceRange::AutoRange: return QCoreApplication::translate("PokitPro", "Auto-range",  "ResistanceRange");
    default:                         return QString();
    }
}
References _10K, _15K, _1M, _30, _3M, _400, _40K, _500K, _5K, _700K, _75, AutoRange, and QCoreApplication::translate().
toString() [4/4]
QString PokitPro::toString (const VoltageRange & range)
Returns range as a user-friendly string.
Definition at line 157 of file pokitpro.cpp.
{
    switch (range) {
    case VoltageRange::_250mV:    return QCoreApplication::translate("PokitPro", "Up to 250mV", "VoltageRange");
    case VoltageRange::_2V:       return QCoreApplication::translate("PokitPro", "Up to 2V",    "VoltageRange");
    case VoltageRange::_10V:      return QCoreApplication::translate("PokitPro", "Up to 10V",   "VoltageRange");
    case VoltageRange::_30V:      return QCoreApplication::translate("PokitPro", "Up to 30V",   "VoltageRange");
    case VoltageRange::_60V:      return QCoreApplication::translate("PokitPro", "Up to 60V",   "VoltageRange");
    case VoltageRange::_125V:     return QCoreApplication::translate("PokitPro", "Up to 125V",  "VoltageRange");
    case VoltageRange::_400V:     return QCoreApplication::translate("PokitPro", "Up to 400V",  "VoltageRange");
    case VoltageRange::_600V:     return QCoreApplication::translate("PokitPro", "Up to 600V",  "VoltageRange");
    case VoltageRange::AutoRange: return QCoreApplication::translate("PokitPro", "Auto-range",  "VoltageRange");
    default:                      return QString();
    }
}
References _10V, _125V, _250mV, _2V, _30V, _400V, _600V, _60V, AutoRange, and QCoreApplication::translate().