Dokit: CapacitanceRange Namespace Reference
CapacitanceRange Namespace Reference
Encapsulates convenience functions for working with capacitance ranges.
Functions
QString toString (const PokitProduct product, const quint8 range)
Returns product's capacitance range as a human-friendly string.
QVariant maxValue (const PokitProduct product, const quint8 range)
Returns the maximum value for product's range in (integer) nanofarads, or the string "Auto".
Detailed Description
Encapsulates convenience functions for working with capacitance ranges.
Function Documentation
maxValue()
QTPOKIT_EXPORT QVariant CapacitanceRange::maxValue (const PokitProduct product, const quint8 range)
Returns the maximum value for product's range in (integer) nanofarads, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned.
Note
Since Pokit Meters do not support capacitance measurement, product should not be PokitProduct::PokitMeter.
See also
PokitPro::maxValue(const PokitPro::CapacitanceRange &range)
Definition at line 157 of file pokitproducts.cpp.
{
    switch (product) {
    case PokitProduct::PokitMeter:
        qCWarning(lc).noquote()
            << QCoreApplication::translate("PokitProducts", "Pokit Meter has no capacitance support", "toString");
        return QVariant();
    case PokitProduct::PokitPro:
        return PokitPro::maxValue(static_cast<PokitPro::CapacitanceRange>(range));
    }
    qCWarning(lc).noquote() << QCoreApplication::translate("CapacitanceRange",
        "Unknown PokitProduct value: %1", "maxValue").arg((int)product);
    return QVariant();
}
References QString::arg(), PokitPro::maxValue(), PokitMeter, PokitPro, and QCoreApplication::translate().
Referenced by MultimeterService::maxValue().
toString()
QTPOKIT_EXPORT QString CapacitanceRange::toString (const PokitProduct product, const quint8 range)
Returns product's capacitance range as a human-friendly string.
Note
Since Pokit Meters do not support capacitance measurement, product should not be PokitProduct::PokitMeter.
See also
PokitPro::toString(const PokitPro::CapacitanceRange &range)
Definition at line 134 of file pokitproducts.cpp.
{
    switch (product) {
    case PokitProduct::PokitMeter:
        qCWarning(lc).noquote()
            << QCoreApplication::translate("PokitProducts", "Pokit Meter has no capacitance support", "toString");
        return QString();
    case PokitProduct::PokitPro:
        return PokitPro::toString(static_cast<PokitPro::CapacitanceRange>(range));
    }
    qCWarning(lc).noquote() << QCoreApplication::translate("CapacitanceRange",
        "Unknown PokitProduct value: %1", "toString").arg((int)product);
    return QString();
}
References QString::arg(), PokitMeter, PokitPro, PokitPro::toString(), and QCoreApplication::translate().
Referenced by MultimeterService::toString().