Dokit: VoltageRange Namespace Reference
VoltageRange Namespace Reference
Encapsulates convenience functions for working with voltage ranges.
Functions
QString toString (const PokitProduct product, const quint8 range)
Returns product's current range as a human-friendly string.
QVariant maxValue (const PokitProduct product, const quint8 range)
Returns the maximum value for product's range in (integer) millivolts, or the string "Auto".
Detailed Description
Encapsulates convenience functions for working with voltage ranges.
Function Documentation
maxValue()
QTPOKIT_EXPORT QVariant VoltageRange::maxValue (const PokitProduct product, const quint8 range)
Returns the maximum value for product's range in (integer) millivolts, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned.
See also
PokitMeter::maxValue(const PokitMeter::VoltageRange &range)
PokitPro::maxValue(const PokitPro::VoltageRange &range)
Definition at line 297 of file pokitproducts.cpp.
{
    switch (product) {
    case PokitProduct::PokitMeter:
        return PokitMeter::maxValue(static_cast<PokitMeter::VoltageRange>(range));
    case PokitProduct::PokitPro:
        return PokitPro::maxValue(static_cast<PokitPro::VoltageRange>(range));
    }
    qCWarning(lc).noquote() << QCoreApplication::translate("VoltageRange",
        "Unknown PokitProduct value: %1", "maxValue").arg((int)product);
    return QVariant();
}
References QString::arg(), PokitPro::maxValue(), PokitMeter::maxValue(), PokitMeter, PokitPro, and QCoreApplication::translate().
Referenced by DataLoggerService::maxValue(), DsoService::maxValue(), and MultimeterService::maxValue().
toString()
QTPOKIT_EXPORT QString VoltageRange::toString (const PokitProduct product, const quint8 range)
Returns product's current range as a human-friendly string.
See also
PokitMeter::toString(const PokitMeter::VoltageRange &range)
PokitPro::toString(const PokitPro::VoltageRange &range)
Definition at line 277 of file pokitproducts.cpp.
{
    switch (product) {
    case PokitProduct::PokitMeter:
        return PokitMeter::toString(static_cast<PokitMeter::VoltageRange>(range));
    case PokitProduct::PokitPro:
        return PokitPro::toString(static_cast<PokitPro::VoltageRange>(range));
    }
    qCWarning(lc).noquote() << QCoreApplication::translate("VoltageRange",
        "Unknown PokitProduct value: %1", "toString").arg((int)product);
    return QString();
}
References QString::arg(), PokitMeter, PokitPro, PokitPro::toString(), PokitMeter::toString(), and QCoreApplication::translate().
Referenced by DataLoggerService::toString(), DsoService::toString(), and MultimeterService::toString().