Dokit: MultimeterService::CharacteristicUuids Struct Reference
MultimeterService::CharacteristicUuids Struct Reference
Characteristics available via the Multimeter service.
#include <multimeterservice.h>
Static Public Attributes
static const QBluetoothUuid settings { QStringLiteral("53dc9a7a-bc19-4280-b76b-002d0e23b078") }
UUID of the Multimeter service's Settings characteristic.
static const QBluetoothUuid reading { QStringLiteral("047d3559-8bee-423a-b229-4417fa603b90") }
UUID of the Multimeter service's Reading characteristic.
Detailed Description
Characteristics available via the Multimeter service.
Definition at line 31 of file multimeterservice.h.
Member Data Documentation
reading
const QBluetoothUuid MultimeterService::CharacteristicUuids::reading { QStringLiteral("047d3559-8bee-423a-b229-4417fa603b90") } inline static
UUID of the Multimeter service's Reading characteristic.
Definition at line 36 of file multimeterservice.h.
{ QStringLiteral("047d3559-8bee-423a-b229-4417fa603b90") };
Referenced by MultimeterServicePrivate::characteristicChanged(), MultimeterServicePrivate::characteristicRead(), MultimeterServicePrivate::characteristicWritten(), PokitDevice::charcteristicToString(), MultimeterService::disableReadingNotifications(), MultimeterService::enableReadingNotifications(), MultimeterService::reading(), and MultimeterService::readReadingCharacteristic().
settings
const QBluetoothUuid MultimeterService::CharacteristicUuids::settings { QStringLiteral("53dc9a7a-bc19-4280-b76b-002d0e23b078") } inline static
UUID of the Multimeter service's Settings characteristic.
Definition at line 33 of file multimeterservice.h.
{ QStringLiteral("53dc9a7a-bc19-4280-b76b-002d0e23b078") };
Referenced by MultimeterServicePrivate::characteristicChanged(), MultimeterServicePrivate::characteristicRead(), MultimeterServicePrivate::characteristicWritten(), PokitDevice::charcteristicToString(), and MultimeterService::setSettings().
The documentation for this struct was generated from the following file:
multimeterservice.h