Dokit: StatusService::CharacteristicUuids Struct Reference
StatusService::CharacteristicUuids Struct Reference
Characteristics available via the Pokit Status service.
#include <statusservice.h>
Static Public Attributes
static const QBluetoothUuid deviceCharacteristics { QStringLiteral("6974f5e5-0e54-45c3-97dd-29e4b5fb0849") }
UUID of the Pokit Status service's Device Characteristics characterstic.
static const QBluetoothUuid status { QStringLiteral("3dba36e1-6120-4706-8dfd-ed9c16e569b6") }
UUID of the Pokit Status service's Status characterstic.
static const QBluetoothUuid name { QStringLiteral("7f0375de-077e-4555-8f78-800494509cc3") }
UUID of the Pokit Status service's Device Name characterstic.
static const QBluetoothUuid flashLed { QStringLiteral("ec9bb1f3-05a9-4277-8dd0-60a7896f0d6e") }
UUID of the Pokit Status service's Flash LED characterstic.
static const QBluetoothUuid torch { QStringLiteral("aaf3f6d5-43d4-4a83-9510-dff3d858d4cc") }
UUID of the Pokit Status service's (undocumented) Torch characterstic.
static const QBluetoothUuid buttonPress { QStringLiteral("8fe5b5a9-b5b4-4a7b-8ff2-87224b970f89") }
UUID of the Pokit Status service's (undocumented) Button Press characterstic.
Detailed Description
Characteristics available via the Pokit Status service.
Definition at line 39 of file statusservice.h.
Member Data Documentation
buttonPress
const QBluetoothUuid StatusService::CharacteristicUuids::buttonPress { QStringLiteral("8fe5b5a9-b5b4-4a7b-8ff2-87224b970f89") } inline static
UUID of the Pokit Status service's (undocumented) Button Press characterstic.
Definition at line 56 of file statusservice.h.
Referenced by StatusService::buttonPress(), StatusServicePrivate::characteristicRead(), PokitDevice::charcteristicToString(), StatusService::disableButtonPressedNotifications(), StatusService::enableButtonPressedNotifications(), StatusService::readButtonPressCharacteristic(), and StatusService::readCharacteristics().
deviceCharacteristics
const QBluetoothUuid StatusService::CharacteristicUuids::deviceCharacteristics { QStringLiteral("6974f5e5-0e54-45c3-97dd-29e4b5fb0849") } inline static
UUID of the Pokit Status service's Device Characteristics characterstic.
Definition at line 41 of file statusservice.h.
Referenced by StatusServicePrivate::characteristicRead(), StatusServicePrivate::characteristicWritten(), PokitDevice::charcteristicToString(), StatusService::deviceCharacteristics(), and StatusService::readDeviceCharacteristics().
flashLed
const QBluetoothUuid StatusService::CharacteristicUuids::flashLed { QStringLiteral("ec9bb1f3-05a9-4277-8dd0-60a7896f0d6e") } inline static
UUID of the Pokit Status service's Flash LED characterstic.
Definition at line 50 of file statusservice.h.
Referenced by StatusServicePrivate::characteristicRead(), StatusServicePrivate::characteristicWritten(), PokitDevice::charcteristicToString(), and StatusService::flashLed().
name
const QBluetoothUuid StatusService::CharacteristicUuids::name { QStringLiteral("7f0375de-077e-4555-8f78-800494509cc3") } inline static
UUID of the Pokit Status service's Device Name characterstic.
Definition at line 47 of file statusservice.h.
Referenced by StatusServicePrivate::characteristicRead(), StatusServicePrivate::characteristicWritten(), PokitDevice::charcteristicToString(), StatusService::deviceName(), StatusService::readNameCharacteristic(), and StatusService::setDeviceName().
status
const QBluetoothUuid StatusService::CharacteristicUuids::status { QStringLiteral("3dba36e1-6120-4706-8dfd-ed9c16e569b6") } inline static
UUID of the Pokit Status service's Status characterstic.
Definition at line 44 of file statusservice.h.
Referenced by StatusServicePrivate::characteristicRead(), StatusServicePrivate::characteristicWritten(), PokitDevice::charcteristicToString(), StatusService::disableStatusNotifications(), StatusService::enableStatusNotifications(), StatusService::readStatusCharacteristic(), and StatusService::status().
torch
const QBluetoothUuid StatusService::CharacteristicUuids::torch { QStringLiteral("aaf3f6d5-43d4-4a83-9510-dff3d858d4cc") } inline static
UUID of the Pokit Status service's (undocumented) Torch characterstic.
Definition at line 53 of file statusservice.h.
Referenced by StatusServicePrivate::characteristicRead(), StatusServicePrivate::characteristicWritten(), PokitDevice::charcteristicToString(), StatusService::disableTorchStatusNotifications(), StatusService::enableTorchStatusNotifications(), StatusService::readCharacteristics(), StatusService::readTorchCharacteristic(), StatusService::setTorchStatus(), and StatusService::torchStatus().
The documentation for this struct was generated from the following file:
statusservice.h