QtPokit: utils.h File Reference
utils.h File Reference
Declares some simple general purpose, utility functions used by QtPokit.
#include "qtpokit_global.h"
#include <QBluetoothDeviceInfo>
#include <QBluetoothUuid>
#include <QJsonArray>
#include <QJsonObject>
#include <QJsonValue>
Functions
QTPOKIT_BEGIN_NAMESPACE QTPOKIT_EXPORT QJsonObject toJson (const QBluetoothDeviceInfo &info)
Returns info as a JSON object.
QTPOKIT_EXPORT QJsonArray toJson (const QBluetoothDeviceInfo::CoreConfigurations &configurations)
Returns configuration as a JSON array of strings.
QTPOKIT_EXPORT QJsonValue toJson (const QBluetoothDeviceInfo::MajorDeviceClass &majorClass)
Returns majorClass as a JSON value.
QTPOKIT_EXPORT QJsonValue toJson (const QBluetoothDeviceInfo::MajorDeviceClass &majorClass, const quint8 minorClass)
Returns minorClass as a JSON value.
QTPOKIT_EXPORT QJsonArray toJson (const QBluetoothDeviceInfo::ServiceClasses &classes)
Returns classes as a JSON array of strings.
QTPOKIT_EXPORT QJsonArray toJson (const QList< QBluetoothUuid > &uuids)
Returns uuids as a JSON array.
QTPOKIT_EXPORT QJsonObject toJson (const QMultiHash< quint16, QByteArray > &data)
Returns Bluetooth manufacturer data as a JSON object that maps the manufacturer IDs (unsigned integers as strings) to arrays of one or more values.
QTPOKIT_EXPORT QString toString (const QBluetoothDeviceInfo::MajorDeviceClass &majorClass)
Returns majorClass as a human-readable string, or a null QString if majorClass is not recognised.
QTPOKIT_EXPORT QString toString (const QBluetoothDeviceInfo::MajorDeviceClass &majorClass, const quint8 minorClass)
Returns minorClass as a human-readable string, or a null QString if minorClass is not recognised as a sub-class of majorClass.
Detailed Description
Declares some simple general purpose, utility functions used by QtPokit.
Definition in file utils.h.
Function Documentation
toJson() [1/7]
QTPOKIT_BEGIN_NAMESPACE QTPOKIT_EXPORT QJsonObject toJson (const QBluetoothDeviceInfo & info)
Returns info as a JSON object.
Todo:
Probably should move all of the JSON ones to a the console app.
Definition at line 37 of file utils.cpp.
{
    if (!info.isValid()) {
        return QJsonObject();
    }
    QJsonObject json{
        { QLatin1String("address"), info.address().toString() },
        { QLatin1String("name"), info.name() },
        { QLatin1String("isCached"), info.isCached() },
        { QLatin1String("majorDeviceClass"), info.majorDeviceClass() },
        { QLatin1String("majorDeviceClass"), toJson(info.majorDeviceClass()) },
        { QLatin1String("minorDeviceClass"), toJson(info.majorDeviceClass(), info.minorDeviceClass()) },
        { QLatin1String("signalStrength"), info.rssi() },
    };
    if (info.coreConfigurations() != QBluetoothDeviceInfo::UnknownCoreConfiguration) {
        json.insert(QLatin1String("coreConfiguration"), toJson(info.coreConfigurations()));
    }
    if (!info.deviceUuid().isNull()) {
        json.insert(QLatin1String("deviceUuid"), info.deviceUuid().toString());
    }
    #if (QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)) // Added in Qt 5.12.
    if (!info.manufacturerData().isEmpty()) {
        json.insert(QLatin1String("manufacturerData"), toJson(info.manufacturerData()));
    }
    #endif
    if (info.serviceClasses() != QBluetoothDeviceInfo::NoService) {
        json.insert(QLatin1String("serviceClasses"), toJson(info.serviceClasses()));
    }
    if (!info.serviceUuids().isEmpty()) {
        json.insert(QLatin1String("serviceUuids"), toJson(info.serviceUuids()));
    }
    return json;
}
References toJson().
Referenced by Scanner::deviceDiscovered(), and toJson().
toJson() [2/7]
QTPOKIT_EXPORT QJsonArray toJson (const QBluetoothDeviceInfo::CoreConfigurations & configurations)
Returns configuration as a JSON array of strings.
Definition at line 73 of file utils.cpp.
{
    QJsonArray array;
    #define QTPOKIT_INTERNAL_IF_SET_THEN_APPEND(flag) \
        if (configurations.testFlag(QBluetoothDeviceInfo::flag)) \
            array.append(QLatin1String(#flag))
    QTPOKIT_INTERNAL_IF_SET_THEN_APPEND(UnknownCoreConfiguration);
    QTPOKIT_INTERNAL_IF_SET_THEN_APPEND(LowEnergyCoreConfiguration);
    QTPOKIT_INTERNAL_IF_SET_THEN_APPEND(BaseRateCoreConfiguration);
  //QTPOKIT_INTERNAL_IF_SET_THEN_APPEND(BaseRateAndLowEnergyCoreConfiguration); // Combination flag.
    #undef QTPOKIT_INTERNAL_IF_SET_THEN_APPEND
    return array;
}
toJson() [3/7]
QTPOKIT_EXPORT QJsonValue toJson (const QBluetoothDeviceInfo::MajorDeviceClass & majorClass)
Returns majorClass as a JSON value.
This is equivalent to toString, except that if toString does not recognise majorClass, then majorClass is returned as a JSON number (not a string).
See also
toString(const QBluetoothDeviceInfo::MajorDeviceClass &majorClass)
Definition at line 93 of file utils.cpp.
{
    const QString string = toString(majorClass);
    return (string.isNull() ? QJsonValue(majorClass) : QJsonValue(string));
}
References toString().
toJson() [4/7]
QTPOKIT_EXPORT QJsonValue toJson (const QBluetoothDeviceInfo::MajorDeviceClass & majorClass, const quint8 minorClass)
Returns minorClass as a JSON value.
This is equivalent to toString, except that if toString does not recognise minorClass as a sub-class of majorClass, then minorClass is returned as a JSON number (not a string).
See also
toString(const QBluetoothDeviceInfo::MajorDeviceClass &majorClass, const quint8 minorClass)
Definition at line 106 of file utils.cpp.
{
    const QString string = toString(majorClass, minorClass);
    return (string.isNull() ? QJsonValue(minorClass) : QJsonValue(string));
}
References toString().
toJson() [5/7]
QTPOKIT_EXPORT QJsonArray toJson (const QBluetoothDeviceInfo::ServiceClasses & classes)
Returns classes as a JSON array of strings.
Definition at line 115 of file utils.cpp.
{
    QJsonArray array;
    #define QTPOKIT_INTERNAL_IF_SET_THEN_APPEND(flag) \
        if (classes.testFlag(QBluetoothDeviceInfo::flag)) \
            array.append(QLatin1String(#flag))
    QTPOKIT_INTERNAL_IF_SET_THEN_APPEND(PositioningService);
    QTPOKIT_INTERNAL_IF_SET_THEN_APPEND(NetworkingService);
    QTPOKIT_INTERNAL_IF_SET_THEN_APPEND(RenderingService);
    QTPOKIT_INTERNAL_IF_SET_THEN_APPEND(CapturingService);
    QTPOKIT_INTERNAL_IF_SET_THEN_APPEND(ObjectTransferService);
    QTPOKIT_INTERNAL_IF_SET_THEN_APPEND(AudioService);
    QTPOKIT_INTERNAL_IF_SET_THEN_APPEND(TelephonyService);
    QTPOKIT_INTERNAL_IF_SET_THEN_APPEND(InformationService);
    #undef QTPOKIT_INTERNAL_IF_SET_THEN_APPEND
    return array;
}
toJson() [6/7]
QTPOKIT_EXPORT QJsonArray toJson (const QList< QBluetoothUuid > & uuids)
Returns uuids as a JSON array.
Definition at line 136 of file utils.cpp.
{
    QJsonArray array;
    for (const QBluetoothUuid &uuid: uuids) {
        array.append(uuid.toString());
    }
    return array;
}
toJson() [7/7]
QTPOKIT_EXPORT QJsonObject toJson (const QMultiHash< quint16, QByteArray > & data)
Returns Bluetooth manufacturer data as a JSON object that maps the manufacturer IDs (unsigned integers as strings) to arrays of one or more values.
Definition at line 163 of file utils.cpp.
{
    QJsonObject object;
    QList<quint16> keys = data.uniqueKeys();
    std::sort(keys.begin(), keys.end());
    for (const quint16 key: keys) {
        // Convert the key's values to a JSON array, reversing the order, because QMultiHash
        // guarantees that the values are orderer "from the most recently inserted to the least
        // recently inserted", which is the oppoosit of what we want.
        QList<QByteArray> values = data.values(key);
        std::reverse(values.begin(), values.end());
        QJsonArray array;
        for (const QByteArray &value: values) {
            array.append(QLatin1String(value.toBase64()));
        }
        object.insert(QString::number(key), array);
    }
    return object;
}
toString() [1/2]
QTPOKIT_EXPORT QString toString (const QBluetoothDeviceInfo::MajorDeviceClass & majorClass)
Returns majorClass as a human-readable string, or a null QString if majorClass is not recognised.
For example, if majorClass is QBluetoothDeviceInfo::ToyDevice, then the string ToyDevice is returned.
Definition at line 190 of file utils.cpp.
{
    #define QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(value) \
        if (majorClass == QBluetoothDeviceInfo::value) \
            return QLatin1String(#value)
    QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(MiscellaneousDevice);
    QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ComputerDevice);
    QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(PhoneDevice);
    #if (QT_VERSION < QT_VERSION_CHECK(5, 13, 0))
    QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(LANAccessDevice); // Deprecated since Qt 5.13.
    #else
    QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkDevice); // Added in Qt 5.13.
    #endif
    QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(AudioVideoDevice);
    QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(PeripheralDevice);
    QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ImagingDevice);
    QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WearableDevice);
    QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ToyDevice);
    QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HealthDevice);
    QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedDevice);
    #undef QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN
    qCDebug(pokitUtils) << "unknown major class" << majorClass;
    return QString(); // Null QString indicates unknown minor class.
}
Referenced by toJson().
toString() [2/2]
QTPOKIT_EXPORT QString toString (const QBluetoothDeviceInfo::MajorDeviceClass & majorClass, const quint8 minorClass)
Returns minorClass as a human-readable string, or a null QString if minorClass is not recognised as a sub-class of majorClass.
For example, if majorClass is QBluetoothDeviceInfo::ToyDevice, and minorClass is QBluetoothDeviceInfo::ToyRobot, then the string ToyRobot is returned.
Definition at line 222 of file utils.cpp.
{
    #define QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(value) \
        if (minorClass == QBluetoothDeviceInfo::value) \
            return QLatin1String(#value)
    switch (majorClass) {
    case QBluetoothDeviceInfo::MiscellaneousDevice:
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedMiscellaneous);
        break;
    case QBluetoothDeviceInfo::ComputerDevice:
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedComputer);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(DesktopComputer);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ServerComputer);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(LaptopComputer);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HandheldClamShellComputer);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HandheldComputer);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WearableComputer);
        break;
    case QBluetoothDeviceInfo::PhoneDevice:
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedPhone);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(CellularPhone);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(CordlessPhone);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(SmartPhone);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WiredModemOrVoiceGatewayPhone);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(CommonIsdnAccessPhone);
        break;
    #if (QT_VERSION < QT_VERSION_CHECK(5, 13, 0))
    case QBluetoothDeviceInfo::LANAccessDevice: // Deprecated since Qt 5.13.
    #else
    case QBluetoothDeviceInfo::NetworkDevice: // Added in Qt 5.13.
    #endif
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkFullService);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkLoadFactorOne);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkLoadFactorTwo);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkLoadFactorThree);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkLoadFactorFour);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkLoadFactorFive);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkLoadFactorSix);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(NetworkNoService);
        break;
    case QBluetoothDeviceInfo::AudioVideoDevice:
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedAudioVideoDevice);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WearableHeadsetDevice);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HandsFreeDevice);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(Microphone);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(Loudspeaker);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(Headphones);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(PortableAudioDevice);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(CarAudio);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(SetTopBox);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HiFiAudioDevice);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(Vcr);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(VideoCamera);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(Camcorder);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(VideoMonitor);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(VideoDisplayAndLoudspeaker);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(VideoConferencing);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(GamingDevice);
        break;
    case QBluetoothDeviceInfo::PeripheralDevice:
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedPeripheral);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(KeyboardPeripheral);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(PointingDevicePeripheral);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(KeyboardWithPointingDevicePeripheral);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(JoystickPeripheral);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(GamepadPeripheral);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(RemoteControlPeripheral);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(SensingDevicePeripheral);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(DigitizerTabletPeripheral);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(CardReaderPeripheral);
        break;
    case QBluetoothDeviceInfo::ImagingDevice:
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedImagingDevice);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ImageDisplay);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ImageCamera);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ImageScanner);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ImagePrinter);
        break;
    case QBluetoothDeviceInfo::WearableDevice:
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedWearableDevice);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WearableWristWatch);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WearablePager);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WearableJacket);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WearableHelmet);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(WearableGlasses);
        break;
    case QBluetoothDeviceInfo::ToyDevice:
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedToy);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ToyRobot);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ToyVehicle);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ToyDoll);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ToyController);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(ToyGame);
        break;
    case QBluetoothDeviceInfo::HealthDevice:
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(UncategorizedHealthDevice);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HealthBloodPressureMonitor);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HealthThermometer);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HealthWeightScale);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HealthGlucoseMeter);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HealthPulseOximeter);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HealthDataDisplay);
        QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN(HealthStepCounter);
        break;
    case QBluetoothDeviceInfo::UncategorizedDevice:
        // There are no minor classes defined (in Qt) for uncategorized devices.
        break;
    }
    #undef QTPOKIT_INTERNAL_IF_EQUAL_THEN_RETURN
    qCDebug(pokitUtils) << "unknown minor class" << minorClass << "for major class" << majorClass;
    return QString(); // Null QString indicates unknown minor class.
}