name: Build and Test

on: [ push, pull_request ]

permissions:
  contents: read

env:
  # Currently, GitHub-hosted runners for public repos specify 4 cores, except macOS 14+
  # See https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/
  #     about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
  CMAKE_BUILD_PARALLEL_LEVEL: 4 # Default only; overridden where appriopriate, such as on macOS 14+ below.
  QT_FORCE_STDERR_LOGGING: 1 # Make sure Qt logs errors (during Workflow runs) to console. Especially for Windows.

jobs:
  linux:
    runs-on: ubuntu-20.04${{ matrix.arch == 'arm64' && '-arm' || '' }}
    strategy:
      fail-fast: false
      matrix:
        qt:
          - 6.2.4
          - 6.3.2
          - 6.4.3
          - 6.5.3
          - 6.6.3
          - 6.7.3
          - 6.8.3
          - 6.9.0
        arch:
          - x86-64
        cc:
          - clang
          - gcc
        exclude:
          # Qt's online installer only provides arm64 builds from Qt 6.7 onwards. Note, Ubuntu (Debian) does provide
          # arm64 Qt builds, so we don't exclude `5` nor `6`, just the Qt online versions (5.x.y and 6.[0-6].y).
          - { qt: 5.9.9,   arch: arm64 }
          - { qt: 5.10.1,  arch: arm64 }
          - { qt: 5.11.3,  arch: arm64 }
          - { qt: 5.12.12, arch: arm64 }
          - { qt: 5.13.2,  arch: arm64 }
          - { qt: 5.14.2,  arch: arm64 }
          - { qt: 5.15.2,  arch: arm64 }
          - { qt: 6.2.4,   arch: arm64 }
          - { qt: 6.3.2,   arch: arm64 }
          - { qt: 6.4.3,   arch: arm64 }
          - { qt: 6.5.3,   arch: arm64 }
          - { qt: 6.6.3,   arch: arm64 }
    steps:
      - name: Upgrade OS
        run: |
          sudo apt-mark hold firefox grub-efi-${{ matrix.arch == 'arm64' && 'arm64' || 'amd64' }}-signed
          sudo apt update && sudo apt upgrade
          sudo apt install lcov llvm
      - uses: actions/setup-python@v5
        with:
          python-version: '>=3.9'
      - name: Install online Qt version
        if: contains(matrix.qt, '.') && matrix.arch != 'arm64' # ie if not using Ubuntu's Qt5/Qt6.
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt }}
          modules: ${{ startsWith(matrix.qt, '6') && 'qtconnectivity' || '' }}
          setup-python: false
          documentation: true
          doc-archives: >-
            ${{ (startsWith(matrix.qt, '5.10.') || startsWith(matrix.qt, '5.11.')) && 'qt' ||
                (startsWith(matrix.qt, '5') && 'qtcore qtbluetooth' || 'qtcore') }}
          doc-modules: ${{ startsWith(matrix.qt, '6') && 'qtbluetooth' || '' }}
          aqtversion: '>=3.2.0' # 3.2.0+ required for Qt 6.8+ support; https://github.com/miurahr/aqtinstall/issues/843
      - uses: actions/checkout@v4
      - name: Build
        id: build
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cc == 'gcc' && 'g++' || 'clang++' }}
          PROJECT_BUILD_ID: ${{ github.run_number }}.linux.${{ matrix.arch }}.${{ matrix.cc }}.qt-${{ matrix.qt }}
        run: |
          [[ '${{ matrix.qt }}' =~ ^[56]$ ]] ||
            qtInstallDocs="$RUNNER_WORKSPACE/Qt/Docs/Qt-${QT_VERSION:-${{ matrix.qt }}}"
          # With coverage instrumentation.
          cmake -D CMAKE_BUILD_TYPE=Release \
                -D ENABLE_COVERAGE=true \
                ${qtInstallDocs:+-D "QT_INSTALL_DOCS=$qtInstallDocs"} \
                -S "$GITHUB_WORKSPACE" -B "$RUNNER_TEMP/coverage"
          # Without coverage instrumentation.
          cmake -D CMAKE_BUILD_TYPE=Release \
                -D ENABLE_COVERAGE=false \
                ${qtInstallDocs:+-D "QT_INSTALL_DOCS=$qtInstallDocs"} \
                -S "$GITHUB_WORKSPACE" -B "$RUNNER_TEMP/release"
          tee -a "$GITHUB_OUTPUT" <<< "dokitVersion=$(cat "$RUNNER_TEMP/release/version.txt")"
          cmake --build "$RUNNER_TEMP/coverage"
          cmake --build "$RUNNER_TEMP/release"
          "$RUNNER_TEMP/coverage/src/cli/dokit" --version
          "$RUNNER_TEMP/release/src/cli/dokit" --version
      - name: Test
        run: |
          ctest --output-on-failure --test-dir "$RUNNER_TEMP/coverage" --verbose
          ctest --output-on-failure --test-dir "$RUNNER_TEMP/release" --verbose
          cmake --build "$RUNNER_TEMP/coverage" --target coverage
      - name: Test localisations
        # \todo For unknown reasons, Qt 6.2.4 w/ GCC fails to include full set of *.qm file - happens locally too, not
        # just on GitHub hosted runners.  We could diagnose further, but this one corner case is very low value today.
        if: startsWith(matrix.qt, '6') && !(startsWith(matrix.qt, '6.2.') && matrix.cc == 'gcc')
        run: |
          declare -Ar languages=(
            [en_AU]='Australia|Unrecognised'
            [en_GB]='United Kingdom|Unrecognised'
            [en_US]='United States|Unrecognized'
          )
          for langId in "${!languages[@]}"; do
            IFS='|' read -r langName localText <<< "${languages[${langId}]}"
            echo "Checking: ${langName} (${langId})"
            output=$(
              LANG="${langId}.UTF-8" \
              "$RUNNER_TEMP/release/src/cli/dokit" calibrate --debug --temperature x 2>&1 || :)
            printf '%s\n--------\n' "${output}"
            grep "Locale:.*${langName}" <<< "${output}"
            grep "App translations: :/i18n/cli/${langId}\.qm" <<< "${output}"
            grep "Library translations: :/i18n/lib/${langId}\.qm" <<< "${output}"
            grep "${localText} temperature format" <<< "${output}"
          done
