name: Translations

on: [ push, pull_request ]

permissions:
  contents: read

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4

jobs:
  lupdate:
    runs-on: ubuntu-24.04
    steps:
      - name: Install Qt
        run: |
          sudo apt-mark hold firefox grub-efi-amd64-signed
          sudo apt update
          sudo apt upgrade
          sudo apt install qt6-{base-{dev{,-tools},doc-dev},connectivity-{dev,doc-html},l10n-tools,tools-dev{,-tools}}
      - uses: actions/checkout@v5
      - name: Check translation files
        run: |
          cmake -S "$GITHUB_WORKSPACE" -B "$RUNNER_TEMP"
          cmake --build "$RUNNER_TEMP" --target {cli,QtPokit}_lupdate # \todo Include gui too, when relevant.
          [[ -z $(git status --porcelain | tee /dev/stderr) ]]
